// © 2024–2026 Andrea Taliento (ANDRYXify) — Tutti i diritti riservati — socialbot.live
// Proprietà intellettuale · ANDRYX-IP::a7f39c1e8b424d90-4f7b-taliento::socialbot.live
//
// IL FRASARIO: LA COMMUNITY. I grazie del bot: follow, abbonamenti e regali,
// raid in arrivo, Bit, shoutout, premi a punti canale. Le regole di scrittura
// sono in testa a frasario/diretta.js.
//
// Chi fa il gesto non ha un genere noto: niente «benvenuto», «sei un grande»,
// «l'hai fatto apposta». Chi regala in anonimo ha i suoi momenti, perche' una
// frase scritta per un nome non si regge senza.

export const GRUPPO = { id: 'community', titolo: ['La community', 'The community', 'La comunidad'] };

export const MOMENTI = {
  follow: {
    titolo: ['Un follow', 'A follow', 'Un follow'],
    quando: ['Quando qualcuno segue il canale per la prima volta.', 'When someone follows the channel for the first time.', 'Cuando alguien sigue el canal por primera vez.'],
    dati: { nome: 'sempre' },
    esempio: { nome: 'Luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Grazie del follow, {nome}! Ora fai ufficialmente parte della banda {:🎉}',
          '{nome} ha premuto follow! Scelta di gran classe {:😎}',
          'Un nuovo follow da {nome}! Il divano è grande, c\'è posto per tutti {:🛋️}',
          '{nome} ci segue! Da oggi niente più scuse per perdersi le live {:😏}',
          'Follow di {nome} registrato. Il mio ego ringrazia {:😄}',
          'Oh, {nome} sale a bordo! Grazie del follow {:🚀}',
          '{nome}, grazie del follow! Prometto di meritarlo, almeno ogni tanto {:😅}',
        ],
        amichevole: [
          'Grazie del follow, {nome}! Fatti sentire in chat quando vuoi {:💜}',
          'Che bello, {nome} ha iniziato a seguire il canale! Grazie {:😊}',
          '{nome}, grazie per il follow! È un piacere averti qui {:🤗}',
          'Un grazie grande a {nome} per il follow {:💜}',
          'Grazie {nome}! Spero che qui ti troverai bene {:🙌}',
          'Nuovo follow da {nome}: grazie, davvero {:😊}',
        ],
        serio: [
          'Grazie del follow, {nome}.',
          '{nome}, grazie per aver seguito il canale.',
          'Grazie {nome}, apprezzo il follow.',
          'Un nuovo follow da {nome}. Grazie.',
          'Grazie per il follow, {nome}. Buona permanenza.',
          '{nome} segue il canale da ora. Grazie.',
        ],
      },
      en: {
        scherzoso: [
          'Thanks for the follow, {nome}! You\'re officially one of us now {:🎉}',
          '{nome} hit follow! A choice of great taste {:😎}',
          'New follow from {nome}! The couch is big, there\'s room for everyone {:🛋️}',
          '{nome} is following! No more excuses for missing streams {:😏}',
          'Follow from {nome} received. My ego says thanks {:😄}',
          'Oh, {nome} just hopped on board! Thanks for the follow {:🚀}',
          '{nome}, thanks for the follow! I promise to earn it, at least sometimes {:😅}',
        ],
        amichevole: [
          'Thanks for the follow, {nome}! Say hi in chat anytime {:💜}',
          'Aw, {nome} just followed the channel! Thank you {:😊}',
          '{nome}, thanks for following! It\'s a pleasure to have you here {:🤗}',
          'A big thank you to {nome} for the follow {:💜}',
          'Thank you, {nome}! I hope you\'ll feel at home here {:🙌}',
          'New follow from {nome}: thank you, really {:😊}',
        ],
        serio: [
          'Thanks for the follow, {nome}.',
          '{nome}, thank you for following the channel.',
          'Thank you, {nome}, I appreciate the follow.',
          'A new follow from {nome}. Thank you.',
          'Thanks for following, {nome}. Enjoy your stay.',
          '{nome} is now following the channel. Thank you.',
        ],
      },
      es: {
        scherzoso: [
          '¡Gracias por el follow, {nome}! Ya eres oficialmente de la banda {:🎉}',
          '¡{nome} le dio a seguir! Una elección con mucha clase {:😎}',
          '¡Nuevo follow de {nome}! El sofá es grande, hay lugar para todos {:🛋️}',
          '¡{nome} nos sigue! Se acabaron las excusas para perderse los streams {:😏}',
          'Follow de {nome} recibido. Mi ego lo agradece {:😄}',
          '¡Oh, {nome} se subió a bordo! Gracias por el follow {:🚀}',
          '¡{nome}, gracias por el follow! Prometo merecerlo, al menos a veces {:😅}',
        ],
        amichevole: [
          '¡Gracias por el follow, {nome}! Escribe en el chat cuando quieras {:💜}',
          '¡Qué bien, {nome} empezó a seguir el canal! Gracias {:😊}',
          '{nome}, ¡gracias por seguirnos! Es un gusto tenerte aquí {:🤗}',
          'Un gracias enorme a {nome} por el follow {:💜}',
          '¡Gracias, {nome}! Espero que te sientas como en casa {:🙌}',
          'Nuevo follow de {nome}: de verdad, gracias {:😊}',
        ],
        serio: [
          'Gracias por el follow, {nome}.',
          '{nome}, gracias por seguir el canal.',
          'Gracias, {nome}, aprecio el follow.',
          'Un nuevo follow de {nome}. Gracias.',
          'Gracias por seguirnos, {nome}. Que disfrutes la transmisión.',
          '{nome} sigue el canal desde ahora. Gracias.',
        ],
      },
    },
  },

  'follow-ritorno': {
    titolo: ['Un follow che torna', 'A returning follow', 'Un follow que vuelve'],
    quando: ['Quando torna a seguirti chi aveva smesso da mesi.', 'When someone who had unfollowed months ago follows again.', 'Cuando vuelve a seguirte quien lo había dejado hace meses.'],
    dati: { nome: 'sempre' },
    esempio: { nome: 'Luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Guarda chi si rivede: {nome}! Ti abbiamo tenuto il posto {:👀}',
          'Rieccoti, {nome}! Lo sapevo che ci saremmo rivisti {:😏}',
          '{nome} di nuovo tra noi! La porta era rimasta socchiusa apposta {:🚪}',
          'Il ritorno di {nome}! Mancava solo la colonna sonora {:🎺}',
          'Oh, {nome} ha rimesso il follow! Facciamo finta che non sia mai successo niente {:😇}',
          '{nome} è di nuovo qui! Il divano ti aspettava {:🛋️}',
        ],
        amichevole: [
          'Che bello rivederti, {nome}! {:💜}',
          '{nome} è di nuovo dei nostri, che piacere {:✨}',
          'Ciao di nuovo, {nome}! Grazie del ritorno {:🤗}',
          'Rieccoti, {nome}! Fatti sentire in chat {:😊}',
          'Che gioia ritrovarti qui, {nome} {:💜}',
          '{nome}, che bello averti di nuovo con noi {:🙌}',
        ],
        serio: [
          'Di nuovo qui, {nome}. Grazie.',
          'Grazie di aver rimesso il follow, {nome}.',
          '{nome} segue di nuovo il canale. Grazie.',
          'Ritroviamo {nome}. Grazie per il ritorno.',
          'Grazie {nome}, fa piacere rivederti.',
          'Un ritorno: {nome} ci segue di nuovo. Grazie.',
        ],
      },
      en: {
        scherzoso: [
          'Look who\'s back: {nome}! We saved your seat {:👀}',
          'There you are, {nome}! I knew we\'d meet again {:😏}',
          '{nome} is back with us! We left the door open on purpose {:🚪}',
          'The return of {nome}! All that\'s missing is the soundtrack {:🎺}',
          'Oh, {nome} followed again! Let\'s pretend nothing ever happened {:😇}',
          '{nome} is here again! The couch missed you {:🛋️}',
        ],
        amichevole: [
          'So good to see you again, {nome}! {:💜}',
          '{nome} is one of us again, what a joy {:✨}',
          'Hi again, {nome}! Thanks for coming back {:🤗}',
          'There you are, {nome}! Say hi in chat {:😊}',
          'Such a joy to find you here again, {nome} {:💜}',
          '{nome}, it\'s lovely to have you with us again {:🙌}',
        ],
        serio: [
          'Back again, {nome}. Thank you.',
          'Thanks for following again, {nome}.',
          '{nome} is following the channel again. Thank you.',
          'Welcome back, {nome}. Thanks for returning.',
          'Thank you, {nome}, good to see you again.',
          'A return: {nome} is following us again. Thank you.',
        ],
      },
      es: {
        scherzoso: [
          'Miren quién volvió: ¡{nome}! Te guardamos el lugar {:👀}',
          '¡Ahí estás, {nome}! Sabía que nos volveríamos a ver {:😏}',
          '¡{nome} está de vuelta! Dejamos la puerta abierta a propósito {:🚪}',
          '¡El regreso de {nome}! Solo falta la música de fondo {:🎺}',
          '¡Oh, {nome} volvió a seguirnos! Hagamos como que nunca pasó nada {:😇}',
          '¡{nome} está aquí otra vez! El sofá te extrañaba {:🛋️}',
        ],
        amichevole: [
          '¡Qué alegría verte de nuevo, {nome}! {:💜}',
          '{nome} vuelve a estar con nosotros, qué gusto {:✨}',
          '¡Hola de nuevo, {nome}! Gracias por volver {:🤗}',
          '¡Ahí estás, {nome}! Escribe en el chat {:😊}',
          'Qué bueno encontrarte aquí otra vez, {nome} {:💜}',
          '{nome}, qué bonito tenerte de nuevo con nosotros {:🙌}',
        ],
        serio: [
          'De nuevo aquí, {nome}. Gracias.',
          'Gracias por volver a seguirnos, {nome}.',
          '{nome} vuelve a seguir el canal. Gracias.',
          'Qué bueno tu regreso, {nome}. Gracias.',
          'Gracias, {nome}, es un gusto verte otra vez.',
          'Un regreso: {nome} nos sigue de nuevo. Gracias.',
        ],
      },
    },
  },

  abbonamento: {
    titolo: ['Un abbonamento', 'A sub', 'Una suscripción'],
    quando: ['Quando qualcuno si abbona al canale.', 'When someone subscribes to the channel.', 'Cuando alguien se suscribe al canal.'],
    dati: { nome: 'sempre', tier: 'a volte' },
    esempio: { nome: 'Luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Grazie della sub, {nome}! Il tuo nome è già inciso nella leggenda {:🏆}',
          '{nome} ha fatto la sub! Ufficialmente parte della famiglia {:🎉}',
          'Sub di {nome}! Abbraccio virtuale in arrivo, non scappare {:🤗}',
          'Grazie {nome} per la sub! Il mio portafoglio e il mio cuore ringraziano {:😄}',
          'Nuova sub da {nome}! Adesso hai il permesso di spammare le emote {:😎}',
          '{nome} con la sub! Non dovevi… ma grazie, ci tenevo {:💜}',
          'Sub in cassa da {nome}! Che classe {:🔥}',
          'Sub di livello {tier} da {nome}! Qui si fa sul serio {:💎}',
        ],
        amichevole: [
          'Grazie di cuore per la sub, {nome} {:💜}',
          '{nome}, grazie per l\'abbonamento! Significa tanto {:🙏}',
          'Che bello, {nome} ha fatto la sub! Grazie per il supporto {:😊}',
          'Grazie {nome}! Il tuo supporto mi aiuta davvero {:🤗}',
          'Una sub da {nome}! Grazie, sei una persona speciale {:💜}',
          'Grazie mille per la sub, {nome}! Adesso fai parte della famiglia {:🙌}',
          'Grazie per la sub di livello {tier}, {nome}! Sono senza parole {:💜}',
        ],
        serio: [
          'Grazie per l\'abbonamento, {nome}.',
          '{nome}, grazie per la sub.',
          'Grazie {nome}, apprezzo molto il tuo supporto.',
          'Un nuovo abbonamento da {nome}. Grazie.',
          'Grazie per la sub, {nome}. Il tuo supporto conta.',
          'Grazie {nome} per aver sostenuto il canale.',
          'Grazie per l\'abbonamento di livello {tier}, {nome}.',
        ],
      },
      en: {
        scherzoso: [
          'Thanks for the sub, {nome}! Your name is already carved into legend {:🏆}',
          '{nome} just subbed! Officially part of the family {:🎉}',
          'Sub from {nome}! Virtual hug incoming, don\'t run {:🤗}',
          'Thanks for the sub, {nome}! My wallet and my heart say thank you {:😄}',
          'New sub from {nome}! You now have permission to spam emotes {:😎}',
          '{nome} with the sub! You didn\'t have to… but thank you, it means a lot {:💜}',
          'Sub secured from {nome}! Pure class {:🔥}',
          'Tier {tier} sub from {nome}! Now we\'re talking {:💎}',
        ],
        amichevole: [
          'Thank you so much for the sub, {nome} {:💜}',
          '{nome}, thanks for subscribing! It really means a lot {:🙏}',
          'Yay, {nome} subscribed! Thanks for the support {:😊}',
          'Thank you, {nome}! Your support really helps {:🤗}',
          'A sub from {nome}! Thank you, you\'re wonderful {:💜}',
          'Thanks a ton for the sub, {nome}! You\'re part of the family now {:🙌}',
          'Thanks for the Tier {tier} sub, {nome}! I\'m speechless {:💜}',
        ],
        serio: [
          'Thank you for subscribing, {nome}.',
          '{nome}, thanks for the sub.',
          'Thank you, {nome}, I really appreciate your support.',
          'A new subscription from {nome}. Thank you.',
          'Thanks for the sub, {nome}. Your support matters.',
          'Thank you, {nome}, for supporting the channel.',
          'Thank you for the Tier {tier} subscription, {nome}.',
        ],
      },
      es: {
        scherzoso: [
          '¡Gracias por la suscripción, {nome}! Tu nombre ya está grabado en la leyenda {:🏆}',
          '¡{nome} se suscribió! Oficialmente parte de la familia {:🎉}',
          '¡Sub de {nome}! Abrazo virtual en camino, no huyas {:🤗}',
          '¡Gracias por la sub, {nome}! Mi billetera y mi corazón te lo agradecen {:😄}',
          '¡Nueva sub de {nome}! Ya tienes permiso para llenar el chat de emotes {:😎}',
          '¡{nome} con la sub! No tenías que hacerlo… pero gracias, significa mucho {:💜}',
          '¡Sub asegurada de {nome}! Pura clase {:🔥}',
          '¡Sub de nivel {tier} de {nome}! Esto va en serio {:💎}',
        ],
        amichevole: [
          'Muchísimas gracias por la suscripción, {nome} {:💜}',
          '{nome}, ¡gracias por suscribirte! Significa mucho para mí {:🙏}',
          '¡Qué bien, {nome} se suscribió! Gracias por el apoyo {:😊}',
          '¡Gracias, {nome}! Tu apoyo de verdad ayuda {:🤗}',
          '¡Una sub de {nome}! Gracias, eres una persona increíble {:💜}',
          '¡Mil gracias por la sub, {nome}! Ya eres parte de la familia {:🙌}',
          '¡Gracias por la sub de nivel {tier}, {nome}! Me dejas sin palabras {:💜}',
        ],
        serio: [
          'Gracias por la suscripción, {nome}.',
          '{nome}, gracias por la sub.',
          'Gracias, {nome}, aprecio mucho tu apoyo.',
          'Una nueva suscripción de {nome}. Gracias.',
          'Gracias por la sub, {nome}. Tu apoyo cuenta.',
          'Gracias, {nome}, por apoyar el canal.',
          'Gracias por la suscripción de nivel {tier}, {nome}.',
        ],
      },
    },
  },

  'abbonamento-rinnovo': {
    titolo: ['Un abbonamento rinnovato', 'A resub', 'Una renovación'],
    quando: ['Quando qualcuno rinnova l’abbonamento e lo dice in chat.', 'When someone renews their sub and shares it in chat.', 'Cuando alguien renueva la suscripción y lo comparte en el chat.'],
    dati: { nome: 'sempre', mesi: 'sempre' },
    esempio: { nome: 'Luna', mesi: 7 },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          '{nome} rinnova la sub: {mesi|un mese|# mesi} insieme! Qui si fa sul serio {:💍}',
          '{mesi|Un mese|# mesi} di sub per {nome}! Praticamente arredamento del canale {:🛋️}',
          'Rinnovo di {nome}, siamo a {mesi|un mese|# mesi}! Fedeltà da medaglia {:🏅}',
          '{nome} non ci lascia: sub rinnovata, {mesi|un mese|# mesi} e non sentirli {:😎}',
          'Ancora tu, {nome}? {mesi|Un mese|# mesi} di sub, ti voglio bene {:💜}',
          '{nome} festeggia {mesi|un mese|# mesi} di sub! Torta virtuale per tutti {:🎂}',
        ],
        amichevole: [
          'Grazie per il rinnovo, {nome}! {mesi|Un mese|# mesi} insieme {:💜}',
          '{nome}, {mesi|un mese|# mesi} di sub: grazie di esserci sempre {:🤗}',
          'Che bello, {nome} rinnova la sub! Siamo a {mesi|un mese|# mesi} {:😊}',
          'Grazie {nome}, {mesi|un mese|# mesi} di supporto: significa tanto {:🙏}',
          '{mesi|Un mese|# mesi} di sub da {nome}! Grazie per la fiducia {:💜}',
          'Rinnovo di {nome}: {mesi|un mese|# mesi} e sempre qui. Grazie {:🙌}',
        ],
        serio: [
          'Grazie per il rinnovo, {nome}: {mesi|un mese|# mesi} di abbonamento.',
          '{nome} rinnova l\'abbonamento. {mesi|Un mese|# mesi} in totale, grazie.',
          'Grazie {nome} per {mesi|un mese|# mesi} di sostegno.',
          'Rinnovo di {nome}: {mesi|un mese|# mesi}. Grazie.',
          '{nome}, grazie per il rinnovo e per {mesi|un mese|# mesi} di sub.',
          'Grazie a {nome} per il sostegno: {mesi|un mese|# mesi} in tutto.',
        ],
      },
      en: {
        scherzoso: [
          '{nome} resubbed: {mesi|one month|# months} together! This is getting serious {:💍}',
          '{mesi|One month|# months} of subs for {nome}! Basically part of the furniture now {:🛋️}',
          'Resub from {nome}, we\'re at {mesi|one month|# months}! Medal-worthy loyalty {:🏅}',
          '{nome} isn\'t going anywhere: resub, {mesi|one month|# months} and counting {:😎}',
          'You again, {nome}? {mesi|One month|# months} of subs, I love you {:💜}',
          '{nome} celebrates {mesi|one month|# months} subbed! Virtual cake for everyone {:🎂}',
        ],
        amichevole: [
          'Thanks for the resub, {nome}! {mesi|One month|# months} together {:💜}',
          '{nome}, {mesi|one month|# months} subbed: thank you for always being here {:🤗}',
          'Yay, {nome} resubbed! We\'re at {mesi|one month|# months} {:😊}',
          'Thank you, {nome}, {mesi|one month|# months} of support means so much {:🙏}',
          '{mesi|One month|# months} of subs from {nome}! Thanks for the trust {:💜}',
          'Resub from {nome}: {mesi|one month|# months} and still here. Thank you {:🙌}',
        ],
        serio: [
          'Thank you for the resub, {nome}: {mesi|one month|# months} subscribed.',
          '{nome} renewed their subscription. {mesi|One month|# months} total, thank you.',
          'Thank you, {nome}, for {mesi|one month|# months} of support.',
          'Resub from {nome}: {mesi|one month|# months}. Thank you.',
          '{nome}, thanks for the resub and for {mesi|one month|# months} subscribed.',
          'Thanks to {nome} for the support: {mesi|one month|# months} in total.',
        ],
      },
      es: {
        scherzoso: [
          '{nome} renueva la sub: ¡{mesi|un mes|# meses} juntos! Esto ya va en serio {:💍}',
          '¡{mesi|Un mes|# meses} de sub para {nome}! Ya eres parte del mobiliario {:🛋️}',
          '¡Renovación de {nome}, vamos por {mesi|un mes|# meses}! Lealtad de medalla {:🏅}',
          '{nome} no se va: sub renovada, {mesi|un mes|# meses} y contando {:😎}',
          '¿Otra vez tú, {nome}? {mesi|Un mes|# meses} de sub, te quiero {:💜}',
          '¡{nome} celebra {mesi|un mes|# meses} de sub! Pastel virtual para todos {:🎂}',
        ],
        amichevole: [
          '¡Gracias por renovar, {nome}! {mesi|Un mes|# meses} juntos {:💜}',
          '{nome}, {mesi|un mes|# meses} de sub: gracias por estar siempre {:🤗}',
          '¡Qué bien, {nome} renovó la sub! Vamos por {mesi|un mes|# meses} {:😊}',
          'Gracias, {nome}: {mesi|un mes de apoyo significa|# meses de apoyo significan} mucho {:🙏}',
          '¡{mesi|Un mes|# meses} de sub de {nome}! Gracias por la confianza {:💜}',
          'Renovación de {nome}: {mesi|un mes|# meses} y sigue aquí. Gracias {:🙌}',
        ],
        serio: [
          'Gracias por renovar, {nome}: {mesi|un mes|# meses} de suscripción.',
          '{nome} renueva la suscripción. {mesi|Un mes|# meses} en total, gracias.',
          'Gracias, {nome}, por {mesi|un mes|# meses} de apoyo.',
          'Renovación de {nome}: {mesi|un mes|# meses}. Gracias.',
          '{nome}, gracias por renovar y por {mesi|un mes|# meses} de sub.',
          'Gracias a {nome} por el apoyo: {mesi|un mes|# meses} en total.',
        ],
      },
    },
  },

  'abbonamento-regalo': {
    titolo: ['Abbonamenti regalati', 'Gifted subs', 'Suscripciones regaladas'],
    quando: ['Quando qualcuno regala abbonamenti alla chat. Chi li riceve non ha un grazie a parte: il grazie va a chi regala.', 'When someone gifts subs to chat. Recipients do not get a separate thank-you: the thanks goes to the gifter.', 'Cuando alguien regala suscripciones al chat. Quien las recibe no tiene un agradecimiento aparte: el agradecimiento va a quien regala.'],
    dati: { nome: 'sempre', quanti: 'sempre' },
    esempio: { nome: 'Luna', quanti: 5 },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          '{nome} regala {quanti|una sub|# sub} alla chat! Babbo Natale ha cambiato indirizzo {:🎅}',
          'Regali in arrivo: {quanti|una sub|# sub} da {nome}! Controllate sotto l\'albero {:🎁}',
          '{nome} ha appena regalato {quanti|una sub|# sub}. Generosità livello leggenda {:🏆}',
          'Fermi tutti: {nome} regala {quanti|una sub|# sub}! Applausi {:👏}',
          '{quanti|Una sub regalata|# sub regalate} da {nome}! Il cuore di questa chat {:💜}',
          'Grazie {nome} per {quanti|la sub regalata|le # sub regalate}! La chat ringrazia in coro {:🎶}',
        ],
        amichevole: [
          'Grazie di cuore, {nome}, per {quanti|la sub regalata|le # sub regalate} {:💜}',
          '{nome} ha regalato {quanti|una sub|# sub} alla community, che gesto {:🤗}',
          'Che generosità, {nome}! {quanti|Una sub regalata|# sub regalate}, grazie {:🎁}',
          'Grazie {nome} per aver regalato {quanti|una sub|# sub}! Che fortuna, chat {:😊}',
          '{quanti|Una sub|# sub} in regalo da {nome}: grazie per pensare agli altri {:💜}',
          '{nome} fa un regalo alla chat: {quanti|una sub|# sub}! Grazie davvero {:🙌}',
        ],
        serio: [
          'Grazie {nome} per {quanti|la sub regalata|le # sub regalate}.',
          '{nome} ha regalato {quanti|un abbonamento|# abbonamenti}. Grazie.',
          'Grazie a {nome}: {quanti|una sub regalata|# sub regalate} alla community.',
          '{quanti|Un abbonamento regalato|# abbonamenti regalati} da {nome}. Grazie per la generosità.',
          'Grazie {nome}, il tuo regalo di {quanti|una sub|# sub} è apprezzato.',
          '{nome} regala {quanti|una sub|# sub} alla chat. Grazie.',
        ],
      },
      en: {
        scherzoso: [
          '{nome} is gifting {quanti|a sub|# subs} to chat! Santa changed addresses {:🎅}',
          'Gifts incoming: {quanti|a sub|# subs} from {nome}! Check under the tree {:🎁}',
          '{nome} just gifted {quanti|a sub|# subs}. Legendary generosity {:🏆}',
          'Hold up: {nome} is gifting {quanti|a sub|# subs}! Round of applause {:👏}',
          '{quanti|A gifted sub|# gifted subs} from {nome}! The heart of this chat {:💜}',
          'Thanks, {nome}, for {quanti|the gifted sub|the # gifted subs}! Chat says thanks in chorus {:🎶}',
        ],
        amichevole: [
          'Thank you so much, {nome}, for {quanti|the gifted sub|the # gifted subs} {:💜}',
          '{nome} gifted {quanti|a sub|# subs} to the community, what a lovely gesture {:🤗}',
          'So generous, {nome}! {quanti|One gifted sub|# gifted subs}, thank you {:🎁}',
          'Thanks, {nome}, for gifting {quanti|a sub|# subs}! Lucky you, chat {:😊}',
          '{quanti|A sub|# subs} gifted by {nome}: thanks for thinking of others {:💜}',
          '{nome} has a gift for chat: {quanti|a sub|# subs}! Thank you, really {:🙌}',
        ],
        serio: [
          'Thank you, {nome}, for {quanti|the gifted sub|the # gifted subs}.',
          '{nome} gifted {quanti|a subscription|# subscriptions}. Thank you.',
          'Thanks to {nome}: {quanti|a gifted sub|# gifted subs} for the community.',
          '{quanti|A gifted subscription|# gifted subscriptions} from {nome}. Thank you for your generosity.',
          'Thank you, {nome}, your gift of {quanti|a sub|# subs} is appreciated.',
          '{nome} is gifting {quanti|a sub|# subs} to chat. Thank you.',
        ],
      },
      es: {
        scherzoso: [
          '¡{nome} regala {quanti|una sub|# subs} al chat! Papá Noel se mudó {:🎅}',
          'Regalos en camino: ¡{quanti|una sub|# subs} de {nome}! Revisen debajo del árbol {:🎁}',
          '{nome} acaba de regalar {quanti|una sub|# subs}. Generosidad de leyenda {:🏆}',
          'Atención: ¡{nome} regala {quanti|una sub|# subs}! Un aplauso {:👏}',
          '¡{quanti|Una sub regalada|# subs regaladas} por {nome}! El corazón de este chat {:💜}',
          '¡Gracias, {nome}, por {quanti|la sub regalada|las # subs regaladas}! El chat te lo agradece a coro {:🎶}',
        ],
        amichevole: [
          'Muchísimas gracias, {nome}, por {quanti|la sub regalada|las # subs regaladas} {:💜}',
          '{nome} regaló {quanti|una sub|# subs} a la comunidad, qué gesto tan bonito {:🤗}',
          '¡Qué generosidad, {nome}! {quanti|Una sub regalada|# subs regaladas}, gracias {:🎁}',
          '¡Gracias, {nome}, por regalar {quanti|una sub|# subs}! Qué suerte, chat {:😊}',
          '{quanti|Una sub|# subs} de regalo de {nome}: gracias por pensar en los demás {:💜}',
          '{nome} tiene un regalo para el chat: ¡{quanti|una sub|# subs}! De verdad, gracias {:🙌}',
        ],
        serio: [
          'Gracias, {nome}, por {quanti|la sub regalada|las # subs regaladas}.',
          '{nome} regaló {quanti|una suscripción|# suscripciones}. Gracias.',
          'Gracias a {nome}: {quanti|una sub regalada|# subs regaladas} para la comunidad.',
          '{quanti|Una suscripción regalada|# suscripciones regaladas} por {nome}. Gracias por la generosidad.',
          'Gracias, {nome}, tu regalo de {quanti|una sub|# subs} es muy apreciado.',
          '{nome} regala {quanti|una sub|# subs} al chat. Gracias.',
        ],
      },
    },
  },

  'regalo-anonimo': {
    titolo: ['Abbonamenti regalati in anonimo', 'Anonymous gifted subs', 'Suscripciones regaladas en anónimo'],
    quando: ['Quando qualcuno regala abbonamenti senza farsi vedere.', 'When someone gifts subs without showing their name.', 'Cuando alguien regala suscripciones sin mostrar su nombre.'],
    dati: { quanti: 'sempre' },
    esempio: { quanti: 3 },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Un anonimo misterioso regala {quanti|una sub|# sub}! Chiunque tu sia, grazie {:🕵️}',
          '{quanti|Una sub|# sub} da un benefattore senza nome! Il mistero si infittisce {:🎭}',
          'Regalo anonimo: {quanti|una sub|# sub}! Babbo Natale in incognito {:🎅}',
          'Qualcuno ha regalato {quanti|una sub|# sub} senza firmarsi. Grazie, mano misteriosa {:🦸}',
          'Un fantasma gentile ha lasciato {quanti|una sub|# sub} in regalo {:👻}',
          'Nessun nome, solo generosità: {quanti|una sub regalata|# sub regalate}! Grazie {:💜}',
        ],
        amichevole: [
          'Qualcuno ha regalato {quanti|una sub|# sub} in forma anonima: grazie, chiunque tu sia {:💜}',
          'Un regalo anonimo di {quanti|una sub|# sub}! Grazie di cuore {:🤗}',
          '{quanti|Una sub regalata|# sub regalate} senza firma. Che gesto gentile {:😊}',
          'Grazie a chi ha regalato {quanti|una sub|# sub} senza farsi vedere {:🙏}',
          'Un dono segreto di {quanti|una sub|# sub} per la chat. Grazie davvero {:💜}',
          'Grazie di cuore a chi ha regalato {quanti|una sub|# sub} in silenzio {:🎁}',
        ],
        serio: [
          'Grazie a chi ha regalato {quanti|una sub|# sub} in forma anonima.',
          '{quanti|Un abbonamento regalato|# abbonamenti regalati} in forma anonima. Grazie.',
          'Regalo anonimo: {quanti|una sub|# sub}. Grazie.',
          'Un utente anonimo ha regalato {quanti|una sub|# sub}. Grazie per la generosità.',
          'Grazie per {quanti|la sub regalata|le # sub regalate} in forma anonima.',
          'Ricevuto un regalo anonimo di {quanti|una sub|# sub}. Grazie.',
        ],
      },
      en: {
        scherzoso: [
          'A mysterious stranger just gifted {quanti|a sub|# subs}! Whoever you are, thank you {:🕵️}',
          '{quanti|A sub|# subs} from a nameless benefactor! The plot thickens {:🎭}',
          'Anonymous gift: {quanti|a sub|# subs}! Santa went undercover {:🎅}',
          'Someone gifted {quanti|a sub|# subs} without signing. Thank you, mystery hand {:🦸}',
          'A friendly ghost left {quanti|a sub|# subs} as a gift {:👻}',
          'No name, just generosity: {quanti|a gifted sub|# gifted subs}! Thank you {:💜}',
        ],
        amichevole: [
          'Someone gifted {quanti|a sub|# subs} anonymously: thank you, whoever you are {:💜}',
          'An anonymous gift of {quanti|a sub|# subs}! Thank you so much {:🤗}',
          '{quanti|A gifted sub|# gifted subs} with no name attached. What a kind gesture {:😊}',
          'Thank you to whoever gifted {quanti|a sub|# subs} behind the scenes {:🙏}',
          'A secret gift of {quanti|a sub|# subs} for chat. Thank you, truly {:💜}',
          'Heartfelt thanks to whoever quietly gifted {quanti|a sub|# subs} {:🎁}',
        ],
        serio: [
          'Thank you to whoever gifted {quanti|a sub|# subs} anonymously.',
          '{quanti|A gifted subscription|# gifted subscriptions} from an anonymous user. Thank you.',
          'Anonymous gift: {quanti|a sub|# subs}. Thank you.',
          'An anonymous user gifted {quanti|a sub|# subs}. Thank you for your generosity.',
          'Thanks for {quanti|the anonymous gifted sub|the # anonymous gifted subs}.',
          'An anonymous gift of {quanti|a sub|# subs} was received. Thank you.',
        ],
      },
      es: {
        scherzoso: [
          '¡Alguien misterioso regala {quanti|una sub|# subs}! Seas quien seas, gracias {:🕵️}',
          '¡{quanti|Una sub|# subs} de alguien sin nombre! El misterio crece {:🎭}',
          'Regalo anónimo: ¡{quanti|una sub|# subs}! Papá Noel de incógnito {:🎅}',
          'Alguien regaló {quanti|una sub|# subs} sin firmar. Gracias, mano misteriosa {:🦸}',
          'Un fantasma amable dejó {quanti|una sub|# subs} de regalo {:👻}',
          'Sin nombre, solo generosidad: ¡{quanti|una sub regalada|# subs regaladas}! Gracias {:💜}',
        ],
        amichevole: [
          'Alguien regaló {quanti|una sub|# subs} de forma anónima: gracias, seas quien seas {:💜}',
          '¡Un regalo anónimo de {quanti|una sub|# subs}! Muchísimas gracias {:🤗}',
          '{quanti|Una sub regalada|# subs regaladas} sin firma. Qué gesto tan amable {:😊}',
          'Gracias a quien regaló {quanti|una sub|# subs} sin dejarse ver {:🙏}',
          'Un regalo secreto de {quanti|una sub|# subs} para el chat. De verdad, gracias {:💜}',
          'Gracias de corazón a quien regaló {quanti|una sub|# subs} en silencio {:🎁}',
        ],
        serio: [
          'Gracias a quien regaló {quanti|una sub|# subs} de forma anónima.',
          '{quanti|Una suscripción regalada|# suscripciones regaladas} de un usuario anónimo. Gracias.',
          'Regalo anónimo: {quanti|una sub|# subs}. Gracias.',
          'Un usuario anónimo regaló {quanti|una sub|# subs}. Gracias por la generosidad.',
          'Gracias por {quanti|la sub regalada|las # subs regaladas} de forma anónima.',
          'Se recibió un regalo anónimo de {quanti|una sub|# subs}. Gracias.',
        ],
      },
    },
  },

  'raid-arrivato': {
    titolo: ['Un raid in arrivo', 'An incoming raid', 'Un raid entrante'],
    quando: ['Quando un altro canale ti manda un raid.', 'When another channel raids you.', 'Cuando otro canal te manda un raid.'],
    dati: { nome: 'sempre', spettatori: 'a volte' },
    esempio: { nome: 'Kiro', spettatori: 42 },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Aprite le porte: arriva il raid di {nome}! Benvenuti tutti {:🎉}',
          'RAID! {nome} sfonda la porta con tutta la sua squadra {:🚀}',
          'Benvenuti raider di {nome}! Il buffet è a destra, i popcorn a sinistra {:🍿}',
          'Allarme simpatia: raid di {nome} in arrivo! Fatevi sentire {:🚨}',
          'Il raid di {nome} è atterrato! Pulitevi le scarpe e mettetevi comodi {:👟}',
          'Grazie del raid, {nome}! Ci hai portato gente bellissima {:😎}',
          'Invasione pacifica da parte di {nome}! Benvenuti, qui si sta bene {:🛸}',
          'Raid di {nome}: {spettatori|arriva una persona|arrivano # persone}! Fatevi sentire in chat {:🎉}',
          '{nome} ci porta {spettatori|una persona|# persone}! Che entrata {:🚀}',
        ],
        amichevole: [
          'Grazie mille per il raid, {nome}! Benvenuti a tutti {:💜}',
          'Che bello, è arrivato il raid di {nome}! Mettetevi comodi {:🤗}',
          'Benvenuti a chi arriva da {nome}! Salutate pure in chat {:😊}',
          'Grazie {nome} per averci portato la tua community {:🙏}',
          'Un raid da {nome}! Grazie, e un caloroso saluto a tutti i nuovi arrivati {:💜}',
          'Benvenuti, raider di {nome}! Qui siete a casa {:🙌}',
          'Grazie {nome} per il raid con {spettatori|una persona|# persone} {:💜}',
        ],
        serio: [
          'Grazie per il raid, {nome}.',
          'Raid in arrivo da {nome}. Benvenuti.',
          'Benvenuti a chi arriva dal canale di {nome}.',
          'Grazie {nome} per il raid. Buona permanenza a tutti.',
          '{nome} ci ha raggiunto con un raid. Grazie.',
          'Ringrazio {nome} per il raid e saluto i nuovi arrivati.',
          'Raid da {nome} con {spettatori|una persona|# persone}. Grazie.',
        ],
      },
      en: {
        scherzoso: [
          'Open the doors: {nome}\'s raid is here! Welcome, everyone {:🎉}',
          'RAID! {nome} bursts in with the whole crew {:🚀}',
          'Welcome, {nome}\'s raiders! Buffet\'s on the right, popcorn on the left {:🍿}',
          'Good vibes alert: raid from {nome} incoming! Make some noise {:🚨}',
          '{nome}\'s raid has landed! Wipe your feet and get comfy {:👟}',
          'Thanks for the raid, {nome}! You brought us awesome people {:😎}',
          'A peaceful invasion by {nome}! Welcome, it\'s nice in here {:🛸}',
          'Raid from {nome}: {spettatori|one person|# people} just arrived! Say hi in chat {:🎉}',
          '{nome} brings us {spettatori|one person|# people}! What an entrance {:🚀}',
        ],
        amichevole: [
          'Thank you so much for the raid, {nome}! Welcome, everyone {:💜}',
          'How lovely, {nome}\'s raid is here! Make yourselves comfy {:🤗}',
          'Welcome to everyone coming from {nome}! Feel free to say hi in chat {:😊}',
          'Thanks, {nome}, for bringing your community over {:🙏}',
          'A raid from {nome}! Thank you, and a warm hello to all the newcomers {:💜}',
          'Welcome, {nome}\'s raiders! Make yourselves at home {:🙌}',
          'Thanks, {nome}, for the raid with {spettatori|one person|# people} {:💜}',
        ],
        serio: [
          'Thank you for the raid, {nome}.',
          'Incoming raid from {nome}. Welcome.',
          'Welcome to everyone arriving from {nome}\'s channel.',
          'Thanks for the raid, {nome}. Enjoy your stay, everyone.',
          '{nome} joined us with a raid. Thank you.',
          'Thank you to {nome} for the raid, and hello to the new arrivals.',
          'Raid from {nome} with {spettatori|one person|# people}. Thank you.',
        ],
      },
      es: {
        scherzoso: [
          'Abran las puertas: ¡llega el raid de {nome}! Bienvenidos todos {:🎉}',
          '¡RAID! {nome} entra con todo su equipo {:🚀}',
          '¡Bienvenidos, raiders de {nome}! El buffet a la derecha, las palomitas a la izquierda {:🍿}',
          'Alerta de buen ambiente: ¡raid de {nome} en camino! Hagan ruido {:🚨}',
          '¡El raid de {nome} aterrizó! Límpiense los zapatos y pónganse cómodos {:👟}',
          '¡Gracias por el raid, {nome}! Nos trajiste gente increíble {:😎}',
          '¡Invasión pacífica de {nome}! Bienvenidos, aquí se está muy bien {:🛸}',
          'Raid de {nome}: ¡{spettatori|llega una persona|llegan # personas}! Saluden en el chat {:🎉}',
          '¡{nome} nos trae {spettatori|una persona|# personas}! Qué entrada {:🚀}',
        ],
        amichevole: [
          '¡Muchísimas gracias por el raid, {nome}! Bienvenidos todos {:💜}',
          '¡Qué alegría, llegó el raid de {nome}! Pónganse cómodos {:🤗}',
          '¡Bienvenidos quienes vienen de {nome}! Saluden en el chat {:😊}',
          'Gracias, {nome}, por traernos a tu comunidad {:🙏}',
          '¡Un raid de {nome}! Gracias, y un saludo cálido a quienes acaban de llegar {:💜}',
          '¡Bienvenidos, raiders de {nome}! Están en su casa {:🙌}',
          'Gracias, {nome}, por el raid con {spettatori|una persona|# personas} {:💜}',
        ],
        serio: [
          'Gracias por el raid, {nome}.',
          'Raid entrante de {nome}. Bienvenidos.',
          'Bienvenidos a quienes llegan del canal de {nome}.',
          'Gracias por el raid, {nome}. Que disfruten la transmisión.',
          '{nome} se unió con un raid. Gracias.',
          'Agradezco a {nome} por el raid y saludo a quienes acaban de llegar.',
          'Raid de {nome} con {spettatori|una persona|# personas}. Gracias.',
        ],
      },
    },
  },

  bit: {
    titolo: ['I Bit', 'Bits', 'Los Bits'],
    quando: ['Quando qualcuno manda Bit con un cheer.', 'When someone cheers with Bits.', 'Cuando alguien manda Bits con un cheer.'],
    dati: { nome: 'sempre', bit: 'sempre' },
    esempio: { nome: 'Luna', bit: 500 },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          '{nome} lancia {bit} bit! Il salvadanaio fa le capriole {:💎}',
          'Pioggia di bit: {bit} da {nome}! Aprite gli ombrelli {:☔}',
          '{bit} bit da {nome}?! Ti meriti una statua in piazza {:🗿}',
          'Cheer da {bit} bit di {nome}! La chat approva all\'unanimità {:👏}',
          'Grazie {nome} per {bit} bit! Questo merita un balletto {:🕺}',
          '{nome} fa brillare la chat con {bit} bit {:✨}',
          'Arrivano bit! {bit}, firmati {nome}. Che stile {:😎}',
        ],
        amichevole: [
          'Grazie per {bit} bit, {nome}! Sei una forza {:💜}',
          '{nome}, grazie di cuore per {bit} bit {:🙏}',
          'Che bello, {bit} bit da {nome}! Grazie per il supporto {:😊}',
          'Grazie {nome} per il cheer da {bit} bit, che regalo {:🤗}',
          '{bit} bit da {nome}: grazie, lo apprezzo tantissimo {:💜}',
          'Grazie mille a {nome} per {bit} bit {:🙌}',
        ],
        serio: [
          'Grazie per {bit} bit, {nome}.',
          '{nome}, grazie per il cheer da {bit} bit.',
          'Cheer da {bit} bit ricevuto da {nome}. Grazie.',
          'Grazie {nome} per il supporto con {bit} bit.',
          'Un cheer di {nome}: {bit} bit. Grazie.',
          'Apprezzo molto il cheer, {nome}: {bit} bit. Grazie.',
        ],
      },
      en: {
        scherzoso: [
          '{nome} throws {bit|# bit|# bits}! The piggy bank is doing backflips {:💎}',
          'It\'s raining Bits: {bit|# bit|# bits} from {nome}! Umbrellas up {:☔}',
          '{bit|# bit|# bits} from {nome}?! You deserve a statue in the town square {:🗿}',
          'A {bit}-bit cheer from {nome}! Chat approves unanimously {:👏}',
          'Thanks, {nome}, for {bit|# bit|# bits}! This calls for a little dance {:🕺}',
          '{nome} lights up chat with {bit|# bit|# bits} {:✨}',
          'Bits incoming! {bit}, signed {nome}. So much style {:😎}',
        ],
        amichevole: [
          'Thanks for {bit|# bit|# bits}, {nome}! You\'re amazing {:💜}',
          '{nome}, thank you so much for {bit|# bit|# bits} {:🙏}',
          'Aw, {bit|# bit|# bits} from {nome}! Thanks for the support {:😊}',
          'Thanks, {nome}, for the {bit}-bit cheer, what a gift {:🤗}',
          '{bit|# bit|# bits} from {nome}: thank you, I really appreciate it {:💜}',
          'Thanks a ton to {nome} for {bit|# bit|# bits} {:🙌}',
        ],
        serio: [
          'Thank you for {bit|# bit|# bits}, {nome}.',
          '{nome}, thanks for the {bit}-bit cheer.',
          '{bit}-bit cheer received from {nome}. Thank you.',
          'Thank you, {nome}, for the support with {bit|# bit|# bits}.',
          'A cheer from {nome}: {bit|# bit|# bits}. Thank you.',
          'I really appreciate the cheer, {nome}: {bit|# bit|# bits}. Thank you.',
        ],
      },
      es: {
        scherzoso: [
          '¡{nome} lanza {bit|# bit|# bits}! La alcancía está dando volteretas {:💎}',
          'Lluvia de bits: ¡{bit|# bit|# bits} de {nome}! Saquen los paraguas {:☔}',
          '¿{bit|# bit|# bits} de {nome}? Te mereces una estatua en la plaza {:🗿}',
          '¡Cheer de {bit|# bit|# bits} de {nome}! El chat lo aprueba por unanimidad {:👏}',
          '¡Gracias, {nome}, por {bit|# bit|# bits}! Esto merece un baile {:🕺}',
          '{nome} hace brillar el chat con {bit|# bit|# bits} {:✨}',
          '¡Llegan bits! Cortesía de {nome}: {bit|# bit|# bits}. Qué estilo {:😎}',
        ],
        amichevole: [
          '¡Gracias por {bit|# bit|# bits}, {nome}! Eres increíble {:💜}',
          '{nome}, muchísimas gracias por {bit|# bit|# bits} {:🙏}',
          '¡Qué bien, {bit|# bit|# bits} de {nome}! Gracias por el apoyo {:😊}',
          'Gracias, {nome}, por el cheer de {bit|# bit|# bits}, qué regalo {:🤗}',
          '{bit|# bit|# bits} de {nome}: gracias, lo aprecio muchísimo {:💜}',
          'Mil gracias a {nome} por {bit|# bit|# bits} {:🙌}',
        ],
        serio: [
          'Gracias por {bit|# bit|# bits}, {nome}.',
          '{nome}, gracias por el cheer de {bit|# bit|# bits}.',
          'Cheer de {bit|# bit|# bits} recibido de {nome}. Gracias.',
          'Gracias, {nome}, por el apoyo con {bit|# bit|# bits}.',
          'Un cheer de {nome}: {bit|# bit|# bits}. Gracias.',
          'Aprecio mucho el cheer, {nome}: {bit|# bit|# bits}. Gracias.',
        ],
      },
    },
  },

  'bit-anonimo': {
    titolo: ['I Bit in anonimo', 'Anonymous Bits', 'Bits en anónimo'],
    quando: ['Quando qualcuno manda Bit senza farsi vedere.', 'When someone cheers Bits anonymously.', 'Cuando alguien manda Bits en anónimo.'],
    dati: { bit: 'sempre' },
    esempio: { bit: 100 },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Qualcuno in incognito ha mandato {bit} bit! Chiunque tu sia, grazie {:🕵️}',
          '{bit} bit da un benefattore misterioso! La trama si infittisce {:🎭}',
          'Cheer anonimo da {bit} bit! Un ninja generoso si aggira in chat {:🥷}',
          'Bit senza firma: {bit}! Grazie, mano invisibile {:👻}',
          '{bit} bit arrivati dal nulla! Grazie, anima misteriosa {:✨}',
          'Nessun nome, solo {bit} bit e tanta classe {:😎}',
        ],
        amichevole: [
          'Grazie a chi ha mandato {bit} bit in forma anonima {:💜}',
          'Un cheer anonimo da {bit} bit! Grazie di cuore {:🙏}',
          'Grazie, chiunque tu sia, per {bit} bit {:🤗}',
          '{bit} bit senza firma: che gesto gentile {:😊}',
          'Grazie mille per {bit} bit, persona misteriosa {:💜}',
          'Un regalo anonimo di {bit} bit. Grazie davvero {:🙌}',
        ],
        serio: [
          'Grazie per il cheer anonimo da {bit} bit.',
          'Cheer anonimo: {bit} bit. Grazie.',
          'Ringrazio chi ha mandato {bit} bit in forma anonima.',
          'Un utente anonimo ha inviato {bit} bit. Grazie.',
          'Grazie per il supporto anonimo di {bit} bit.',
          'È arrivato un cheer anonimo da {bit} bit. Grazie.',
        ],
      },
      en: {
        scherzoso: [
          'Someone undercover just sent {bit|# bit|# bits}! Whoever you are, thank you {:🕵️}',
          '{bit|# bit|# bits} from a mysterious benefactor! The plot thickens {:🎭}',
          'Anonymous {bit}-bit cheer! A generous ninja is lurking in chat {:🥷}',
          'Unsigned Bits: {bit}! Thank you, invisible hand {:👻}',
          '{bit|# bit|# bits} out of nowhere! Thank you, mysterious soul {:✨}',
          'No name, just {bit|# bit|# bits} and a lot of class {:😎}',
        ],
        amichevole: [
          'Thank you to whoever sent {bit|# bit|# bits} anonymously {:💜}',
          'An anonymous {bit}-bit cheer! Thank you so much {:🙏}',
          'Thank you, whoever you are, for {bit|# bit|# bits} {:🤗}',
          '{bit|# bit|# bits} with no name attached: what a kind gesture {:😊}',
          'Thanks a ton for {bit|# bit|# bits}, mystery friend {:💜}',
          'An anonymous gift of {bit|# bit|# bits}. Thank you, truly {:🙌}',
        ],
        serio: [
          'Thank you for the anonymous {bit}-bit cheer.',
          'Anonymous cheer: {bit|# bit|# bits}. Thank you.',
          'Thanks to whoever sent {bit|# bit|# bits} anonymously.',
          'An anonymous user sent {bit|# bit|# bits}. Thank you.',
          'Thank you for the anonymous support of {bit|# bit|# bits}.',
          'An anonymous {bit}-bit cheer came in. Thank you.',
        ],
      },
      es: {
        scherzoso: [
          '¡Alguien de incógnito mandó {bit|# bit|# bits}! Seas quien seas, gracias {:🕵️}',
          '¡{bit|# bit|# bits} de alguien misterioso! La trama se complica {:🎭}',
          '¡Cheer anónimo de {bit|# bit|# bits}! Un ninja generoso anda por el chat {:🥷}',
          'Bits sin firma: ¡{bit}! Gracias, mano invisible {:👻}',
          '¡Un regalo del cielo: {bit|# bit|# bits}! Gracias, alma misteriosa {:✨}',
          'Sin nombre, solo {bit|# bit|# bits} y mucha clase {:😎}',
        ],
        amichevole: [
          'Gracias a quien mandó {bit|# bit|# bits} de forma anónima {:💜}',
          '¡Un cheer anónimo de {bit|# bit|# bits}! Muchísimas gracias {:🙏}',
          'Gracias, seas quien seas, por {bit|# bit|# bits} {:🤗}',
          '{bit|# bit|# bits} sin firma: qué gesto tan amable {:😊}',
          'Mil gracias por {bit|# bit|# bits}, persona misteriosa {:💜}',
          'Un regalo anónimo de {bit|# bit|# bits}. De verdad, gracias {:🙌}',
        ],
        serio: [
          'Gracias por el cheer anónimo de {bit|# bit|# bits}.',
          'Cheer anónimo: {bit|# bit|# bits}. Gracias.',
          'Agradezco a quien envió {bit|# bit|# bits} de forma anónima.',
          'Un usuario anónimo envió {bit|# bit|# bits}. Gracias.',
          'Gracias por el apoyo anónimo de {bit|# bit|# bits}.',
          'Llegó un cheer anónimo de {bit|# bit|# bits}. Gracias.',
        ],
      },
    },
  },

  // I KICKS di Kick: il sostegno di Kick, con parole sue (non sono Bit).
  kicks: {
    titolo: ['I Kicks', 'Kicks', 'Los Kicks'],
    quando: ['Quando qualcuno regala Kicks su Kick.', 'When someone gifts Kicks on Kick.', 'Cuando alguien regala Kicks en Kick.'],
    dati: { nome: 'sempre', kicks: 'sempre' },
    esempio: { nome: 'Luna', kicks: 500 },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          '{nome} regala {kicks|# Kick|# Kicks}! Il salvadanaio verde fa la ola {:💚}',
          'Piovono Kicks: {kicks|# Kick|# Kicks} da {nome}! Fuori gli ombrelli {:☔}',
          '{kicks|# Kick|# Kicks} da {nome}?! Qui ci vuole una statua {:🗿}',
          '{nome} calcia forte: {kicks|# Kick|# Kicks}! La chat esulta {:⚽}',
          'Grazie {nome} per {kicks|# Kick|# Kicks}! Parte il balletto {:🕺}',
          'Arrivano Kicks! {kicks}, firmati {nome}. Che stile {:😎}',
        ],
        amichevole: [
          'Grazie per {kicks|# Kick|# Kicks}, {nome}! Sei una forza {:💚}',
          '{nome}, grazie di cuore per {kicks|# Kick|# Kicks} {:🙏}',
          'Che bello, {kicks|# Kick|# Kicks} da {nome}! Grazie del supporto {:😊}',
          '{kicks|# Kick|# Kicks} da {nome}: grazie, lo apprezzo tantissimo {:🤗}',
          'Grazie mille a {nome} per {kicks|# Kick|# Kicks} {:🙌}',
          '{nome} ha regalato {kicks|# Kick|# Kicks}: grazie davvero {:💚}',
        ],
        serio: [
          'Grazie per {kicks|# Kick|# Kicks}, {nome}.',
          '{nome}, grazie per {kicks|# Kick|# Kicks}.',
          '{kicks|# Kick|# Kicks} ricevuti da {nome}. Grazie.',
          'Grazie {nome} per il supporto con {kicks|# Kick|# Kicks}.',
          'Un regalo di {nome}: {kicks|# Kick|# Kicks}. Grazie.',
          'Apprezzo molto, {nome}: {kicks|# Kick|# Kicks}. Grazie.',
        ],
      },
      en: {
        scherzoso: [
          '{nome} gifts {kicks|# Kick|# Kicks}! The green piggy bank is doing the wave {:💚}',
          'It\'s raining Kicks: {kicks|# Kick|# Kicks} from {nome}! Umbrellas up {:☔}',
          '{kicks|# Kick|# Kicks} from {nome}?! This calls for a statue {:🗿}',
          '{nome} kicks hard: {kicks|# Kick|# Kicks}! Chat goes wild {:⚽}',
          'Thanks, {nome}, for {kicks|# Kick|# Kicks}! Time for a little dance {:🕺}',
          'Kicks incoming! {kicks}, signed {nome}. So much style {:😎}',
        ],
        amichevole: [
          'Thanks for {kicks|# Kick|# Kicks}, {nome}! You\'re amazing {:💚}',
          '{nome}, thank you so much for {kicks|# Kick|# Kicks} {:🙏}',
          'Aww, {kicks|# Kick|# Kicks} from {nome}! Thanks for the support {:😊}',
          '{kicks|# Kick|# Kicks} from {nome}: thank you, I really appreciate it {:🤗}',
          'Huge thanks to {nome} for {kicks|# Kick|# Kicks} {:🙌}',
          '{nome} gifted {kicks|# Kick|# Kicks}: thank you, truly {:💚}',
        ],
        serio: [
          'Thank you for {kicks|# Kick|# Kicks}, {nome}.',
          '{nome}, thanks for {kicks|# Kick|# Kicks}.',
          '{kicks|# Kick|# Kicks} received from {nome}. Thank you.',
          'Thank you, {nome}, for the support with {kicks|# Kick|# Kicks}.',
          'A gift from {nome}: {kicks|# Kick|# Kicks}. Thank you.',
          'Much appreciated, {nome}: {kicks|# Kick|# Kicks}. Thank you.',
        ],
      },
      es: {
        scherzoso: [
          '¡{nome} regala {kicks|# Kick|# Kicks}! La hucha verde hace la ola {:💚}',
          'Llueven Kicks: ¡{kicks|# Kick|# Kicks} de {nome}! Saquen los paraguas {:☔}',
          '¿¡{kicks|# Kick|# Kicks} de {nome}!? Esto merece una estatua {:🗿}',
          '{nome} patea fuerte: ¡{kicks|# Kick|# Kicks}! El chat lo celebra {:⚽}',
          '¡Gracias {nome} por {kicks|# Kick|# Kicks}! Toca bailecito {:🕺}',
          '¡Llegan Kicks! {kicks}, firmados por {nome}. Qué estilo {:😎}',
        ],
        amichevole: [
          '¡Gracias por {kicks|# Kick|# Kicks}, {nome}! Eres genial {:💚}',
          '{nome}, mil gracias por {kicks|# Kick|# Kicks} {:🙏}',
          'Qué bonito, ¡{kicks|# Kick|# Kicks} de {nome}! Gracias por el apoyo {:😊}',
          '{kicks|# Kick|# Kicks} de {nome}: gracias, lo valoro muchísimo {:🤗}',
          'Gracias a {nome} por {kicks|# Kick|# Kicks} {:🙌}',
          '{nome} ha regalado {kicks|# Kick|# Kicks}: gracias de verdad {:💚}',
        ],
        serio: [
          'Gracias por {kicks|# Kick|# Kicks}, {nome}.',
          '{nome}, gracias por {kicks|# Kick|# Kicks}.',
          '{kicks|# Kick|# Kicks} recibidos de {nome}. Gracias.',
          'Gracias {nome} por el apoyo con {kicks|# Kick|# Kicks}.',
          'Un regalo de {nome}: {kicks|# Kick|# Kicks}. Gracias.',
          'Lo valoro mucho, {nome}: {kicks|# Kick|# Kicks}. Gracias.',
        ],
      },
    },
  },
  'kicks-anonimo': {
    titolo: ['I Kicks in anonimo', 'Anonymous Kicks', 'Kicks en anónimo'],
    quando: ['Quando qualcuno regala Kicks su Kick senza farsi vedere.', 'When someone gifts Kicks on Kick anonymously.', 'Cuando alguien regala Kicks en Kick en anónimo.'],
    dati: { kicks: 'sempre' },
    esempio: { kicks: 100 },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Qualcuno in incognito ha regalato {kicks|# Kick|# Kicks}! Chiunque tu sia, grazie {:🕵️}',
          '{kicks|# Kick|# Kicks} da chi non si firma! La trama si infittisce {:🎭}',
          'Kicks senza nome: {kicks}! Un ninja generoso si aggira in chat {:🥷}',
          'Regalo misterioso: {kicks|# Kick|# Kicks}! Grazie, mano invisibile {:👻}',
          '{kicks|# Kick|# Kicks} arrivati dal nulla. Il fantasma più gentile di Kick {:💚}',
          'Chi sarà? {kicks|# Kick|# Kicks} in anonimo, e un grazie gigante {:🎁}',
        ],
        amichevole: [
          'Grazie a chi ha regalato {kicks|# Kick|# Kicks} in anonimo {:💚}',
          '{kicks|# Kick|# Kicks} in anonimo: grazie di cuore, chiunque tu sia {:🙏}',
          'Che bel gesto, {kicks|# Kick|# Kicks} senza firma. Grazie {:😊}',
          'Grazie mille per {kicks|# Kick|# Kicks}, anche se non so chi sei {:🤗}',
          'Un regalo anonimo da {kicks|# Kick|# Kicks}: grazie davvero {:🙌}',
          'Chiunque tu sia, grazie per {kicks|# Kick|# Kicks} {:💚}',
        ],
        serio: [
          'Grazie per {kicks|# Kick|# Kicks} in anonimo.',
          '{kicks|# Kick|# Kicks} ricevuti in anonimo. Grazie.',
          'Grazie a chi ha regalato {kicks|# Kick|# Kicks}.',
          'Un regalo anonimo: {kicks|# Kick|# Kicks}. Grazie.',
          'Apprezzo il gesto: {kicks|# Kick|# Kicks} in anonimo. Grazie.',
          'Grazie per il supporto anonimo con {kicks|# Kick|# Kicks}.',
        ],
      },
      en: {
        scherzoso: [
          'Someone undercover gifted {kicks|# Kick|# Kicks}! Whoever you are, thank you {:🕵️}',
          '{kicks|# Kick|# Kicks} from someone who won\'t sign! The plot thickens {:🎭}',
          'Unsigned Kicks: {kicks}! A generous ninja is lurking in chat {:🥷}',
          'Mystery gift: {kicks|# Kick|# Kicks}! Thank you, invisible hand {:👻}',
          '{kicks|# Kick|# Kicks} out of nowhere. The kindest ghost on Kick {:💚}',
          'Who could it be? {kicks|# Kick|# Kicks} anonymously, and a giant thank you {:🎁}',
        ],
        amichevole: [
          'Thanks to whoever gifted {kicks|# Kick|# Kicks} anonymously {:💚}',
          '{kicks|# Kick|# Kicks} anonymously: thank you so much, whoever you are {:🙏}',
          'What a kind gesture, {kicks|# Kick|# Kicks} with no name. Thank you {:😊}',
          'Thanks a lot for {kicks|# Kick|# Kicks}, even if I don\'t know who you are {:🤗}',
          'An anonymous gift of {kicks|# Kick|# Kicks}: thank you, truly {:🙌}',
          'Whoever you are, thank you for {kicks|# Kick|# Kicks} {:💚}',
        ],
        serio: [
          'Thank you for {kicks|# Kick|# Kicks}, sent anonymously.',
          '{kicks|# Kick|# Kicks} received anonymously. Thank you.',
          'Thanks to whoever gifted {kicks|# Kick|# Kicks}.',
          'An anonymous gift: {kicks|# Kick|# Kicks}. Thank you.',
          'I appreciate it: {kicks|# Kick|# Kicks}, anonymously. Thank you.',
          'Thank you for the anonymous support with {kicks|# Kick|# Kicks}.',
        ],
      },
      es: {
        scherzoso: [
          '¡Alguien de incógnito ha regalado {kicks|# Kick|# Kicks}! Seas quien seas, gracias {:🕵️}',
          '¡{kicks|# Kick|# Kicks} de alguien que no firma! La trama se complica {:🎭}',
          'Kicks sin nombre: ¡{kicks}! Un ninja generoso anda por el chat {:🥷}',
          'Regalo misterioso: ¡{kicks|# Kick|# Kicks}! Gracias, mano invisible {:👻}',
          '{kicks|# Kick|# Kicks} llegados de la nada. El fantasma más amable de Kick {:💚}',
          '¿Quién será? {kicks|# Kick|# Kicks} en anónimo, y un gracias gigante {:🎁}',
        ],
        amichevole: [
          'Gracias a quien ha regalado {kicks|# Kick|# Kicks} en anónimo {:💚}',
          '{kicks|# Kick|# Kicks} en anónimo: mil gracias, seas quien seas {:🙏}',
          'Qué gesto tan bonito, {kicks|# Kick|# Kicks} sin firma. Gracias {:😊}',
          'Muchas gracias por {kicks|# Kick|# Kicks}, aunque no sé quién eres {:🤗}',
          'Un regalo anónimo de {kicks|# Kick|# Kicks}: gracias de verdad {:🙌}',
          'Seas quien seas, gracias por {kicks|# Kick|# Kicks} {:💚}',
        ],
        serio: [
          'Gracias por {kicks|# Kick|# Kicks} en anónimo.',
          '{kicks|# Kick|# Kicks} recibidos en anónimo. Gracias.',
          'Gracias a quien ha regalado {kicks|# Kick|# Kicks}.',
          'Un regalo anónimo: {kicks|# Kick|# Kicks}. Gracias.',
          'Valoro el gesto: {kicks|# Kick|# Kicks} en anónimo. Gracias.',
          'Gracias por el apoyo anónimo con {kicks|# Kick|# Kicks}.',
        ],
      },
    },
  },
  shoutout: {
    titolo: ['Lo shoutout', 'The shoutout', 'El shoutout'],
    quando: ['Quando lo staff fa !so e lo shoutout ufficiale di Twitch è partito.', 'When staff types !so and the official Twitch shoutout went through.', 'Cuando el staff usa !so y el shoutout oficial de Twitch salió.'],
    dati: { nome: 'sempre', link: 'sempre', gioco: 'a volte' },
    esempio: { nome: 'Kiro', link: 'twitch.tv/kiro', gioco: 'Minecraft' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Andate a seguire @{nome}, fidatevi di me: {link} {:📣}',
          'Shoutout a @{nome}! Un canale che merita, parola mia {link} {:😎}',
          'Grande @{nome}! Passate a lasciare un follow, non ve ne pentirete {link} {:🔥}',
          'Tutti da @{nome}, e dite che vi mando io {link} {:😏}',
          'Consiglio del giorno: seguire @{nome}. Fatelo ora, ringrazierete dopo {link} {:✨}',
          '@{nome} è gente di qualità, andate a dare un\'occhiata {link} {:👀}',
          'Shoutout a @{nome}, che stava giocando a {gioco}! Andate a curiosare {link} {:🎮}',
        ],
        amichevole: [
          'Un saluto speciale a @{nome}! Passate dal suo canale: {link} {:💜}',
          'Vi consiglio con il cuore il canale di @{nome}: {link} {:🤗}',
          'Shoutout a @{nome}! Lasciate un follow, se lo merita {link} {:😊}',
          'Fate un salto da @{nome}, è un bel posto: {link} {:💜}',
          'Tanto affetto per @{nome}! Andate a seguire {link} {:🙌}',
          'Conoscete @{nome}? Se no, è il momento giusto: {link} {:😊}',
          'Andate da @{nome}, che stava giocando a {gioco}: {link} {:💜}',
        ],
        serio: [
          'Vi consiglio il canale di @{nome}: {link}',
          'Shoutout a @{nome}. Il canale è qui: {link}',
          'Un canale che merita: @{nome}. {link}',
          'Andate a seguire @{nome}: {link}',
          'Vi segnalo @{nome}. Trovate il canale qui: {link}',
          'Shoutout ufficiale per @{nome}: {link}',
          'Shoutout a @{nome}, l\'ultimo gioco era {gioco}: {link}',
        ],
      },
      en: {
        scherzoso: [
          'Go follow @{nome}, trust me on this one: {link} {:📣}',
          'Shoutout to @{nome}! A channel worth it, you have my word {link} {:😎}',
          'Big love to @{nome}! Go drop a follow, you won\'t regret it {link} {:🔥}',
          'Everyone go to @{nome}, and tell them I sent you {link} {:😏}',
          'Tip of the day: follow @{nome}. Do it now, thank me later {link} {:✨}',
          '@{nome} is quality people, go take a look {link} {:👀}',
          'Shoutout to @{nome}, who was playing {gioco}! Go check them out {link} {:🎮}',
        ],
        amichevole: [
          'A special hello to @{nome}! Stop by their channel: {link} {:💜}',
          'I wholeheartedly recommend @{nome}\'s channel: {link} {:🤗}',
          'Shoutout to @{nome}! Leave a follow, they deserve it {link} {:😊}',
          'Pop over to @{nome}, it\'s a lovely place: {link} {:💜}',
          'So much love for @{nome}! Go follow {link} {:🙌}',
          'Do you know @{nome}? If not, now\'s the time: {link} {:😊}',
          'Go visit @{nome}, who was playing {gioco}: {link} {:💜}',
        ],
        serio: [
          'I recommend @{nome}\'s channel: {link}',
          'Shoutout to @{nome}. The channel is here: {link}',
          'A channel worth your time: @{nome}. {link}',
          'Go follow @{nome}: {link}',
          'Worth checking out: @{nome}. Find the channel here: {link}',
          'Official shoutout for @{nome}: {link}',
          'Shoutout to @{nome}, last seen playing {gioco}: {link}',
        ],
      },
      es: {
        scherzoso: [
          'Vayan a seguir a @{nome}, háganme caso: {link} {:📣}',
          '¡Shoutout para @{nome}! Un canal que vale la pena, palabra {link} {:😎}',
          '¡Mucho amor para @{nome}! Dejen su follow, no se van a arrepentir {link} {:🔥}',
          'Todos a ver a @{nome}, y digan que van de mi parte {link} {:😏}',
          'Consejo del día: seguir a @{nome}. Háganlo ya, me lo agradecerán después {link} {:✨}',
          '@{nome} es gente de calidad, vayan a echar un vistazo {link} {:👀}',
          '¡Shoutout para @{nome}, que estaba jugando {gioco}! Vayan a curiosear {link} {:🎮}',
        ],
        amichevole: [
          '¡Un saludo especial a @{nome}! Pasen por su canal: {link} {:💜}',
          'Les recomiendo de corazón el canal de @{nome}: {link} {:🤗}',
          '¡Shoutout para @{nome}! Dejen un follow, se lo merece {link} {:😊}',
          'Den una vuelta por el canal de @{nome}, es un lugar muy bonito: {link} {:💜}',
          '¡Mucho cariño para @{nome}! Vayan a seguir {link} {:🙌}',
          '¿Conocen a @{nome}? Si no, es el momento: {link} {:😊}',
          'Pasen a ver a @{nome}, que estaba jugando {gioco}: {link} {:💜}',
        ],
        serio: [
          'Les recomiendo el canal de @{nome}: {link}',
          'Shoutout para @{nome}. El canal está aquí: {link}',
          'Un canal que vale la pena: @{nome}. {link}',
          'Vayan a seguir a @{nome}: {link}',
          'Les presento a @{nome}. Encuentran el canal aquí: {link}',
          'Shoutout oficial para @{nome}: {link}',
          'Shoutout para @{nome}, su último juego fue {gioco}: {link}',
        ],
      },
    },
  },

  riscatto: {
    titolo: ['Un premio a punti canale', 'A channel points reward', 'Un premio de puntos del canal'],
    quando: ['Quando qualcuno riscatta un premio a punti canale.', 'When someone redeems a channel points reward.', 'Cuando alguien canjea un premio de puntos del canal.'],
    dati: { nome: 'sempre', premio: 'sempre' },
    esempio: { nome: 'Luna', premio: 'Idratati' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          '{nome} ha riscattato «{premio}»! Punti spesi con saggezza {:😄}',
          'Riscatto in arrivo: «{premio}» per {nome}! {:🎁}',
          '{nome} si prende «{premio}», e la chat trattiene il fiato {:😮}',
          'Premio «{premio}» per {nome}! I punti canale girano che è un piacere {:💫}',
          '{nome} sblocca «{premio}». Scelta audace {:😎}',
          'Din don! {nome} ha speso i suoi punti per «{premio}» {:🔔}',
        ],
        amichevole: [
          '{nome} ha riscattato «{premio}», grazie per giocare con noi {:💜}',
          'Che bello, {nome} ha scelto «{premio}» {:😊}',
          'Grazie {nome}! «{premio}» arriva subito {:🤗}',
          '{nome} ha usato i punti canale per «{premio}», grazie {:🙌}',
          'Ecco «{premio}» per {nome}! Grazie di partecipare {:💜}',
          'Riscatto di {nome}: «{premio}». Grazie {:😊}',
        ],
        serio: [
          '{nome} ha riscattato «{premio}».',
          'Riscatto ricevuto da {nome}: «{premio}».',
          'Premio «{premio}» riscattato da {nome}.',
          '{nome} ha usato i punti canale per «{premio}».',
          'Nuovo riscatto: «{premio}», da {nome}.',
          'Riscattato «{premio}». Grazie, {nome}.',
        ],
      },
      en: {
        scherzoso: [
          '{nome} redeemed “{premio}”! Points well spent {:😄}',
          'Redemption incoming: “{premio}” for {nome}! {:🎁}',
          '{nome} goes for “{premio}”, and chat holds its breath {:😮}',
          'One “{premio}” for {nome}! Channel points are flying {:💫}',
          '{nome} unlocks “{premio}”. Bold choice {:😎}',
          'Ding! {nome} spent their points on “{premio}” {:🔔}',
        ],
        amichevole: [
          '{nome} redeemed “{premio}”, thanks for playing along {:💜}',
          'How fun, {nome} picked “{premio}” {:😊}',
          'Thanks, {nome}! “{premio}” coming right up {:🤗}',
          '{nome} used channel points for “{premio}”, thank you {:🙌}',
          'One “{premio}” for {nome}! Thanks for joining in {:💜}',
          'Redemption from {nome}: “{premio}”. Thank you {:😊}',
        ],
        serio: [
          '{nome} redeemed “{premio}”.',
          'Redemption received from {nome}: “{premio}”.',
          'Reward “{premio}” redeemed by {nome}.',
          '{nome} used channel points for “{premio}”.',
          'New redemption: “{premio}”, from {nome}.',
          '“{premio}” redeemed. Thank you, {nome}.',
        ],
      },
      es: {
        scherzoso: [
          '¡{nome} canjeó «{premio}»! Puntos bien gastados {:😄}',
          'Canje en camino: ¡«{premio}» para {nome}! {:🎁}',
          '{nome} va por «{premio}», y el chat contiene la respiración {:😮}',
          '¡Premio «{premio}» para {nome}! Los puntos del canal vuelan {:💫}',
          '{nome} desbloquea «{premio}». Qué valentía {:😎}',
          '¡Ding! {nome} gastó sus puntos en «{premio}» {:🔔}',
        ],
        amichevole: [
          '{nome} canjeó «{premio}», gracias por jugar con nosotros {:💜}',
          'Qué divertido, {nome} eligió «{premio}» {:😊}',
          '¡Gracias, {nome}! «{premio}» enseguida {:🤗}',
          '{nome} usó puntos del canal para «{premio}», gracias {:🙌}',
          '¡Aquí está «{premio}» para {nome}! Gracias por participar {:💜}',
          'Canje de {nome}: «{premio}». Gracias {:😊}',
        ],
        serio: [
          '{nome} canjeó «{premio}».',
          'Canje recibido de {nome}: «{premio}».',
          'Recompensa «{premio}» canjeada por {nome}.',
          '{nome} usó puntos del canal para «{premio}».',
          'Nuevo canje: «{premio}», de {nome}.',
          '«{premio}» canjeado. Gracias, {nome}.',
        ],
      },
    },
  },
};
