// © 2024–2026 Andrea Taliento (ANDRYXify) — Tutti i diritti riservati — socialbot.live
// Proprietà intellettuale · ANDRYX-IP::a7f39c1e8b424d90-4f7b-taliento::socialbot.live
//
// IL FRASARIO: LA DIRETTA. Quello che il bot dice da solo attorno alla diretta:
// quando parte e quando finisce, la pubblicita', l'hype train, il promemoria
// dei link, il raid verso un altro canale.
//
// Come si scrive una frase (vale per tutto il frasario, docs/VOCE.md):
//  · parla lo streamer, in prima persona, e non dichiara un genere: «eccomi»,
//    non «sono tornato»;
//  · niente ora del giorno («stasera»): una diretta puo' essere a mezzogiorno;
//  · un numero porta singolare e plurale, {quanti|una sub|# sub}, e nessun
//    articolo davanti («i 8 bit» non esiste);
//  · la faccina in fondo si scrive {:💜}: se la chat ha un'emote allegra, esce
//    quella;
//  · {community} sta solo in frasi in piu': le sei di ogni lingua e tono
//    devono stare in piedi senza.

const NUMERI_PUBBLICITA = { secondi: 'a volte', durata: 'a volte', canale: 'sempre' };

export const GRUPPO = { id: 'diretta', titolo: ['La diretta', 'The stream', 'El stream'] };

export const MOMENTI = {
  'inizio-diretta': {
    titolo: ['La diretta parte', 'The stream starts', 'Empieza el stream'],
    quando: ['Quando vai in onda su Twitch.', 'When you go live on Twitch.', 'Cuando sales en vivo en Twitch.'],
    dati: {},
    esempio: {},
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Si parte! Mettetevi comodi e tenete le mani lontane dai popcorn altrui {:🍿}',
          'Siamo in onda! Chi c\'è batta un colpo in chat {:👋}',
          'Luci accese, microfono acceso, caffè quasi finito: si comincia {:☕}',
          'Diretta partita! Avvisate gli amici, i parenti e pure il gatto {:📣}',
          'Semaforo verde, si comincia! Allacciate le cinture {:🚦}',
          'La live è partita e io sono già in ritardo su tutto {:😅}',
          'Eccoci in onda. Oggi niente scuse, solo divertimento {:🔥}',
          'Si parte, {community}! Fatevi sentire in chat {:🔥}',
        ],
        amichevole: [
          'Si comincia! Che bello ritrovarvi qui {:💜}',
          'Siamo in diretta, mettetevi comodi e salutate pure in chat {:😊}',
          'Ciao a tutti, la live è partita! Com\'è andata la vostra giornata?',
          'Eccoci in onda! Grazie a chi è già arrivato {:🙌}',
          'La diretta è iniziata: prendete qualcosa da bere e fate come a casa vostra {:☕}',
          'Si parte! Scrivete un saluto, mi fa sempre piacere leggervi {:💜}',
          'Eccoci, {community}! Che bello ritrovarvi {:💜}',
        ],
        serio: [
          'La diretta è iniziata.',
          'Siamo in onda. Buona visione.',
          'Si comincia. Grazie a chi è già qui.',
          'Diretta avviata: benvenuti in chat.',
          'Siamo live. Per le domande, scrivete pure in chat.',
          'Iniziamo. Mettetevi comodi.',
          'Si comincia, {community}.',
        ],
      },
      en: {
        scherzoso: [
          'We\'re live! Grab your snacks and keep your hands off everyone else\'s {:🍿}',
          'And we\'re on! Say something in chat so I know I\'m not talking to myself {:👋}',
          'Lights on, mic on, coffee almost gone. Let\'s go {:☕}',
          'Stream\'s up! Tell your friends, your family and your cat {:📣}',
          'Green light, we\'re rolling! Buckle up {:🚦}',
          'We\'re live and I\'m already behind on everything {:😅}',
          'Showtime! No excuses today, just good times {:🔥}',
          'Let\'s go, {community}! Make some noise in chat {:🔥}',
        ],
        amichevole: [
          'We\'re live! So good to see you all here {:💜}',
          'Stream\'s starting, get comfy and say hi in chat {:😊}',
          'Hey everyone, we\'re live! How\'s your day going?',
          'And we\'re on! Thanks to everyone who\'s already here {:🙌}',
          'We just went live: grab a drink and make yourselves at home {:☕}',
          'Here we go! Drop a hello in chat, I love reading you {:💜}',
          'Hey {community}, we\'re live! Missed you {:💜}',
        ],
        serio: [
          'The stream has started.',
          'We\'re live. Enjoy the stream.',
          'Starting now. Thanks to everyone already here.',
          'Stream is live. Welcome to the chat.',
          'We\'re on air. Questions are welcome in chat.',
          'Let\'s begin. Make yourselves comfortable.',
          'We\'re live, {community}.',
        ],
      },
      es: {
        scherzoso: [
          '¡Arrancamos! Pónganse cómodos y no toquen las palomitas ajenas {:🍿}',
          '¡Estamos en vivo! Quien esté ahí, que dé señales de vida en el chat {:👋}',
          'Luces encendidas, micro encendido, café casi terminado: empezamos {:☕}',
          '¡Stream en marcha! Avisen a sus amigos, a su familia y al gato {:📣}',
          '¡Luz verde, arrancamos! Abróchense los cinturones {:🚦}',
          'Empezó el stream y yo ya voy tarde con todo {:😅}',
          '¡Empezamos! Hoy nada de excusas, solo diversión {:🔥}',
          '¡Arrancamos, {community}! Hagan ruido en el chat {:🔥}',
        ],
        amichevole: [
          '¡Estamos en vivo! Qué alegría verlos por aquí {:💜}',
          'Empieza el stream, pónganse cómodos y saluden en el chat {:😊}',
          '¡Hola a todos, ya estamos en vivo! ¿Cómo les va el día?',
          '¡Aquí estamos! Gracias a quienes ya llegaron {:🙌}',
          'Comenzó la transmisión: tomen algo y siéntanse como en casa {:☕}',
          '¡Empezamos! Dejen un saludo en el chat, me encanta leerlos {:💜}',
          '¡Hola, {community}! Ya estamos en vivo {:💜}',
        ],
        serio: [
          'La transmisión ha comenzado.',
          'Estamos en vivo. Disfruten el stream.',
          'Empezamos. Gracias a quienes ya están aquí.',
          'Transmisión en vivo. Bienvenidos al chat.',
          'Ya estamos al aire. Las preguntas, en el chat.',
          'Comenzamos. Pónganse cómodos.',
          'Estamos en vivo, {community}.',
        ],
      },
    },
  },

  'fine-diretta': {
    titolo: ['La diretta finisce', 'The stream ends', 'Termina el stream'],
    quando: ['Quando chiudi la diretta su Twitch.', 'When you end the stream on Twitch.', 'Cuando terminas el stream en Twitch.'],
    dati: {},
    esempio: {},
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Diretta finita! Grazie di esserci stati, ora andate a bere un bicchiere d\'acqua {:💧}',
          'Si spengono le luci. Grazie a tutti, alla prossima {:👋}',
          'Fine della live! Se vi siete divertiti, era tutto calcolato {:😎}',
          'Anche per oggi è andata. Grazie, siete stati una chat bellissima {:💜}',
          'Live chiusa! Nessun pixel è stato maltrattato durante questa diretta {:🎬}',
          'Ci si vede alla prossima! Nel frattempo, fate i bravi {:😇}',
          'La diretta è finita, ma i ricordi restano. E anche le clip {:🎞️}',
          'Grazie {community}, anche oggi è stato bello! Alla prossima {:💜}',
        ],
        amichevole: [
          'La live è finita, grazie di cuore a chi è passato {:💜}',
          'Per oggi è tutto! Grazie della compagnia, a presto {:🤗}',
          'Diretta conclusa. È stato bello passare questo tempo insieme {:😊}',
          'Si chiude qui! Grazie a tutti, abbiate cura di voi {:👋}',
          'Grazie per essere stati qui, ci vediamo alla prossima live {:💜}',
          'Fine della diretta. Grazie per ogni messaggio in chat {:🙏}',
          'Grazie, {community}! Alla prossima live {:💜}',
        ],
        serio: [
          'La diretta è terminata. Grazie per la visione.',
          'Fine della live. Grazie a tutti.',
          'Per oggi è tutto. Alla prossima.',
          'La diretta si chiude qui. Grazie per la presenza.',
          'Diretta conclusa. Ci vediamo la prossima volta.',
          'Chiudiamo qui. Grazie di aver seguito.',
          'Grazie, {community}. Alla prossima.',
        ],
      },
      en: {
        scherzoso: [
          'Stream\'s over! Thanks for hanging out, now go drink some water {:💧}',
          'Lights out. Thanks, everyone, see you next time {:👋}',
          'That\'s a wrap! If you had fun, that was the plan all along {:😎}',
          'Another one in the books. Thanks, you were an awesome chat {:💜}',
          'Stream ended! No pixels were harmed in the making of this stream {:🎬}',
          'See you next time! Until then, behave {:😇}',
          'The stream is over, but the memories live on. So do the clips {:🎞️}',
          'Thanks, {community}, that was fun! See you next time {:💜}',
        ],
        amichevole: [
          'Stream\'s over, thank you so much for stopping by {:💜}',
          'That\'s it for today! Thanks for the company, see you soon {:🤗}',
          'We\'re done for now. It was great spending this time together {:😊}',
          'Wrapping up here! Thanks, everyone, take care {:👋}',
          'Thanks for being here, see you on the next stream {:💜}',
          'Stream ended. Thanks for every message in chat {:🙏}',
          'Thank you, {community}! See you next stream {:💜}',
        ],
        serio: [
          'The stream has ended. Thanks for watching.',
          'End of stream. Thank you all.',
          'That\'s all for today. Until next time.',
          'The stream ends here. Thanks for being here.',
          'Stream over. See you next time.',
          'We\'re wrapping up. Thanks for following along.',
          'Thank you, {community}. Until next time.',
        ],
      },
      es: {
        scherzoso: [
          '¡Se acabó el stream! Gracias por estar, ahora vayan a tomar agua {:💧}',
          'Se apagan las luces. Gracias a todos, nos vemos en el próximo {:👋}',
          '¡Fin del stream! Si se divirtieron, todo era parte del plan {:😎}',
          'Otro stream para el recuerdo. Gracias, fueron un chat increíble {:💜}',
          '¡Stream terminado! Ningún píxel salió herido en esta transmisión {:🎬}',
          '¡Nos vemos en el próximo! Mientras tanto, pórtense bien {:😇}',
          'El stream terminó, pero los recuerdos quedan. Y los clips también {:🎞️}',
          '¡Gracias, {community}, fue genial! Nos vemos pronto {:💜}',
        ],
        amichevole: [
          'Terminó el stream, mil gracias a quienes pasaron {:💜}',
          '¡Eso es todo por hoy! Gracias por la compañía, hasta pronto {:🤗}',
          'Transmisión terminada. Fue muy bonito pasar este rato juntos {:😊}',
          '¡Cerramos aquí! Gracias a todos, cuídense {:👋}',
          'Gracias por estar aquí, nos vemos en el próximo stream {:💜}',
          'Fin de la transmisión. Gracias por cada mensaje en el chat {:🙏}',
          '¡Gracias, {community}! Nos vemos en el próximo stream {:💜}',
        ],
        serio: [
          'La transmisión ha terminado. Gracias por ver.',
          'Fin del stream. Gracias a todos.',
          'Eso es todo por hoy. Hasta la próxima.',
          'La transmisión termina aquí. Gracias por acompañarnos.',
          'Stream finalizado. Nos vemos la próxima vez.',
          'Cerramos aquí. Gracias por seguir la transmisión.',
          'Gracias, {community}. Hasta la próxima.',
        ],
      },
    },
  },

  'pubblicita-prima': {
    titolo: ['Prima della pubblicità', 'Before an ad break', 'Antes de la publicidad'],
    quando: ['Poco prima che parta una pausa pubblicitaria, con la pubblicità in chat accesa in Regia.', 'Shortly before an ad break, with ads in chat switched on in Control room.', 'Poco antes de una pausa publicitaria, con la publicidad en el chat activada en Realización.'],
    dati: NUMERI_PUBBLICITA,
    esempio: { secondi: 90, durata: '1:30', canale: 'Luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Tra poco arriva la pubblicità: momento perfetto per sgranchirsi le gambe {:🏃}',
          'Pubblicità in arrivo! Approfittatene per riempire il bicchiere {:🥤}',
          'Avviso ai naviganti: fra poco pubblicità. Non cambiate canale {:📺}',
          'Tra un attimo parte la pubblicità. Io non scappo, promesso {:🤞}',
          'Fra poco pausa pubblicitaria: stretching obbligatorio per tutti {:🙆}',
          'Occhio, sta per partire la pubblicità. Tenete il posto caldo {:🔥}',
          'Fra poco {secondi|un secondo|# secondi} di pubblicità: giusto il tempo di uno snack {:🍪}',
          'Tra poco pubblicità, {community}: non andate lontano {:👀}',
        ],
        amichevole: [
          'Fra poco parte la pubblicità: restate qui, torno subito {:💜}',
          'Tra un momento c\'è una pausa pubblicitaria, ci vediamo dall\'altra parte {:😊}',
          'Piccolo avviso: sta per arrivare la pubblicità. Grazie della pazienza {:🙏}',
          'Fra poco pubblicità: un attimo di pausa e ripartiamo {:☕}',
          'Sta per partire la pubblicità, non andate via {:🤗}',
          'Tra poco una breve pausa pubblicitaria. Aspettatemi qui {:💜}',
          'Fra poco {secondi|un secondo|# secondi} di pubblicità, poi si riparte {:😊}',
        ],
        serio: [
          'Tra poco inizia la pubblicità.',
          'Avviso: pausa pubblicitaria in arrivo.',
          'Fra poco parte la pubblicità. Si riprende subito dopo.',
          'Pubblicità in arrivo a breve.',
          'Tra qualche istante ci sarà una pausa pubblicitaria.',
          'Breve pausa pubblicitaria in arrivo. Restate collegati.',
          'Tra poco {secondi|un secondo|# secondi} di pubblicità.',
        ],
      },
      en: {
        scherzoso: [
          'Ad break coming up: perfect time for a quick stretch {:🙆}',
          'Ads incoming! Go refill your drink {:🥤}',
          'Heads up: ads in a moment. Don\'t touch that dial {:📺}',
          'Ads are about to roll. I\'m not going anywhere, promise {:🤞}',
          'Ad break soon: mandatory leg stretch for everyone {:🏃}',
          'Careful, ads are about to start. Keep my seat warm {:🔥}',
          'Ads in a moment: {secondi|one second|# seconds}, just enough for a snack {:🍪}',
          'Ads coming up, {community}: don\'t go too far {:👀}',
        ],
        amichevole: [
          'An ad break is starting soon: stick around, I\'ll be right back {:💜}',
          'Quick ad break in a moment, see you on the other side {:😊}',
          'Just a heads-up: ads are coming up. Thanks for your patience {:🙏}',
          'Ads in a moment: short pause and then we\'re back {:☕}',
          'The ads are about to start, don\'t go anywhere {:🤗}',
          'Short ad break coming up. Wait for me here {:💜}',
          '{secondi|One second|# seconds} of ads coming up, then we\'re back {:😊}',
        ],
        serio: [
          'An ad break will start shortly.',
          'Notice: ad break coming up.',
          'Ads will start soon. We\'ll resume right after.',
          'Ad break coming up shortly.',
          'There will be a short ad break in a moment.',
          'Short ad break ahead. Stay tuned.',
          'Ads starting soon: {secondi|one second|# seconds}.',
        ],
      },
      es: {
        scherzoso: [
          'Se viene la publicidad: momento perfecto para estirarse {:🙆}',
          '¡Publicidad en camino! Vayan a rellenar el vaso {:🥤}',
          'Atención: en un momento hay publicidad. No cambien de canal {:📺}',
          'Ya casi empieza la publicidad. Yo no me voy, lo prometo {:🤞}',
          'Pausa publicitaria en breve: estirar las piernas es obligatorio {:🏃}',
          'Ojo, que está por empezar la publicidad. Guárdenme el lugar {:🔥}',
          'En un rato, {secondi|un segundo|# segundos} de publicidad: justo para un snack {:🍪}',
          'Se viene la publicidad, {community}: no se vayan lejos {:👀}',
        ],
        amichevole: [
          'En breve empieza la publicidad: quédense, vuelvo enseguida {:💜}',
          'En un momento hay una pausa publicitaria, nos vemos del otro lado {:😊}',
          'Aviso rápido: se viene la publicidad. Gracias por la paciencia {:🙏}',
          'Publicidad en un momento: una pausa corta y seguimos {:☕}',
          'Está por empezar la publicidad, no se vayan {:🤗}',
          'En breve, una pausa publicitaria corta. Espérenme aquí {:💜}',
          'Se vienen {secondi|un segundo|# segundos} de publicidad y seguimos {:😊}',
        ],
        serio: [
          'En breve comenzará la publicidad.',
          'Aviso: pausa publicitaria en camino.',
          'La publicidad empieza pronto. Continuamos justo después.',
          'Pausa publicitaria en breve.',
          'En unos instantes habrá una pausa publicitaria.',
          'Se aproxima una breve pausa publicitaria. Sigan conectados.',
          'En breve, {secondi|un segundo|# segundos} de publicidad.',
        ],
      },
    },
  },

  'pubblicita-parte': {
    titolo: ['La pubblicità parte', 'The ad break starts', 'Empieza la publicidad'],
    quando: ['Quando Twitch fa partire una pausa pubblicitaria, con la pubblicità in chat accesa in Regia.', 'When Twitch starts an ad break, with ads in chat switched on in Control room.', 'Cuando Twitch empieza una pausa publicitaria, con la publicidad en el chat activada en Realización.'],
    dati: NUMERI_PUBBLICITA,
    esempio: { secondi: 90, durata: '1:30', canale: 'Luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Pubblicità partita! Fate finta che sia l\'intervallo al cinema {:🎬}',
          'Via con la pubblicità. Io intanto mi sgranchisco le dita {:🙌}',
          'Ecco la pubblicità: non è colpa mia, giuro {:😇}',
          'Parte la pubblicità! Chi torna per primo vince la mia stima eterna {:🏆}',
          'Pubblicità in corso: tenete duro, ci rivediamo tra poco {:💪}',
          'Momento pubblicità! Nessuno si muova... anzi sì, andate a prendere l\'acqua {:💧}',
          '{secondi|Un secondo|# secondi} di pubblicità: ce la potete fare {:💪}',
          'Pubblicità partita, {community}! Resistete, torno subito {:🙏}',
        ],
        amichevole: [
          'Parte la pubblicità: non andate via, ci vediamo fra poco {:💜}',
          'È iniziata la pausa pubblicitaria. Grazie di aspettarmi {:🙏}',
          'Pubblicità in corso, torno tra un attimo {:😊}',
          'Ecco la pubblicità: approfittatene per una pausa, ci vediamo subito dopo {:☕}',
          'Pausa pubblicitaria iniziata. Restate qui con me {:🤗}',
          'La pubblicità è partita, grazie della pazienza {:💜}',
          'Pubblicità per {secondi|un secondo|# secondi}. Non andate via, ci vediamo fra poco {:💜}',
        ],
        serio: [
          'Pausa pubblicitaria in corso.',
          'È iniziata la pubblicità. Si riprende a breve.',
          'Pubblicità in corso. Grazie per l\'attesa.',
          'Pausa pubblicitaria iniziata.',
          'In pausa per la pubblicità. Torniamo subito.',
          'Pubblicità avviata. A tra poco.',
          'Pubblicità in corso per {secondi|un secondo|# secondi}.',
          'Pausa pubblicitaria di {durata}.',
        ],
      },
      en: {
        scherzoso: [
          'Ads are rolling! Pretend it\'s intermission at the movies {:🎬}',
          'Here come the ads. I\'ll just stretch my fingers meanwhile {:🙌}',
          'Ad time: not my fault, I swear {:😇}',
          'Ads started! First one back wins my eternal respect {:🏆}',
          'Ads in progress: hang in there, see you in a bit {:💪}',
          'Ad break! Nobody move... actually, yes, go grab some water {:💧}',
          '{secondi|One second|# seconds} of ads: you can do this {:💪}',
          'Ads are on, {community}! Hang tight, I\'ll be right back {:🙏}',
        ],
        amichevole: [
          'Ads are on: don\'t go anywhere, see you in a bit {:💜}',
          'The ad break just started. Thanks for waiting for me {:🙏}',
          'Ads running, I\'ll be right back {:😊}',
          'Here are the ads: take a little break, see you right after {:☕}',
          'Ad break started. Stay here with me {:🤗}',
          'The ads started, thanks for your patience {:💜}',
          'Ads for {secondi|one second|# seconds}. Don\'t leave, see you soon {:💜}',
        ],
        serio: [
          'Ad break in progress.',
          'The ads have started. We\'ll resume shortly.',
          'Ads running. Thanks for waiting.',
          'Ad break started.',
          'Paused for ads. Back shortly.',
          'Ads are on. See you in a moment.',
          'Ad break in progress: {secondi|one second|# seconds}.',
          'Ad break lasting {durata}.',
        ],
      },
      es: {
        scherzoso: [
          '¡Arrancó la publicidad! Imaginen que es el intermedio del cine {:🎬}',
          'Aquí viene la publicidad. Yo mientras tanto estiro los dedos {:🙌}',
          'Hora de publicidad: no es culpa mía, lo juro {:😇}',
          '¡Empezó la publicidad! Quien vuelva primero se gana mi respeto eterno {:🏆}',
          'Publicidad en curso: aguanten, nos vemos en un rato {:💪}',
          '¡Pausa publicitaria! Que nadie se mueva... bueno, sí, vayan por agua {:💧}',
          '{secondi|Un segundo|# segundos} de publicidad: ustedes pueden {:💪}',
          '¡Arrancó la publicidad, {community}! Aguanten, vuelvo enseguida {:🙏}',
        ],
        amichevole: [
          'Empezó la publicidad: no se vayan, nos vemos en un rato {:💜}',
          'Comenzó la pausa publicitaria. Gracias por esperarme {:🙏}',
          'Publicidad en curso, vuelvo en un momento {:😊}',
          'Aquí está la publicidad: aprovechen para descansar, nos vemos justo después {:☕}',
          'Pausa publicitaria en marcha. Quédense aquí conmigo {:🤗}',
          'Arrancó la publicidad, gracias por la paciencia {:💜}',
          'Publicidad por {secondi|un segundo|# segundos}. No se vayan, ya vuelvo {:💜}',
        ],
        serio: [
          'Pausa publicitaria en curso.',
          'Comenzó la publicidad. Continuamos en breve.',
          'Publicidad en curso. Gracias por esperar.',
          'Pausa publicitaria iniciada.',
          'En pausa por publicidad. Volvemos enseguida.',
          'Publicidad activa. Hasta dentro de un momento.',
          'Publicidad en curso: {secondi|un segundo|# segundos}.',
          'Pausa publicitaria de {durata}.',
        ],
      },
    },
  },

  'pubblicita-dopo': {
    titolo: ['Dopo la pubblicità', 'After the ad break', 'Después de la publicidad'],
    quando: ['Quando la pausa pubblicitaria è finita, con la pubblicità in chat accesa in Regia.', 'When the ad break is over, with ads in chat switched on in Control room.', 'Cuando termina la pausa publicitaria, con la publicidad en el chat activada en Realización.'],
    dati: NUMERI_PUBBLICITA,
    esempio: { secondi: 90, durata: '1:30', canale: 'Luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Eccomi! La pubblicità è finita e io sono ancora qui {:😎}',
          'Fine della pubblicità! Ditemi che non siete scappati {:👀}',
          'Riecco la diretta! Ammettetelo, vi è mancata {:😅}',
          'Pubblicità finita, si riparte! Chi c\'è ancora? {:🙋}',
          'E siamo di nuovo in onda, con ancora più energia {:⚡}',
          'Fine della pausa! Rimettete giù i popcorn, si ricomincia {:🍿}',
          'Eccoci di nuovo, {community}! Si riparte {:🔥}',
        ],
        amichevole: [
          'Eccomi di nuovo! Grazie di aver aspettato {:💜}',
          'La pubblicità è finita, si riparte {:😊}',
          'Rieccoci! Grazie per essere rimasti {:🙏}',
          'Fine della pausa, torniamo a noi {:🤗}',
          'Ci sono di nuovo! Com\'è andata la pausa? {:☕}',
          'Si ricomincia! Grazie della pazienza {:💜}',
          'Rieccoci, {community}! Grazie di aver aspettato {:💜}',
        ],
        serio: [
          'La pausa pubblicitaria è terminata.',
          'Si riprende. Grazie per l\'attesa.',
          'Pubblicità finita, torniamo alla diretta.',
          'Di nuovo in onda.',
          'Fine della pubblicità. Riprendiamo.',
          'Rieccoci. Continuiamo da dove eravamo.',
          'Si riprende, {community}.',
        ],
      },
      en: {
        scherzoso: [
          'I\'m back! The ads are over and I\'m still here {:😎}',
          'Ads are done! Tell me you didn\'t run away {:👀}',
          'The stream is back! Admit it, you missed it {:😅}',
          'Ads over, let\'s get going! Who\'s still here? {:🙋}',
          'And we\'re back on air, with even more energy {:⚡}',
          'Break\'s over! Put the popcorn down, we\'re back {:🍿}',
          'We\'re back, {community}! Let\'s go {:🔥}',
        ],
        amichevole: [
          'I\'m back! Thanks for waiting {:💜}',
          'The ads are over, here we go again {:😊}',
          'We\'re back! Thanks for sticking around {:🙏}',
          'Break\'s over, back to us {:🤗}',
          'Back again! How was the break? {:☕}',
          'Here we go again! Thanks for your patience {:💜}',
          'We\'re back, {community}! Thanks for waiting {:💜}',
        ],
        serio: [
          'The ad break has ended.',
          'Resuming now. Thanks for waiting.',
          'Ads are over, back to the stream.',
          'Back on air.',
          'End of the ad break. Let\'s continue.',
          'We\'re back. Picking up where we left off.',
          'Resuming, {community}.',
        ],
      },
      es: {
        scherzoso: [
          '¡Aquí estoy! Terminó la publicidad y sigo en pie {:😎}',
          '¡Se acabó la publicidad! Díganme que no se escaparon {:👀}',
          '¡Volvió el stream! Admítanlo, lo extrañaron {:😅}',
          '¡Fin de la publicidad, seguimos! ¿Quién sigue por aquí? {:🙋}',
          'Y volvemos al aire, con más energía que antes {:⚡}',
          '¡Terminó la pausa! Suelten las palomitas, que seguimos {:🍿}',
          '¡Volvimos, {community}! Seguimos {:🔥}',
        ],
        amichevole: [
          '¡Ya volví! Gracias por esperar {:💜}',
          'Terminó la publicidad, seguimos {:😊}',
          '¡Aquí estamos de nuevo! Gracias por quedarse {:🙏}',
          'Se acabó la pausa, volvemos a lo nuestro {:🤗}',
          '¡De vuelta! ¿Qué tal la pausa? {:☕}',
          '¡Seguimos! Gracias por la paciencia {:💜}',
          '¡Volvimos, {community}! Gracias por esperar {:💜}',
        ],
        serio: [
          'La pausa publicitaria ha terminado.',
          'Continuamos. Gracias por esperar.',
          'Terminó la publicidad, volvemos al stream.',
          'De nuevo al aire.',
          'Fin de la pausa publicitaria. Seguimos.',
          'Volvemos. Seguimos donde lo dejamos.',
          'Continuamos, {community}.',
        ],
      },
    },
  },

  'treno-parte': {
    titolo: ['L’hype train parte', 'The hype train starts', 'Arranca el hype train'],
    quando: ['Quando parte un hype train, con «Dillo in chat» acceso nel suo riquadro.', 'When a hype train starts, with “Say it in chat” on in its box.', 'Cuando arranca un hype train, con «Dilo en el chat» activado en su recuadro.'],
    dati: { livello: 'sempre', punti: 'sempre', prossimo: 'sempre', manca: 'sempre', chi: 'a volte' },
    esempio: { livello: 1, punti: 320, prossimo: 2, manca: 180, chi: 'Luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Hype train partito! Tutti a bordo, si parte {:🚂}',
          'Ciuf ciuf! L\'hype train è in stazione, saliamo {:🚂}',
          'È partito l\'hype train! Chi spinge di più si prende la mia gratitudine eterna {:🔥}',
          'Hype train in partenza! Biglietti in mano, si va {:🎟️}',
          'Il treno dell\'hype è partito e non ha i freni {:🚀}',
          'Hype train avviato! Vediamo fin dove arriviamo stavolta {:🔥}',
          'Hype train partito, {community}! Spingiamo {:🚂}',
        ],
        amichevole: [
          'È partito l\'hype train! Grazie a chi l\'ha fatto partire {:💜}',
          'Hype train in corsa: ogni aiuto conta, grazie {:🙌}',
          'Che bello, è partito l\'hype train! Spingiamo insieme {:🚂}',
          'L\'hype train si è messo in moto, grazie a tutti {:😊}',
          'Hype train partito! Vediamo insieme dove arriva {:💜}',
          'Si parte con l\'hype train, grazie per il supporto {:🙏}',
          'Hype train partito, {community}! Grazie a tutti {:💜}',
        ],
        serio: [
          'È partito un hype train.',
          'Hype train avviato. Grazie a chi contribuisce.',
          'Hype train in corso, livello {livello}.',
          'Hype train iniziato. Grazie per il supporto.',
          'Parte l\'hype train.',
          'Hype train attivo. Ogni contributo conta.',
        ],
      },
      en: {
        scherzoso: [
          'Hype train is leaving the station! All aboard {:🚂}',
          'Choo choo! The hype train just pulled in, hop on {:🚂}',
          'Hype train started! Whoever pushes hardest gets my eternal gratitude {:🔥}',
          'Hype train departing! Tickets out, let\'s ride {:🎟️}',
          'The hype train has left and it has no brakes {:🚀}',
          'Hype train is rolling! Let\'s see how far we get this time {:🔥}',
          'Hype train started, {community}! Let\'s push {:🚂}',
        ],
        amichevole: [
          'The hype train just started! Thanks to whoever kicked it off {:💜}',
          'Hype train on the move: every bit of help counts, thank you {:🙌}',
          'Yay, the hype train started! Let\'s push together {:🚂}',
          'The hype train is rolling, thank you all {:😊}',
          'Hype train started! Let\'s see where it takes us together {:💜}',
          'Here comes the hype train, thanks for the support {:🙏}',
          'Hype train started, {community}! Thank you all {:💜}',
        ],
        serio: [
          'A hype train has started.',
          'Hype train started. Thanks to everyone contributing.',
          'Hype train in progress, level {livello}.',
          'Hype train underway. Thank you for the support.',
          'The hype train begins.',
          'Hype train active. Every contribution counts.',
        ],
      },
      es: {
        scherzoso: [
          '¡Arrancó el hype train! Todos a bordo {:🚂}',
          '¡Chu chu! El hype train llegó a la estación, súbanse {:🚂}',
          '¡Empezó el hype train! Quien empuje más se gana mi gratitud eterna {:🔥}',
          '¡Hype train saliendo! Boletos en mano, vámonos {:🎟️}',
          'El hype train ya salió y no tiene frenos {:🚀}',
          '¡Hype train en marcha! A ver hasta dónde llegamos esta vez {:🔥}',
          '¡Arrancó el hype train, {community}! A empujar {:🚂}',
        ],
        amichevole: [
          '¡Empezó el hype train! Gracias a quien lo puso en marcha {:💜}',
          'Hype train en camino: toda ayuda cuenta, gracias {:🙌}',
          '¡Qué bien, arrancó el hype train! Empujemos juntos {:🚂}',
          'El hype train está en marcha, gracias a todos {:😊}',
          '¡Hype train en marcha! Veamos juntos hasta dónde llega {:💜}',
          'Arranca el hype train, gracias por el apoyo {:🙏}',
          '¡Arrancó el hype train, {community}! Gracias a todos {:💜}',
        ],
        serio: [
          'Ha comenzado un hype train.',
          'Hype train iniciado. Gracias a quienes contribuyen.',
          'Hype train en curso, nivel {livello}.',
          'Hype train en marcha. Gracias por el apoyo.',
          'Comienza el hype train.',
          'Hype train activo. Cada aporte cuenta.',
        ],
      },
    },
  },

  'treno-livello': {
    titolo: ['L’hype train sale di livello', 'The hype train levels up', 'El hype train sube de nivel'],
    quando: ['Quando l’hype train arriva al livello dopo.', 'When the hype train reaches the next level.', 'Cuando el hype train llega al siguiente nivel.'],
    dati: { livello: 'sempre', punti: 'sempre', prossimo: 'sempre', manca: 'sempre', chi: 'a volte' },
    esempio: { livello: 3, punti: 2400, prossimo: 4, manca: 900, chi: 'Luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Hype train al livello {livello}! Qualcuno fermi questa locomotiva {:🚂}',
          'Livello {livello}! Il treno va più veloce di me il lunedì mattina {:😅}',
          'Siamo al livello {livello} dell\'hype train, pazzesco {:🔥}',
          'Livello {livello} raggiunto! Prossima fermata: la leggenda {:🏆}',
          'L\'hype train sale al livello {livello}, e non accenna a fermarsi {:🚀}',
          'Livello {livello}! Il capotreno ringrazia tutti {:🎩}',
        ],
        amichevole: [
          'Hype train al livello {livello}! Grazie a tutti {:💜}',
          'Siamo arrivati al livello {livello}, che bello {:😊}',
          'Livello {livello} dell\'hype train raggiunto, grazie davvero {:🙏}',
          'L\'hype train è al livello {livello}! Siete fantastici {:🙌}',
          'Livello {livello}! Grazie a chi sta spingendo {:💜}',
          'Nuovo livello: {livello}! Che squadra {:🤗}',
        ],
        serio: [
          'Hype train al livello {livello}.',
          'Raggiunto il livello {livello} dell\'hype train.',
          'L\'hype train sale al livello {livello}. Grazie.',
          'Si passa al livello {livello}. Grazie per il contributo.',
          'Hype train: livello {livello}.',
          'Nuovo livello dell\'hype train: {livello}.',
        ],
      },
      en: {
        scherzoso: [
          'Hype train at level {livello}! Somebody stop this locomotive {:🚂}',
          'Level {livello}! This train moves faster than me on a Monday morning {:😅}',
          'We\'re at level {livello} of the hype train, this is wild {:🔥}',
          'Level {livello} reached! Next stop: legend status {:🏆}',
          'The hype train climbs to level {livello} and shows no sign of stopping {:🚀}',
          'Level {livello}! The conductor thanks you all {:🎩}',
        ],
        amichevole: [
          'Hype train at level {livello}! Thank you all {:💜}',
          'We made it to level {livello}, how awesome {:😊}',
          'Level {livello} of the hype train reached, thank you so much {:🙏}',
          'The hype train is at level {livello}! You\'re amazing {:🙌}',
          'Level {livello}! Thanks to everyone pushing {:💜}',
          'New level: {livello}! What a team {:🤗}',
        ],
        serio: [
          'Hype train at level {livello}.',
          'Hype train level {livello} reached.',
          'The hype train rises to level {livello}. Thank you.',
          'Moving up to level {livello}. Thanks for contributing.',
          'Hype train: level {livello}.',
          'New hype train level: {livello}.',
        ],
      },
      es: {
        scherzoso: [
          '¡Hype train en nivel {livello}! Que alguien detenga esta locomotora {:🚂}',
          '¡Nivel {livello}! Este tren va más rápido que yo un lunes por la mañana {:😅}',
          'Vamos por el nivel {livello} del hype train, esto es una locura {:🔥}',
          '¡Nivel {livello} alcanzado! Próxima parada: la leyenda {:🏆}',
          'El hype train sube al nivel {livello} y no piensa frenar {:🚀}',
          '¡Nivel {livello}! El maquinista les da las gracias {:🎩}',
        ],
        amichevole: [
          '¡Hype train en nivel {livello}! Gracias a todos {:💜}',
          'Llegamos al nivel {livello}, qué alegría {:😊}',
          'Nivel {livello} del hype train alcanzado, muchísimas gracias {:🙏}',
          '¡El hype train está en nivel {livello}! Son increíbles {:🙌}',
          '¡Nivel {livello}! Gracias a quienes están empujando {:💜}',
          '¡Nuevo nivel: {livello}! Qué equipo {:🤗}',
        ],
        serio: [
          'Hype train en nivel {livello}.',
          'Alcanzado el nivel {livello} del hype train.',
          'El hype train sube al nivel {livello}. Gracias.',
          'Pasamos al nivel {livello}. Gracias por contribuir.',
          'Hype train: nivel {livello}.',
          'Nuevo nivel del hype train: {livello}.',
        ],
      },
    },
  },

  'treno-quasi': {
    titolo: ['Manca poco al livello', 'The next level is close', 'Falta poco para el nivel'],
    quando: ['Nell’ultimo quarto verso il livello dopo, una volta per livello.', 'In the last quarter toward the next level, once per level.', 'En el último cuarto hacia el siguiente nivel, una vez por nivel.'],
    dati: { livello: 'sempre', punti: 'sempre', prossimo: 'sempre', manca: 'sempre', chi: 'a volte' },
    esempio: { livello: 2, punti: 1500, prossimo: 3, manca: 120, chi: 'Luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Manca pochissimo al livello {prossimo}: {manca|un punto|# punti}! Forza {:💪}',
          'Il livello {prossimo} si vede dal finestrino! Ancora {manca|un punto|# punti} {:👀}',
          'Ultima spinta! Solo {manca|un punto|# punti} al livello {prossimo} {:🚂}',
          'Ci siamo quasi: {manca|un punto|# punti} e siamo al livello {prossimo} {:🔥}',
          'Livello {prossimo} a un passo: ancora {manca|un punto|# punti}, chi ci porta? {:🙋}',
          'Il treno sbuffa, il livello {prossimo} è lì: {manca|un punto|# punti} {:💨}',
        ],
        amichevole: [
          'Manca poco al livello {prossimo}: ancora {manca|un punto|# punti} {:💜}',
          'Siamo vicinissimi al livello {prossimo}: {manca|serve un punto|servono # punti} {:😊}',
          'Ancora {manca|un punto|# punti} e arriviamo al livello {prossimo}, dai {:🙌}',
          'Il livello {prossimo} è a un passo: {manca|manca un punto|mancano # punti} {:💜}',
          'Quasi al livello {prossimo}! Con {manca|un punto|# punti} ci siamo {:🤗}',
          'Un ultimo sforzo: {manca|un punto|# punti} per il livello {prossimo} {:🙏}',
        ],
        serio: [
          '{manca|Manca un punto|Mancano # punti} al livello {prossimo}.',
          'Livello {prossimo} vicino: {manca|manca un punto|mancano # punti}.',
          'Per il livello {prossimo} {manca|serve ancora un punto|servono ancora # punti}.',
          'Hype train: {manca|un punto|# punti} al livello {prossimo}.',
          'Il livello {prossimo} è vicino. Ancora {manca|un punto|# punti}.',
          'Quasi al livello {prossimo}: {manca|un punto rimasto|# punti rimasti}.',
        ],
      },
      en: {
        scherzoso: [
          'So close to level {prossimo}: {manca|one point|# points} to go! Come on {:💪}',
          'Level {prossimo} is right outside the window! Just {manca|one more point|# more points} {:👀}',
          'Final push! Only {manca|one point|# points} to level {prossimo} {:🚂}',
          'Almost there: {manca|one point|# points} and we hit level {prossimo} {:🔥}',
          'Level {prossimo} is one step away: {manca|one point|# points} left, who\'s taking us there? {:🙋}',
          'The train is huffing and puffing, level {prossimo} is right there: {manca|one point|# points} {:💨}',
        ],
        amichevole: [
          'Level {prossimo} is close: {manca|one more point|# more points} {:💜}',
          'We\'re so close to level {prossimo}: we need {manca|one point|# points} {:😊}',
          '{manca|One more point|# more points} and we reach level {prossimo}, let\'s go {:🙌}',
          'Level {prossimo} is just a step away: {manca|one point|# points} left {:💜}',
          'Almost at level {prossimo}! {manca|One point|# points} and we\'re there {:🤗}',
          'One last effort: {manca|one point|# points} for level {prossimo} {:🙏}',
        ],
        serio: [
          '{manca|One point|# points} left to level {prossimo}.',
          'Level {prossimo} is near: {manca|one point|# points} remaining.',
          'Level {prossimo} needs {manca|one more point|# more points}.',
          'Hype train: {manca|one point|# points} to level {prossimo}.',
          'Level {prossimo} is close. {manca|One point|# points} to go.',
          'Almost level {prossimo}: {manca|one point|# points} short.',
        ],
      },
      es: {
        scherzoso: [
          '¡Muy cerca del nivel {prossimo}: {manca|falta un punto|faltan # puntos}! Vamos {:💪}',
          '¡El nivel {prossimo} ya se ve por la ventanilla! Solo {manca|un punto|# puntos} más {:👀}',
          '¡Último empujón! Solo {manca|un punto|# puntos} para el nivel {prossimo} {:🚂}',
          'Ya casi: {manca|un punto|# puntos} y llegamos al nivel {prossimo} {:🔥}',
          'El nivel {prossimo} está a un paso: {manca|queda un punto|quedan # puntos}, ¿quién nos lleva? {:🙋}',
          'El tren resopla y el nivel {prossimo} está ahí: {manca|un punto|# puntos} {:💨}',
        ],
        amichevole: [
          'Falta poco para el nivel {prossimo}: {manca|un punto|# puntos} más {:💜}',
          'Estamos muy cerca del nivel {prossimo}: {manca|hace falta un punto|hacen falta # puntos} {:😊}',
          '{manca|Un punto|# puntos} más y llegamos al nivel {prossimo}, vamos {:🙌}',
          'El nivel {prossimo} está a un paso: {manca|falta un punto|faltan # puntos} {:💜}',
          '¡Casi en el nivel {prossimo}! Con {manca|un punto|# puntos} lo logramos {:🤗}',
          'Un último esfuerzo: {manca|un punto|# puntos} para el nivel {prossimo} {:🙏}',
        ],
        serio: [
          '{manca|Falta un punto|Faltan # puntos} para el nivel {prossimo}.',
          'Nivel {prossimo} cerca: {manca|queda un punto|quedan # puntos}.',
          'Para el nivel {prossimo} {manca|se necesita un punto más|se necesitan # puntos más}.',
          'Hype train: {manca|un punto|# puntos} para el nivel {prossimo}.',
          'El nivel {prossimo} está cerca. {manca|Un punto|# puntos} más.',
          'A punto del nivel {prossimo}: {manca|un punto|# puntos} de distancia.',
        ],
      },
    },
  },

  'treno-fine': {
    titolo: ['L’hype train finisce', 'The hype train ends', 'Termina el hype train'],
    quando: ['Quando l’hype train si chiude.', 'When the hype train ends.', 'Cuando el hype train termina.'],
    dati: { livello: 'sempre', punti: 'sempre', prossimo: 'sempre', manca: 'sempre', chi: 'a volte' },
    esempio: { livello: 4, punti: 5200, prossimo: 5, manca: 0, chi: 'Luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Hype train arrivato al capolinea: livello {livello}! Scendete con calma {:🚉}',
          'Fine corsa! Livello {livello} e zero feriti, grazie a tutti {:🚂}',
          'L\'hype train si ferma al livello {livello}. Che viaggio {:🔥}',
          'Treno finito al livello {livello}! Il capotreno si inchina {:🎩}',
          'Livello {livello} e il treno si ferma qui. Siete stati una forza {:💪}',
          'Capolinea al livello {livello}! La prossima volta si punta più in alto {:🚀}',
          'Hype train chiuso al livello {livello}! Menzione d\'onore per {chi} {:🏆}',
          'Livello {livello}, fine della corsa. Grazie {chi}, che spinta {:🔥}',
        ],
        amichevole: [
          'L\'hype train è finito al livello {livello}. Grazie di cuore a tutti {:💜}',
          'Siamo arrivati al livello {livello}, che bel viaggio insieme {:😊}',
          'Hype train concluso: livello {livello}! Grazie per il supporto {:🙏}',
          'Fine del treno al livello {livello}. Siete stati fantastici {:🤗}',
          'Livello {livello} raggiunto e treno in stazione. Grazie davvero {:💜}',
          'Il treno si è fermato al livello {livello}: grazie a chi ha spinto {:🙌}',
          'Hype train finito al livello {livello}. Un grazie speciale a {chi} {:💜}',
        ],
        serio: [
          'Hype train terminato al livello {livello}.',
          'L\'hype train si è concluso al livello {livello}. Grazie a tutti.',
          'Fine dell\'hype train: livello {livello}.',
          'Hype train chiuso al livello {livello}, con {punti|un punto|# punti}.',
          'Treno concluso al livello {livello}. Grazie per il contributo.',
          'L\'hype train si ferma al livello {livello}.',
          'Hype train terminato al livello {livello}. Grazie, {chi}.',
        ],
      },
      en: {
        scherzoso: [
          'The hype train reached the end of the line: level {livello}! Mind the gap {:🚉}',
          'Last stop! Level {livello} and zero injuries, thanks everyone {:🚂}',
          'The hype train stops at level {livello}. What a ride {:🔥}',
          'Train\'s done at level {livello}! The conductor takes a bow {:🎩}',
          'Level {livello} and the train stops here. You were a powerhouse {:💪}',
          'End of the line at level {livello}! Next time we aim higher {:🚀}',
          'Hype train wrapped at level {livello}! Honorable mention to {chi} {:🏆}',
          'Level {livello}, end of the ride. Thanks {chi}, what a push {:🔥}',
        ],
        amichevole: [
          'The hype train ended at level {livello}. Thank you all so much {:💜}',
          'We made it to level {livello}, what a lovely ride together {:😊}',
          'Hype train complete: level {livello}! Thanks for the support {:🙏}',
          'Train\'s over at level {livello}. You were amazing {:🤗}',
          'Level {livello} reached and the train is in the station. Thank you, really {:💜}',
          'The train stopped at level {livello}: thanks to everyone who pushed {:🙌}',
          'Hype train ended at level {livello}. A special thank you to {chi} {:💜}',
        ],
        serio: [
          'Hype train ended at level {livello}.',
          'The hype train finished at level {livello}. Thank you all.',
          'End of the hype train: level {livello}.',
          'Hype train closed at level {livello}, with {punti|one point|# points}.',
          'Train complete at level {livello}. Thanks for contributing.',
          'The hype train stops at level {livello}.',
          'Hype train ended at level {livello}. Thank you, {chi}.',
        ],
      },
      es: {
        scherzoso: [
          '¡El hype train llegó a la última estación: nivel {livello}! Bajen con cuidado {:🚉}',
          '¡Fin del recorrido! Nivel {livello} y cero heridos, gracias a todos {:🚂}',
          'El hype train se detiene en el nivel {livello}. Qué viaje {:🔥}',
          '¡Tren terminado en el nivel {livello}! El maquinista hace una reverencia {:🎩}',
          'Nivel {livello} y el tren se queda aquí. Fueron una fuerza de la naturaleza {:💪}',
          '¡Última parada en el nivel {livello}! La próxima apuntamos más alto {:🚀}',
          '¡Hype train cerrado en el nivel {livello}! Mención de honor para {chi} {:🏆}',
          'Nivel {livello}, fin del viaje. Gracias {chi}, qué empujón {:🔥}',
        ],
        amichevole: [
          'El hype train terminó en el nivel {livello}. Muchísimas gracias a todos {:💜}',
          'Llegamos al nivel {livello}, qué viaje tan bonito juntos {:😊}',
          'Hype train completado: ¡nivel {livello}! Gracias por el apoyo {:🙏}',
          'Terminó el tren en el nivel {livello}. Fueron increíbles {:🤗}',
          'Nivel {livello} alcanzado y el tren en la estación. De verdad, gracias {:💜}',
          'El tren se detuvo en el nivel {livello}: gracias a quienes empujaron {:🙌}',
          'El hype train terminó en el nivel {livello}. Un gracias especial a {chi} {:💜}',
        ],
        serio: [
          'Hype train finalizado en el nivel {livello}.',
          'El hype train concluyó en el nivel {livello}. Gracias a todos.',
          'Fin del hype train: nivel {livello}.',
          'Hype train cerrado en el nivel {livello}, con {punti|un punto|# puntos}.',
          'Tren completado en el nivel {livello}. Gracias por contribuir.',
          'El hype train se detiene en el nivel {livello}.',
          'Hype train finalizado en el nivel {livello}. Gracias, {chi}.',
        ],
      },
    },
  },

  'treno-stato': {
    titolo: ['A che punto è l’hype train', 'Hype train status', 'Cómo va el hype train'],
    quando: ['Quando in chat qualcuno scrive !treno durante un hype train.', 'When someone types !treno in chat during a hype train.', 'Cuando alguien escribe !treno en el chat durante un hype train.'],
    dati: { livello: 'sempre', quanto: 'sempre', meta: 'sempre', secondi: 'sempre' },
    esempio: { livello: 2, quanto: 640, meta: 1200, secondi: 180 },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Hype train al livello {livello}, {quanto}/{meta} per il prossimo. Tempo rimasto: {secondi|un secondo|# secondi} {:⏳}',
          'Treno al livello {livello}! Siamo a {quanto} su {meta}, e {secondi|resta un secondo|restano # secondi} {:🚂}',
          'Livello {livello}, contatore a {quanto}/{meta}. Il capotreno dice: {secondi|un secondo|# secondi} e si chiude {:🎩}',
          'Ecco il treno: livello {livello}, {quanto} su {meta} per salire. Avete {secondi|un secondo|# secondi} {:🔥}',
          'A che punto siamo? Livello {livello}, {quanto}/{meta}, {secondi|un secondo|# secondi} sul cronometro {:⏱️}',
          'Hype train vivo e vegeto: livello {livello}, {quanto} su {meta}, {secondi|ancora un secondo|ancora # secondi} {:💨}',
        ],
        amichevole: [
          'L\'hype train è al livello {livello}: {quanto} su {meta} per il prossimo, {secondi|resta un secondo|restano # secondi} {:💜}',
          'Siamo al livello {livello}, a quota {quanto}/{meta}. Tempo rimasto: {secondi|un secondo|# secondi} {:😊}',
          'Livello {livello} dell\'hype train, {quanto} su {meta} verso il prossimo. {secondi|Resta un secondo|Restano # secondi} {:🙌}',
          'Il treno viaggia al livello {livello}: {quanto}/{meta}, e {secondi|un secondo|# secondi} per spingere {:🤗}',
          'Ecco a che punto siamo: livello {livello}, {quanto} su {meta}, {secondi|un secondo rimasto|# secondi rimasti} {:💜}',
          'Hype train in corsa al livello {livello}: {quanto}/{meta}, con {secondi|un secondo|# secondi} ancora sul conto {:🙏}',
        ],
        serio: [
          'Hype train al livello {livello}: {quanto} su {meta} per il prossimo, {secondi|resta un secondo|restano # secondi}.',
          'Livello {livello}. Avanzamento {quanto}/{meta}. Tempo rimasto: {secondi|un secondo|# secondi}.',
          'Hype train: livello {livello}, {quanto}/{meta}, {secondi|un secondo|# secondi} alla scadenza.',
          'Stato dell\'hype train: livello {livello}, {quanto} su {meta}. Scade tra {secondi|un secondo|# secondi}.',
          'Livello attuale {livello}, progresso {quanto} su {meta}, {secondi|un secondo rimanente|# secondi rimanenti}.',
          'Hype train in corso. Livello {livello}, {quanto}/{meta}; {secondi|manca un secondo|mancano # secondi} alla fine.',
        ],
      },
      en: {
        scherzoso: [
          'Hype train at level {livello}, {quanto}/{meta} to the next one. Time left: {secondi|one second|# seconds} {:⏳}',
          'Train at level {livello}! We\'re at {quanto} of {meta}, with {secondi|one second|# seconds} left {:🚂}',
          'Level {livello}, meter at {quanto}/{meta}. The conductor says {secondi|one second|# seconds} until we close {:🎩}',
          'Here\'s the train: level {livello}, {quanto} of {meta} to climb. You\'ve got {secondi|one second|# seconds} {:🔥}',
          'Where are we at? Level {livello}, {quanto}/{meta}, {secondi|one second|# seconds} on the clock {:⏱️}',
          'Hype train alive and kicking: level {livello}, {quanto} of {meta}, {secondi|one more second|# more seconds} {:💨}',
        ],
        amichevole: [
          'The hype train is at level {livello}: {quanto} of {meta} to the next, {secondi|one second|# seconds} left {:💜}',
          'We\'re at level {livello}, sitting at {quanto}/{meta}. Time left: {secondi|one second|# seconds} {:😊}',
          'Hype train level {livello}, {quanto} of {meta} toward the next one. {secondi|One second|# seconds} to go {:🙌}',
          'The train is cruising at level {livello}: {quanto}/{meta}, and {secondi|one second|# seconds} to push {:🤗}',
          'Here\'s where we are: level {livello}, {quanto} of {meta}, {secondi|one second|# seconds} remaining {:💜}',
          'Hype train rolling at level {livello}: {quanto}/{meta}, with {secondi|one second|# seconds} still on the clock {:🙏}',
        ],
        serio: [
          'Hype train at level {livello}: {quanto} of {meta} to the next, {secondi|one second|# seconds} left.',
          'Level {livello}. Progress {quanto}/{meta}. Time remaining: {secondi|one second|# seconds}.',
          'Hype train: level {livello}, {quanto}/{meta}, {secondi|one second|# seconds} until it expires.',
          'Hype train status: level {livello}, {quanto} of {meta}. Expires in {secondi|one second|# seconds}.',
          'Current level {livello}, progress {quanto} of {meta}, {secondi|one second|# seconds} remaining.',
          'Hype train in progress. Level {livello}, {quanto}/{meta}; {secondi|one second|# seconds} to the end.',
        ],
      },
      es: {
        scherzoso: [
          'Hype train en nivel {livello}, {quanto}/{meta} para el siguiente. Tiempo restante: {secondi|un segundo|# segundos} {:⏳}',
          '¡Tren en nivel {livello}! Vamos {quanto} de {meta}, y {secondi|queda un segundo|quedan # segundos} {:🚂}',
          'Nivel {livello}, contador en {quanto}/{meta}. El maquinista dice: {secondi|un segundo|# segundos} y se cierra {:🎩}',
          'Aquí está el tren: nivel {livello}, {quanto} de {meta} para subir. Tienen {secondi|un segundo|# segundos} {:🔥}',
          '¿Cómo vamos? Nivel {livello}, {quanto}/{meta}, {secondi|un segundo|# segundos} en el reloj {:⏱️}',
          'Hype train más vivo que nunca: nivel {livello}, {quanto} de {meta}, {secondi|un segundo más|# segundos más} {:💨}',
        ],
        amichevole: [
          'El hype train está en nivel {livello}: {quanto} de {meta} para el siguiente, {secondi|queda un segundo|quedan # segundos} {:💜}',
          'Estamos en nivel {livello}, con {quanto}/{meta}. Tiempo restante: {secondi|un segundo|# segundos} {:😊}',
          'Nivel {livello} del hype train, {quanto} de {meta} hacia el siguiente. {secondi|Queda un segundo|Quedan # segundos} {:🙌}',
          'El tren avanza en nivel {livello}: {quanto}/{meta}, y {secondi|un segundo|# segundos} para empujar {:🤗}',
          'Así vamos: nivel {livello}, {quanto} de {meta}, {secondi|un segundo restante|# segundos restantes} {:💜}',
          'Hype train en marcha en nivel {livello}: {quanto}/{meta}, con {secondi|un segundo|# segundos} todavía en el reloj {:🙏}',
        ],
        serio: [
          'Hype train en nivel {livello}: {quanto} de {meta} para el siguiente, {secondi|queda un segundo|quedan # segundos}.',
          'Nivel {livello}. Progreso {quanto}/{meta}. Tiempo restante: {secondi|un segundo|# segundos}.',
          'Hype train: nivel {livello}, {quanto}/{meta}, {secondi|un segundo|# segundos} para que expire.',
          'Estado del hype train: nivel {livello}, {quanto} de {meta}. Expira en {secondi|un segundo|# segundos}.',
          'Nivel actual {livello}, progreso {quanto} de {meta}, {secondi|un segundo restante|# segundos restantes}.',
          'Hype train en curso. Nivel {livello}, {quanto}/{meta}; {secondi|falta un segundo|faltan # segundos} para el final.',
        ],
      },
    },
  },

  'promemoria-link': {
    titolo: ['Il promemoria dei link', 'The links reminder', 'El recordatorio de enlaces'],
    quando: ['In diretta, a chat viva, al massimo ogni tre quarti d’ora, con «Ricorda i tuoi social» acceso.', 'While live and chat is active, at most every forty-five minutes, with “Remind viewers of your socials” on.', 'En directo, con el chat activo, como mucho cada tres cuartos de hora, con «Recuerda tus redes» activado.'],
    dati: { link: 'sempre' },
    esempio: { link: 'socialbot.live/u/luna' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Tutti i miei social in un posto solo, così non vi perdete niente 👉 {link} {:✨}',
          'Piccolo promemoria: i miei link non mordono, passate a trovarli {link} {:😄}',
          'Se volete stalkerarmi legalmente, trovate tutto qui: {link} {:👀}',
          'Social, canali, tutto quanto: un link solo, zero fatica {link} {:🔗}',
          'Non ditemi che non mi seguite ancora ovunque: {link} {:😏}',
          'Per chi si fosse perso qualcosa, qui c\'è tutto: {link} {:📌}',
          '{community}, i miei link sono sempre qui: {link} {:✨}',
        ],
        amichevole: [
          'Se ti va, mi trovi con tutti i miei social qui: {link} {:💜}',
          'Piccolo promemoria, tutti i miei link sono qui: {link} {:😊}',
          'Passa a trovarmi anche fuori da qui, trovi tutto a questo link: {link} {:🤗}',
          'Per non perderti nulla, i miei link: {link} {:💜}',
          'Ci vediamo anche sugli altri social! Tutto qui: {link} {:🙌}',
          'Se vuoi restare in contatto, ecco dove trovarmi: {link} {:😊}',
        ],
        serio: [
          'I miei link e i social: {link}',
          'Tutti i collegamenti del canale sono qui: {link}',
          'Per seguirmi anche altrove: {link}',
          'Social e contatti in un\'unica pagina: {link}',
          'Promemoria: la pagina con tutti i miei link è {link}',
          'Trovate i miei canali a questo indirizzo: {link}',
        ],
      },
      en: {
        scherzoso: [
          'All my socials in one place, so you never miss a thing 👉 {link} {:✨}',
          'Friendly reminder: my links don\'t bite, go say hi {link} {:😄}',
          'Want to stalk me legally? Everything\'s here: {link} {:👀}',
          'Socials, channels, the whole thing: one link, zero effort {link} {:🔗}',
          'Don\'t tell me you\'re not following me everywhere yet: {link} {:😏}',
          'In case you missed anything, it\'s all here: {link} {:📌}',
          '{community}, my links are always right here: {link} {:✨}',
        ],
        amichevole: [
          'If you\'d like, you can find all my socials here: {link} {:💜}',
          'Quick reminder, all my links are here: {link} {:😊}',
          'Come find me outside of here too, it\'s all at this link: {link} {:🤗}',
          'So you don\'t miss anything, here are my links: {link} {:💜}',
          'See you on my other socials too! Everything\'s here: {link} {:🙌}',
          'If you want to stay in touch, here\'s where to find me: {link} {:😊}',
        ],
        serio: [
          'My links and socials: {link}',
          'All the channel\'s links are here: {link}',
          'To follow me elsewhere: {link}',
          'Socials and contacts on one page: {link}',
          'Reminder: the page with all my links is {link}',
          'You can find my channels at this address: {link}',
        ],
      },
      es: {
        scherzoso: [
          'Todas mis redes en un solo lugar, para que no se pierdan nada 👉 {link} {:✨}',
          'Recordatorio amistoso: mis enlaces no muerden, pasen a verlos {link} {:😄}',
          '¿Quieren espiarme legalmente? Todo está aquí: {link} {:👀}',
          'Redes, canales, todo: un solo enlace, cero esfuerzo {link} {:🔗}',
          'No me digan que todavía no me siguen en todos lados: {link} {:😏}',
          'Por si se perdieron algo, aquí está todo: {link} {:📌}',
          '{community}, mis enlaces siempre están aquí: {link} {:✨}',
        ],
        amichevole: [
          'Si quieres, encuentras todas mis redes aquí: {link} {:💜}',
          'Pequeño recordatorio, todos mis enlaces están aquí: {link} {:😊}',
          'Visítame también fuera de aquí, está todo en este enlace: {link} {:🤗}',
          'Para que no te pierdas nada, mis enlaces: {link} {:💜}',
          '¡Nos vemos también en mis otras redes! Todo aquí: {link} {:🙌}',
          'Si quieres seguir en contacto, aquí me encuentras: {link} {:😊}',
        ],
        serio: [
          'Mis enlaces y redes: {link}',
          'Todos los enlaces del canal están aquí: {link}',
          'Para seguirme en otros sitios: {link}',
          'Redes y contactos en una sola página: {link}',
          'Recordatorio: la página con todos mis enlaces es {link}',
          'Encuentran mis canales en esta dirección: {link}',
        ],
      },
    },
  },

  'raid-uscita': {
    titolo: ['Il raid verso un altro canale', 'Raiding another channel', 'El raid a otro canal'],
    quando: ['Quando fai partire un raid dalla Regia.', 'When you start a raid from the Control room.', 'Cuando inicias un raid desde Realización.'],
    dati: { nome: 'sempre' },
    esempio: { nome: 'Kiro' },
    spegnibile: true,
    frasi: {
      it: {
        scherzoso: [
          'Si va in raid da {nome}! Preparate i saluti migliori {:🚀}',
          'Zaino in spalla, raid verso {nome}! Comportatevi bene, siamo ospiti {:🎒}',
          'Raid in partenza per {nome}! Entriamo con stile, niente porte sfondate {:😎}',
          'Tutti con me: facciamo raid da {nome} e lasciamo il segno {:🔥}',
          'Destinazione {nome}! Tenetevi forte, il raid sta partendo {:🛸}',
          'Raid verso {nome}! Portate energia e buone maniere {:💪}',
          '{community}, si va in raid da {nome}! Fatevi sentire {:🚀}',
        ],
        amichevole: [
          'Andiamo a trovare {nome} con un raid! Salutate con affetto {:💜}',
          'Raid in partenza verso {nome}, portiamo un po\' di calore {:🤗}',
          'Ci spostiamo da {nome}! Grazie per la live, e fatevi sentire di là {:😊}',
          'Facciamo raid da {nome}: facciamo vedere com\'è la nostra community {:🙌}',
          'Si va da {nome}! Entriamo in punta di piedi e con tanti saluti {:💜}',
          'Raid verso {nome}. Grazie per essere stati qui, ci vediamo di là {:🤗}',
        ],
        serio: [
          'Raid in partenza verso {nome}.',
          'Facciamo raid da {nome}. Grazie per la visione.',
          'Ci spostiamo sul canale di {nome}. Salutate pure all\'arrivo.',
          'Raid avviato: destinazione {nome}.',
          'La diretta prosegue con un raid verso {nome}.',
          'Raid verso {nome}. Grazie a tutti, a presto.',
        ],
      },
      en: {
        scherzoso: [
          'We\'re raiding {nome}! Get your best greetings ready {:🚀}',
          'Pack your bags, raid headed to {nome}! Behave, we\'re guests {:🎒}',
          'Raid departing for {nome}! Let\'s enter in style, no kicking down doors {:😎}',
          'Everyone with me: we\'re raiding {nome} and leaving our mark {:🔥}',
          'Destination {nome}! Hold on tight, the raid is taking off {:🛸}',
          'Raid to {nome}! Bring energy and good manners {:💪}',
          '{community}, we\'re raiding {nome}! Make some noise {:🚀}',
        ],
        amichevole: [
          'Let\'s visit {nome} with a raid! Say hi with lots of love {:💜}',
          'Raid heading to {nome}, let\'s bring some warmth {:🤗}',
          'We\'re moving over to {nome}! Thanks for the stream, and make yourselves heard over there {:😊}',
          'We\'re raiding {nome}: let\'s show them what our community is like {:🙌}',
          'Off to {nome}! Let\'s tiptoe in with lots of hellos {:💜}',
          'Raid to {nome}. Thanks for being here, see you over there {:🤗}',
        ],
        serio: [
          'Raid departing to {nome}.',
          'We\'re raiding {nome}. Thanks for watching.',
          'We\'re moving to {nome}\'s channel. Feel free to say hi when we arrive.',
          'Raid started: destination {nome}.',
          'The stream continues with a raid to {nome}.',
          'Raid to {nome}. Thank you all, see you soon.',
        ],
      },
      es: {
        scherzoso: [
          '¡Nos vamos de raid con {nome}! Preparen sus mejores saludos {:🚀}',
          'Mochila al hombro, ¡raid rumbo a {nome}! Pórtense bien, somos visitas {:🎒}',
          '¡Raid saliendo hacia {nome}! Entramos con estilo, sin tirar puertas {:😎}',
          'Todos conmigo: hacemos raid a {nome} y dejamos huella {:🔥}',
          '¡Destino: {nome}! Agárrense fuerte, el raid despega {:🛸}',
          '¡Raid a {nome}! Lleven energía y buenos modales {:💪}',
          '{community}, ¡nos vamos de raid con {nome}! Hagan ruido {:🚀}',
        ],
        amichevole: [
          '¡Vamos a visitar a {nome} con un raid! Saluden con mucho cariño {:💜}',
          'Raid rumbo a {nome}, llevemos un poco de calidez {:🤗}',
          '¡Nos mudamos con {nome}! Gracias por el stream, y háganse notar allá {:😊}',
          'Hacemos raid a {nome}: mostremos cómo es nuestra comunidad {:🙌}',
          '¡Nos vamos con {nome}! Entremos despacito y con muchos saludos {:💜}',
          'Raid a {nome}. Gracias por estar aquí, nos vemos allá {:🤗}',
        ],
        serio: [
          'Raid en camino hacia {nome}.',
          'Hacemos raid a {nome}. Gracias por ver la transmisión.',
          'Pasamos al canal de {nome}. Saluden al llegar, si quieren.',
          'Raid iniciado: destino {nome}.',
          'La transmisión continúa con un raid a {nome}.',
          'Raid a {nome}. Gracias a todos, hasta pronto.',
        ],
      },
    },
  },
};
