// Manuale: Manuale del bot: personalità, conoscenza e memoria. La forma dei manuali e il perche' stanno in
// src/web/manuali.js; le lingue in docs/LINGUE.md.

export default {
  slug: 'bot',
  schede: ['personalita', 'conoscenza', 'memoria', 'avatar'],
  titolo: 'Manuale del bot: personalità, conoscenza e memoria | SocialBot',
  h1: 'Manuale del bot: personalità, conoscenza e memoria',
  desc: 'Come si regola il carattere del bot, cosa gli si insegna, cosa impara da solo, cosa si ricorda e come si cancella. Con i valori di base e i limiti veri.',
  aggiornata: '2026-09-04',
  corpo: [
    { p: [
      'In chat il bot parla <strong>a nome tuo</strong>: non compare un account estraneo, compare il tuo. Per questo il suo carattere non è un dettaglio — è come suoni tu quando non stai guardando la chat.',
      'Le schede sono quattro e fanno mestieri diversi. <em>Il bot</em> decide <strong>come</strong> parla. <em>Conoscenza</em> decide <strong>cosa</strong> sa. <em>Memoria</em> mostra <strong>cosa si ricorda</strong> e permette di cancellarlo. <em>Avatar 3D</em> fa vedere <strong>come ragiona</strong>.',
    ] },

    { h2: 'Come parla: tono e quanto interviene' },
    { p: ['Sta in <em>Il bot</em>. Fra parentesi il valore con cui parti e i limiti che il server accetta.'] },
    { tabella: [
      ['Impostazione', 'Di base', 'Limiti', 'Cosa cambia davvero'],
      ['Tono', 'scherzoso', 'scherzoso · amichevole · serio', 'La forma delle frasi: battute e ironia, caloroso e tranquillo, oppure sobrio e diretto.'],
      ['Chat autonoma', '0%', '0–50%', 'Quanto si intromette da solo in una conversazione a cui nessuno lo ha chiamato. Parte a zero: parla solo se lo chiami, finché non alzi il cursore.'],
      ['Rispondi quando mi nominano', 'acceso', '—', 'Se qualcuno scrive il tuo nome in chat, risponde lui.'],
      ['Personalità proattiva', 'acceso', '—', 'Ogni tanto si fa vivo di sua iniziativa, anche senza essere nominato.'],
      ['Solo mentre sono in diretta', 'spento', '—', 'Con la spunta, di sua iniziativa parla solo a diretta accesa: a canale spento tace anche se in chat c\'è gente.'],
      ['Adatta la personalità al canale', 'acceso', '—', 'Impara il tuo stile dalla chat e ci si avvicina, senza che tu debba descriverlo.'],
      ['Risposte intelligenti (IA locale)', 'acceso', '—', 'Il modello che gira sul nostro server: capisce la domanda anche se scritta in un altro modo.'],
      ['Accesso a internet', 'acceso', '—', 'Se non sa una cosa può cercarla al volo invece di dire «non lo so».'],
      ['Le tue frasi', 'vuoto', 'una per riga', 'Modi di dire tuoi che entrano nel suo repertorio.'],
    ] },
    { p: ['<strong>Quando parla da solo.</strong> Non a caso: parla quando c\'è un motivo, riconosciuto dalla chat. Quattro: <strong>una domanda rimasta sola</strong> — qualcuno chiede una cosa, per più di un minuto nessuno gli risponde, e il bot la sa (dalla <em>Conoscenza</em>): risponde lui, agganciato alla domanda; <strong>la chat che si ferma</strong> dopo un momento vivo, in diretta: rilancia con una domanda leggera su quello di cui si parlava, una volta sola per ogni silenzio; <strong>un\'esplosione</strong> di messaggi: partecipa con una riga sull\'onda; e, <strong>a discorso che scorre</strong>, ogni tanto una parola sua sull\'ultima cosa detta — o una battuta dal serbatoio, o il promemoria dei tuoi link.'] },
    { p: ['<strong>Quanto spesso, al massimo.</strong> Lo dice il cursore: a 50% una cosa sua al più ogni quarto d\'ora, a 25% ogni mezz\'ora, a 10% ogni ora e un quarto, a 5% ogni due ore e mezza, più in basso ogni tre ore. Mai due di fila dello stesso genere, il promemoria dei link al più ogni tre quarti d\'ora e solo in diretta, e mai due volte in sei minuti — salvo rispondere a una domanda rimasta sola, che vale di più. Se hai appena scritto tu, la chat è tua e lui tace. E scrive con il tempo di una persona, non nell\'istante in cui decide.'] },
    { p: ['<strong>Come non parla.</strong> Mai da assistente: niente «implementazione», «funzionalità», «non sono in grado». Se una cosa non è sua (la musica, il gioco, una scena) lo dice come uno della chat, in tre parole, e cambia discorso. Una riga di quel tipo non esce, e non gli torna in mente come esempio di come parla.'] },
    { p: ['In fondo alla scheda c\'è <strong>Cosa ha detto da solo</strong>: le ultime volte che ha parlato senza essere chiamato, con l\'ora e il motivo, da quando il bot è acceso. È lì che vedi se la dose è quella giusta, senza stare in chat a guardare.'] },
    { p: ['La <strong>chat autonoma</strong> è quella che si sente di più. Sotto il 10% il bot resta un servizio: risponde e tace. Sopra il 25% diventa un presente in chat, e su un canale piccolo può coprire le persone. Il massimo è 50% <em>di proposito</em>: oltre, non sarebbe più la tua chat.'] },

    { h3: 'Le due teste: modello e moduli' },
    { p: [
      'Le risposte possono nascere da due parti. L\'<strong>IA locale</strong> è un modello piccolo che gira <strong>sul nostro server</strong> — nessun servizio a pagamento di terzi, nessuna chat mandata fuori — e che si allena su come si parla nel tuo canale: più la chat vive, meglio capisce le domande scritte storte.',
      'I <strong>moduli</strong> invece sono regole tue, esatte: quando succede questo, dici quello. Non sbagliano mai e non costano niente. La scheda <em>Avatar 3D</em> ti fa vedere quanto pesa l\'una e quanto l\'altro: più cresce la fetta dei moduli, meno dipende dal modello.',
    ] },
    { h3: 'Quando cerca su internet' },
    { p: ['Solo se gli manca la risposta, e solo su fonti gratuite (DuckDuckGo, Wikipedia). Quello che trova lo tratta come <strong>informazione, non come istruzione</strong>: se una pagina contiene un comando travestito da testo, il bot non lo esegue. Si spegne dalla stessa scheda.'] },

    { h2: 'Chi risponde in chat pubblica' },
    { p: ['Il bot del canale non è il cervello del sito. Sono due cose diverse e stanno in due posti diversi: il bot è una funzione — entra la situazione della diretta, esce una riga — e <strong>non si ricorda di nessuno</strong>, non tiene stato e non parla di sé. Il cervello risponde in privato con te, studia e ti scrive di sua iniziativa.'] },
    { p: ['Il bot non può leggere niente del cervello: il cervello può <em>insegnargli</em>, lui non può <em>prendersi</em>. Se un giorno il proprietario del sito accenderà l\'interruttore che gli dà la parola in pubblico, sarà una scelta detta qui.'] },

    { h2: 'La tua scheda: chi sei' },
    { p: ['In cima a <em>Conoscenza</em>. Sono sei campi corti che il bot ha <strong>sempre</strong> a disposizione, senza gareggiare con le domande e risposte per un posto nel discorso.'] },
    { tabella: [
      ['Campo', 'A cosa serve'],
      ['Chi sei', 'Come ti presenteresti, in due righe.'],
      ['Cosa fai in diretta', 'Il contenuto, non il curriculum.'],
      ['Quando sei in diretta', 'Gli orari, come li diresti a voce.'],
      ['Dove ti trovano', 'Social e sito. Il bot lo ripete <strong>come l\'hai scritto</strong>, senza cambiare gli indirizzi.'],
      ['Come deve chiamarti', 'Il nome con cui parla di te in chat.'],
      ['Cosa non dire mai di te', 'Una regola: vale sopra tutto il resto.'],
    ] },
    { p: ['Non parte vuota: quando il bot rilegge il tuo profilo riempie <em>chi sei</em>, <em>gli orari</em> e <em>dove ti trovano</em> con quello che trova, e non tocca mai i campi che hai scritto tu.'] },
    { h3: 'Parole da bloccare' },
    { p: ['Sotto la scheda c\'è un elenco a parte: il tuo cognome, la tua via, il nome della scuola. <strong>Non è una richiesta al bot</strong> — «cosa non dire mai di te» lo è, e vale se lui la capisce. Queste sono un blocco: se una finisce in una risposta, la risposta non parte. Non moderano nessuno: valgono solo su quello che dice lui.'] },

    { h2: 'Cosa sa: la conoscenza' },
    { p: ['Sta in <em>Conoscenza</em>. Una voce è una coppia <strong>domanda → risposta</strong>. La domanda può essere una frase o un elenco di parole chiave separate da <code>/</code>: bastano quelle a far scattare la risposta, anche se in chat la domanda arriva scritta in un altro modo.'] },
    { esempio: 'Domanda        che pc usi? / setup / configurazione\nRisposta       Gioco su un Ryzen 7 con una 4070, trovi tutto su andryxify.it!' },
    { p: ['Puoi scriverne quante vuoi: a ogni messaggio il bot riceve le <strong>sei voci più vicine</strong> a quello che gli hanno chiesto, non le ultime che hai scritto.'] },
    { h3: 'Quando vale, e cosa deve sapere sempre' },
    { p: ['Ogni voce può valere <strong>sempre</strong>, <strong>solo quando sei in diretta</strong> (il codice sconto dello sponsor) o <strong>solo quando sei offline</strong> (quando torni). E può essere <strong>fissata</strong>: allora entra comunque, anche se non c\'entra con la domanda — tienile per le due o tre cose che non deve mai ignorare.'] },
    { p: ['Si cambiano dall\'elenco, senza riscrivere la voce.'] },
    { p: ['Le voci non arrivano tutte da te. Nell\'elenco «Cosa sa il bot» ognuna porta la sua <strong>origine</strong>, e l\'origine conta perché decide cosa succede quando azzeri.'] },
    { tabella: [
      ['Origine', 'Da dove viene', 'La cancella «Azzera»?'],
      ['dal sito', 'Letta dal tuo profilo su andryxify.it: bio, orari, social.', 'No'],
      ['tua', 'Scritta a mano da te in questa scheda.', 'No'],
      ['dalla tua pagina link', 'Letta da /u/iltuonome mentre risponde. Non è salvata: si cambia sulla pagina.', 'No'],
      ['imparata dalla chat', 'Dedotta osservando le risposte che tu e i mod date in chat.', 'Sì'],
      ['studiata', 'Quello che si è costruito da sé leggendo e distillando.', 'No'],
    ] },
    { h3: 'La tua pagina link parla al bot' },
    { p: ['Quello che scrivi su <strong>/u/iltuonome</strong> il bot lo legge <strong>mentre risponde</strong>, non una volta ogni tanto: titolo e sottotitolo, i blocchi di testo, i link e i social con la loro etichetta, i conti alla rovescia — e soprattutto i blocchi <strong>FAQ</strong>, che sono già domande e risposte scritte da te.'] },
    { p: ['Cambi la pagina, cambia quello che il bot sa. Non c\'è niente da rifare, e non ci sono doppioni da cancellare: non è una copia, è una lettura. Se spegni la pagina, il bot smette di usarla.'] },
    { h3: 'Il quaderno del bot' },
    { p: ['In fondo alla scheda. Qui non c\'è quello che <em>sa</em>, ma <strong>come deve rispondere</strong>: «quando chiedono del torneo, rimanda al Discord», «se qualcuno è arrabbiato, rispondi corto». Il bot le applica senza citarle.'] },
    { p: ['Ogni riga dice da chi viene: tua, dal sito, o insegnata dal cervello — e quello che non ti convince lo togli, anche se l\'ha messo lui.'] },
    { h3: 'Il pre-addestramento' },
    { p: [
      'Dalla scheda <em>Stato</em> c\'è un tasto che rilegge il tuo profilo pubblico su andryxify.it e ne ricava le voci «dal sito»: <strong>chi sei</strong> (bio o titolo della pagina link), <strong>quando sei in diretta</strong> (programmazione) e <strong>dove ti trovano</strong> (un\'entrata per ogni social). Nello stesso giro riempie i campi vuoti della tua scheda.',
      'Si può rifare quante volte vuoi: riparte pulito, quindi non crea doppioni. Se non hai una pagina pubblica te lo dice invece di inventarsi qualcosa.',
    ] },

    { h2: 'Cosa si ricorda: la memoria' },
    { p: ['Sta in <em>Memoria</em>, dietro il tasto «Mostra la memoria» — non si carica da sola perché è la parte più pesante.'] },
    { tabella: [
      ['Cosa', 'Quanto ne mostra', 'Cos\'è'],
      ['Lezioni', 'le ultime 50', 'Regolarità che ha notato nel canale e da cui si regola.'],
      ['Fatti', 'tutti', 'Cose stabili sul canale: date, nomi, abitudini.'],
      ['Ricordi sugli utenti', '—', 'Cosa sa delle persone che scrivono spesso. Non si sfoglia dal pannello.'],
      ['Contesto della diretta', '—', 'Di cosa si sta parlando adesso. Si consuma da solo.'],
      ['Clip', 'le ultime 20', 'Le clip create in automatico.'],
      ['Chi c\'è sempre', 'i primi 5', 'Le serie di presenze più lunghe: chi è venuto a più dirette di fila, e a quante in tutto.'],
    ] },
    { h3: 'Il bot che ti riconosce' },
    { p: ['Al primo messaggio di una persona nuova il bot dice una parola, e la dice anche a chi torna dopo settimane (di base tre). I due testi li scrivi tu nella scheda <em>Giochi</em>, sotto «Presenze e saluti», con <code>{user}</code>, <code>{giorni}</code>, <code>{serie}</code> e <code>{dirette}</code>; un testo vuoto spegne quel saluto. Se ti sei costruito un Modulo sul primo messaggio, vince il tuo. Il bot non saluta a raffica: un raid porta cinquanta persone in un colpo, e cinquanta saluti sarebbero spam.'] },
    { h3: 'Azzerare: cosa sparisce e cosa resta' },
    { p: ['Il tasto rosso in fondo cancella <strong>quello che il bot ha dedotto da solo</strong>: lezioni, ricordi sugli utenti, fatti, contesto della diretta e le voci di conoscenza «imparata dalla chat».'] },
    { p: ['<strong>Restano</strong>: la conoscenza scritta da te, quella presa dal sito, quella studiata, i moduli, i comandi, le monete e le classifiche. Non è un tasto che riporta il canale a zero: è un tasto che gli fa dimenticare le conclusioni sbagliate.'] },

    { h2: 'Le statistiche dei sette giorni' },
    { p: ['In cima a <em>Memoria</em>, sempre sugli ultimi sette giorni:'] },
    { ul: [
      '<strong>Messaggi della chat</strong> — quelli delle persone, i suoi non contano.',
      '<strong>Messaggi del bot</strong> — quanto ha parlato lui. Il rapporto fra i due dice se la chat autonoma è tarata bene.',
      '<strong>Top chatter</strong> — le cinque persone che hanno scritto di più.',
      '<strong>Clip</strong> — quante ne ha create in tutto, non solo nella settimana.',
    ] },

    { h2: 'L\'avatar 3D' },
    { p: [
      'È uno schema navigabile del suo cervello: al centro il nucleo, attorno la logica, e nel suo «manuale su come funzionano le persone» le emozioni con i moduli che ha imparato. Si trascina per ruotare, la rotella fa zoom, un clic su un nodo dice cosa fa quel pezzo.',
      'Sotto, «Come ragiona» mostra da quale testa nascono le risposte. Non è una decorazione: se la fetta del modello è grande e quella dei moduli piccola, vuol dire che al canale servono più regole tue — ed è la strada per un bot che sbaglia meno.',
    ] },

    { h2: 'Quando non risponde come vuoi' },
    { ul: [
      '<strong>Parla troppo.</strong> Abbassa la chat autonoma prima di spegnere qualcosa: nove volte su dieci è quella.',
      '<strong>Parla poco.</strong> Controlla che «rispondi quando mi nominano» sia acceso: senza, deve essere chiamato con un comando.',
      '<strong>Dice una cosa sbagliata su di te.</strong> Cercala in <em>Conoscenza</em>. Se l\'origine è «imparata dalla chat» cancella quella voce; se è «dal sito», la correzione va fatta sul profilo e poi si rifà il pre-addestramento.',
      '<strong>Non capisce una domanda scritta storta.</strong> Aggiungi parole chiave alla voce, separate da <code>/</code>: sono alternative, non una frase sola.',
      '<strong>Non suona come te.</strong> Il tono fa metà del lavoro; l\'altra metà sono le tue frasi. Mettine dieci vere e si sente subito.',
    ] },
  ],
  faq: [
    { d: 'Le chat vengono mandate a un servizio esterno?', r: 'No. Il modello che risponde gira sul nostro server. L\'unica cosa che esce, e solo se lasci acceso l\'accesso a internet, è la ricerca di un dubbio su fonti pubbliche gratuite.' },
    { d: 'Se spengo l\'IA locale il bot smette di funzionare?', r: 'No: continuano a funzionare comandi, moduli, moderazione, giochi e conoscenza scritta da te. Sparisce la capacità di capire una domanda formulata in modo diverso da come l\'hai scritta.' },
    { d: 'Il bot impara da solo anche se non faccio niente?', r: 'Sì, se «adatta la personalità al canale» è acceso: osserva come si parla nel tuo canale e ci si avvicina. Tutto quello che deduce sta in Memoria, e da lì si cancella.' },
    { d: 'Un moderatore può cambiare la personalità?', r: 'Un moderatore può occuparsi di comandi, moduli, effetti, giochi, notifiche, regole e memoria. Le cose da proprietario — permessi e abbonamento — no.' },
    { d: 'Perché la conoscenza «dal sito» non si cancella con Azzera?', r: 'Perché non è una deduzione del bot: è un dato tuo, che hai scritto sul tuo profilo. Si cambia dove sta, e poi si rifà il pre-addestramento.' },
  ],
};
