// Manuale: Effetti & suoni. La forma dei manuali e il perche' stanno in
// src/web/manuali.js; le lingue in docs/LINGUE.md.

export default {
  slug: 'effetti',
  schede: ['effetti'],
  titolo: 'Manuale degli effetti: media, gesti e punti canale | SocialBot',
  h1: 'Manuale degli effetti: media, gesti e punti canale',
  desc: 'Caricare suoni, immagini e video da lanciare in chat, usare la libreria condivisa, i gesti della webcam e gli effetti sui premi a punti canale di Twitch.',
  aggiornata: '2026-09-27',
  corpo: [
    { h2: 'Effetti & suoni', scheda: 'effetti', p: [
      'Qui carichi suoni, immagini, GIF e video e li fai partire nell\'overlay: da un comando in chat, da un gesto davanti alla webcam o da un premio a punti canale. Ci sono anche otto effetti pronti, disegnati da noi. Gli stessi media li ritrovi negli alert, nel player, nei cartelli e in ogni campo che ha il pulsante «Dalla libreria».',
      'La scheda sta nel gruppo «Scena & overlay» ed è compresa in ogni piano, anche in quello gratuito. Se leggi «Chiusa da andryxify», per il tuo canale è chiusa, e sotto c\'è il motivo quando c\'è.',
      'La usano il proprietario del canale e i moderatori. I premi a punti canale sono di Twitch e chiedono il permesso dei punti canale.',
      'Gli effetti compaiono in ogni overlay dove c\'è l\'elemento «Effetti a schermo». Il suono esce dalla diretta se nella sorgente Browser di OBS hai spuntato «Controlla l\'audio via OBS» (<a href="/manuale/overlay">manuale dell\'Overlay Studio</a>).',
    ] },

    { h3: 'Effetti dai gesti (webcam)' },
    { p: [
      'Un overlay che legge i gesti delle mani e le espressioni del volto e fa partire effetti a schermo. Gira tutto nel browser: la webcam non esce dal tuo computer, al bot arriva solo il nome del gesto.',
      '«Attiva il tracking webcam» è acceso di serie. Il setup consigliato tiene la webcam come sorgente normale di OBS, con qualità e ritardo intatti, e usa due link.',
    ] },
    { passi: [
      { t: 'Apri il rilevatore', d: 'Copia il primo link, «1) Rilevatore», e aprilo in Chrome. Tieni la scheda aperta, anche dietro le altre: è lei che guarda la webcam.' },
      { t: 'Metti l\'overlay giochi in OBS', d: 'Copia il secondo link, «2) Overlay giochi», e aggiungilo in OBS come sorgente Browser trasparente, sopra la tua webcam. Non usa la webcam, quindi niente conflitti e niente ritardo.' },
      { t: 'Scegli la webcam', d: 'Premi «Rileva webcam», consenti la fotocamera e scegli la tua in «Webcam da usare». Senza scelta vale «Webcam predefinita del sistema». Il nome vale anche nell\'overlay in OBS.' },
      { t: 'Salva', d: 'Premi «Salva impostazioni webcam».' },
    ] },
    { p: [
      'Il «Modo tutto-in-uno» dà un link solo, con webcam ed effetti insieme. Funziona solo se la sorgente Browser di OBS può usare la fotocamera, e spesso non può: se resta nera, torna ai due link.',
      'I link della webcam usano la chiave dell\'overlay. Tienili per te. Se il proprietario fa un link nuovo nell\'Overlay Studio, cambiano anche questi e vanno ricopiati.',
      'In «Gesto/espressione → effetto e/o scrittura in chat» ci sono nove righe: Vittoria, Pollice su, Mano aperta, Indice, Pugno, Felice, Triste, Arrabbiato, Sorpreso. A sinistra scrivi il comando di un tuo effetto, senza <code>!</code>; il campo ti propone i tuoi. A destra scrivi un testo o un\'emote che il bot scrive in chat, fino a 120 caratteri. Lascia vuoto quello che non ti serve.',
      'Lo stesso gesto ripetuto entro due secondi e mezzo conta una volta sola. L\'effetto di un gesto parte sempre, senza guardare «Chi può usarlo» e il cooldown.',
      '<strong>«Minigiochi con la webcam (gesti ed espressioni)»</strong>, acceso di serie, fa giocare nello stesso overlay. Per farne partire uno tieni la mano aperta per circa un secondo, poi scegli col gesto: Vittoria per Mima, Pollice su per Non ridere, Indice per Reaction. Dalla chat partono con <code>!mima</code>, <code>!nonridere</code>, <code>!reaction</code> e <code>!battaglia</code>. Nella Battaglia gli spettatori scrivono <code>!sfida vittoria</code>, o un altro gesto. I punteggi finiscono in chat.',
    ] },
    { p: ['La sezione «Effetti & giochi» accende e regola il resto. Le scelte valgono dopo «Salva impostazioni webcam».'] },
    { tabella: [
      ['Controllo', 'Di base', 'Cosa fa'],
      ['«Effetti cinematici»', 'acceso', 'l\'interruttore di tutti gli effetti qui sotto'],
      ['Kamehameha, Fireball, «Fulmini», «Trail mani», Combo, «Snap di Thanos»', 'accesi', 'gli effetti delle mani'],
      ['«Tempo fermo (2 mani a V)»', 'acceso', 'il tempo si ferma con due mani a V'],
      ['«Laser occhi (sorpresa)», «Fuoco bocca (bocca aperta)», «Aura sorriso»', 'accesi', 'gli effetti sul viso'],
      ['«Inquadratura → scatto (2 mani a cornice)»', 'acceso', 'le mani a cornice fanno uno scatto'],
      ['«Puzzle con le mani (pizzica e trascina)»', 'spento', 'acceso, parte con <code>!puzzle</code> in chat ed esce con <code>!puzzlestop</code>'],
      ['«Sensibilità»', '5', 'da 1 a 10: più alta, pose più facili da attivare'],
      ['«Specchia (facecam selfie)»', 'acceso', 'per la webcam a specchio'],
      ['«Suoni»', 'acceso', 'i suoni degli effetti'],
      ['«Minigiochi (quali attivi)»', 'tutti', 'Mima · Non ridere · Reaction · Battaglia'],
      ['«Meme dalle espressioni»', 'acceso', 'fai una faccia e compare il suo meme'],
    ] },
    { p: [
      'I meme sono sei: Risata, Sorpresa, Rabbia, Tristezza, Paura, Disgusto. Di serie ognuno è un\'emoji. Al suo posto metti un\'altra emoji o l\'indirizzo di un\'immagine o di una GIF, fino a 300 caratteri. Il pulsante della libreria ci mette una tua immagine.',
      'Per reazioni più ricche, con messaggi, contatori e attese per ruolo, nella scheda «Comandi» c\'è l\'innesco «Gesto webcam (mani/volto)» (<a href="/manuale/moduli">manuale dei comandi</a>).',
    ] },

    { h3: 'La libreria dei media' },
    { p: [
      'Un posto solo per foto, GIF, video e suoni: i tuoi e quelli che gli altri streamer hanno condiviso. In alto ci sono «Tutti», «Immagini», «Video», «Audio», «Solo i miei» e «Cerca per nome…».',
      'Di serie vedi i media condivisi dagli altri, i più presi per primi. Con «Solo i miei» vedi i tuoi, anche quelli privati.',
      'Ogni scheda mostra il nome, l\'autore oppure «tuo» con «condiviso» o «privato», quante volte è stata presa e «con suono» se è una combo. I suoni hanno il tasto per ascoltarli, immagini e video quello per guardarli.',
      'Su un media di un altro, <strong>«Aggiungi»</strong> lo copia nella tua libreria e il pannello ti dice il comando: «Aggiunto come !nome alla tua libreria». La copia è privata e tiene il nome dell\'autore. Come comando in chat la può lanciare chiunque, senza cooldown.',
      'Su un tuo media, <strong>«Condividi»</strong> ti chiede con che nome lo vedranno gli altri, fino a 60 caratteri. «Non condividere» lo rende di nuovo privato.',
      'Ogni pulsante «Dalla libreria» del pannello apre la stessa libreria in una finestra. «Usa» prende un tuo media, «Prendi e usa» copia quello di un altro e lo usa. «Dal mio computer» carica un file nuovo: il comando nasce dal nome del file, lo possono lanciare solo i moderatori e non ha cooldown. Se il file non è del tipo che serve lì leggi «Qui non ci va questo tipo di file.»',
    ] },

    { h3: 'Carica un effetto' },
    { tabella: [
      ['Campo', 'Di base', 'Limiti'],
      ['«File (audio / immagine / video)»', '', 'fino a 60 MB; le GIF valgono come video'],
      ['«Togli uno sfondo a tinta unita»', 'spento', 'solo immagini e video; compare con l\'anteprima del file'],
      ['«Colore da togliere»', 'il colore dell\'angolo in alto a sinistra', 'un clic sull\'anteprima prende quello sotto il clic'],
      ['«Sensibilità»', '25', 'da 1 a 60: più è alta, più colori vicini a quello scelto spariscono'],
      ['«Bordi morbidi»', '8', 'da 0 a 40: la fascia in cui il soggetto sfuma nel fondo'],
      ['«Suono da abbinare»', 'nessuno', 'facoltativo, solo con un\'immagine o un video: fa una <strong>combo</strong>, media e suono che partono insieme'],
      ['«Comando in chat»', 'il nome del file', 'facoltativo; solo lettere minuscole, numeri e _, fino a 24 caratteri'],
      ['«Chi può usarlo»', 'Tutti', 'Tutti · Solo sub · Solo VIP · Solo mod; moderatori e proprietario passano sempre'],
      ['«Cooldown (s)»', '10', 'da 0 a 3600 secondi'],
      ['«Volume (%)»', '80', 'da 0 a 100'],
      ['«Durata a schermo (ms)»', '5000', 'da 500 a 30000; conta solo per le immagini'],
      ['«Dove appare»', 'Nella scena, dove lo metti nello Studio', 'solo immagini e video: Nella scena, dove lo metti nello Studio · A tutto schermo, riempito · A tutto schermo, intero'],
      ['«Rendi pubblico»', 'spento', 'lo condivide nella libreria'],
      ['«Nome nella libreria condivisa»', 'il comando', '60 caratteri'],
    ] },
    { p: [
      'Scelto un file, sotto compare la sua anteprima su una scacchiera: dove è trasparente, la scacchiera si vede. Se il tuo video o la tua immagine ha un fondo di un colore solo, come un telo verde, spunta «Togli uno sfondo a tinta unita»: il colore si prende dall\'angolo in alto a sinistra, o dal punto dell\'anteprima che clicchi. Se l\'angolo è già trasparente, il colore sceglilo col clic. Nell\'anteprima il fondo sparisce subito, e quello che vedi è quello che va in onda: il server lo toglie con lo stesso calcolo. Se il soggetto si mangia, abbassa la «Sensibilità»; se resta un alone del fondo, alzala o allarga i «Bordi morbidi».',
      'Un riflesso del fondo sul soggetto, come il verde sui capelli davanti a un telo verde, resta: un colore solo non lo distingue. Se il browser non sa mostrare il formato, l\'anteprima non c\'è e il pannello te lo dice, ma il fondo si toglie lo stesso. Se il browser non sa far scorrere un\'animazione, nell\'anteprima vedi solo il primo fotogramma: in onda si muove. Un WebP animato a cui togli lo sfondo diventa un video, e si muove ancora. Da un AVIF lo sfondo non si toglie: va in onda com\'è, e se ha un fondo da togliere esportalo in PNG, WebP o video.',
      '<strong>«Dove appare».</strong> Nella scena, l\'immagine o il video sta nell\'area «Effetti a schermo» dell\'Overlay Studio. «Riempito» copre tutto lo schermo e taglia i bordi che avanzano; «intero» si vede tutto, e ai lati resta trasparente. Mai stirato. Va a tutto schermo solo negli overlay dove c\'è «Effetti a schermo».',
      'Premi «Carica effetto». Ogni file si comprime da solo, così l\'overlay resta leggero. L\'audio diventa mono, a volume uniforme, lungo al massimo 30 secondi. Le immagini diventano WebP col lato lungo al massimo di 1920 pixel, abbastanza per il tutto schermo. I video, le GIF e i PNG animati diventano video fino a 720 pixel di altezza e al massimo 30 secondi. Una GIF o un PNG animato va in onda al ritmo con cui lo vedi nel browser, anche se dichiara fotogrammi velocissimi. Un video trasparente resta trasparente, qualunque formato abbia: WebM o MKV con l\'alfa, MOV ProRes 4444, Animation o PNG, MOV e MP4 HEVC con l\'alfa di iPhone e Final Cut, AVI Ut Video, GIF e APNG. WebP animati e AVIF si tengono come sono, fino a 8 MB. Se un file dichiara la trasparenza e ne uscirebbe senza, il caricamento si ferma e te lo dice. Dai file caricati si tolgono i dati nascosti, come la posizione e il telefono con cui sono stati fatti. Audio e video durano quanto il file, fino a 30 secondi.',
      'Quando è finito il pannello lo conferma col comando nuovo: «Media caricato nella tua libreria», o «Combo caricata (media + suono)», seguito da <code>!comando</code>.',
      'Il comando è facoltativo: serve a chi vuole lanciare il media dalla chat. Se il media ti serve solo per un alert, per l\'overlay o per condividerlo, lascialo vuoto: il nome lo prende dal file.',
      'Un comando che esiste già viene <strong>sostituito</strong>: file, chi può usarlo, cooldown, volume, durata e «Dove appare» diventano quelli nuovi. È anche il modo per cambiarli dopo. Se non abbini un suono nuovo, la combo tiene quello di prima.',
      'Gli effetti sono al massimo 60 per canale, effetti pronti compresi. Lo spazio del canale, di serie 500 MB, vale per effetti, font, icone e media dei tasti di CONSOLify.',
    ] },
    { tabella: [
      ['Messaggio', 'Cosa vuol dire'],
      ['«Scegli un file da caricare.»', 'Manca il file.'],
      ['«file troppo grande (max 60MB)»', 'Il file supera 60 MB: accorcialo o rimpiccioliscilo prima.'],
      ['«tipo di file non supportato (usa audio, immagine o video)»', 'Il file non è audio, immagine o video.'],
      ['«questo file non lo so leggere: vanno bene PNG, JPG, WebP, AVIF, GIF, TIFF, MP4, WebM, MOV, MKV, AVI, MP3, WAV e OGG»', 'Il file dice di essere un\'immagine o un video, ma dentro non c\'è niente che si possa leggere: salvalo in uno di quei formati.'],
      ['«da un AVIF lo sfondo non si toglie: caricalo com\'è, o esportalo in PNG, WebP o video e riprova»', 'Un AVIF va in onda così com\'è: caricalo senza togliere lo sfondo, o esportalo in un altro formato.'],
      ['«la trasparenza di questo video si perderebbe: esportalo in WebM (VP9 con canale alfa) o in MOV ProRes 4444 e riprova»', 'Il video dichiara la trasparenza, o gli hai chiesto di togliere lo sfondo, ma quello che uscirebbe sarebbe opaco. Esportalo in uno dei due formati detti.'],
      ['«WebP animato troppo pesante: tienilo sotto gli 8 MB, o caricalo come GIF o video», o lo stesso per un AVIF', 'Un WebP animato o un AVIF non si ricomprime: sopra gli 8 MB peserebbe troppo sull\'overlay.'],
      ['«il suono abbinato si può mettere solo su immagini o video»', 'Hai abbinato un suono a un audio.'],
      ['«il file da abbinare deve essere un AUDIO»', 'Il secondo file non è un suono.'],
      ['«hai raggiunto il massimo di 60 effetti»', 'Elimina un effetto, oppure sostituiscine uno usando lo stesso comando.'],
      ['«spazio del canale esaurito: togli qualche media, effetto o font e riprova»', 'Libera spazio eliminando qualcosa.'],
    ] },

    { h3: 'Effetti pronti a tutto schermo' },
    { p: [
      'Otto effetti disegnati da noi, che coprono <strong>tutto lo schermo</strong> dell\'overlay dove gli effetti sono accesi. Ogni riquadro mostra l\'effetto, e passandoci sopra si muove; quello scelto si vede grande accanto ai suoi campi, ed è l\'effetto vero, lo stesso che va in onda. Si scelgono anche con le frecce della tastiera.',
      '«Aggiungi l\'effetto» lo mette fra i tuoi effetti col comando che scrivi, o col suo nome se lo lasci vuoto: «Aggiunto come !coriandoli: lo trovi nei tuoi effetti ✓». Se il comando è già di un altro effetto leggi «il comando !nome è già di un altro effetto», e quello non si tocca. Da lì parte come gli altri: dalla chat, da un premio a punti canale, da un comando della scheda «Comandi», da un gesto della webcam o da un livello delle donazioni.',
      'Per cambiarlo dopo, «Modifica» nella sua riga lo riapre qui, con «Modifichi» e il suo comando. Il comando resta quello; «Salva le modifiche» cambia il resto, e puoi anche passare a un altro disegno. «Prova sull\'overlay» lo manda in diretta, «Chiudi la modifica» torna a un effetto nuovo.',
    ] },
    { tabella: [
      ['Effetto', 'Com\'è', 'Durata di serie (limiti)'],
      ['Coriandoli', 'Due cannoni negli angoli in basso: i pezzi salgono, rallentano e ricadono girando.', '7 s (2 a 20)'],
      ['Fuochi d\'artificio', 'Razzi che salgono e scoppiano in sfere di scintille, alcune a due colori.', '8 s (4 a 30)'],
      ['Cuori', 'Salgono ondeggiando, battono piano e si dissolvono in alto.', '6 s (2 a 30)'],
      ['Neve', 'Fiocchi a profondità diverse; i più vicini sono cristalli.', '10 s (3 a 30)'],
      ['Palloncini', 'Salgono col loro filo fino a uscire dallo schermo.', '8 s (3 a 30)'],
      ['Bolle', 'Salgono ondeggiando e scoppiano.', '7 s (2 a 30)'],
      ['Stelle', 'Scintillii che si accendono e si spengono, e qualche stella cadente.', '5 s (2 a 30)'],
      ['Lampo', 'Un lampo che si spegne piano. Uno per volta: più lampi di fila possono far male a chi soffre di epilessia fotosensibile, e l\'overlay non li fa.', '1 s (1 a 3)'],
    ] },
    { tabella: [
      ['Campo', 'Di base', 'Limiti'],
      ['«Colori»', 'quelli dell\'effetto', 'fino a 5; «Colore» ne aggiunge uno, la × lo toglie, «Colori di serie» li rimette'],
      ['«Quanti»', 'Normale', 'Pochi · Normale · Tanti; il lampo non ce l\'ha'],
      ['«Durata»', 'quella dell\'effetto', 'i limiti della tabella qui sopra'],
      ['«Suono»', 'Nessuno', 'uno dei «Suoni pronti» o dei «I tuoi suoni»'],
      ['«Volume (%)»', '80', 'da 0 a 100'],
      ['«Comando in chat»', 'il nome dell\'effetto', 'facoltativo; solo lettere minuscole, numeri e _, fino a 24 caratteri'],
      ['«Chi può usarlo»', 'Tutti', 'Tutti · Solo sub · Solo VIP · Solo mod'],
      ['«Cooldown (s)»', '10', 'da 0 a 3600 secondi'],
    ] },
    { p: ['Un effetto pronto non è un media: non entra nella libreria e non si condivide.'] },

    { h3: 'I tuoi effetti' },
    { p: [
      'L\'elenco dei tuoi effetti. Ogni riga mostra <code>!comando</code>, il tipo, «tutto schermo», «combo» e «pubblico» quando servono, poi chi può usarlo, cooldown, volume e durata. Con la lista vuota leggi «Nessun effetto ancora: caricane uno qui sopra e provalo!»',
      'Immagini e video hanno «Dove appare»: si cambia lì e vale subito («Ora va a tutto schermo ✓», «Ora sta nella scena ✓»). Se a tutto schermo un media si ingrandisce più di una volta e mezza, la riga lo dice: «A tutto schermo questo media si ingrandisce 2,4 volte (è 800×450) e si vedrà sgranato: ricaricalo dal file originale.»',
      '«Condividi» lo mette nella libreria col nome che scegli, «Rendi privato» lo toglie. Gli effetti pronti hanno «Modifica» al suo posto. <strong>«Prova»</strong> te lo fa vedere qui, com\'è in onda: dice dove appare, a tutto schermo o nella scena, e lo mostra col suo suono, sopra una scacchiera che fa vedere dove è trasparente. «Rivedi» lo fa ripartire, «Manda all’overlay» lo manda in diretta. «Elimina» lo cancella dopo una conferma: il file sparisce dal server, e dove lo usavi non parte più.',
      'In fondo la riga «Spazio del canale» dice quanti MB usi e quanti ne hai.',
      '<strong>Come parte dalla chat.</strong> Qualcuno scrive <code>!comando</code> all\'inizio del messaggio. Se non ha il ruolo giusto, o il cooldown non è finito, non succede niente e il bot non risponde. Il cooldown vale per tutta la chat, non per persona.',
      'Un effetto lanciato dalla chat compare nell\'elemento <strong>«Effetti a schermo»</strong> dell\'Overlay Studio, o a tutto schermo se l\'hai scelto. I suoni partono subito. Immagini, video ed effetti pronti si mettono in fila e passano uno alla volta. Quando un effetto lo lancia un comando della scheda «Comandi», un gesto o un premio a punti canale, «Chi può usarlo» e il cooldown non contano.',
    ] },

    { h3: 'Effetti sui tuoi punti canale' },
    { p: [
      'Attacca un effetto a un premio a punti canale che hai già su Twitch. Quando qualcuno lo riscatta, nell\'overlay parte quello che scegli.',
      'La carta elenca tutti i tuoi premi, anche quelli creati fuori da qui. Per ognuno scegli fra «niente», «Suoni pronti», «I miei suoni caricati», «Immagini / Video» ed «Effetti pronti a tutto schermo». Il pulsante della libreria sceglie da lì. Nel campo sotto scrivi un messaggio in chat facoltativo, fino a 300 caratteri, con <code>{user}</code> per chi riscatta.',
      'Si salva da solo: «Effetto impostato ✓» e «Messaggio salvato ✓». Senza effetto e senza messaggio il premio torna libero.',
      '«Prova» fa sentire nel pannello un suono pronto. Su un tuo media o su un effetto pronto apre l\'anteprima, com\'è in onda, e da lì lo mandi all\'overlay. Senza scelta leggi «Scegli prima un effetto.»',
    ] },
    { tabella: [
      ['Solo per immagini e video', 'Di base', 'Limiti'],
      ['«Dove appare»', 'al centro dello schermo', 'trascini il riquadro nel box'],
      ['«Dimensione»', '100%', 'da 30 a 300%'],
      ['«Rotazione»', '0°', 'da −180 a 180°'],
      ['«Green screen» (solo video)', 'spento', 'toglie dal video lo sfondo di un colore'],
      ['«Colore da togliere»', 'verde puro', 'qualunque colore'],
      ['«Sensibilità»', '140', 'da 40 a 260'],
    ] },
    { p: [
      'Un media che in «I tuoi effetti» va a tutto schermo non ha una posizione: al posto del box leggi «A tutto schermo: questo media copre lo schermo, e la posizione qui non serve. Si cambia in «I tuoi effetti».»',
      'Se leggi «Per leggere i tuoi punti canale serve un permesso in più.», premi «Concedi il permesso» e autorizza di nuovo Twitch.',
      'Se non hai ancora premi, creane uno nella carta qui sotto e torna qui.',
    ] },

    { h3: 'Alert a punti canale' },
    { p: ['Crea un premio a punti canale nuovo su Twitch. Quando uno spettatore lo riscatta spendendo i suoi punti, parte un effetto nell\'overlay, un messaggio in chat, o tutti e due. Il premio compare da solo nella tua pagina Twitch.'] },
    { tabella: [
      ['Campo', 'Di base', 'Limiti'],
      ['«Nome del premio»', 'vuoto', 'da 2 a 45 caratteri'],
      ['«Costo (punti canale)»', '500', 'da 1 a 1.000.000'],
      ['«Effetto da lanciare»', 'nessun effetto', 'uno dei tuoi effetti'],
      ['«Messaggio in chat»', 'vuoto', 'facoltativo, 300 caratteri, <code>{user}</code> è chi riscatta'],
    ] },
    { p: [
      'Premi «Crea il premio». Serve almeno un effetto o un messaggio. L\'effetto compare nell\'area «Effetti a schermo» dell\'Overlay Studio, o a tutto schermo se l\'hai messo così. Il premio compare anche nella carta sopra, dove puoi dargli un posto suo sullo schermo e una grandezza.',
      '«I tuoi premi» elenca quelli creati da qui, con costo ed effetto. La ✕ lo elimina anche da Twitch, dopo una conferma: «Elimino questo premio da Twitch?».',
    ] },
    { tabella: [
      ['Messaggio', 'Cosa fare'],
      ['«dai un nome al premio»', 'Scrivi almeno due caratteri.'],
      ['«scegli un effetto o scrivi un messaggio»', 'Riempi almeno uno dei due.'],
      ['«Twitch ha rifiutato il premio (nome già usato?)»', 'Su Twitch c\'è già un premio con quel nome: cambialo.'],
      ['«Per creare premi a punti canale serve un permesso in più.»', 'Premi «Concedi il permesso».'],
    ] },

    { h3: 'Quando non funziona' },
    { ul: [
      '<strong>Scrivo il comando e non parte niente.</strong> Controlla «Chi può usarlo» e il cooldown: il bot resta zitto apposta. Il comando va all\'inizio del messaggio. L\'overlay deve essere aperto in OBS, con «Effetti a schermo» acceso in quell\'overlay.',
      '<strong>Si vede ma non si sente.</strong> In OBS la sorgente Browser deve avere «Controlla l\'audio via OBS». Controlla anche il volume dell\'effetto.',
      '<strong>Due immagini non compaiono insieme.</strong> È voluto: immagini, video ed effetti pronti passano uno alla volta, in fila.',
      '<strong>A tutto schermo è sgranato.</strong> Il file è piccolo per lo schermo intero, e la riga dell\'effetto te lo dice. Ricaricalo dal file originale con lo stesso comando.',
      '<strong>Il rilevatore non vede i gesti.</strong> La scheda del rilevatore deve restare aperta in Chrome, con la fotocamera consentita. Prova ad alzare la «Sensibilità».',
      '<strong>L\'overlay dei gesti è nero in OBS.</strong> Stai usando il modo tutto-in-uno: usa i due link del setup consigliato.',
      '<strong>Un premio non fa partire l\'effetto.</strong> Controlla il permesso dei punti canale e che il premio abbia un effetto scelto nella carta «Effetti sui tuoi punti canale».',
    ] },
  ],
  faq: [
    { d: 'Posso lanciare lo stesso media dalla chat e da un premio?', r: 'Sì. Il comando parte dalla chat con le sue regole, il premio lo lancia senza guardare ruolo e cooldown.' },
    { d: 'Come cambio il cooldown di un effetto che ho già?', r: 'Ricarica il file in «Carica un effetto» con lo stesso comando e i valori nuovi: sostituisce quello di prima. Un effetto pronto lo cambi con «Modifica».' },
    { d: 'Quello che prendo dalla libreria resta legato all\'autore?', r: 'È una copia tua, privata, che tiene il nome dell\'autore. Se lui lo cancella, la tua copia resta.' },
    { d: 'Posso decidere dove compare un effetto?', r: 'Sì. Nella scena, dove metti «Effetti a schermo» nell\'Overlay Studio; a tutto schermo, con «Dove appare» nella riga dell\'effetto; e per un premio a punti canale anche in un punto suo.' },
    { d: 'Posso togliere lo sfondo verde a un video?', r: 'Sì: mentre lo carichi spunta «Togli uno sfondo a tinta unita» e clicca sul fondo nell\'anteprima. Quello che vedi lì è quello che va in onda.' },
    { d: 'La webcam finisce sui vostri server?', r: 'No. I gesti si riconoscono nel browser del tuo computer: al bot arriva solo il nome del gesto.' },
  ],
};
