// Manuale: Manuale dei moduli. La forma dei manuali e il perche' stanno in
// src/web/manuali.js; le lingue in docs/LINGUE.md.

export default {
  slug: 'moduli',
  schede: ['moduli'],
  titolo: 'Manuale dei moduli: automazioni della chat | SocialBot',
  h1: 'Manuale dei moduli',
  desc: 'Quando succede qualcosa, se valgono certe condizioni, allora il bot fa. Inneschi, condizioni, azioni e variabili dei moduli di SocialBot, uno per uno.',
  aggiornata: '2026-09-04',
  corpo: [
    { p: [
      'Un <strong>modulo</strong> è un\'automazione che ti costruisci: <strong>QUANDO</strong> succede qualcosa, <strong>SE</strong> valgono certe condizioni, <strong>ALLORA</strong> il bot fa una o più cose.',
      'Con i moduli si fanno i comandi che ti mancano, le risposte automatiche, i giochi a monete, i saluti agli eventi, i timer, e i collegamenti verso servizi tuoi. Un modulo è <strong>dati</strong>, mai codice: quello che può fare è l\'elenco di azioni qui sotto, e nient\'altro. È il motivo per cui puoi costruirci sopra senza poter rompere niente — tuo o di altri.',
    ] },

    { h2: 'QUANDO: i sei inneschi' },
    { tabella: [
      ['Innesco', 'Parte quando', 'Cosa gli dai'],
      ['Comando', 'qualcuno scrive <code>!nome</code> in chat', 'il nome (senza <code>!</code>) e gli alias'],
      ['Parola', 'in un messaggio compare un testo', 'il testo, e se deve <em>contenerlo</em>, <em>esserlo</em> o <em>iniziare</em> così'],
      ['Evento', 'succede qualcosa sul canale', 'quale evento (sotto)'],
      ['Timer', 'ogni tot minuti', 'i minuti, e se vuoi un minimo di messaggi nuovi'],
      ['Manuale', 'solo quando lo lanci tu', 'niente: si lancia da «Prova» o da fuori'],
      ['Voce', 'lo dici a voce mentre streammi', 'la frase da riconoscere'],
    ] },
    { h3: 'Gli eventi' },
    { tabella: [
      ['Evento', 'Quando'],
      ['Nuovo follow', 'qualcuno inizia a seguirti'],
      ['Sub / resub', 'qualcuno si abbona o rinnova'],
      ['Raid', 'un altro canale ti manda i suoi spettatori'],
      ['Bits / cheer', 'qualcuno manda dei bit'],
      ['Riscatto punti canale', 'qualcuno riscatta un premio dei punti Twitch'],
      ['Primo messaggio di un utente', 'qualcuno scrive per la prima volta nel tuo canale'],
      ['Sei andato in live', 'la diretta comincia'],
      ['Fine live', 'la diretta finisce'],
      ['Gesto webcam (mani/volto)', 'la webcam riconosce un gesto o un\'espressione'],
    ] },
    { p: ['Il timer non parla nel vuoto: se chiedi un minimo di messaggi nuovi, il modulo tace quando la chat è ferma. È la differenza fra un promemoria e un bot che parla da solo davanti a nessuno.'] },

    { h2: 'SE: le condizioni' },
    { p: ['Sono tutte facoltative, e si sommano: passano <strong>tutte</strong> o il modulo non parte.'] },
    { tabella: [
      ['Condizione', 'Cosa fa', 'Limiti'],
      ['Chi può', 'da tutti, solo abbonati, solo VIP, solo moderatori', 'scala: tutti &lt; sub &lt; VIP &lt; mod'],
      ['Piattaforme', 'solo Twitch, solo Kick, o dove vuoi', 'se non scegli, vale ovunque'],
      ['Solo in diretta', 'il modulo tace a canale spento', '—'],
      ['Solo offline', 'il contrario: solo a canale spento', '—'],
      ['Monete richieste', 'serve almeno quel saldo, ma non si paga', '0–1.000.000'],
      ['Costo', 'quante monete si pagano per usarlo', '0–1.000.000, oppure una variabile'],
      ['Attesa', 'quanto aspetta prima di poter ripartire, per tutti', 'secondi'],
      ['Attesa a testa', 'quanto aspetta la stessa persona', '0–86.400 secondi'],
      ['Probabilità', 'quante volte su cento parte', '0–100'],
      ['Messaggio se non basta', 'cosa dice a chi non ha abbastanza monete', '300 caratteri'],
    ] },
    { h3: 'In che ordine vengono controllate' },
    { p: ['L\'ordine non è un dettaglio: decide <strong>quando si paga</strong>.'] },
    { tabella: [
      ['1', 'Chi può usarlo'],
      ['2', 'La piattaforma'],
      ['3', 'Diretta accesa o spenta'],
      ['4', 'Monete richieste e costo — qui si <em>controlla</em>, non si paga'],
      ['5', 'L\'attesa di tutti'],
      ['6', 'L\'attesa della singola persona'],
      ['7', 'Il pagamento: qui le monete escono davvero'],
      ['8', 'La probabilità'],
    ] },
    { p: ['Quindi si paga <strong>dopo</strong> le attese e <strong>prima</strong> del dado: chi gioca paga la giocata anche quando perde — che è come funziona una giocata — ma non paga se il comando era in attesa. Dopo il pagamento hai <code>$costo</code> (quanto è uscito) e <code>$saldo</code> (quanto è rimasto) da usare nei testi.'] },

    { h2: 'ALLORA: le quindici azioni' },
    { p: ['Si eseguono <strong>in fila</strong>, fino a otto per modulo. Se una fallisce, le altre vanno avanti lo stesso: un webhook spento non deve spegnere il messaggio in chat.'] },
    { tabella: [
      ['Azione', 'Cosa fa', 'Cosa le dai', 'Serve'],
      ['Scrivi in chat', 'manda un messaggio', 'il testo (fino a 400 caratteri)', '—'],
      ['Fai partire un effetto', 'lancia un tuo effetto o suono', 'quale effetto', 'un effetto già creato'],
      ['Dai o togli punti', 'muove le monete del canale', 'aggiungi/togli/imposta, a chi, quanto', '—'],
      ['Contatore', 'tiene un numero che cresce', 'nome, e se incrementare, azzerare o impostare', '—'],
      ['Crea una clip', 'salva una clip del momento', 'un testo da dire (facoltativo)', 'il permesso clip'],
      ['Cambia categoria Twitch', 'cambia il gioco del canale', 'il gioco, anche da <code>$args</code>', 'il permesso di modifica canale'],
      ['Cambia titolo stream', 'cambia il titolo', 'il testo (fino a 140 caratteri)', 'il permesso di modifica canale'],
      ['Metti una canzone in coda', 'aggiunge un brano su Spotify', 'il brano, anche da <code>$args</code>', 'add-on Musica e Spotify collegato'],
      ['Annuncio in chat (/announce)', 'un messaggio evidenziato in chat', 'il testo e il colore', 'il permesso annunci'],
      ['Shoutout (banner)', 'lo shoutout ufficiale di Twitch', 'chi, o il nome dopo il comando, o chi ha raidato', 'il permesso shoutout'],
      ['Mostra testo sull\'overlay', 'scrive a schermo nella diretta; dove e come si vede lo scegli nell\'Overlay Studio, elemento «Testo a schermo»', 'il testo e per quanto', 'l\'overlay in scena'],
      ['Timeout in chat', 'mette in pausa chi ha scritto', 'i secondi', 'il permesso di moderazione'],
      ['Aspetta', 'una pausa prima dell\'azione dopo', 'i secondi (fino a 30)', '—'],
      ['Chiama un webhook', 'manda i dati a un indirizzo tuo', 'l\'URL, e se usare la risposta', 'un servizio tuo'],
      ['Regia: scena, muto o transizione', 'comanda il programma con cui mandi in onda', 'la scena, o la fonte e come mutarla, o la transizione', 'il pannello aperto sul computer della regia, collegato in CONSOLify'],
      ['Modalità della chat a tempo', 'mette la chat in solo emote, messaggi unici o solo abbonati per un tempo, poi la rimette com\'era', 'quale modalità e per quanto (vuoto = 2 minuti, oppure 5m, 90s o $arg1)', 'il permesso di gestire le impostazioni della chat'],
    ] },
    { h3: 'Dai o togli punti' },
    { p: [
      'È l\'azione che trasforma un modulo in un gioco. <em>Aggiungi</em> e <em>togli</em> spostano, <em>imposta</em> mette una cifra esatta.',
      'Il destinatario può essere <strong>chi ha scritto</strong>, il <strong>nome dopo il comando</strong>, <strong>uno a caso</strong> fra chi ha parlato di recente, o un <strong>nome fisso</strong>. La quantità può essere un numero o una variabile: <code>$random(10,50)</code>, <code>$arg1</code>.',
      'Dopo, <code>$mossa</code> dice quante monete si sono mosse <strong>davvero</strong> e <code>$bersaglio</code> su chi. Sono la stessa cifra per tutte le azioni che seguono: senza, un furto toglierebbe una somma alla vittima e ne darebbe un\'altra al ladro.',
    ] },
    { h3: 'Chiama un webhook' },
    { p: [
      'Manda il contesto in JSON a un indirizzo tuo. Se rispondi con <code>{"reply": "testo"}</code> e hai spuntato «usa la risposta», il bot scrive quel testo in chat — con le variabili già espanse.',
      'Accetta solo <code>http</code> e <code>https</code>, e <strong>non può puntare dentro una rete privata</strong>: gli indirizzi interni sono rifiutati sia scritti direttamente sia dopo aver risolto il nome, e un redirect non aggira il controllo. Cinque secondi di tempo, risposta letta fino a 10 KB.',
    ] },

    { h3: 'Regia: scena, muto o transizione' },
    { p: [
      'È lo stesso passo dei tasti di CONSOLify, messo dentro un Modulo: così una scena cambia a comando (<code>!brb</code>), a voce, o quando succede qualcosa: un raid, l\'inizio o la fine della diretta.',
      'I nomi sono quelli del programma. Se la regia è collegata da questa pagina te li propongo mentre scrivi; una scena può venire anche dal comando: <code>$arg1</code> dopo <code>!scena</code>.',
      'Lo esegue il pannello aperto sul computer della regia, non il server: tienilo aperto mentre streami. Se non c\'è, il passo salta e le altre azioni del Modulo vanno avanti lo stesso.',
      'Tra i modelli pronti trovi <strong>Torno subito</strong> (scena di pausa e microfono muto), <strong>Sono tornato</strong> e <strong>Raid: scena dedicata</strong>: i nomi delle scene li adatti ai tuoi.',
    ] },

    { h2: 'Il ramo ALTRIMENTI' },
    { p: [
      'È quello che succede <strong>quando il dado non passa</strong>. Ha senso solo con una probabilità sotto il 100%: il pannello non lo lascia salvare altrimenti, perché un modulo che sembra fare due cose e ne fa una sola è peggio di un errore.',
      'Le azioni del ramo «altrimenti» sono le stesse quindici, e il costo è già stato pagato: la giocata persa può raccontarlo con <code>$costo</code> e <code>$saldo</code>.',
    ] },

    { h2: 'Le variabili' },
    { p: ['Si scrivono nei testi e diventano quello che valgono. Una variabile che non esiste sparisce, non lascia scritto il suo nome. Non c\'è nessun modo di eseguire codice: sono sostituzioni, e basta.'] },
    { h3: 'Chi scrive e cosa dice' },
    { tabella: [
      ['<code>$user</code>', 'chi ha scritto'],
      ['<code>$touser</code>', 'il nome scritto dopo il comando (o chi scrive, se manca)'],
      ['<code>$target</code>', 'come <code>$touser</code>'],
      ['<code>$args</code>', 'tutto quello che c\'è dopo il comando'],
      ['<code>$arg1</code>', 'la prima parola dopo il comando (poi <code>$arg2</code>, <code>$arg3</code>…)'],
      ['<code>$canale</code>', 'il nome del tuo canale'],
    ] },
    { h3: 'La diretta adesso' },
    { tabella: [
      ['<code>$uptime</code>', 'da quanto sei in diretta (vuoto se offline)'],
      ['<code>$gioco</code>', 'la categoria attuale'],
      ['<code>$titolo</code>', 'il titolo attuale'],
      ['<code>$spettatori</code>', 'quanti stanno guardando ora'],
    ] },
    { h3: 'Le persone' },
    { tabella: [
      ['<code>$followage</code>', 'da quanto ti segue chi scrive, o il nome dopo il comando'],
      ['<code>$ore</code>', 'ore guardate sul tuo canale (anche <code>$oreguardate</code>, <code>$watchtime</code>)'],
      ['<code>$serie</code>', 'dirette di fila di chi scrive, o del nome dopo il comando; <code>$dirette</code> quante in tutto, <code>$recordserie</code> la serie più lunga'],
      ['<code>$chattercaso</code>', 'uno a caso fra chi ha scritto di recente'],
      ['<code>$cita</code>', 'una citazione a caso fra quelle salvate'],
      ['<code>$giocotarget</code>', 'l\'ultima categoria di chi nomini dopo il comando'],
      ['<code>$titolotarget</code>', 'l\'ultimo titolo di chi nomini dopo il comando'],
    ] },
    { h3: 'Le monete' },
    { tabella: [
      ['<code>$punti</code>', 'quante ne ha chi scrive'],
      ['<code>$punti(nome)</code>', 'quante ne ha un altro'],
      ['<code>$monete</code>', 'come si chiama la tua moneta'],
      ['<code>$posizione</code>', 'in che posizione è chi scrive'],
      ['<code>$top(3)</code>', 'i primi tre, già scritti'],
      ['<code>$costo</code>', 'quanto è costato questo modulo'],
      ['<code>$saldo</code>', 'quanto è rimasto dopo il pagamento'],
      ['<code>$mossa</code>', 'quante monete ha mosso l\'ultima azione punti'],
      ['<code>$bersaglio</code>', 'su chi le ha mosse'],
    ] },
    { h3: 'Quando l\'innesco è un evento' },
    { tabella: [
      ['<code>$raider</code>', 'chi ti ha raidato'],
      ['<code>$viewers</code>', 'quanti ne ha portati'],
      ['<code>$mesi</code>', 'da quanti mesi è abbonato'],
      ['<code>$bits</code>', 'quanti bit ha mandato'],
      ['<code>$premio</code>', 'quale premio ha riscattato'],
      ['<code>$gesto</code>', 'il gesto riconosciuto dalla webcam'],
      ['<code>$emozione</code>', 'l\'espressione riconosciuta'],
    ] },
    { h3: 'Data e ora' },
    { tabella: [
      ['<code>$data</code>', 'la data di oggi'],
      ['<code>$ora</code>', 'che ore sono'],
      ['<code>$giorno</code>', 'che giorno della settimana è'],
    ] },
    { h3: 'Le funzioni' },
    { tabella: [
      ['<code>$random(1,100)</code>', 'un numero fra due'],
      ['<code>$random(6)</code>', 'un numero da 1 a 6'],
      ['<code>$decimale(1,2)</code>', 'un numero con la virgola'],
      ['<code>$misura(1,50,cm)</code>', 'un numero con l\'unità che vuoi'],
      ['<code>$pick(a|b|c)</code>', 'una a caso fra queste (anche <code>$scegli</code>)'],
      ['<code>$count(nome)</code>', 'quanto vale un contatore'],
      ['<code>$titolo($args)</code>', 'cambia il titolo mentre scrivi il messaggio'],
      ['<code>$categoria($args)</code>', 'cambia la categoria mentre scrivi il messaggio'],
    ] },
    { h3: 'Quelle a caso' },
    { p: ['Danno un valore nuovo <strong>a ogni volta che compaiono</strong>: due <code>$dado</code> nella stessa frase danno due numeri diversi.'] },
    { tabella: [
      ['<code>$dado</code>', 'da 1 a 6'],
      ['<code>$moneta</code>', 'testa o croce'],
      ['<code>$sino</code>', 'sì o no'],
      ['<code>$random</code> <code>$numero</code>', 'da 0 a 100'],
      ['<code>$percentuale</code>', 'da 0% a 100%'],
      ['<code>$livello</code>', 'da 1 a 100'],
      ['<code>$altezza</code>', 'da 1,40 m a 2,10 m'],
      ['<code>$peso</code>', 'da 40 a 130 kg'],
      ['<code>$lunghezza</code>', 'da 1 a 30 cm'],
      ['<code>$grandezza</code>', 'da 1 a 50 cm'],
      ['<code>$eta</code>', 'da 1 a 99 anni'],
      ['<code>$temperatura</code>', 'da -10 a 45 °C'],
      ['<code>$velocita</code>', 'da 1 a 320 km/h'],
      ['<code>$distanza</code>', 'da 1 a 1000 km'],
      ['<code>$soldi</code> <code>$euro</code>', 'da 0 a 100.000 €'],
      ['<code>$colore</code>', 'un colore'],
      ['<code>$animale</code>', 'un animale'],
      ['<code>$emoji</code>', 'una emoji'],
    ] },

    { h2: 'Tre esempi' },
    { h3: 'Un comando con una risposta viva' },
    { esempio: 'QUANDO   comando  !abbraccia\nALLORA   scrivi in chat\n         $user abbraccia $touser per $random(3,30) secondi.' },
    { h3: 'Un saluto ai raid, con lo shoutout' },
    { esempio: 'QUANDO   evento  Raid\nALLORA   scrivi in chat\n         Benvenuti! $raider è arrivato con $viewers persone.\nALLORA   shoutout  (a chi ha raidato)' },
    { h3: 'Una scommessa' },
    { esempio: 'QUANDO   comando  !scommetti\nSE       costo $arg1 · probabilità 45\nALLORA   dai punti  a chi scrive  +$arg1\nALLORA   scrivi in chat\n         $user punta $costo $monete e vince! Ora ne ha $punti.\nALTRIMENTI  scrivi in chat\n         $user punta $costo $monete e perde tutto. Ne restano $saldo.' },
    { p: ['Nel terzo: il costo è la cifra scritta da chi gioca, si paga sempre, e la vincita raddoppia perché la puntata era già uscita.'] },

    { h2: 'I contatori, e i comandi che decidi tu' },
    { p: ['Un contatore \u00e8 un numero con un nome: le morti, i tentativi, le volte che l\u2019hai detto. Sale, scende, torna a zero, e pu\u00f2 comparire a schermo nell\u2019overlay che hai gi\u00e0.'] },
    { p: ['<strong>Le parole le scegli tu</strong>, contatore per contatore. Sette verbi, e per ognuno decidi con quali parole si chiama e <strong>chi pu\u00f2 usarlo</strong>: tutti, solo i sub, i VIP in su, oppure mod e streamer. Se vuoi che aggiungere sia aperto a tutti ma azzerare no, si fa.'] },
    { tabella: [
      ['Leggi', 'il nome da solo', 'dice a che punto \u00e8'],
      ['Aggiungi', '<code>+</code> \u00b7 <code>add</code>', 'sale del passo, o del numero che scrivi'],
      ['Togli', '<code>-</code> \u00b7 <code>meno</code>', 'scende'],
      ['Azzera', '<code>reset</code> \u00b7 <code>azzera</code>', 'torna a zero'],
      ['Imposta', '<code>set</code>', 'lo porta al numero che scrivi'],
      ['Mostra a schermo', '<code>on</code> \u00b7 <code>mostra</code>', 'lo fa comparire, <strong>senza toccare il numero</strong>'],
      ['Nascondi', '<code>off</code> \u00b7 <code>nascondi</code>', 'lo toglie dallo schermo'],
    ] },
    { p: ['Quelle in tabella sono le parole di partenza: cambiale come vuoi. Lasciare una casella vuota <strong>toglie</strong> quel comando.'] },
    { p: ['<strong>Il numero vale attaccato o staccato</strong>, sempre: <code>!morti +3</code> e <code>!morti + 3</code> sono la stessa cosa, e lo stesso vale per tutti gli altri verbi. Senza numero vale il <strong>passo</strong> del contatore.'] },
    { p: ['<strong>Mostrare non azzera.</strong> Prima lo faceva, e chi aveva quarantasette morti e voleva solo farle comparire se le ritrovava a zero. Sono due verbi diversi: se vuoi tutte e due le cose, scrivi due comandi \u2014 o mettili sullo stesso tasto di CONSOLify.'] },
    { p: ['A chi non pu\u00f2, il bot <strong>lo dice</strong> invece di tacere, una volta ogni tanto per persona: un rifiuto muto sembra un bot rotto, uno a ogni tentativo diventa un modo per farlo parlare a raffica.'] },

    { h2: 'I comandi pronti, e chi vince' },
    { p: ['Il bot porta con sé una quarantina di comandi già fatti — giochi, sorteggi, ore guardate, shoutout, VIP, sondaggi, musica. In <em>Comandi</em>, in fondo alla scheda, ci sono tutti: ognuno si <strong>spegne</strong>, si <strong>rinomina</strong> e si può <strong>riservare</strong> ad abbonati, VIP o moderatori.'] },
    { p: ['Rinominare <strong>sostituisce</strong>: se chiami <code>!slot</code> in un altro modo, il nome di serie smette di rispondere. Un comando ha un nome, e lo scegli tu.'] },
    { p: ['Due comandi non possono chiamarsi allo stesso modo: il secondo non partirebbe mai. Se ci provi, il pannello rifiuta e ti dice quale nome è già preso.'] },
    { p: ['E la regola di sempre resta: <strong>un comando tuo con lo stesso nome vince su quello pronto</strong>. Non devi spegnere niente per sovrascrivere un comando di serie — basta crearne uno tuo che si chiami così.'] },

    { h2: 'Limiti e sicurezza' },
    { ul: [
      'Otto azioni per modulo, e la fila si ferma lì.',
      'Un messaggio in chat arriva a 400 caratteri, un titolo a 140.',
      'Una pausa può durare al massimo 30 secondi.',
      'Un\'azione punti può muovere al massimo un milione di monete per volta.',
      'I webhook non possono raggiungere una rete privata, non seguono i redirect e hanno cinque secondi di tempo.',
      'Le variabili sono sostituzioni di testo: nessun codice viene eseguito, né tuo né di chi scrive in chat.',
      'Il bot non innesca sé stesso: quello che dice non fa ripartire i tuoi moduli.',
    ] },

    { h2: 'Lanciare un modulo da fuori' },
    { p: [
      'Ogni canale ha una <strong>chiave</strong> (la vede solo il proprietario, mai un moderatore). Con quella, un programma tuo — un\'estensione, un pulsante della tastiera fisica, uno script — può far scrivere il bot o lanciare un modulo.',
      'Si manda una <code>POST</code> all\'indirizzo del canale con la chiave nell\'intestazione <code>Authorization</code>, e nel corpo cosa fare: un messaggio, un effetto, o un modulo. Trenta richieste al minuto. Una chiave sbagliata riceve un 404, senza dire perché.',
    ] },

    { h2: 'Quando un modulo non parte' },
    { ul: [
      '<strong>Controlla l\'ordine delle condizioni.</strong> Se c\'è un\'attesa in corso il modulo tace <em>prima</em> di pagare: sembra rotto e invece sta aspettando.',
      '<strong>La probabilità è quella che sembra?</strong> Con 20 su 100, quattro volte su cinque non succede niente — e senza il ramo «altrimenti» quel silenzio è indistinguibile da un guasto.',
      '<strong>Ti manca un permesso.</strong> Categoria, titolo, annunci, shoutout e clip li fa Twitch: se il permesso non c\'è, il bot lo dice in chat una volta e va avanti. Si riautorizza dalla dashboard.',
      '<strong>Hai un comando pronto con lo stesso nome?</strong> Vince il tuo, sempre. Se volevi quello pronto, cambia nome al tuo.',
      '<strong>Provalo.</strong> Il tasto «Prova» esegue il modulo saltando tutte le condizioni: se funziona lì, il problema è in una condizione, non in un\'azione.',
    ] },
  ],
  faq: [
    { d: 'Che differenza c\'è fra un comando e un modulo?', r: 'Un comando è un modulo con l\'innesco più semplice. Nel pannello i comandi hanno una schermata più corta perché la maggior parte delle volte basta quella; quando serve di più — condizioni, più azioni, un costo — è lo stesso motore.' },
    { d: 'Un modulo può fare più cose di seguito?', r: 'Sì, fino a otto azioni in fila, e puoi metterci una pausa in mezzo. Se una fallisce le altre continuano, così un servizio esterno spento non porta giù il resto.' },
    { d: 'Posso usare i moduli per fare un gioco a monete?', r: 'È esattamente quello per cui c\'è l\'azione punti, insieme al costo e alla probabilità. Nella scheda Giochi, in «I tuoi giochi», trovi sei ricette già scritte da cui partire: si aprono e si modificano lì, senza cambiare scheda.' },
    { d: 'I moduli funzionano anche su Kick?', r: 'Sì. Se vuoi, ogni modulo può essere limitato a una piattaforma sola; se non scegli niente vale ovunque.' },
    { d: 'Che succede se scrivo una variabile che non esiste?', r: 'Sparisce dal testo, senza lasciare il suo nome in chat e senza errori. Conviene comunque provare il modulo prima di lasciarlo agli spettatori.' },
  ],
};
