// Manuale: Manuale dei comandi. La forma dei manuali e il perche' stanno in
// src/web/manuali.js; le lingue in docs/LINGUE.md.

export default {
  slug: 'moduli',
  schede: ['moduli', 'ascolto'],
  titolo: 'Manuale dei comandi: moduli, contatori e voce | SocialBot',
  h1: 'Manuale dei comandi: moduli, contatori e comandi vocali',
  desc: 'Comandi rapidi, moduli QUANDO, SE, ALLORA, contatori, CONTATORify e comandi vocali di SocialBot: ogni carta, ogni campo, i valori di base e i limiti.',
  aggiornata: '2026-09-27',
  corpo: [
    { p: [
      'Questo manuale copre le due schede della famiglia <em>Comandi</em>, nel gruppo <em>Chat e pubblico</em>: <em>Comandi</em>, dove costruisci quello che il bot fa in chat, e <em>Comandi vocali</em>, dove lo comandi a voce mentre streammi.',
      'Un <strong>modulo</strong> è un\'automazione: <strong>QUANDO</strong> succede qualcosa, <strong>SE</strong> valgono certe condizioni, <strong>ALLORA</strong> il bot fa una o più cose. Un comando in chat è un modulo che scatta quando qualcuno scrive <code>!nome</code>. Un modulo è fatto di dati, mai di codice: può fare solo le azioni elencate qui sotto.',
    ] },

    // ------------------------------------------------------------ COMANDI
    { h2: 'Comandi', scheda: 'moduli', p: [
      'Qui crei i comandi della chat, le automazioni, i contatori, e scegli come si comportano i comandi che il bot porta già con sé.',
      'La scheda ha due parti, che scegli dalla barra in alto: <strong>«Comandi e contatori»</strong> e <strong>«CONTATORify»</strong>. Il pannello si ricorda l\'ultima che hai aperto.',
      'È nel piano <strong>Essenziale</strong>, gratis: le poche cose che chiedono un altro piano lo dicono al loro posto. Il tetto è di <strong>100 moduli per canale</strong>: oltre, il pannello risponde «hai raggiunto il massimo di 100 moduli». Proprietario e moderatori del pannello la usano allo stesso modo, con tre eccezioni che restano al proprietario: la chiave dei <em>Connettori avanzati</em>, i premi a punti canale dei contatori e i punti importati da un altro bot.',
    ] },

    { h3: 'Comando rapido' },
    { p: [
      'Il modo più corto per fare un comando. Scrivi il nome dopo il <code>!</code> e cosa deve rispondere, poi premi <strong>«Aggiungi comando»</strong>.',
      'Il nome tiene lettere minuscole, cifre e trattino basso, fino a 24 caratteri. Sotto la <strong>«Risposta»</strong> ci sono le variabili più usate: un clic le mette dove sta il cursore. La legenda <strong>«Cosa significano i $ (legenda)»</strong> le spiega tutte.',
      'Il comando nasce come modulo col nome «Comando !nome», aperto a tutti e senza attese. Lo trovi in <strong>«I tuoi moduli»</strong>: da lì lo cambi con «Modifica».',
      'Se manca il nome il pannello dice «Scrivi il nome del comando (senza !).», se manca la risposta «Scrivi cosa deve rispondere il bot.». Il pannello non controlla se il nome esiste già: due moduli con lo stesso comando rispondono tutti e due.',
    ] },
    { p: [
      'Nel riquadro <strong>«Comandi pronti (1 clic)»</strong> ci sono due comandi già configurati, riservati a moderatori e streamer. <strong>«Crea comando !categoria»</strong> crea <code>!categoria</code> (anche <code>!gioco</code>): in chat si scrive <code>!categoria Fortnite</code> e il bot cerca su Twitch la categoria più somigliante. <strong>«Crea comando !titolo»</strong> crea <code>!titolo</code>, che si usa come <code>!titolo In diretta!</code>. Se il comando c\'è già, accanto leggi «!categoria esiste già ✓» e non ne nasce un secondo. Serve il permesso <em>Gestione canale</em> di Twitch.',
      'Lo stesso lo fai dentro una risposta qualsiasi con <code>$categoria($args)</code> e <code>$titolo($args)</code>: il pezzo sparisce dal messaggio, il cambio avviene, e la conferma la scrivi tu attorno.',
    ] },

    { h3: 'Comodità in chat' },
    { p: ['Tre interruttori, che valgono dopo <strong>«Salva»</strong>.'] },
    { tabella: [
      ['Interruttore', 'Di base', 'Cosa fa'],
      ['«Gestisci i comandi dalla chat (per i mod)»', 'spento', 'I moderatori creano comandi di solo testo senza aprire il pannello: <code>!comando aggiungi !nome risposta</code>, <code>!comando modifica !nome risposta</code>, <code>!comando elimina !nome</code>, <code>!comando lista</code>, e le forme corte <code>!addcom</code>, <code>!editcom</code>, <code>!delcom</code>.'],
      ['«Conta le ore guardate in chat»', 'acceso', 'Ogni cinque minuti di diretta accredita il tempo a chi è in chat, anche a chi non scrive. Accende <code>!ore</code>, <code>!classificaore</code> e la variabile <code>$ore</code>.'],
      ['«Comandi base pronti»', 'acceso', 'Accende <code>!so</code>/<code>!shoutout</code> (solo moderatori e streamer, solo in diretta), <code>!followage</code>, <code>!uptime</code> e <code>!bit</code>.'],
    ] },
    { p: [
      'I comandi creati dalla chat sono solo testo: accettano solo <code>{user}</code> (il nome di chi scrive), fino a 400 caratteri, con un nome fino a 25 caratteri. Non compaiono in «I tuoi moduli»: li elenchi in chat con <code>!comando lista</code>, che può scrivere chiunque. Crearli, cambiarli e toglierli resta sempre ai moderatori e a te. Per variabili, condizioni ed effetti serve un modulo.',
      '<code>!bot</code> e <code>!ia</code> rispondono sempre, qualunque cosa dicano questi interruttori: chiunque in chat può sapere che alcune risposte sono scritte da un\'intelligenza artificiale. Se ti costruisci un tuo <code>!bot</code>, risponde il tuo.',
    ] },

    { h3: 'Moduli' },
    { p: [
      '<strong>«Nuovo modulo (avanzato)»</strong> apre l\'editor vuoto. Sotto ci sono i modelli: ognuno apre l\'editor già compilato, e niente è salvato finché non premi «Salva». Se la regia è collegata, i modelli di regia prendono le tue scene che contengono Pausa, Gioco o Raid nel nome, e la fonte del microfono; se non la trovano, scrivono quei nomi e tu li adatti ai tuoi.',
    ] },
    { tabella: [
      ['Modello', 'Cosa prepara'],
      ['«Saluto»', '<code>!ciao</code> risponde «Ciao $user!»'],
      ['«Shoutout»', '<code>!so</code> (anche <code>!shoutout</code>, <code>!sh</code>), solo mod: shoutout ufficiale al nome dopo il comando, con il suo ultimo gioco'],
      ['«Auto-shoutout ai raid»', 'all\'evento Raid, shoutout a chi ti ha raidato e un grazie in chat'],
      ['«Annuncio»', '<code>!annuncio</code> (anche <code>!ann</code>), solo mod: annuncio evidenziato col testo scritto dopo'],
      ['«Timer annuncio»', 'ogni 15 minuti, se ci sono almeno 10 messaggi nuovi: «Ricordati di seguire il canale!»'],
      ['«Social»', '<code>!social</code> col link della tua pagina'],
      ['«Contatore morti»', '<code>!morte</code>, solo mod: fa +1 al contatore <code>morti</code> e scrive «Morti oggi: $count(morti)»'],
      ['«Comando vocale: clippa»', 'quando dici «clippa» o «salva la clip», crea una clip'],
      ['«Collega il mio bot (webhook)»', '<code>!chiedi</code> chiama un tuo indirizzo e scrive la sua risposta. Si salva solo dopo aver scritto l\'URL.'],
      ['«Torno subito (regia)»', '<code>!brb</code> (anche <code>!pausa</code>), solo mod: scena di pausa, microfono muto, messaggio'],
      ['«Sono tornato (regia)»', '<code>!torno</code> (anche <code>!back</code>), solo mod: scena di gioco, microfono acceso, «Rieccomi!»'],
      ['«Raid: scena dedicata»', 'all\'evento Raid: scena Raid, benvenuto, 20 secondi, di nuovo la scena di gioco'],
      ['«Macchinetta a monete»', '<code>!slot</code>: costa 50 monete, vince 1 volta su 4 da 150 a 400, 30 secondi a testa'],
      ['«Scommessa»', '<code>!scommetti 100</code> (anche <code>!punta</code>): paga la puntata, 45 volte su 100 la raddoppia, 60 secondi a testa'],
      ['«Furto»', '<code>!furto</code> (anche <code>!ruba</code>): serve averne almeno 100, 40 volte su 100 ruba da 20 a 80 monete a uno a caso, 5 minuti a testa'],
      ['«Regala monete»', '<code>!regala @nome 50</code> (anche <code>!dona</code>): passa monete tue a un altro'],
      ['«Quante monete ho»', '<code>!monete</code> (anche <code>!punti</code>, <code>!saldo</code>): saldo, posizione e primi tre'],
      ['«Dai monete (mod)»', '<code>!dai @nome 50</code>, solo mod: monete dal nulla a qualcuno'],
    ] },
    { p: ['Le sei ricette a monete sono le stesse che trovi in «I tuoi giochi» nella scheda <em>Giochi &amp; classifiche</em>. Il <a href="/manuale/giochi">manuale dei giochi</a> spiega le monete.'] },

    { h3: 'Porta qui quello che hai già' },
    { p: [
      'Serve a chi arriva da Nightbot, StreamElements, Fossabot o un altro bot. Porta qui i comandi, i timer e i punti del tuo pubblico. Incolla l\'export del tuo bot (JSON), un CSV o quello che copi da un foglio di calcolo, oppure un elenco con una riga per cosa: <code>!social I miei social sono…</code> per un comando, <code>ogni 15 minuti: Seguimi su Instagram</code> per un timer, <code>marco 1200</code> per i punti di una persona. Con <strong>«Apri un file»</strong> scegli un file .json, .csv o .txt fino a 1,5 MB.',
      '<strong>«Guarda cosa succede»</strong> non scrive niente: ti mostra cosa entrerebbe. In cima leggi «Ho letto…» con quanti comandi, timer e saldi ha trovato; se i posti dei moduli non bastano, anche quanti ne restano. Sotto c\'è una parte per ognuno. Se cambi il testo, l\'anteprima sparisce e la rifai: si importa solo quello che hai visto.',
      'Se il pannello risponde che non riconosce il formato, incolla l\'export così com\'è, oppure riscrivi le righe nella forma dell\'elenco qui sopra.',
    ] },
    { tabella: [
      ['Parte', 'Cosa c\'è dentro'],
      ['«Comandi»', 'i comandi pronti da importare, con la risposta già tradotta. «sostituisce quello che hai» vuol dire che hai già un comando con quel nome e verrà aggiornato; «identico: lo salto» che è già uguale.'],
      ['«Timer»', 'i timer, ognuno col suo messaggio e sotto quando parla: «ogni 15 min, se in chat ci sono almeno 2 messaggi, anche a canale spento». Un timer si riconosce dal nome, quindi «sostituisce quello che hai» e «identico: lo salto» valgono come per i comandi. Uno spento nel bot di prima «entra spento».'],
      ['«Punti»', 'quante persone ricevono monete, quante in tutto, e i saldi più alti come saranno dopo.'],
    ] },
    { p: [
      '<strong>Da rivedere.</strong> Dentro «Comandi» e «Timer» ci può essere un secondo elenco: sono quelli che usano cose del bot di prima che qui si fanno in un altro modo, per esempio una chiamata a un sito esterno (qui è l\'azione «Chiama un webhook»), o un timer che partiva solo in certi giorni. Accanto c\'è il perché. Entrano solo se spunti <strong>«Importa lo stesso quelli da rivedere: li sistemo io dopo»</strong>, così come sono: un comando da rivedere scrive in chat il pezzo che non si è tradotto, finché non lo sistemi tu.',
      '<strong>«Scartati».</strong> Si apre con un clic e dice cosa non entra, col motivo: un nome che non si può usare, un nome ripetuto nel file, una risposta vuota, un bot, un numero che non è un saldo, un intervallo che non si legge o più lungo di un giorno.',
      'Le variabili si traducono da sole: <code>$(user)</code> diventa <code>$user</code>, <code>$(touser)</code> diventa <code>$touser</code>, <code>$(query)</code> diventa <code>$args</code>, <code>$(1)</code> diventa <code>$arg1</code>, <code>$(channel)</code>, <code>$(game)</code>, <code>$(title)</code>, <code>$(uptime)</code> e <code>$(viewers)</code> diventano <code>$canale</code>, <code>$gioco</code>, <code>$titolo</code>, <code>$uptime</code> e <code>$spettatori</code>, <code>$(count)</code> diventa il contatore col nome del comando.',
    ] },
    { h3: 'Timer da un altro bot' },
    { p: [
      'L\'intervallo si legge in minuti, in forme come <code>15m</code>, <code>1h</code> o <code>2 ore</code>, e nell\'orario che usa Nightbot (<code>*/15 * * * *</code>). Un orario che non si ripete a distanze uguali, o che valeva solo in certi giorni, entra da rivedere col motivo accanto. Il minimo di messaggi in chat resta lo stesso numero che avevi, fino a 1.000.',
      'Un timer di Nightbot parla anche a canale spento, come faceva là. Uno di StreamElements che aveva un ritmo per la diretta e uno per fuori diventa due timer, «(in diretta)» e «(fuori diretta)». Se alternava più messaggi, qui ne esce uno per volta, scelto a caso. Un timer senza nome prende le prime parole del suo messaggio, così importare due volte lo stesso elenco non lo raddoppia.',
      'Un timer che scriveva <code>!discord</code> faceva partire il comando. Qui un timer scrive e basta, quindi prende la risposta di <code>!discord</code>, se il comando c\'è. Se non c\'è, entra da rivedere.',
    ] },
    { h3: 'Punti da un altro bot' },
    { p: [
      'I punti diventano monete del canale e si sommano a quelle che ognuno ha già qui. In <strong>«Ogni quanti punti di prima, una moneta»</strong> scegli il cambio, di base 1: con 10, mille punti diventano cento monete. Cambiarlo rifà l\'anteprima.',
      'Puoi importare di nuovo quando vuoi: conta l\'ultimo file, e nessuno riceve due volte gli stessi punti. Chi non è nel file resta com\'è. Le ore guardate non si portano.',
      'I punti li importa solo il proprietario del canale, come le monete date a mano. Un moderatore vede l\'anteprima, e importando porta comandi e timer.',
    ] },
    { p: [
      'Premi <strong>«Importa»</strong>. Il pannello dice cosa ha fatto: comandi e timer nuovi e aggiornati, e a quante persone sono arrivate monete. Ogni comando diventa un modulo che si chiama «!nome», con l\'azione «Scrivi in chat»; ogni timer un modulo «A tempo (timer)». Comandi e timer si dividono i 100 posti dei moduli: se finiscono, leggi quanti «non sono entrati: hai finito i posti.».',
      'Dal bot di prima non arrivano il livello utente né le attese: un comando che là era solo per i mod qui è aperto a tutti. Riserva a mano quelli che vanno riservati. Si leggono i primi 500 comandi, 100 timer e 50.000 saldi del file, e ogni risposta fino a 400 caratteri.',
    ] },

    { h3: 'I tuoi moduli' },
    { p: [
      'L\'elenco di quello che hai costruito. Ogni riga ha l\'interruttore (acceso o spento, subito), il nome e un riassunto che si legge così: «QUANDO scrivono !ciao · SE solo i mod → invia un messaggio».',
      '<strong>«Prova»</strong> esegue il modulo una volta, adesso, saltando tutte le condizioni, come se l\'avessi scritto tu. In prova <code>$args</code> vale «esempio prova» e le variabili degli eventi hanno valori finti (RaiderDiProva, 42 spettatori, 100 bit). <strong>«Modifica»</strong> apre l\'editor. <strong>«Elimina»</strong> chiede conferma e non si torna indietro.',
      'Se l\'elenco è vuoto leggi «Nessun modulo ancora: parti da un modello qui sopra».',
    ] },

    { h3: 'L\'editor: nome e QUANDO' },
    { p: [
      'Si apre sotto l\'elenco. In cima c\'è il riassunto del modulo, che cambia mentre scrivi. Il <strong>«Nome del modulo»</strong> è obbligatorio: senza, il pannello dice «Dai un nome al modulo.». Ne restano i primi 80 caratteri.',
      'In <strong>«Cosa fa scattare il modulo»</strong> scegli uno dei sei inneschi.',
    ] },
    { tabella: [
      ['Innesco', 'Parte quando', 'Campi'],
      ['«Un comando in chat»', 'qualcuno scrive <code>!nome</code>', '«Comando (senza !)», «Alias» separati da spazio, «Attiva anche senza !», «Abilita anche su Telegram»'],
      ['«Una parola, frase o domanda in chat»', 'in un messaggio compare un testo', 'una frase per casella («+ Aggiungi frase»), «Come confrontarle», punteggiatura, maiuscole, Telegram'],
      ['«Comando vocale (dal tuo PC)»', 'lo dici al microfono con la pagina di ascolto aperta', '«Frasi da ascoltare (una per riga)», «Manda il messaggio anche su Telegram quando lo dico a voce»'],
      ['«Un evento del canale»', 'succede qualcosa sul canale', '«Quale evento»'],
      ['«A tempo (timer)»', 'ogni tot minuti', '«Ogni quanti minuti», «Solo se almeno N messaggi», «Falla parlare anche a canale spento»'],
      ['«Manuale / da un mio servizio»', 'solo quando lo lanci tu', 'nessuno: parte da «Prova» o dai <em>Connettori avanzati</em>'],
    ] },
    { p: [
      '<strong>Comando.</strong> «Attiva anche senza !» fa scattare il comando anche quando qualcuno scrive solo la parola, da sola nel messaggio (<code>disc</code> e non <code>!disc</code>). Dentro una frase non scatta.',
      '<strong>Parola.</strong> «Come confrontarle» ha tre scelte: «Compare dentro il messaggio», «È esattamente il messaggio», «Il messaggio inizia così». Basta che una frase combaci. «Ignora la punteggiatura» è acceso di base, così «come stai?» combacia con «come stai». «Rispetta maiuscole/minuscole» è spento di base.',
      '<strong>Telegram.</strong> Con «Abilita anche su Telegram» il modulo risponde anche nel gruppo, dove il comando scatta pure dentro una frase e senza <code>!</code>. Nel gruppo il bot esegue solo le azioni «Scrivi in chat», e risponde il primo modulo che combacia. Un modulo vocale con Telegram acceso manda i suoi messaggi anche nel gruppo. Serve il «Bot interattivo nel gruppo», che accendi nella scheda <em>Telegram</em> del gruppo <em>Le tue community</em>, nel piano Base.',
      '<strong>Voce.</strong> Scrivi le frasi come le dici, una per riga: il pannello le salva in minuscolo. Basta che la frase compaia dentro quello che dici: «ok clippa adesso» fa scattare «clippa». Scattano solo col pacchetto «Comandi Vocali» e con la pagina di ascolto aperta: tutto nella sezione <em>Comandi vocali</em> più sotto.',
      '<strong>Timer.</strong> Minuti da 1 a 1.440 (di base 15), messaggi da 0 a 1.000 (0 vuol dire a tempo e basta). Di norma un timer parla solo mentre sei in diretta: per farlo parlare a canale spento spunta «Falla parlare anche a canale spento» oppure la condizione «Solo se sono offline». I messaggi contati sono quelli delle persone, non del bot. Un timer appena creato parla la prima volta dopo un intervallo intero. Se più timer scadono insieme, parlano uno alla volta a 7 secondi di distanza.',
    ] },
    { h3: 'Gli eventi' },
    { tabella: [
      ['Evento', 'Quando', 'Variabili in più'],
      ['Nuovo follow', 'qualcuno ti segue per la prima volta. Chi toglie e rimette il follow non lo fa scattare di nuovo.', '<code>$user</code> è chi segue'],
      ['Sub / resub', 'qualcuno si abbona o rinnova', '<code>$mesi</code>'],
      ['Raid', 'un altro canale ti manda i suoi spettatori', '<code>$raider</code>, <code>$viewers</code>'],
      ['Bits / cheer', 'qualcuno manda dei bit', '<code>$bits</code>'],
      ['Riscatto punti canale', 'qualcuno riscatta un qualsiasi premio a punti canale', '<code>$premio</code>'],
      ['Primo messaggio di un utente', 'qualcuno scrive per la prima volta nel tuo canale (lo segna Twitch)', '<code>$user</code>'],
      ['Sei andato in live', 'la diretta comincia', ''],
      ['Fine live', 'la diretta finisce', ''],
      ['Gesto webcam (mani/volto)', 'il tracking della webcam riconosce un gesto della mano o un\'espressione del volto', '<code>$gesto</code>, <code>$emozione</code>'],
    ] },
    { p: ['Se costruisci un modulo sul primo messaggio, il saluto automatico del bot alle facce nuove tace e resta il tuo. Il gesto richiede il tracking della webcam, che si accende in <em>Scena &amp; overlay</em>, <em>Effetti &amp; suoni</em>: lo spiega il <a href="/manuale/effetti">manuale degli effetti</a>.'] },

    { h3: 'SE: le condizioni' },
    { p: [
      'Stanno in <strong>«Se (facoltativo)»</strong>, che si apre con un clic. È già aperto se il modulo ha un livello diverso da «Tutti», un «Cooldown (s)», una probabilità sotto 100 o una delle due condizioni sulla diretta. Sono tutte facoltative e si sommano: devono passare <strong>tutte</strong>, o il modulo non parte.',
    ] },
    { tabella: [
      ['Campo', 'Cosa fa', 'Di base', 'Limiti'],
      ['«Chi può attivarlo»', '«Tutti», «Solo sub», «Solo VIP», «Solo mod». Vale da quel livello in su: «Solo sub» lascia passare anche VIP e mod.', 'Tutti', 'scala: tutti, sub, VIP, mod'],
      ['«Cooldown (s)»', 'dopo che è partito, per un po\' non riparte per nessuno', '0', 'da 0 a 86.400 secondi'],
      ['«Cooldown per persona (s)»', 'ferma solo chi l\'ha appena usato: è quello che serve ai giochi', '0', 'da 0 a 86.400 secondi'],
      ['«Probabilità (%)»', 'quante volte su cento parte', '100', 'da 0 a 100'],
      ['«Da quanti Bit in su» e «Fino a quanti Bit»', 'compaiono solo con gli eventi Bits / cheer, Raid e Sub / resub, e il nome segue l\'evento: «Da quanti spettatori in su» col raid, «Da quanti mesi in su» col sub. È la fascia in cui il modulo scatta.', '0, cioè nessun limite', 'da 0 a 10.000.000'],
      ['«Costa (monete)»', 'quante monete paga chi lo usa. Accetta un numero o una variabile, come <code>$arg1</code>.', 'niente', 'da 0 a 1.000.000; una variabile fino a 60 caratteri'],
      ['«Serve almeno (senza spenderli)»', 'serve avere quel saldo, che non viene toccato', '0', 'da 0 a 1.000.000'],
      ['«Cosa dire a chi non ha abbastanza monete»', 'il messaggio a chi non può pagare. Senza, tace.', 'vuoto', '300 caratteri'],
      ['«Su quali piattaforme»', 'Twitch, Kick, YouTube. Nessuna spuntata vuol dire su tutte.', 'tutte', 'compare solo con almeno due piattaforme collegate'],
      ['«Solo se sono in live»', 'il modulo tace a canale spento', 'spento', ''],
      ['«Solo se sono offline»', 'il modulo parla solo a canale spento', 'spento', ''],
    ] },
    { p: [
      'Nelle etichette la moneta ha il nome che le hai dato in <em>Giochi &amp; classifiche</em>. Con le fasce fai una scala: un modulo per 1-99 bit, uno per 100-999, uno da 1.000 in su. Un massimo più basso del minimo viene ignorato. Chi resta fuori dalla fascia non paga e non consuma il cooldown.',
      'Sugli eventi, sui timer, sulla voce, su Telegram e sui moduli manuali «Chi può attivarlo» non ferma niente. Lo stesso vale per «Costa (monete)» e «Serve almeno»: paga solo chi fa scattare il modulo scrivendo in chat un comando o una parola, col suo nome utente. Sugli eventi (anche il primo messaggio), sui timer, sulla voce, su Telegram e sui moduli manuali il modulo parte e non paga nessuno, nemmeno tu.',
    ] },
    { h3: 'In che ordine vengono controllate' },
    { p: ['L\'ordine decide <strong>quando si paga</strong>.'] },
    { tabella: [
      ['Passo', 'Controllo'],
      ['1', '«Chi può attivarlo»'],
      ['2', '«Su quali piattaforme»'],
      ['3', 'la fascia di bit, spettatori o mesi'],
      ['4', 'in live o offline'],
      ['5', 'il saldo richiesto e il costo: qui si <em>controlla</em> e basta'],
      ['6', '«Cooldown (s)»'],
      ['7', '«Cooldown per persona (s)»'],
      ['8', 'il pagamento: qui le monete escono davvero'],
      ['9', '«Probabilità (%)»'],
    ] },
    { p: [
      'Si paga dopo le attese e prima del dado. Chi gioca paga anche quando perde, e non paga se il comando era in attesa o se non poteva usarlo. Chi non ha abbastanza monete non consuma il cooldown. Dopo il pagamento hai <code>$costo</code> (quanto è uscito) e <code>$saldo</code> (quanto è rimasto) da usare nei testi.',
    ] },

    { h3: 'ALLORA: le sedici azioni' },
    { p: [
      'Si eseguono in fila, dall\'alto, e il bot ne fa al massimo <strong>otto per modulo</strong>: quelle dopo l\'ottava non partono. Con ↑ e ↓ cambi l\'ordine, con × ne togli una, con «+ Aggiungi azione» ne aggiungi. Se un\'azione fallisce, le altre vanno avanti lo stesso. Senza nemmeno un\'azione il pannello dice «Aggiungi almeno un\'azione.».',
    ] },
    { tabella: [
      ['Azione', 'Cosa fa', 'Campi', 'Serve'],
      ['Scrivi in chat', 'manda un messaggio', 'il testo, fino a 400 caratteri', ''],
      ['Fai partire un effetto', 'lancia un tuo effetto o suono, senza guardare chi può usarlo e le sue attese', '«Quale effetto», fra i tuoi effetti accesi', 'un effetto creato in <em>Scena &amp; overlay</em>, <em>Effetti &amp; suoni</em>, e l\'overlay in scena'],
      ['Crea una clip', 'salva una clip del momento e scrive in chat «Clip salvata!» col link', 'nessuno', 'diretta su Twitch e il permesso clip'],
      ['Cambia categoria Twitch', 'cerca su Twitch la categoria più somigliante e la imposta', '«Categoria / gioco», anche con variabili come <code>$args</code>; «Annuncia il cambio in chat»', 'il permesso <em>Gestione canale</em>'],
      ['Cambia titolo stream', 'cambia il titolo della diretta', '«Nuovo titolo», fino a 140 caratteri, con variabili; «Annuncia il cambio in chat»', 'il permesso <em>Gestione canale</em>'],
      ['Contatore', 'muove un contatore', '«Nome contatore»; «Operazione»: «Incrementa (+1)», «Azzera», «Imposta a…»; «Valore (se "imposta")»', 'niente: se il contatore non c\'è ancora, nasce nella carta <em>Contatori</em>'],
      ['Chiama un webhook', 'manda i dati del momento a un indirizzo tuo', '«URL del tuo servizio (https)»; «Usa la risposta come messaggio in chat»', 'un tuo servizio'],
      ['Aspetta', 'una pausa prima dell\'azione dopo', '«Secondi da aspettare», di base 2', 'al massimo 30 secondi'],
      ['Mostra testo sull\'overlay', 'scrive un testo a schermo nella diretta; dove e come si vede lo scegli nell\'Overlay Studio, elemento «Testo a schermo»', 'il testo; «Durata a schermo (ms)» da 500 a 30.000, di base 5.000', 'l\'overlay in scena, con «Testo a schermo» acceso nell\'Overlay Studio (lo è di base)'],
      ['Timeout in chat', 'mette in pausa chi ha scritto il comando', '«Timeout (secondi)» da 1 a 1.209.600 (14 giorni), di base 600', 'il permesso di moderazione'],
      ['Metti una canzone in coda', 'aggiunge un brano alla coda del tuo Spotify', '«Brano da mettere in coda» (nome, artista o <code>$args</code>); «Annuncia in chat il brano aggiunto»', 'Spotify collegato, Premium e l\'app aperta'],
      ['Annuncio in chat (/announce)', 'l\'annuncio evidenziato di Twitch', 'il testo; «Colore dell\'annuncio»: «Predefinito (viola)», «Blu», «Verde», «Arancione», «Viola»', 'il permesso annunci'],
      ['Shoutout (banner)', 'lo shoutout ufficiale di Twitch', '«Canale a cui fare shoutout» (vuoto vuol dire il nome dopo il comando, o chi ti raida); «Messaggio extra in chat (facoltativo)»', 'essere in diretta e il permesso shoutout'],
      ['Dai o togli punti', 'muove le monete del canale', '«Cosa fare»: «Dai», «Togli», «Porta esattamente a»; «Quanti»; «A chi»', 'fino a 1.000.000 di monete per volta'],
      ['Regia: scena, muto o transizione', 'comanda il programma con cui mandi in onda', '«Cosa fare»: «Cambia scena», «Muta o smuta una fonte», «Cambia transizione»; il nome della scena, della fonte o della transizione, fino a 80 caratteri; per la fonte «Come»: «Muta», «Smuta», «Inverti»', 'il pannello aperto sul computer della regia, collegata in CONSOLify'],
      ['Modalità della chat a tempo', 'mette la chat in una modalità per un tempo, poi la rimette com\'era', '«Quale modalità»: «Solo emote», «Messaggi unici», «Solo abbonati»; «Per quanto»; «Lo dico in chat, quando parte e quando finisce»', 'il permesso di gestire le impostazioni della chat'],
    ] },
    { p: [
      '<strong>Messaggi del bot.</strong> Con «Annuncia il cambio in chat» acceso, categoria e titolo scrivono «🎮 Categoria aggiornata: …» e «📝 Titolo aggiornato: …», e se la categoria non si trova «🤔 Non ho trovato la categoria "…".». Se manca il permesso per categoria, titolo, annuncio o shoutout, il bot lo dice in chat con un 🔒 e le altre azioni vanno avanti: se il comando l\'ha scritto uno dello staff (tu o un moderatore) gli dice anche di riautorizzare dalla dashboard, agli altri solo che adesso non può. La clip, se non riesce (canale spento o permesso mancante), non scrive niente. Lo shoutout scrive il «Messaggio extra» solo se è riuscito.',
      '<strong>Cambia categoria.</strong> Fra le categorie di Twitch sceglie quella che contiene le parole che hai scritto: «diablo 4» non diventa «Diablo». Capisce i numeri romani o scritti in lettere e le sigle più usate, come «gta 5» o «cs2». Se nessuna somiglia abbastanza, non cambia niente.',
      '<strong>Contatore.</strong> «Incrementa (+1)» aggiunge uno, qualunque sia il passo del contatore; «Azzera» riporta a zero; «Imposta a…» mette il numero di «Valore (se "imposta")». Il nome è quello del comando del contatore, senza <code>!</code>: <code>morti</code> muove lo stesso numero di <code>!morti</code>, di <code>$count(morti)</code> e di CONTATORify. Se quel contatore non c\'è ancora, nasce nella carta <em>Contatori</em>. L\'azione cambia il numero senza scriverlo in chat: per dirlo aggiungi «Scrivi in chat» con <code>$count(morti)</code>.',
      '<strong>Dai o togli punti.</strong> «A chi» ha quattro scelte: «Chi ha scritto», «Chi è taggato dopo il comando», «Uno a caso fra chi è in chat» (pescato fra chi ha scritto di recente, di preferenza non l\'autore) e «Un nome fisso», che chiede il «Nome utente». «Quanti» accetta un numero o una variabile: <code>$random(10,50)</code>, <code>$arg1</code>. Dopo, <code>$mossa</code> dice quante monete si sono mosse davvero e <code>$bersaglio</code> su chi: a chi ha 5 monete non se ne tolgono 80. Le azioni che seguono vedono la stessa cifra, così un furto dà al ladro esattamente quello che ha tolto.',
      '<strong>Chiama un webhook.</strong> Il bot manda in <code>POST</code> un JSON con canale, chi ha scritto, gli argomenti, l\'evento e le variabili del momento. Se rispondi con <code>{"reply": "testo"}</code> e hai spuntato «Usa la risposta come messaggio in chat», il bot scrive quel testo, con le variabili già espanse. Accetta solo indirizzi <code>http</code> e <code>https</code>, non raggiunge indirizzi di una rete privata, non segue i reindirizzamenti, aspetta 5 secondi e legge fino a 10 KB di risposta.',
      '<strong>Regia.</strong> È lo stesso passo dei tasti di CONSOLify: così una scena cambia con <code>!brb</code>, a voce o a un raid. Se la regia è collegata da questa pagina, i nomi di scene, fonti e transizioni te li propone mentre scrivi. Una scena può venire dal comando: <code>$arg1</code> dopo <code>!scena</code>. Lo esegue il pannello aperto sul computer della regia, non il server: se non c\'è, il passo salta e il resto va avanti. Il collegamento lo spiega il <a href="/manuale/consolify">manuale di CONSOLify</a>.',
      '<strong>Modalità della chat a tempo.</strong> «Per quanto» vuoto vale 2 minuti; accetta <code>5m</code>, <code>90s</code>, <code>1h</code> o <code>$arg1</code>, fino a 40 caratteri. Un numero senza unità vale minuti, e la durata sta fra 10 secondi e un\'ora. Una durata che non si capisce vale 2 minuti. Con «Lo dico in chat» acceso il bot scrive «🎉 Chat in modalità solo emote per 2 minuti!» e quando finisce «✓ Fine della modalità solo emote: chat di nuovo libera.». Se la stessa modalità l\'ha già accesa il bot, si allunga fino alla fine più lontana. Alla fine la chat torna com\'era da sola, anche se il bot si riavvia in mezzo. Se un moderatore aveva già acceso quella modalità, il bot la lascia stare. Chat lenta e soli follower non ci sono: le usa lo scudo contro gli attacchi.',
      '<strong>Metti una canzone in coda.</strong> Le richieste musicali sono nel piano Essenziale. Spotify lo colleghi in <em>Durante la diretta</em>, <em>Regia</em>, <em>Musica</em>. Il bot scrive «🎵 In coda: …», oppure «🎵 Non ho trovato "…" su Spotify.», «🎵 Nessun dispositivo Spotify attivo.», «🎵 Il brano non è stato aggiunto.». Se Spotify non è collegato, a chi è dello staff dice «🎵 Spotify non è collegato: fallo dal pannello.», agli altri «🎵 La musica qui non è attiva.». Il <a href="/manuale/diretta">manuale della diretta</a> spiega come si collega.',
    ] },

    { h3: 'Il ramo Altrimenti' },
    { p: [
      'È quello che succede quando la <strong>probabilità</strong> non passa: il ramo del gioco perso. Compare solo con «Probabilità (%)» sotto 100. Se provi a salvare azioni in «Altrimenti» con la probabilità a 100, il pannello risponde che il blocco scatta solo quando la probabilità non passa.',
      'Le azioni sono le stesse sedici. Il costo è già stato pagato, così la giocata persa può raccontarlo con <code>$costo</code> e <code>$saldo</code>. Lascialo vuoto se non serve: in quel caso chi perde non legge niente.',
    ] },

    { h3: 'Salva, Prova, Annulla' },
    { p: [
      '<strong>«Salva»</strong> salva e chiude l\'editor. <strong>«Prova»</strong> prima salva, poi esegue il modulo saltando le condizioni: «Salvato e provato: guarda chat/overlay». <strong>«Annulla»</strong> chiude senza salvare.',
      'Se qualcosa non va il pannello dice cosa: un webhook senza <code>http</code> o <code>https</code>, un cambio di categoria o di titolo senza testo, una canzone senza brano, un annuncio vuoto, un\'azione punti senza quantità o con un nome utente non valido, una regia senza scena, fonte o transizione.',
    ] },

    { h3: 'Le variabili' },
    { p: [
      'Si scrivono nei testi e diventano quello che valgono. Nell\'editor c\'è un bottone per ognuna: un clic la mette nel campo dove stai scrivendo. Una variabile che non esiste sparisce dal testo senza lasciare il suo nome. Sono sostituzioni di testo e basta: nessun codice viene eseguito, né tuo né di chi scrive in chat.',
    ] },
    { p: ['<strong>Chi scrive e cosa dice</strong>'] },
    { tabella: [
      ['Variabile', 'Diventa'],
      ['<code>$user</code>', 'chi ha scritto'],
      ['<code>$touser</code>', 'il nome scritto dopo il comando, o chi scrive se manca'],
      ['<code>$target</code>', 'come <code>$touser</code>'],
      ['<code>$args</code>', 'tutto quello che c\'è dopo il comando'],
      ['<code>$arg1</code>', 'la prima parola dopo il comando (poi <code>$arg2</code>, <code>$arg3</code>…)'],
      ['<code>$canale</code>', 'il nome del tuo canale'],
    ] },
    { p: ['<strong>La diretta adesso</strong>'] },
    { tabella: [
      ['Variabile', 'Diventa'],
      ['<code>$uptime</code>', 'da quanto sei in diretta (vuota se offline)'],
      ['<code>$gioco</code>', 'la categoria attuale'],
      ['<code>$titolo</code>', 'il titolo attuale'],
      ['<code>$spettatori</code>', 'quanti stanno guardando ora'],
    ] },
    { p: ['<strong>Le persone</strong>'] },
    { tabella: [
      ['Variabile', 'Diventa'],
      ['<code>$followage</code>', 'da quanto ti segue chi scrive, o il nome dopo il comando. Serve il permesso di leggere i follower: senza, resta vuota.'],
      ['<code>$ore</code>', 'le ore guardate da chi scrive, o dal nome dopo il comando (anche <code>$oreguardate</code>, <code>$watchtime</code>). Serve «Conta le ore guardate in chat» acceso.'],
      ['<code>$serie</code>', 'le dirette di fila di chi scrive, o del nome dopo il comando; <code>$dirette</code> quante in tutto, <code>$recordserie</code> la serie più lunga'],
      ['<code>$chattercaso</code>', 'uno a caso fra chi ha scritto di recente, di preferenza non chi ha lanciato il comando'],
      ['<code>$cita</code>', 'una citazione a caso fra quelle salvate con <code>!cita</code>'],
      ['<code>$giocotarget</code>', 'l\'ultima categoria di chi nomini dopo il comando: senza un nome dopo il comando resta vuota'],
      ['<code>$titolotarget</code>', 'l\'ultimo titolo di chi nomini dopo il comando'],
    ] },
    { p: ['<strong>Le monete</strong>'] },
    { tabella: [
      ['Variabile', 'Diventa'],
      ['<code>$punti</code>', 'quante monete ha chi scrive'],
      ['<code>$punti(nome)</code>', 'quante ne ha un altro (anche <code>$punti($touser)</code>)'],
      ['<code>$monete</code>', 'come hai chiamato la tua moneta'],
      ['<code>$posizione</code>', 'in che posizione è chi scrive'],
      ['<code>$top(3)</code>', 'i primi tre, già scritti (da 1 a 10). <code>$top</code> da solo, o <code>$classifica</code>, sono i primi tre'],
      ['<code>$costo</code>', 'quanto è costato questo modulo'],
      ['<code>$saldo</code>', 'quanto è rimasto dopo il pagamento'],
      ['<code>$mossa</code>', 'quante monete ha mosso l\'ultima azione «Dai o togli punti»'],
      ['<code>$bersaglio</code>', 'su chi le ha mosse'],
    ] },
    { p: ['<strong>Data e ora</strong>'] },
    { tabella: [
      ['Variabile', 'Diventa'],
      ['<code>$data</code>', 'la data di oggi'],
      ['<code>$ora</code>', 'che ore sono'],
      ['<code>$giorno</code>', 'che giorno della settimana è'],
    ] },
    { p: ['<strong>Le funzioni</strong>'] },
    { tabella: [
      ['Variabile', 'Diventa'],
      ['<code>$random(1,100)</code>', 'un numero fra due'],
      ['<code>$random(6)</code>', 'un numero da 1 a 6'],
      ['<code>$decimale(1,2)</code>', 'un numero con due decimali, come 1,73'],
      ['<code>$misura(1,50,cm)</code>', 'un numero con l\'unità che vuoi, come 23 cm'],
      ['<code>$pick(a|b|c)</code>', 'una a caso fra queste (anche <code>$scegli</code>)'],
      ['<code>$count(nome)</code>', 'quanto vale un contatore, per esempio <code>$count(morti)</code>'],
      ['<code>$titolo($args)</code>', 'cambia il titolo della diretta e sparisce dal testo'],
      ['<code>$categoria($args)</code>', 'cambia la categoria e sparisce dal testo'],
    ] },
    { p: ['<strong>Quelle a caso</strong>. Danno un valore nuovo ogni volta che compaiono: due <code>$dado</code> nella stessa frase danno due numeri diversi.'] },
    { tabella: [
      ['Variabile', 'Diventa'],
      ['<code>$dado</code>', 'da 1 a 6'],
      ['<code>$moneta</code>', 'testa o croce'],
      ['<code>$sino</code>', 'sì o no'],
      ['<code>$random</code> <code>$numero</code>', 'da 0 a 100'],
      ['<code>$percentuale</code>', 'da 0% a 100% (anche <code>$percento</code>)'],
      ['<code>$livello</code>', 'da 1 a 100'],
      ['<code>$altezza</code>', 'da 1,40 m a 2,10 m'],
      ['<code>$peso</code>', 'da 40 a 130 kg'],
      ['<code>$lunghezza</code>', 'da 1 a 30 cm'],
      ['<code>$grandezza</code>', 'da 1 a 50 cm'],
      ['<code>$eta</code>', 'da 1 a 99 anni'],
      ['<code>$temperatura</code>', 'da -10 a 45 °C'],
      ['<code>$velocita</code>', 'da 1 a 320 km/h'],
      ['<code>$distanza</code>', 'da 1 a 1000 km'],
      ['<code>$soldi</code> <code>$euro</code>', 'da 0 a 100.000 €'],
      ['<code>$colore</code>', 'un colore'],
      ['<code>$animale</code>', 'un animale'],
      ['<code>$emoji</code>', 'una emoji'],
    ] },
    { p: ['<strong>Tre esempi</strong>'] },
    { esempio: 'QUANDO   comando  !abbraccia\nALLORA   Scrivi in chat\n         $user abbraccia $touser per $random(3,30) secondi.' },
    { esempio: 'QUANDO   evento  Raid\nALLORA   Scrivi in chat\n         Benvenuti! $raider è arrivato con $viewers persone.\nALLORA   Shoutout (banner)  a chi ha raidato' },
    { esempio: 'QUANDO   comando  !scommetti\nSE       Costa $arg1 · Probabilità 45\nALLORA   Dai o togli punti  Dai $arg1 a chi ha scritto\nALLORA   Dai o togli punti  Dai $arg1 a chi ha scritto\nALLORA   Scrivi in chat\n         $user vince! Ora ha $punti $monete.\nALTRIMENTI  Scrivi in chat\n         $user perde la puntata. Restano $saldo $monete.' },
    { p: ['Nel terzo la puntata esce prima del dado: per raddoppiarla, chi vince se la vede restituire due volte.'] },

    { h3: 'Connettori avanzati' },
    { p: [
      'Servono per far dire o fare qualcosa al bot da un tuo servizio: un\'estensione, un tasto fisico, uno script, un bot che hai già. La chiave la vede e la crea solo il <strong>proprietario</strong>: un moderatore vede «nessuna chiave», e se prova a crearla il pannello risponde «solo il proprietario del canale può farlo».',
      '<strong>«Genera chiave»</strong> crea la chiave e te la mostra una volta sola: copiala subito con «Copia». Il bot ne conserva solo un\'impronta, e dopo leggi «c\'è, ma non si può rivedere». Se la perdi, <strong>«Rigenera»</strong> ne fa una nuova e quella di prima smette subito di funzionare. Il pannello chiede conferma.',
      'In <strong>«URL a cui inviare le richieste»</strong> c\'è l\'indirizzo del tuo canale, <code>https://socialbot.live/api/ext/</code> seguito dal tuo nome. <strong>«Esempio d\'uso»</strong> mostra una chiamata pronta.',
      'Si manda una <code>POST</code> in JSON con la chiave nell\'intestazione <code>Authorization: Bearer LA_TUA_CHIAVE</code>, oppure nell\'indirizzo come <code>?key=</code>. Nel corpo, <code>azione</code> dice cosa fare.',
    ] },
    { tabella: [
      ['azione', 'Altri campi', 'Cosa fa'],
      ['<code>messaggio</code>', '<code>testo</code>', 'il bot scrive il testo in chat, con le variabili espanse'],
      ['<code>effetto</code>', '<code>comando</code>', 'fa partire quell\'effetto'],
      ['<code>modulo</code>', '<code>modulo</code>: il numero o il nome', 'esegue il modulo rispettando le sue condizioni'],
      ['<code>clip</code>', '<code>motivo</code>, facoltativo', 'crea una clip; serve «Comandi Vocali» o «Clip Automatiche»'],
      ['<code>tiktok-live</code>', 'nessuno', 'avvisa che sei in diretta su TikTok; serve il piano Base'],
      ['<code>youtube-post</code>, <code>tiktok-post</code>, <code>instagram-post</code>', '<code>titolo</code>, <code>url</code>', 'avvisa un nuovo post; serve il piano Base'],
      ['<code>donazione</code>', '<code>importo</code> (obbligatorio), <code>valuta</code>, <code>nome</code>, <code>messaggio</code>, <code>id</code>', 'una donazione arrivata da un altro servizio; senza <code>valuta</code>, o con una che il bot non conosce, vale quella delle tue donazioni; con lo stesso <code>id</code> non conta due volte'],
    ] },
    { p: [
      'Al massimo 30 richieste al minuto: oltre, la risposta è <code>429</code>. Una chiave sbagliata riceve <code>404</code>, senza spiegazioni. Un\'azione fuori dal tuo piano riceve <code>403</code>, una sconosciuta «azione non riconosciuta».',
    ] },

    { h3: 'Contatori' },
    { p: [
      'Un contatore è un numero con un nome: le morti, i tentativi, le volte che l\'hai detto. Sale, scende, torna a zero e può comparire a schermo nell\'overlay che hai già in OBS, senza aggiungere niente. È lo stesso numero dappertutto: il comando in chat, l\'azione «Contatore» dei moduli, <code>$count(nome)</code>, i tasti di CONSOLify e CONTATORify.',
      'Lo crei in fondo alla carta, in <strong>«Nuovo contatore»</strong>, e premi <strong>«Crea contatore»</strong>. Se manca il comando, il pannello dice «Scrivi un comando (es. morti).». Lo puoi creare anche dall\'Overlay Studio, fra le cose da aggiungere («Un contatore»): è lo stesso contatore, e lo ritrovi qui.',
    ] },
    { tabella: [
      ['Campo', 'Cosa fa', 'Limiti'],
      ['«Comando (senza !)»', 'il nome, che è anche il comando in chat: <code>morti</code> diventa <code>!morti</code>', '30 caratteri: lettere minuscole, cifre, trattino basso'],
      ['«Etichetta»', 'come lo dice il bot: «Morti: 12»', '40 caratteri'],
      ['«Emoji»', 'davanti all\'etichetta', 'facoltativa'],
      ['«Passo (+)»', 'di quanto sale o scende ogni volta', 'da 1 a 1.000, di base 1'],
      ['«Parola automatica»', 'il contatore sale da solo di uno per ogni volta che la parola compare in chat, come parola intera. Non conta i messaggi dello streamer.', '40 caratteri, facoltativa'],
    ] },
    { p: [
      'Ogni contatore ha una riga col valore e i tasti: <strong>«Accendi a schermo»</strong> o <strong>«Spegni a schermo»</strong>, <strong>+</strong> e <strong>−</strong> del passo, <strong>«Reset»</strong>, <strong>«Crea premio»</strong> o <strong>«Scollega premio»</strong>, e il cestino per eliminarlo. Eliminare chiede conferma: il numero si perde e il comando smette di rispondere.',
      '<strong>«Crea premio»</strong> (solo il proprietario) crea su Twitch un premio a punti canale col nome dell\'etichetta. Chiede quanti punti costa: di base 100, da 1 a 1.000.000. Chi lo riscatta fa salire il contatore di un passo. Serve il permesso dei punti canale: senza, il pannello dice «Creazione premio non riuscita (hai concesso i permessi punti canale?)». Se elimini il contatore il premio resta su Twitch, e lo togli da lì.',
    ] },
    { p: ['<strong>«Comandi e permessi»</strong>. Sette verbi, e per ognuno scegli con quali parole si chiama e chi può usarlo: «Tutti», «Solo sub», «VIP e sopra», «Mod e streamer». Le parole si separano con uno spazio, fino a sei per verbo. Lasciare vuota la casella toglie quel comando. Poi premi «Salva comandi».'] },
    { tabella: [
      ['Verbo', 'Parole di base', 'Chi, di base', 'Cosa fa'],
      ['Leggi', 'il nome da solo: <code>!morti</code>', 'Tutti', 'dice a che punto è'],
      ['Aggiungi', '<code>+</code> · <code>add</code>', 'Mod e streamer', 'sale del passo, o del numero che scrivi'],
      ['Togli', '<code>-</code> · <code>meno</code>', 'Mod e streamer', 'scende del passo, o del numero'],
      ['Azzera', '<code>reset</code> · <code>azzera</code>', 'Mod e streamer', 'torna a zero'],
      ['Imposta', '<code>set</code>', 'Mod e streamer', 'lo porta al numero che scrivi'],
      ['Mostra a schermo', '<code>on</code> · <code>mostra</code>', 'Mod e streamer', 'lo fa comparire nell\'overlay, senza toccare il numero'],
      ['Nascondi', '<code>off</code> · <code>nascondi</code>', 'Mod e streamer', 'lo toglie dallo schermo'],
    ] },
    { p: [
      'Il numero vale attaccato o staccato: <code>!morti +3</code>, <code>!morti + 3</code>, <code>!morti+3</code> e <code>!morti set10</code> funzionano tutti. Senza numero vale il passo. Un numero da solo, <code>!morti 7</code>, imposta, se «Imposta» ha almeno una parola. Attaccati al nome funzionano solo i simboli: <code>!morti+</code> sì, <code>!mortireset</code> no.',
      'Quando il numero cambia dalla chat, da un premio riscattato, da CONSOLify, da CONTATORify o da un gioco che lo dice da solo, il bot lo dice in chat («💀 Morti: 13»). Anche «Mostra a schermo» e «Nascondi» dalla chat ripetono il numero. I tasti del pannello, la parola automatica e l\'azione «Contatore» dei moduli lo cambiano senza scrivere niente. In tutti i casi il widget a schermo si aggiorna.',
      'A chi non può il bot risponde «!morti qui è riservato ai moderatori e allo streamer.», al massimo una volta al minuto per persona. Una lettura rifiutata resta muta.',
      'Se hai un modulo acceso o un comando creato dalla chat con lo stesso nome, risponde quello e il contatore tace.',
    ] },
    { p: ['<strong>«Personalizza l\'aspetto a schermo (overlay)»</strong>. Vale dopo «Salva aspetto», e l\'overlay si aggiorna subito.'] },
    { tabella: [
      ['Campo', 'Di base', 'Limiti'],
      ['«Mostra in overlay»', 'spento', 'lo stesso effetto di «Accendi a schermo»'],
      ['«Posizione a schermo»', '«In basso a sinistra»', 'nove posizioni, più «Personalizzata (X/Y sotto)»'],
      ['«Regolazione fine (X/Y manuali)»', 'X 4, Y 94', 'da 0 a 100 %'],
      ['«Colore testo»', 'bianco', ''],
      ['«Dimensione (px)»', '40', 'da 10 a 200'],
      ['«Colore sfondo»', 'nero semitrasparente', 'il colore che scegli tiene la stessa trasparenza; con «Sfondo trasparente» non c\'è sfondo'],
      ['«Font»', 'Sistema', 'Sistema, Inter, Space Grotesk, JetBrains Mono, Fraunces, Bricolage'],
      ['«Grassetto»', 'acceso', ''],
      ['«Formato del testo»', '<code>{emoji} {etichetta}: {valore}</code>', '80 caratteri'],
    ] },

    { h3: 'Comandi pronti' },
    { p: [
      'Qui ci sono tutti i comandi che il bot porta già con sé, divisi per famiglia: giochi in chat, giochi con la webcam, sorteggi, ore guardate, serie di presenze, compleanni, VIP, sondaggi, richieste musicali, modalità della chat, e gli altri. Quasi tutti si spengono, si rinominano e si possono riservare: le eccezioni lo dicono sulla loro riga. Le scelte valgono dopo <strong>«Salva i comandi»</strong>.',
    ] },
    { tabella: [
      ['Controllo', 'Cosa fa'],
      ['interruttore', 'accende o spegne il comando. Un pallino al suo posto vuol dire che è sempre acceso.'],
      ['«nome tuo»', 'il nome nuovo, fino a 20 lettere minuscole e cifre. Rinominare sostituisce: i nomi di serie smettono di rispondere. «non si rinomina» vale per il comando che fa entrare nel sorteggio, perché la parola la scegli quando lo apri, e per <code>!bot</code>.'],
      ['«chi può»', '«tutti», «abbonati», «VIP», «moderatori». Un comando che di serie è per i moderatori non si apre a tutti: scegliere più in basso lo lascia al suo livello. «non si riserva» vale per <code>!bot</code>.'],
    ] },
    { p: [
      '<code>!bot</code> (anche <code>!ia</code>, <code>!ai</code> e <code>!socialbot</code>) sta da solo nella famiglia «Trasparenza IA»: non si spegne, non si rinomina e non si riserva, perché chiunque in chat deve poter sapere che alcune risposte sono scritte da un\'intelligenza artificiale. Risponde con una frase fissa, e non fa domande al bot.',
    ] },
    { p: [
      'Accanto al nome vedi «costa monete» se il comando usa le monete, e le attese («30s a testa», «2 min per tutti»). Le attese dei giochi si cambiano nelle regole dei giochi, in <em>Giochi &amp; classifiche</em>.',
      'Se un\'intera famiglia è spenta, sopra leggi «famiglia spenta: questi comandi non rispondono». Si riaccende dal suo interruttore, nella scheda di quella funzione: per esempio i giochi in <em>Giochi &amp; classifiche</em>, le ore guardate, i comandi base e la gestione dei comandi dalla chat in <em>Comodità in chat</em>.',
      'A chi non può il bot risponde dicendo a chi è riservato, per esempio «!slot qui è riservato a chi è abbonato.».',
      'Due comandi non possono chiamarsi allo stesso modo: il pannello non salva e ti dice quale nome è già di un altro comando. Un comando tuo con lo stesso nome vince sempre su quello pronto, alias compresi: non devi spegnere niente. Se il tuo modulo è spento, risponde di nuovo quello pronto.',
      'I comandi dei giochi compaiono anche nella scheda <em>Giochi &amp; classifiche</em>: è la stessa impostazione, vista da due posti. Ogni «Salva i comandi» salva le righe della sua lista, e lascia le altre come le avevi salvate.',
    ] },

    { h3: 'CONTATORify: le morti contate da sole' },
    { p: [
      'Sta nella seconda parte della scheda, <strong>«CONTATORify»</strong>. La schermata di morte di un gioco è sempre la stessa immagine. La mostri una volta al pannello, e da lì il contatore sale da solo mentre giochi. Funziona con qualunque contatore: insegnagli la schermata di vittoria e hai <code>!vittorie</code>.',
      'Serve la regia collegata in CONSOLify e questo pannello aperto sul computer da cui mandi in onda. L\'immagine dello schermo non esce da lì: al server arriva solo «+1».',
    ] },
    { tabella: [
      ['Controllo', 'Cosa fa', 'Di base e limiti'],
      ['«Conta le morti guardando lo schermo»', 'accende il giro di controllo, e si salva subito', 'spento; senza almeno una schermata insegnata resta spento'],
      ['«Quale fonte guardo»', 'la fonte del programma di regia da guardare', 'si sceglie fra le fonti della regia collegata'],
      ['«Ogni quanto guardo (secondi)»', 'ogni quanto guarda la fonte', 'di base 2, da 1 a 30'],
      ['«Quale contatore faccio salire»', 'il contatore della schermata che insegni', 'fra quelli della carta <em>Contatori</em>'],
      ['«Sono morto adesso: è questa»', 'prende l\'impronta di quello che c\'è a schermo adesso', 'premilo mentre la schermata di morte è a schermo'],
      ['«Mettila in comune con gli altri streamer»', 'pubblica la schermata nella libreria, col gioco che hai in categoria', 'spuntata di base'],
    ] },
    { p: [
      'Quando premi il tasto, il pannello controlla se la schermata la conosce già. Se l\'ha insegnata qualcun altro ti chiede «La conosco già: è la morte di «…»»: con «Prendi la sua» non devi insegnare niente, con «La insegno io» vai avanti. Poi chiede «Che schermata è?», di base «Morte», e premi «Impara».',
      'Se manca qualcosa il pannello lo dice: «Scegli prima quale fonte devo guardare.», «Serve un contatore da far salire: creane uno nella scheda Comandi.», «Non riesco a guardare quella fonte: la regia è collegata?».',
      'La riga sotto «Ogni quanto guardo (secondi)» ti dice cosa vede: «Spento.», «La regia non è collegata: senza, non posso guardare niente.», «Guardo…», «Adesso vedo «…» (distanza N).», «Nessuna schermata riconosciuta adesso.», «Contata: …».',
      'Conta quando la schermata <strong>compare</strong>, non finché resta: una morte che dura cinque secondi vale uno. Dopo una morte contata, per 4 secondi non ne conta altre. Conta solo mentre il programma di regia è in onda: le prove fuori diretta non sporcano il numero. Ogni morte fa salire il contatore del suo passo e il bot la dice in chat.',
      'Puoi insegnare fino a 8 schermate, una per gioco: quella che combacia vince, così non devi dire tu a cosa stai giocando. Ogni schermata tiene fino a 12 impronte.',
    ] },
    { p: ['Nell\'elenco delle schermate insegnate ogni riga ha i suoi tasti.'] },
    { tabella: [
      ['Tasto', 'Cosa fa'],
      ['«Non l\'ha presa adesso»', 'la schermata è a schermo ma non è stata contata: aggiunge l\'impronta che mancava. Se la schermata viene dalla libreria, chiede se pubblicare la versione migliorata («Pubblicala» o «Solo per me»).'],
      ['«Prendi la versione nuova»', 'compare quando qualcuno ha migliorato la stessa schermata nella libreria («Qualcuno l\'ha migliorata: N impronte in più.»). Le tue impronte restano, le sue si aggiungono.'],
      ['«Togli»', 'toglie la schermata'],
    ] },

    { h3: 'Le schermate che hanno già insegnato gli altri' },
    { p: [
      'Ogni schermata messa in comune la trovano tutti. Scrivi il gioco in <strong>«Che gioco stai giocando»</strong> e premi <strong>«Cerca»</strong> o Invio. Ogni risultato dice la lingua delle scritte, quante impronte ha e quante volte è stata presa. Scegli il contatore e premi <strong>«Prendila»</strong>.',
      'Una schermata presa è tua: quello che succede dopo nella libreria non la cambia, a meno che tu prenda una versione nuova. Se non trovi il tuo gioco leggi «Nessuno l\'ha ancora insegnata.»: insegnala tu, e il prossimo la trova.',
    ] },

    { h3: 'Certi giochi lo dicono da soli' },
    { p: [
      '<strong>Counter-Strike 2</strong> e <strong>Dota 2</strong> pubblicano da soli quante volte sei morto. Lì non c\'è niente da riconoscere e il pannello non serve aperto: a parlare col bot è il gioco.',
    ] },
    { passi: [
      { t: 'Scegli il contatore', d: 'In «Quale contatore», accanto al gioco. «non contare» lo spegne per quel gioco.' },
      { t: 'Scarica il file', d: 'Premi «Scarica il file» e mettilo nella cartella scritta sotto il nome del gioco, dentro la cartella del gioco: <code>game/csgo/cfg</code> per Counter-Strike 2, <code>game/dota/cfg/gamestate_integration</code> per Dota 2.' },
      { t: 'Riavvia il gioco', d: 'Da lì in poi la riga sotto dice quando il gioco ha parlato l\'ultima volta, oppure «Nessun gioco ha ancora parlato.».' },
    ] },
    { p: [
      'Contano solo le tue morti: da spettatore o in un replay non sale niente. Fuori diretta il gioco parla ma il contatore non sale. La prima lettura dopo l\'avvio non conta, perché le morti già fatte in quella partita non sono successe adesso. Ogni morte fa salire il contatore del suo passo e il bot la dice in chat.',
      'Il file contiene una chiave che serve solo a far salire i contatori. Se il file è finito in giro, <strong>«Rifai la chiave»</strong> ne fa una nuova: i file che hai già messo smettono di funzionare e vanno riscaricati.',
    ] },

    // ------------------------------------------------------------ COMANDI VOCALI
    { h2: 'Comandi vocali', scheda: 'ascolto', p: [
      'Qui comandi il bot a voce mentre streammi, e lasci che il server riconosca da solo i momenti forti della diretta.',
      'La trovi accanto a <em>Comandi</em>, nella barra in alto della famiglia <em>Comandi</em>. Serve il pacchetto <strong>«Comandi Vocali»</strong> (0,99 € al mese, oppure dentro il pacchetto «Tutto»), che non è nell\'Essenziale né nel Base. Senza, la scheda mostra «Non nel tuo piano», con «Guarda la demo» e il tasto per sbloccarlo; lo trovi anche nella scheda <em>Abbonamento</em>.',
      'I comandi vocali veri e propri si costruiscono in <em>Comandi</em>, con l\'innesco «Comando vocale (dal tuo PC)»: è lo stesso motore dei comandi di chat.',
    ] },

    { h3: 'Momenti salienti (dal server)' },
    { p: [
      'Qui è il <strong>server</strong> che ascolta l\'audio della tua diretta Twitch e crea una clip da solo quando «esplode»: urla, risate, hype. Funziona anche se il tuo computer è occupato a giocare, e non c\'entra col microfono.',
    ] },
    { tabella: [
      ['Controllo', 'Di base', 'Cosa fa'],
      ['interruttore «Ascolto acceso» / «Ascolto spento»', 'spento', 'si salva subito'],
      ['«Sensibilità»', '5', 'da 1 a 10, vale dopo «Salva»: se il server ti sta già ascoltando, entro un minuto. Più alta prende anche i momenti meno intensi, più bassa solo i picchi veri.'],
    ] },
    { p: [
      'Accanto all\'interruttore leggi «in ascolto ora» quando il server ti sta ascoltando, «non in ascolto» quando no. Si aggiorna quando riapri il pannello.',
      'L\'ascolto parte solo mentre sei in diretta. Il server controlla ogni minuto chi è in diretta con l\'ascolto acceso: può metterci un minuto a partire. Consuma risorse del server ed è limitato a pochi canali insieme: se i posti sono pieni, il tuo aspetta e parte appena se ne libera uno.',
      'Nei primi secondi ascolta senza creare clip, per capire il volume normale della tua diretta. Fra due clip passano almeno 90 secondi. C\'è un ritardo di 15-30 secondi dovuto a Twitch, ma la clip prende comunque il momento, perché guarda indietro. Le clip finiscono in <em>Durante la diretta</em>, <em>Regia</em>, <em>Clip</em>, fra le «Ultime clip».',
    ] },

    { h3: 'Comando vocale' },
    { p: [
      'I comandi vocali lavorano <strong>nel tuo browser</strong>. <strong>«Apri l\'ascolto vocale»</strong> apre la pagina di ascolto in una scheda nuova: premi «Avvia ascolto» e tienila aperta mentre streammi. Quando dici una frase chiave, il bot fa quello che hai impostato nei moduli.',
      'Il modello pronto «Comando vocale: clippa», nella carta <em>Moduli</em> di <em>Comandi</em>, crea una clip quando dici «clippa» o «salva la clip».',
    ] },

    { h3: 'Cambia categoria a voce' },
    { p: [
      'Dici la parola chiave seguita dal gioco, «<strong>categoria</strong> Fortnite», e il bot cambia la categoria del canale su Twitch. Se ti sente male prova comunque a indovinare il gioco più somigliante fra le categorie di Twitch. Conta ogni parola che dici: «diablo 4» non diventa «Diablo». Capisce i numeri romani o detti in lettere e le sigle più usate, come «gta 5» o «cs2». Se nessuna categoria somiglia abbastanza non cambia niente.',
    ] },
    { tabella: [
      ['Controllo', 'Di base', 'Limiti'],
      ['interruttore «Attivo» / «Spento»', 'spento', 'vale dopo «Salva»'],
      ['«Parola chiave (quella che dici prima del gioco)»', 'categoria', '30 caratteri; «gioco», «passa a», quella che vuoi'],
      ['«Annuncia il cambio in chat»', 'acceso', 'il bot scrive «🎮 Categoria aggiornata: …»'],
    ] },
    { p: [
      'La parola chiave va detta <em>prima</em> del nome: «categoria Fortnite», non «metti Fortnite». Serve il permesso <em>Gestione canale</em> di Twitch. Se manca, sotto compare un avviso con «Concedi il permesso»: autorizzi e torni qui.',
    ] },

    { h3: 'Cambia titolo a voce' },
    { p: [
      'Dici la parola chiave seguita dal titolo, «<strong>titolo</strong> Si torna su Elden Ring, si punta al boss!», e il bot aggiorna il titolo della diretta su Twitch, come lo dici. Il titolo si ferma a 140 caratteri.',
    ] },
    { tabella: [
      ['Controllo', 'Di base', 'Limiti'],
      ['interruttore «Attivo» / «Spento»', 'spento', 'vale dopo «Salva»'],
      ['«Parola chiave (quella che dici prima del titolo)»', 'titolo', '30 caratteri; per esempio «nuovo titolo»'],
      ['«Annuncia il cambio in chat»', 'acceso', 'il bot scrive «📝 Titolo aggiornato: …»'],
    ] },
    { p: ['Usa lo stesso permesso <em>Gestione canale</em> della categoria: se manca, l\'avviso ha il collegamento «Concedilo qui».'] },

    { h3: 'Impara mentre parlo' },
    { p: [
      'La vede solo il <strong>proprietario</strong>. Con la pagina di ascolto aperta, il bot ti sente parlare in diretta e impara i tuoi modi di dire e il tuo tono. Impara solo dalla tua voce, mai da quella di un moderatore collegato al pannello.',
      'L\'interruttore si salva subito ed è spento di base. La trascrizione avviene nel browser: al bot arrivano le frasi che dici, di almeno 12 caratteri e fino a 200, senza i comandi. Il bot tiene le ultime 60.',
    ] },

    { h3: 'La pagina di ascolto vocale' },
    { p: [
      'È la pagina che apri con «Apri l\'ascolto vocale». Si usa dal computer da cui streammi, con lo stesso accesso del pannello.',
    ] },
    { tabella: [
      ['Parte', 'Cosa fa'],
      ['«Avvia ascolto» / «Ferma»', 'accende e spegne il microfono. Sotto leggi «In ascolto…» o «Fermo».'],
      ['«Frasi che sta ascoltando»', 'le frasi dei tuoi moduli vocali accesi. Si caricano quando premi «Avvia ascolto» e poi da sole ogni minuto. Se non ce ne sono: «Nessuna frase: crea un Modulo con innesco "voce" nella dashboard.»'],
      ['«Registro»', 'cosa ha sentito e cosa è successo, con l\'ora. Tiene le ultime 200 righe.'],
    ] },
    { p: [
      'Il riconoscimento è in <strong>italiano</strong>. Su Chrome ed Edge usa quello del browser, che non scarica niente. Dove il browser non ce l\'ha (Dia, Arc, Brave) usa un motore locale: la prima volta scarica un modello di qualche decina di MB, poi funziona anche offline. Il cambio lo fa da solo e lo scrive nel registro.',
      'La stessa frase non scatta due volte in 4 secondi.',
      'Oltre ai tuoi moduli e ai due comandi di categoria e titolo, la pagina capisce il VIP: «<strong>vip a</strong> chiara», «vip a chiara <strong>per un mese</strong>» (anche «per 2 settimane», «per 3 giorni», «per sempre»; senza durata vale una settimana), e «<strong>togli vip a</strong> chiara». Il nome si cerca fra chi ha scritto in chat, e il bot risponde in chat: «👑 VIP a … per una settimana!», oppure «Non trovo nessuno che somigli a "…" in chat 🤔». Basta la parola «vip» seguita da un nome: attento a come la usi mentre parli.',
      'Durante una penitenza a punti canale la pagina manda anche le frasi intere, per contare le parole vietate. Nel registro leggi «Penitenza in corso: conto quello che dici finché non finisce.». Le penitenze le spiega il <a href="/manuale/interazione">manuale di sondaggi, giveaway e penitenze</a>.',
    ] },
    { p: ['<strong>I messaggi del registro</strong>'] },
    { tabella: [
      ['Leggi', 'Cosa vuol dire, e cosa fai'],
      ['«"…" → modulo scattato»', 'un tuo modulo vocale è partito'],
      ['«"…" inviato (nessun modulo ha reagito)»', 'la frase è arrivata ma nessun modulo è partito: guarda le condizioni del modulo, e se hai il pacchetto «Comandi Vocali»'],
      ['«categoria cambiata in "…"», «titolo cambiato in "…"»', 'fatto'],
      ['«categoria non trovata per "…"»', 'nessuna categoria somiglia abbastanza: ridillo più chiaro'],
      ['«non sono riuscito a cambiare categoria», «non sono riuscito a cambiare titolo»', 'Twitch non ha accettato il cambio: riprova fra poco'],
      ['«manca il permesso di gestione canale»', 'concedi il permesso <em>Gestione canale</em> dalla scheda <em>Comandi vocali</em>'],
      ['«Permesso microfono negato…»', 'consenti il microfono per questo sito dall\'icona nella barra del browser e premi di nuovo «Avvia ascolto»'],
      ['«Sessione scaduta: rientra dalla dashboard e riapri questa pagina.»', 'entra di nuovo nel pannello e riapri la pagina'],
      ['«Nessun motore vocale disponibile in questo browser: prova con Chrome.»', 'cambia browser'],
    ] },
  ],
  faq: [
    { d: 'Ho creato un comando e non risponde. Perché?', r: 'Guarda che il suo interruttore in «I tuoi moduli» sia acceso. Poi le condizioni: un cooldown in corso, «Solo se sono in live» a canale spento, una probabilità sotto 100 senza ramo «Altrimenti». Premi «Prova»: salta le condizioni, e se lì funziona il problema è in una condizione, non in un\'azione.' },
    { d: 'Che differenza c\'è fra un comando e un modulo?', r: 'Nessuna nel motore: un comando è un modulo con l\'innesco «Un comando in chat». Il «Comando rapido» è la scorciatoia per un comando che risponde e basta. I comandi creati dalla chat con <code>!comando aggiungi</code> invece sono solo testo con <code>{user}</code>, e non compaiono fra i moduli.' },
    { d: 'Il mio timer non parla mai.', r: 'Di base un timer parla solo mentre sei in diretta: per farlo parlare a canale spento spunta «Falla parlare anche a canale spento». Se hai chiesto un minimo di messaggi, a chat ferma tace. Un timer nuovo parla la prima volta dopo un intervallo intero.' },
    { d: 'Ho un contatore !morti e anche un modulo !morti: risponde solo il modulo.', r: 'Un tuo modulo acceso con lo stesso nome vince su tutto il resto, contatori e comandi pronti compresi. Cambia nome al modulo, oppure spegnilo.' },
    { d: 'Ho importato i comandi da Nightbot e quelli per mod li usano tutti.', r: 'Dal bot di prima non arrivano il livello utente né le attese. Apri quei moduli con «Modifica» e metti «Solo mod» in «Chi può attivarlo».' },
    { d: 'Ho perso la chiave dei Connettori avanzati.', r: 'Non si può rivedere: il bot ne conserva solo un\'impronta. Premi «Rigenera», copia quella nuova e sostituiscila dove usavi la vecchia, che smette subito di funzionare.' },
    { d: 'CONTATORify non conta le morti.', r: 'Guarda la riga sotto «Ogni quanto guardo (secondi)». «La regia non è collegata» vuol dire che il pannello non vede il programma di regia: collegalo in CONSOLify. Se vede la schermata ma non conta, controlla di essere in onda. Se la schermata è a schermo e non la vede, premi «Non l\'ha presa adesso».' },
    { d: 'Il comando vocale non parte.', r: 'La pagina di ascolto deve essere aperta e in ascolto, col microfono concesso. Serve il pacchetto «Comandi Vocali». Il riconoscimento è in italiano: scrivi le frasi come le dici. Guarda il «Registro» della pagina: dice se la frase è arrivata e se un modulo è partito.' },
    { d: '«Categoria Fortnite» non cambia il gioco.', r: 'La parola chiave va detta prima del nome, e «Cambia categoria a voce» deve essere su «Attivo» e salvato. Se manca il permesso <em>Gestione canale</em>, la scheda mostra l\'avviso con «Concedi il permesso».' },
    { d: 'Il bot registra la mia voce?', r: 'No. La voce diventa testo nel tuo browser, e l\'audio non esce da lì. Coi comandi vocali al bot arriva solo la frase che contiene una parola chiave. Durante una penitenza arrivano le frasi intere, finché dura. Con «Impara mentre parlo» acceso arrivano anche le frasi che dici, e il bot tiene le ultime 60. I momenti salienti lavorano sull\'audio pubblico della diretta, quello che sentono già tutti.' },
    { d: 'I moduli funzionano anche su Kick e YouTube?', r: 'Sì. Con almeno due piattaforme collegate compare «Su quali piattaforme», per limitare un modulo a una sola. Se non scegli niente vale ovunque.' },
    { d: 'Posso fare un gioco a monete con i moduli?', r: 'Sì: servono l\'azione «Dai o togli punti», «Costa (monete)» e la probabilità. Parti da una delle sei ricette a monete nella carta <em>Moduli</em>.' },
  ],
};
