// Manuale: Manuale dell'overlay. La forma dei manuali e il perche' stanno in
// src/web/manuali.js; le lingue in docs/LINGUE.md.

export default {
  slug: 'overlay',
  schede: ['alert', 'effetti'],
  titolo: 'Manuale dell\'overlay: alert, chat, obiettivo e contatori | SocialBot',
  h1: 'Manuale dell\'overlay',
  desc: 'Cosa può comparire sulla diretta, con i valori di base e i limiti veri: alert degli eventi, chat a schermo, obiettivo, contatori, ultimo follower e sub, effetti.',
  aggiornata: '2026-09-04',
  corpo: [
    { p: [
      'L\'overlay è <strong>una pagina web</strong>. In OBS si mette come sorgente <em>Browser</em>, e da quel momento tutto quello che decidi nel pannello compare sulla diretta senza toccare più niente lì dentro.',
      'Si compone nella scheda <em>Overlay Studio</em>, e si vede subito mentre lo cambi.',
    ] },

    { h2: 'Gli elementi' },
    { p: ['Tutto quello che può comparire è un <strong>elemento della scena</strong>: si accende, si sposta e si veste dallo stesso posto. Non ci sono cose che seguono regole proprie.'] },
    { tabella: [
      ['Elemento', 'Cos\'è', 'Dove sta di serie'],
      ['Alert eventi', 'Un cartello animato con suono quando arriva un follow, un sub, dei bit o un raid.', 'in alto al centro'],
      ['Chat a schermo', 'I messaggi della chat, con emote e badge.', 'in basso a sinistra'],
      ['Ultimo follower', 'Una pastiglia col nome di chi ha seguito per ultimo.', 'in basso a destra'],
      ['Ultimo sub', 'La stessa cosa per l\'ultimo abbonato.', 'in basso a destra'],
      ['Obiettivi', 'Barre che si riempiono mentre arrivano follower, sub o bit. Quanti ne vuoi.', 'dove li metti tu'],
      ['Contatori', 'I numeri che tu e i mod muovete in chat: morti, tentativi, quello che vuoi.', 'dove li metti tu'],
      ['Player musica', 'Quello che stai ascoltando su Spotify: copertina, titolo e avanzamento.', 'in basso a sinistra'],
      ['Conto alla rovescia', 'Quanto manca all\'inizio della diretta. Con «parte da solo» parte appena lo accendi e ogni volta che un overlay si apre e lo trova fermo.', 'in alto a destra'],
      ['Sfida a tempo', 'La carta della penitenza riscattata coi punti canale: parola, colpi e tempo che manca.', 'in alto a destra'],
      ['Boss', 'La carta del boss di turno: nome, vita, tempo che resta, chi lo colpisce e quanto.', 'in alto al centro'],
      ['Testo a schermo', 'La scritta che un comando manda con «Mostra testo sull\'overlay».', 'al centro'],
      ['Nome del comando', 'La pastiglia «!comando» che compare quando parte un effetto.', 'in basso al centro'],
      ['Effetti & suoni', 'Immagini, video e suoni che partono da un comando o da un premio a punti.', 'al centro'],
    ] },
    { p: ['Sulla tela dello Studio ci sono <strong>tutti</strong>, obiettivi e contatori compresi: quello che vedi lì è quello che va in onda, nello stesso punto.'] },

    { h2: 'Il banco di regia' },
    { p: ['A sinistra i <strong>livelli</strong> (l\'elenco di quello che c\'è, con l\'occhio per toglierlo da questo overlay), al centro la <strong>tela</strong> 1920×1080, a destra le <strong>proprietà</strong> di quello che hai scelto: posizione, dimensione, rotazione e tutto il suo aspetto. Le due sponde si arrotolano per dare spazio alla tela, si staccano trascinandole per la testa e si riagganciano con un doppio clic.'] },
    { tabella: [
      ['Per fare', 'Come'],
      ['Spostare', 'Trascina. Si aggancia da solo ai bordi, ai centri e agli altri elementi; <strong>Alt</strong> mentre trascini toglie l\'aggancio.'],
      ['Spostare al pixel', 'Frecce. Con <strong>Maiusc</strong> vanno dieci volte più in là.'],
      ['Ridimensionare', 'La maniglia in basso a destra, la <strong>rotellina</strong>, o il numero nelle proprietà.'],
      ['Ruotare', 'La maniglia col cerchio, <strong>Maiusc+rotellina</strong>, o i gradi nelle proprietà.'],
      ['Allineare', 'I sei pulsanti in alto: bordi e centri della tela.'],
      ['Immagine di riferimento', 'Il tasto <strong>Riferimento</strong> (oppure incolla, o trascina un file sulla tela) mette sotto la tela uno screenshot della scena o una grafica, con la trasparenza che vuoi e un interruttore per nasconderla. Resta nel tuo browser, per overlay: non va sul server e non va in onda.'],
      ['Dare un perimetro', 'Tira un <strong>bordo</strong> dell\'elemento selezionato (o spunta <strong>Riquadro</strong> nelle proprietà): da lì il riquadro è la scatola dell\'elemento: lo tiri e lui prende quella forma, largo, stretto, quadrato. I bordi si agganciano alla griglia e agli altri riquadri; larghezza e altezza si scrivono anche a numero.'],
      ['Bloccare', 'Il lucchetto nel livello, o <strong>Blocca</strong> nelle proprietà: un livello bloccato non si sposta, non si ridimensiona e non si ruota per sbaglio.'],
      ['Ingrandire', '<strong>Ctrl+rotellina</strong> sulla tela, attorno al puntatore; i pulsanti dello zoom attorno al centro; <strong>Adatta</strong> rimette tutta la scena nello schermo.'],
      ['Spegnere l\'aggancio', 'La spunta <strong>Aggancia</strong>: senza, gli elementi non vengono tirati da guide e centri. <strong>Alt</strong> lo toglie solo mentre trascini.'],
      ['Tornare com\'era', '<strong>Ctrl+Z</strong> e <strong>Ctrl+Y</strong>, o le due frecce in alto a sinistra.'],
      ['Rimettere a posto', '<strong>Doppio clic</strong> sull\'elemento: torna nel suo angolo di serie.'],
      ['Vedere com\'è dal vivo', 'La spunta <strong>Dal vivo</strong>: alert e chat finti che si susseguono mentre lavori.'],
    ] },
    { p: ['Gli angoli della tela sono gli stessi dell\'overlay vero (un dito dai bordi), quindi un elemento «in alto a destra» sta a filo dello schermo anche in OBS. Il salvataggio è automatico: la posizione si scrive appena molli il mouse. L\'aspetto (colori, font, forma) invece esce con <strong>Salva overlay</strong>: se provi a cambiare scheda, overlay o pagina con modifiche non salvate, l\'editor te lo chiede prima. Se un salvataggio non riesce, te lo dice.'] },
    { p: ['<strong>Il riquadro.</strong> La chat dentro un riquadro va a capo alla sua larghezza, impila le righe dal basso e quando non ci stanno più la più vecchia esce dall\'alto: un riquadro di due caselle per tre mostra quante righe ci stanno. Per tutto il resto (alert, widget, obiettivi, conto alla rovescia, player, contatori) il riquadro è la scatola: l\'altezza dà la grandezza, la larghezza dà lo spazio. Il player in un riquadro largo ha tanto posto per il titolo, in uno quasi quadrato è quasi quadrato, in uno basso e largo è una barra sottile; carattere e proporzioni interne non si deformano. Niente esce dalla tela.'] },
    { p: ['Quello che vedi sulla tela ha le misure della diretta: il player tiene la stessa larghezza qualunque sia il brano, la chat si ferma alla larghezza che hai scelto, e un elemento spento resta sulla tela ma sbiadito, così lo trovi e lo riaccendi.'] },

    { h2: 'Metterlo in OBS' },
    { ul: [
      '<strong>Sorgenti → + → Browser.</strong>',
      'Incolla il link e metti <strong>1920 × 1080</strong>.',
      'Spunta <strong>«Aggiorna browser quando la scena diventa attiva»</strong>.',
    ] },
    { p: [
      'Puoi averne <strong>più d\'uno</strong>: ogni overlay ha il suo link, il suo elenco di elementi e il suo stile. Un overlay «solo alert» in una scena e uno «solo chat» in un\'altra è la ragione per cui esistono.',
      '<strong>Il link è un segreto.</strong> Chi ce l\'ha può far comparire cose nel tuo overlay: non va in un video, in uno screenshot o in una chat.',
      '<strong>Se il link è scappato</strong> — in un video, in uno screenshot, in una chat — accanto al link c\'è il tasto per farne uno nuovo: quello vecchio smette di funzionare all\'istante, per tutti i tuoi overlay, e il nuovo lo rimetti nelle sorgenti del programma con cui mandi in onda. Non serve chiedere niente a nessuno.',
    ] },

    { h2: 'Le occasioni' },
    { p: [
      'Un\'occasione è un\'<strong>aggiunta sopra l\'overlay che hai già</strong>: «i miei overlay ce li ho, ma stasera è subathon e voglio anche il conto alla rovescia». La accendi e compare, la spegni e torna tutto com\'era. Il link in OBS resta lo stesso: non tocchi niente di là.',
      'Nel banco, accanto alla tendina dell\'overlay c\'è quella dell\'<strong>occasione</strong>. Su <em>Tutti i giorni</em> stai lavorando all\'overlay di sempre. Se ne scegli una, una fascia sopra la tela te lo dice, e da quel momento <strong>quello che accendi, spegni e sposti finisce nell\'occasione</strong>, non nell\'overlay di sempre. I livelli lo segnano: <em>in più</em>, <em>via</em>, <em>spostato</em>.',
      'Sceglierla <strong>non la manda in onda</strong>: quello è un gesto a parte, la spunta <em>In onda adesso</em> nella fascia. Ne va in onda <strong>una alla volta</strong>, così alla domanda «cosa sto vedendo?» c\'è sempre una risposta sola.',
      '<strong>Nuova…</strong> apre i modelli, con l\'anteprima di come verrebbe su questo overlay e la riga di cosa cambierebbe davvero: Subathon, Torno subito, Serata speciale, o una vuota da farsi da sé. Se un modello dice «queste cose ce le hai già così» non è rotto: vuol dire che su questo overlay quella roba è già accesa.',
      'Rimettere una cosa com\'era la toglie dall\'occasione: l\'occasione si tiene solo ciò che <strong>differisce</strong>. Per questo spegnerla non perde niente, e per questo se domani cambi l\'overlay di sempre l\'occasione ti segue, tranne che su ciò che nomina lei.',
    ] },

    { h2: 'Alert eventi' },
    { p: ['Cinque eventi, ognuno con il suo interruttore, il suo testo, il suo suono e il suo colore.'] },
    { tabella: [
      ['Evento', 'Testo di serie', 'Suono', 'Parole che puoi usare'],
      ['Follow', '<code>{user} ha seguito il canale!</code>', 'campanello', '<code>{user}</code>'],
      ['Sub', '<code>{user} si è abbonato! ({mesi} mesi)</code>', 'tada', '<code>{user}</code> <code>{mesi}</code>'],
      ['Bit', '<code>{user} ha lanciato {bits} bit!</code>', 'moneta', '<code>{user}</code> <code>{bits}</code>'],
      ['Raid', '<code>{user} è arrivato in raid con {viewers} spettatori!</code>', 'trombetta', '<code>{user}</code> <code>{viewers}</code>'],
      ['Donazione', '<code>{user} ha offerto {importo}! {messaggio}</code>', 'moneta', '<code>{user}</code> <code>{importo}</code> <code>{messaggio}</code>'],
    ] },
    { p: ['Bit, raid e donazioni hanno una <strong>soglia</strong>: sotto quel numero l\'alert non parte. È il modo di non far suonare il campanello per un bit solo. La donazione arriva da Ko-fi o dalla chiave API del canale: come si collega è scritto nel manuale della pagina link.'] },
    { tabella: [
      ['Impostazione', 'Di base', 'Limiti'],
      ['Durata', '6 secondi', '—'],
      ['Posizione', 'in alto al centro', 'alto · centro · basso, oppure dove lo trascini'],
      ['Dimensione del testo', '27', '—'],
      ['Opacità dello sfondo', '88%', '—'],
      ['Angoli', '18px', '—'],
      ['Cornice', '2px, accesa', '—'],
      ['Icona', 'accesa, 46px', '—'],
      ['Volume', '100%', 'per evento'],
    ] },
    { p: ['Lo stile è comune ai quattro (forma, materia, cornice, composizione, animazione), il <strong>colore d\'accento</strong> no: è per evento, così a colpo d\'occhio si riconosce cosa è appena successo.'] },

    { h2: 'Chat a schermo' },
    { tabella: [
      ['Impostazione', 'Di base', 'Cosa fa'],
      ['Righe visibili', '8', 'Quante ne resta a schermo prima che scorrano via.'],
      ['Dissolvenza', 'spenta', 'Se acceso, ogni riga sparisce dopo i secondi che scegli.'],
      ['Larghezza', '30%', 'Quanto è larga la colonna.'],
      ['Opacità', '78%', 'Lo sfondo delle righe.'],
      ['Colore dei nomi', 'quello di Twitch', 'Oppure uno fisso, se preferisci un look uniforme.'],
    ] },
    { p: ['Le emote di Twitch e quelle 7TV del tuo canale compaiono come immagini, e i badge accanto al nome. Le emote 7TV si gestiscono da <em>Emote (7TV)</em>.'] },
    { p: ['Se trasmetti su due piattaforme, in <strong>Quali chat</strong> scegli quali finiscono in questo overlay. Toglierne una la lascia fuori di qui e basta: la chat resta accesa, e il bot continua a leggerla e a rispondere.'] },
    { p: ['Per tenerle <strong>divise</strong> fai un secondo overlay con l\'altra accesa: ha un link suo, quindi in regia diventano due fonti che metti dove vuoi. Per tenerle <strong>unite</strong> lasciale accese tutte e due nello stesso overlay, e se vuoi accendi <em>Segna da dove arriva</em>: ogni riga porta un segno che dice da quale chat viene.'] },

    { h2: 'Gli obiettivi' },
    { p: ['Barre che si riempiono da sole. <strong>Quanti ne vuoi</strong> (fino a sei), e ognuno è indipendente: il suo traguardo, il suo posto, il suo aspetto. Tre obiettivi in fila che salgono insieme, o uno in ogni angolo con colori diversi: decidi tu.'] },
    { tabella: [
      ['Per ogni obiettivo', 'Di base', 'Limiti'],
      ['Conta', 'follower', 'follower · abbonati · bit · euro donati (sale dell\'importo di ogni donazione, e si può mostrare anche sulla pagina link)'],
      ['Traguardo', '100', 'da 1 a 1.000.000'],
      ['Parte da', '0', 'il gradino sotto: «1000 follower» invece di «altri 1000»'],
      ['Titolo', 'vuoto', '60 caratteri'],
      ['Dove', 'in alto a sinistra', 'i quattro angoli, o dove lo trascini'],
      ['Aspetto', '—', 'colore del testo, dello sfondo e della barra, opacità, angoli, carattere, forma, materia, cornice, dimensione'],
    ] },
    { p: ['Due obiettivi che contano la stessa cosa <strong>salgono insieme</strong>: è il modo di fare una scala («100 follower», «500 follower») senza doverla rifare a mano. E ognuno si azzera per conto suo.'] },
    { p: ['<strong>«Quanti ne ho adesso»</strong> va a chiedere a Twitch il numero vero e lo mette come partenza: se hai 450 follower e metti 1000 di traguardo, la barra parte già quasi a metà. Per i <strong>bit</strong> non funziona, perché Twitch non tiene un totale di sempre — solo la classifica di un periodo: lì la partenza la scrivi tu.'] },
    { p: [
      '<strong>Il conto è quello vero</strong>: lo tiene il bot contando gli eventi che gli passano davanti. Un cheer da 500 bit vale 500, non 1.',
      'Sta nelle impostazioni del canale, quindi <strong>sopravvive a un riavvio</strong>: un obiettivo che si azzera da solo la notte non è un obiettivo. A rimetterlo a zero sei tu, col tasto «Riparti da zero» del singolo obiettivo.',
    ] },

    { h2: 'Il player' },
    { p: ['Quello che stai ascoltando, a schermo. Compare quando la musica parte e sparisce quando la fermi (o resta con un trattino, se preferisci). Legge da <strong>Spotify</strong>: si collega nella scheda <em>Richieste musicali</em>.'] },
    { tabella: [
      ['Scelta', 'Di base', 'Cosa puoi metterci'],
      ['Disposizione', 'copertina a sinistra', 'copertina a sinistra · a destra · sopra (poster) · solo la copertina · libera: ogni pezzo dove lo trascini sulla tela dello Studio, con righe e barra larghe quanto vuoi e il testo allineato come vuoi. Si parte da dove i pezzi stanno già, e la carta è il riquadro'],
      ['Righe', 'una', 'una riga sola, oppure titolo sopra e artista sotto'],
      ['Copertina', 'quadrata', 'quadrata · tonda · vinile che gira mentre suona · il mio video in chiaro (non con i temi vinile e CD: lì resta il disco) · niente'],
      ['Corpo', 'normale', 'slim · normale · cicciotto: la taglia di tutto il player, copertina compresa'],
      ['Tema', 'nessuno', 'ogni tema porta la sua figura e il suo moto, e si muove solo mentre suona: vinile (il disco sporge da dietro e gira) · CD (gira e cambia riflesso) · cassetta (le bobine girano) · terminale (prompt e cursore) · manga (retino che pulsa a tempo) · esagono (copertina a sei lati, con un anello che ruota). Ogni tema entra ed esce come l\'oggetto vero: il vinile esce dalla custodia e prende giri, poi frena e rientra; il CD apre la custodia, esce e gira, poi si ferma, rientra e la custodia si chiude; la cassetta ferma le bobine e viene espulsa; il terminale si accende e si spegne come un tubo catodico; la pagina del manga si volta; l\'esagono si dispiega e si ripiega. «Rivedi l\'entrata» te lo fa vedere sulla tela'],
      ['Avanzamento', 'barra sotto', 'barra sotto · anello attorno alla copertina · niente'],
      ['Tempi', 'niente', 'trascorso · quanto manca · tutti e due'],
      ['Le onde', 'onde che ballano', 'onde che ballano · onde e copertina che pulsa · niente onde (spariscono)'],
      ['Sfondo', 'niente', 'la copertina sfocata · i colori del disco che scorrono · il mio video sfocato'],
      ['Il mio video', 'nessuno', 'un video corto caricato fra gli Effetti, in loop e muto: Spotify non dà un video del brano, quindi è tuo, e vale per lo sfondo e per la copertina'],
      ['Colore', 'il tuo accento', 'oppure preso dai colori della copertina, disco per disco'],
      ['Titolo lungo', 'scorre', 'solo se non ci sta: si misura, non si indovina'],
      ['Entrata', 'dissolvenza', 'dissolvenza · scivola da lato · sale dal basso · secca'],
      ['A ogni brano', 'si rianima', 'la copertina rientra e il testo risale, come un cambio di scena'],
      ['Misure', 'tutte a 100', 'un cursore per pezzo — spazio attorno, copertina, figura dietro (il vinile, il CD o l\'anello), prima e seconda riga, tempi, barra, onde — da 40 a 250: 100 è come il corpo, e «Di serie» riporta tutto lì'],
      ['Colori a parte', 'spenti', 'accesi, prima riga, seconda riga, tempi, barra e onde hanno ognuno il suo colore; spenti, seguono testo e accento'],
    ] },
    { p: ['<strong>Le onde sono una domanda sola.</strong> «Niente onde» le toglie: non le lascia lì ferme. Un equalizzatore che non si muove non è spento, è finto — e occupa posto per fingere.'] },
    { p: ['<strong>La copertina pulsa solo se il battito si sa.</strong> Quando Spotify ci dice quanti battiti al minuto ha il brano, la copertina va con quelli. Quando non lo dice — capita, e non dipende da te — resta ferma, invece di pulsare a una velocità che non c\'entra niente con la canzone. Le onde ballano comunque: quelle non promettono di stare a tempo.'] },
    { p: ['Il testo è tuo: <code>{titolo}</code>, <code>{artista}</code> e <code>{album}</code> vengono sostituiti, su una riga o su due. E come ogni elemento ha colori, carattere, forma, materia, cornice, dimensione — e lo trascini dove vuoi.'] },

    { h2: 'Il conto alla rovescia' },
    { p: ['Quanto manca all\'inizio. Scegli i minuti e premi <strong>Fai partire</strong>: il conto sta nel canale, quindi anche se ricarichi l\'overlay o riavvii tutto continua da dove era. Quando arriva a zero scrive quello che vuoi tu — «Si comincia!» di base — e può restare o sparire.'] },

    { h3: 'Subathon' },
    { p: ['Il subathon non è un secondo conto: è <strong>questo</strong>, con una regola in più. Lo accendi sotto al conto alla rovescia e decidi quanto vale un sub, cento bit e un euro donato. Da quel momento il tempo che arriva si somma a quello che manca, e a schermo si vede il timer che hai già messo in scena, con la veste che gli hai dato.'] },
    { p: ['Il <strong>tetto</strong> è su quanto manca, non su quanto hai aggiunto in tutto: «non può mancare più di dodici ore» risponde alla domanda vera, cioè a che ora vai a dormire. A zero ore non c\'è tetto. Se il conto è già arrivato a zero, un sub non lo fa ripartire: la diretta è finita, e riaprirla è una tua scelta.'] },
    { p: ['Con l\'avviso acceso il bot dice in chat quanto è salito e per merito di chi (<code>{chi}</code>, <code>{quanto}</code>). Chi guarda può chiedere <code>!subathon</code> per sapere quanto manca.'] },

    { h2: 'I cartelli' },
    { p: ['Una scritta o un’immagine tua, ferma in scena. Non la muove nessun evento: la scrivi, la metti dove vuoi e resta lì — il titolo della serata, le regole della chat, il tuo logo, un «torno subito» sulla schermata di pausa. Ne puoi avere fino a otto.'] },
    { p: ['La <strong>scritta</strong> va a capo dove la mandi tu, e se le dai una larghezza va a capo anche da sola; a zero il cartello è largo quanto la riga più lunga. L’<strong>immagine</strong> si sceglie fra quelle che hai già in <em>Effetti &amp; suoni</em>: si caricano lì, e qui si trovano già pronte.'] },
    { p: ['Di suo un cartello non ha nessuna scatola dietro: sono parole (o un disegno) posate sulla scena. Se la vuoi, alzi l’opacità dello sfondo e scegli forma, materia e cornice come per ogni altro elemento.'] },
    { p: ['Quel che c’è scritto è <strong>uno solo e vale per tutti i tuoi overlay</strong>. Quello che cambia da scena a scena è <strong>se si vede, dove sta e come appare</strong>: due scene, due posti, due vesti, lo stesso cartello. E se ne vuoi uno diverso per scena, ne fai due e in ogni overlay ne accendi uno.'] },

    { h2: 'L’hype train' },
    { p: ['Il treno lo fa Twitch, non il bot: livello, punti, traguardo e quanto manca li decide lui. Qui si vedono, e basta accendere l’elemento nell’overlay. Non c’è niente da far partire e niente da contare: quando il treno parte, compare; quando Twitch dice che è finito, il cartello resta il tempo di leggere il livello raggiunto e poi se ne va.'] },
    { p: ['Nella scena si vede il <strong>livello</strong>, la barra fino al livello dopo, <strong>quanto manca</strong> prima che scada e, se vuoi, <strong>chi sta spingendo di più</strong> e il record del canale. È un elemento come gli altri: si trascina nello Studio, prende la veste che gli dai, e ogni overlay decide se mostrarlo.'] },
    { p: ['In chat il bot parla in tre momenti: quando il treno <strong>parte</strong>, quando <strong>sale di livello</strong> (<code>{livello}</code>) e quando <strong>finisce</strong> (<code>{livello}</code>, <code>{chi}</code>, <code>{punti}</code>). Non a ogni sub: quello lo dicono già gli alert. La chat e la scena sono due interruttori separati, così chi il treno ce l’ha già a schermo da Twitch può tenersi solo le righe in chat. Chi guarda può chiedere <code>!treno</code>.'] },
    { p: ['I sub e i bit che fanno crescere il treno <strong>contano già</strong> negli obiettivi e nel subathon, uno per uno: qui non si contano una seconda volta. E serve il permesso nuovo su Twitch: se il pannello te lo chiede, è per questo.'] },

    { h2: 'La classifica dei Bit' },
    { p: ['Chi ha messo più Bit, in un angolo della scena. Scegli <strong>di quando</strong> — oggi, questa settimana, questo mese, quest\u2019anno, da sempre — e <strong>quante righe</strong>, da una a dieci. È un elemento come gli altri: si trascina nello Studio, prende la veste che gli dai, e ogni overlay decide se mostrarlo.'] },
    { p: ['I numeri sono quelli di <strong>Twitch</strong>, gli stessi che rispondono a <code>!bit</code>: non è un conto nostro che con il suo non torna. Si aggiorna da sola quando arriva un cheer, perché è l\u2019unico momento in cui può cambiare. Chi ha cheerato in anonimo non compare, perché non compare nemmeno da Twitch.'] },
    { p: ['Se Twitch per un momento non risponde, la classifica <strong>resta quella di prima</strong> invece di sparire: un intoppo di un minuto non deve svuotare un angolo della scena. E serve il permesso di leggere i Bit: se il pannello te lo chiede, è per questo.'] },

    { h2: 'I contatori' },
    { p: ['Sono i numeri che vivono in chat — <code>!morti</code>, <code>!tentativi</code> — e si creano in <em>Comandi</em>. Nell\'overlay sono un elemento come gli altri: si spengono tutti insieme dall\'elenco e prendono la veste della scena.'] },
    { p: ['Se a un contatore dai colore, sfondo o posizione tuoi, <strong>quelli vincono</strong>: la scena veste solo quello che non hai deciso.'] },
    { p: ['Nello Studio si trascinano come tutto il resto, e la dimensione che leggi in percentuale è la loro altezza vera: <strong>100%</strong> sono i 40 pixel di serie.'] },

    { h2: 'Ultimo follower e ultimo sub' },
    { p: ['Due pastiglie che restano a schermo. Il testo è tuo: <code>{nome}</code> viene sostituito col nome. L\'icona si può cambiare, togliere, o sostituire con un\'immagine caricata negli Effetti.'] },

    { h2: 'Quando non si vede niente' },
    { ul: [
      '<strong>La pagina è bianca o vuota in OBS.</strong> Controlla il link: senza la sua chiave l\'indirizzo risponde «non trovato», di proposito.',
      '<strong>Gli alert non partono.</strong> Servono i permessi di Twitch per follow, sub, bit e raid: si riautorizzano dalla scheda Stato. E l\'interruttore del singolo evento dev\'essere acceso, oltre a quello generale.',
      '<strong>Parte l\'alert ma non il suono.</strong> In OBS la sorgente Browser deve avere il <strong>«Controlla l\'audio via OBS»</strong>, altrimenti l\'audio esce dal browser e non dalla diretta.',
      '<strong>Vedo tutto doppio.</strong> Due sorgenti Browser con lo stesso link nella stessa scena: tienine una, o dai a ciascuna il suo overlay con i suoi elementi.',
      '<strong>La chat non compare.</strong> È spenta di base: si accende dal suo interruttore.',
      '<strong>La chat si è fermata e non arriva più niente.</strong> La pagina aveva perso il filo col bot, per un riavvio o un salto di rete. Ora lo riprende da sola e rilegge tutto; una sorgente rimasta aperta da prima di questo aggiornamento va ricaricata una volta.',
      '<strong>L\'obiettivo resta a zero.</strong> Conta da quando l\'hai acceso: gli eventi di prima non tornano indietro.',
      '<strong>Ho spostato tutto e non mi piace più.</strong> Doppio clic su un elemento lo rimette dov\'era.',
    ] },
  ],
  faq: [
    { d: 'Serve installare un plugin in OBS?', r: 'No. È una pagina web: basta la sorgente Browser che OBS ha già.' },
    { d: 'Posso usare overlay diversi in scene diverse?', r: 'Sì, ed è il motivo per cui ognuno ha il suo link: elementi e stile sono suoi. Un «solo alert» sopra il gioco e un «solo chat» nella scena della pausa, per dire.' },
    { d: 'Se cambio qualcosa devo ricaricare OBS?', r: 'No: quello che cambi arriva subito. Ricaricare serve solo se hai chiuso e riaperto tutto.' },
    { d: 'Chi ha il link può fare danni?', r: 'Può far comparire cose nel tuo overlay, quindi non va condiviso. Non dà accesso al pannello né al tuo account. Se è scappato, fai un link nuovo dal tasto accanto al link: il vecchio muore subito.' },
    { d: 'L\'obiettivo conta anche a canale spento?', r: 'Conta gli eventi che arrivano, e i follow arrivano anche da offline. Se non li vuoi, si spegne e si riaccende quando serve.' },
    { d: 'Posso mettere l\'overlay in Streamlabs o in un altro programma?', r: 'Sì: va bene qualunque programma che sappia aprire una pagina web come sorgente.' },
  ],
};
