// © 2024–2026 Andrea Taliento (ANDRYXify) — Tutti i diritti riservati — socialbot.live
// Proprietà intellettuale · ANDRYX-IP::a7f39c1e8b424d90-4f7b-taliento::socialbot.live
// Manuale: Overlay Studio. La forma dei manuali e il perche' stanno in
// src/web/manuali.js; le lingue in docs/LINGUE.md.

export default {
  slug: 'overlay',
  schede: ['alert'],
  titolo: 'Manuale dell\'Overlay Studio: alert, chat, obiettivi | SocialBot',
  h1: 'Manuale dell\'Overlay Studio',
  desc: 'Comporre l\'overlay per OBS: overlay e occasioni, la tela, alert, chat, player, conto alla rovescia, obiettivi e cartelli, con i valori di base e i limiti.',
  aggiornata: '2026-09-27',
  corpo: [
    { h2: 'Overlay Studio', scheda: 'alert', p: [
      'L\'overlay è <strong>una pagina web</strong>. In OBS si mette come sorgente <em>Browser</em>. Da lì in poi quello che decidi nella scheda «Overlay Studio», nel gruppo «Scena & overlay», compare in diretta senza toccare più niente in OBS.',
      'La scheda si apre sul <strong>banco</strong>: a sinistra i livelli, al centro la tela 1920×1080, a destra le proprietà. Le impostazioni di alert, chat, ultimo follower e sub, player, conto alla rovescia, conto alla pubblicità, hype train, classifica Bit, boss, testo a schermo, nome del comando e muro delle emote stanno dentro «Proprietà»: selezioni l\'elemento sulla tela e le trovi lì, divise in gruppi che si aprono uno alla volta. Sotto il banco restano le carte «Metterlo nella diretta», «Gli obiettivi», «Cartelli» e «CSS avanzato».',
      'In testa alla scheda <strong>«Tutto schermo»</strong> toglie il menù di lato e lascia tutta la larghezza alla tela. Il menù si disfa a matita e aspetta sul bordo sinistro: ci arrivi col cursore e si ridisegna, lo lasci e si disfa. «Rimetti il menù» lo riporta di lato. Il browser ricorda la scelta per questa scheda.',
      'La scheda c\'è in ogni piano, anche in quello gratuito. La usano il proprietario del canale e i moderatori. Le poche cose riservate al proprietario sono segnate qui sotto.',
      'Su un telefono tenuto in verticale compare la carta «Gira il telefono»: il banco lavora in orizzontale.',
    ] },

    { h3: 'Gli overlay e le occasioni' },
    { p: ['Puoi avere fino a <strong>12 overlay</strong>. Ognuno ha il suo link, i suoi elementi accesi, le sue posizioni e il suo aspetto: un overlay «solo alert» in una scena e uno «solo chat» in un\'altra. I controlli stanno nella testata del banco.'] },
    { tabella: [
      ['Controllo', 'Cosa fa'],
      ['«Overlay»', 'Sceglie l\'overlay che stai modificando. Se hai modifiche non salvate il pannello chiede prima: «Salva ed esci», «Esci senza salvare» o «Resta qui».'],
      ['«Nuovo…»', 'Crea un overlay. In «Parti da» scegli «Come quello che sto modificando» oppure una delle nove vesti pronte. Il nome di serie è «Overlay» col suo numero. Nasce con dentro tutti gli elementi e con un link suo.'],
      ['«Rinomina»', 'Cambia il nome nell\'elenco. Il link resta lo stesso.'],
      ['«Duplica»', 'Copia visibilità, posizioni, aspetto e CSS in un overlay nuovo, con un link suo. Il nome di serie finisce con «(copia)».'],
      ['«Elimina»', 'Toglie l\'overlay dopo una conferma. Il suo link smette di funzionare e in OBS resta una sorgente vuota. L\'ultimo overlay non si toglie: «Deve restare almeno un overlay.»'],
      ['«link overlay»', 'Il link sta nascosto apposta. L\'icona dei due fogli lo copia, l\'occhio lo apre in una scheda del browser per guardarlo.'],
      ['La chiave accanto al link', 'Solo il proprietario. Premi una volta e poi di nuovo entro cinque secondi: nasce un link nuovo e il vecchio smette subito di funzionare, per tutti gli overlay e per i link della webcam in «Effetti & suoni». Poi rimetti il link nuovo nelle sorgenti di OBS.'],
      ['«Salva overlay»', 'Salva insieme alert, chat, ultimo follower e sub, CSS e visibilità. OBS non va riavviato.'],
      ['«?»', 'Apre «Come funziona» in cima alla scheda.'],
    ] },
    { p: ['Al tredicesimo overlay il pannello risponde «Massimo 12 overlay.»'] },
    { p: [
      'Un\'<strong>occasione</strong> è un\'aggiunta sopra l\'overlay che hai già. La accendi e compare, la spegni e torna tutto com\'era. Il link in OBS resta lo stesso.',
      'La tendina «Occasione» parte da «Tutti i giorni», cioè l\'overlay di sempre. Scegli un\'occasione e sopra la tela compare la fascia «Stai modificando», col nome e il riassunto di cosa cambia. Da quel momento quello che accendi, spegni e sposti finisce nell\'occasione. I livelli lo segnano con «in più», «via» e «spostato».',
      'Scegliere un\'occasione non la manda in onda. La manda la spunta «In onda adesso» nella fascia. In onda ce n\'è una sola per overlay, e nella tendina porta «· in onda». Il pannello conferma con «In onda. Su OBS non tocchi niente.» e, quando la spegni, con «Spenta: torna tutto com\'era.»',
      '«Nuova…» apre quattro modelli, ognuno con l\'anteprima su questo overlay e la riga di cosa cambierebbe davvero. «Subathon» accende conto alla rovescia, obiettivi e hype train. «Torno subito» toglie alert, chat, ultimo follower e ultimo sub, e tiene musica e conto alla rovescia. «Serata speciale» accende cartelli, effetti e obiettivi. «La faccio io» parte uguale a com\'è adesso. Se un modello dice «queste cose ce le hai già così», su questo overlay quella roba è già accesa.',
      'Il nome, in «Come la chiami», arriva a 40 caratteri. Le occasioni sono al massimo 8 per overlay: alla nona compare «Massimo 8 occasioni per overlay.»',
      '«Torna a tutti i giorni» chiude la fascia. «Elimina» toglie l\'occasione dopo una conferma, e l\'overlay di sempre resta com\'è.',
      'L\'occasione tiene solo quello che differisce dall\'overlay di sempre. Rimettere una cosa com\'era la toglie dall\'occasione. Se domani cambi l\'overlay di sempre, l\'occasione segue le modifiche, tranne su quello che nomina lei.',
    ] },

    { h3: 'La tela, i livelli e le proprietà' },
    { p: [
      '<strong>«Livelli»</strong>, a sinistra, elenca quello che c\'è in questo overlay. Ogni riga ha la presa per trascinarla, il nome, la posizione, il lucchetto e l\'occhio, e le righe stanno nell\'ordine dei livelli: in cima il primo piano. L\'occhio toglie l\'elemento da questo overlay e lo rimette. Un <strong>«!»</strong> rosso vuol dire che l\'elemento è spento del tutto: premilo e si accende («Elemento acceso ✓»). Se l\'overlay è vuoto leggi «Questo overlay è vuoto: con «Aggiungi» ci metti dentro quello che vuoi.»',
      '<strong>«Aggiungi»</strong>, in fondo ai livelli, ha due parti. «Rimetti in questo overlay» elenca gli elementi che qui non ci sono. «Crea» fa un elemento nuovo: «Un cartello o un\'immagine», «Un obiettivo», «Un contatore».',
      '<strong>«Proprietà»</strong>, a destra, mostra l\'elemento scelto. In alto ci sono «Blocca», «Dietro», «Davanti» e «Ripristina». Sotto ci sono «X» e «Y» in percentuale, da 0 a 100 a passi di 0,1, la spunta «Riquadro», «Dimensione» da 30 a 300% e «Rotazione» da −180 a 180°. Con «Riquadro» acceso la dimensione lascia il posto a «Larg.» e «Alt.», da 2 a 100%. Più giù c\'è tutto l\'aspetto dell\'elemento. Per i contatori, la sfida a tempo e gli effetti a schermo una riga ti manda alla scheda dove si decide cosa fanno. Senza niente di scelto leggi «Scegli un elemento sulla tela o nei livelli per modificarlo.»',
      'Le due sponde si arrotolano col trattino, si staccano trascinandole per la testa e si riagganciano con un doppio clic. Il browser ricorda dove le hai messe.',
      'Sotto la tela una riga riassume nome, X, Y, dimensione e rotazione dell\'elemento scelto, con i tasti utili.',
    ] },
    { tabella: [
      ['Per fare', 'Come'],
      ['Scegliere', 'Clic sull\'elemento o sulla sua riga nei livelli. <strong>Esc</strong> toglie la scelta.'],
      ['Spostare', 'Trascina. Si aggancia da solo al centro, ai bordi, ai terzi della tela e ai centri degli altri elementi.'],
      ['Spostare fine', 'Tieni <strong>Ctrl</strong> (⌘ su Mac) mentre trascini: va a un quinto della velocità e non si aggancia.'],
      ['Spostare dritto', 'Tieni <strong>Maiusc</strong> mentre trascini: resta su un asse.'],
      ['Spostare senza aggancio', 'Tieni <strong>Alt</strong> mentre trascini, oppure spegni la spunta «Aggancia».'],
      ['Annullare il trascinamento', '<strong>Esc</strong> prima di mollare: torna dov\'era.'],
      ['Spostare al pixel', 'Le frecce. Con <strong>Maiusc</strong> vanno di dieci pixel.'],
      ['Ridimensionare', 'La maniglia ⤡, <strong>Alt+rotellina</strong> sull\'elemento (con Ctrl a passi fini) o «Dimensione».'],
      ['Ruotare', 'La maniglia ⟳, <strong>Maiusc+rotellina</strong> sull\'elemento o «Rotazione».'],
      ['Dare un perimetro', 'Tira un bordo dell\'elemento scelto, oppure spunta «Riquadro».'],
      ['Allineare', 'I sei pulsanti in alto: sinistra, centro, destra, alto, centro, basso. Senza niente di scelto: «Scegli prima un livello.»'],
      ['Bloccare', 'Il lucchetto nel livello o «Blocca»: un elemento bloccato non si sposta, non si ridimensiona e non si ruota per sbaglio.'],
      ['Davanti e dietro', 'Nei «Livelli» in cima c\'è quello in primo piano. Trascina una riga dalla presa, i sei puntini a sinistra: più su va davanti, più giù va dietro, e la tela lo segue mentre la muovi. Da tastiera Alt+↑ e Alt+↓ (con Maiusc fino in cima o in fondo), oppure Ctrl+] e Ctrl+[, o «Davanti» e «Dietro» in «Proprietà». Scegliere un elemento non lo porta davanti: le maniglie stanno sopra a tutto. Di serie in fondo stanno il muro delle emote e gli effetti a schermo, in cima l\'alert e i contatori. In diretta l\'ordine è lo stesso della tela, ed è di ogni overlay; un\'occasione può avere il suo. Anche l\'ordine torna indietro con Ctrl+Z.'],
      ['Rimettere a posto', 'Doppio clic sull\'elemento, <strong>Canc</strong>, oppure «Ripristina»: torna nella sua posizione di serie.'],
      ['Tornare indietro', '<strong>Ctrl+Z</strong>. Per rifare: <strong>Ctrl+Y</strong> o Ctrl+Maiusc+Z. Le due frecce in alto a sinistra fanno lo stesso. Tengono 60 passi per overlay, finché la pagina resta aperta.'],
      ['Ingrandire la tela', '<strong>Ctrl+rotellina</strong> attorno al puntatore, oppure «−» e «+» a passi del 25%, da 50% a 400%. «Adatta» rimette tutta la scena nello schermo.'],
      ['Sul telefono', 'Tocca un elemento e trascinalo col dito. Le maniglie tonde lo ridimensionano e lo ruotano.'],
    ] },
    { p: [
      'Le spunte della barra: <strong>«Griglia»</strong>, accesa di serie. <strong>«Zone sicure»</strong> disegna due cornici tratteggiate, al 5% e al 10% dai bordi. <strong>«Aggancia»</strong> è accesa di serie e il browser la ricorda. <strong>«Dal vivo»</strong> fa passare una riga di chat finta ogni due-quattro secondi e un alert finto ogni sette.',
      '<strong>«Riferimento»</strong> mette sotto la tela uno screenshot della scena o una grafica. Puoi anche incollarla o trascinarla sulla tela. Serve un\'immagine PNG, JPG o WebP fino a 25 MB. Poi compaiono il cursore della trasparenza, da 10 a 100 e di serie 60, la spunta «Mostra» e «Togli». Resta nel tuo browser, una per overlay: non va sul server e non va in onda.',
      '<strong>Il riquadro.</strong> La chat dentro un riquadro va a capo alla sua larghezza e impila le righe dal basso. Quando non ci stanno più, la riga più vecchia esce dall\'alto. Per tutti gli altri elementi il riquadro è la scatola: l\'altezza dà la grandezza, la larghezza dà lo spazio. Il player in un riquadro largo ha tanto posto per il titolo, in uno basso e largo diventa una barra sottile. Carattere e proporzioni interne non si deformano, e niente esce dalla tela.',
      'Quello che vedi sulla tela ha le misure della diretta. Gli angoli della tela sono quelli dell\'overlay vero, quindi un elemento «in alto a destra» sta allo stesso posto anche in OBS. Un elemento spento resta sulla tela, sbiadito, così lo ritrovi.',
    ] },

    { h3: 'Gli elementi in scena' },
    { tabella: [
      ['Elemento', 'Cos\'è', 'Dove sta di serie', 'Dove si decide cosa fa'],
      ['«Alert eventi»', 'Un cartello animato con suono per follow, sub, bit, raid e donazioni.', 'in alto al centro', 'qui, in «Proprietà»'],
      ['«Chat a schermo»', 'I messaggi della chat, con emote e badge.', 'in basso a sinistra', 'qui, in «Proprietà»'],
      ['«Ultimo follower», «Ultimo sub»', 'Una pastiglia col nome dell\'ultimo arrivato.', 'in basso a destra', 'qui, in «Proprietà»'],
      ['Obiettivi', 'Barre che si riempiono da sole. Fino a 6.', 'in alto a sinistra', 'carta «Gli obiettivi»'],
      ['Contatori', 'I numeri che tu e i moderatori muovete in chat.', 'in basso a sinistra', 'scheda «Comandi»'],
      ['Cartelli', 'Una scritta o un\'immagine ferma in scena. Fino a 8.', 'in basso a sinistra', 'carta «Cartelli»'],
      ['«Player musica»', 'Quello che stai ascoltando su Spotify.', 'in basso a sinistra', 'qui, in «Proprietà»'],
      ['«Conto alla rovescia»', 'Quanto manca all\'inizio, anche in subathon.', 'in alto a destra', 'qui, in «Proprietà»'],
      ['«Conto alla pubblicità»', 'Quanto manca alla prossima pubblicità, e durante la pausa quanto manca al ritorno. I tempi li dice Twitch.', 'in alto a destra', 'qui, in «Proprietà»'],
      ['«Hype train»', 'Il treno di Twitch: livello, barra, tempo che resta.', 'in alto a destra', 'qui, in «Proprietà»'],
      ['«Classifica Bit»', 'Chi ha messo più Bit.', 'in alto a sinistra', 'qui, in «Proprietà»'],
      ['«Sfida a tempo»', 'La carta della penitenza riscattata coi punti canale.', 'in alto a destra', 'scheda «Penitenze»'],
      ['«Boss»', 'La carta del boss di turno: nome, vita, tempo che resta, chi lo colpisce e quanto.', 'in alto al centro', 'scheda «Giochi»'],
      ['«Testo a schermo»', 'La scritta che un comando manda con «Mostra testo sull\'overlay».', 'al centro', 'scheda «Comandi»'],
      ['«Nome del comando»', 'La pastiglia «!comando» che compare quando parte un effetto.', 'in basso al centro', 'scheda «Effetti & suoni»'],
      ['«Muro delle emote»', 'Le emote che la chat scrive volano sulla scena; la stessa emote ripetuta cresce e poi esplode. Di serie spento.', 'tutto lo schermo', 'qui, in «Proprietà»'],
      ['«Effetti a schermo»', 'L\'area dove compaiono le immagini e i video dei tuoi effetti.', 'al centro', 'scheda «Effetti & suoni»'],
    ] },
    { p: [
      'Le immagini e i video di «Effetti & suoni» compaiono nell\'elemento <strong>«Effetti a schermo»</strong>: lo sposti e lo ridimensioni come gli altri, e in un riquadro si adattano senza deformarsi. Sulla tela c\'è un\'immagine d\'esempio, messa come un effetto vero. Quelli che hai messo <strong>a tutto schermo</strong>, e gli effetti pronti, non passano da quest\'area: coprono lo schermo, al posto degli effetti nell\'ordine dei livelli. Anche loro compaiono solo negli overlay dove «Effetti a schermo» c\'è. Un premio a punti canale con una posizione sua la tiene, sullo schermo intero: si sceglie nella scheda «Effetti & suoni» (<a href="/manuale/effetti">manuale degli effetti</a>). I tasti di CONSOLify non sono elementi della tela: compaiono in ogni overlay.',
      'Un <strong>contatore</strong> si crea anche da qui: «Aggiungi», poi «Un contatore». Si apre «Un contatore nuovo» con «Comando (senza !)» fino a 30 caratteri, «Etichetta» fino a 40, «Emoji» facoltativa, «Passo (+)» da 1 a 1000 e «Parola automatica» facoltativa, che fa +1 ogni volta che quella parola compare in chat. «Crea e mettilo qui» lo mette in questo overlay. «Crea in una copia dell\'overlay» fa un overlay nuovo con tutto quello che vedi più il contatore, e lascia com\'è quello di sempre. Con 12 overlay la copia non si può fare. Se il comando è già di un altro contatore, il pannello te lo dice e il contatore lo rimetti dall\'elenco di «Aggiungi».',
      'In «Proprietà» un contatore ha «A schermo», «Cosa scrive» (fino a 80 caratteri, con <code>{emoji}</code>, <code>{etichetta}</code> e <code>{valore}</code>; di serie <code>{emoji} {etichetta}: {valore}</code>), i colori «Testo» e «Sfondo», «Carattere» (Sistema, Inter, Space Grotesk, JetBrains Mono, Fraunces, Bricolage), «Senza sfondo» e «Grassetto». La dimensione al 100% vale 40 pixel di altezza. Il valore lo muovete in chat con <code>!comando+</code> e <code>!comando reset</code>; il resto sta nel <a href="/manuale/moduli">manuale dei comandi</a>.',
    ] },

    { h3: 'Cosa vale per ogni overlay e cosa per tutto il canale' },
    { tabella: [
      ['Cosa', 'Di ogni overlay', 'Una sola per il canale'],
      ['Tutti gli elementi', 'se si vedono, posizione, dimensione, rotazione, riquadro, blocco, ordine dei livelli', 'l\'interruttore generale dell\'elemento, tranne ultimo follower e ultimo sub'],
      ['Alert eventi', 'l\'aspetto: forma, materia, cornice, composizione, animazioni, font, colori, misure', 'interruttori, testi, suoni, immagini, icone, colori e volumi dei singoli eventi, soglie, posizione di serie e durata'],
      ['Chat a schermo', 'l\'aspetto e «Quali chat in questo overlay»', 'interruttore, posizione di serie, messaggi visibili, sparizione'],
      ['Ultimo follower e ultimo sub', 'interruttore, testo, icona, aspetto', 'il nome mostrato'],
      ['CSS avanzato', 'tutto', ''],
      ['Obiettivi e cartelli', 'se si vedono e dove', 'traguardo e conto, testo o immagine, aspetto'],
      ['Player, conto alla rovescia, conto alla pubblicità, hype train, classifica Bit, sfida a tempo, boss, testo a schermo, nome del comando, contatori, muro delle emote', 'se si vedono e dove', 'tutte le impostazioni e l\'aspetto'],
      ['Effetti a schermo', 'se si vedono, dove e quanto grandi', 'cosa fa ogni effetto, nella scheda «Effetti & suoni»'],
    ] },
    { p: [
      'Per avere due obiettivi o due cartelli con un aspetto diverso in due scene ne fai due, e in ogni overlay accendi quello giusto.',
      '<strong>Si salvano da soli</strong>, appena molli il mouse o cambi un valore: posizioni, dimensioni, rotazioni, riquadri, blocchi, ordine dei livelli, visibilità, occasioni, «Quali chat in questo overlay», player, conto alla rovescia, conto alla pubblicità, hype train, classifica Bit, boss, testo a schermo, nome del comando, muro delle emote, obiettivi, cartelli e contatori. I loro pulsanti «Salva» salvano subito, senza aspettare.',
      '<strong>Aspettano un pulsante</strong>: alert eventi («Salva alert»), chat a schermo («Salva chat»), ultimo follower e ultimo sub, CSS («Salva CSS»). «Salva overlay» li salva tutti insieme. Finché non salvi, in basso resta la barra delle modifiche non salvate, con «Annulla» per tornare a com\'era. Se cambi scheda, overlay o pagina il pannello chiede prima.',
      'Se un salvataggio non riesce leggi «Non riesco a salvare: controlla la connessione, riprovo al prossimo cambiamento.»',
      'In cima a ogni gruppo «Aspetto» c\'è la riga <strong>«Veste»</strong> con nove vesti pronte: Viola classico, Neon, Minimal chiaro, Retro arcade, Manga, Vetro, Terminale, Nastro, Esagoni. Una veste cambia l\'elemento che stai guardando; sul muro delle emote accende o spegne l\'ombra. «a tutto l’overlay» stende la veste scelta su tutti gli elementi. Dopo cambi a mano quello che vuoi. Se premi «a tutto l’overlay» senza aver scelto una veste leggi «Scegli prima una veste qui sopra.»',
    ] },

    { h3: 'Metterlo nella diretta' },
    { passi: [
      { t: 'Aggiungi la sorgente', d: 'Nel tuo programma di diretta (OBS, Streamlabs…): «Sorgenti → + → Browser».' },
      { t: 'Incolla il link', d: 'Copialo con l\'icona accanto a «link overlay» e metti 1920 × 1080.' },
      { t: 'Spunta l\'aggiornamento', d: '«Aggiorna browser quando la scena diventa attiva».' },
      { t: 'Fai sentire i suoni', d: 'Nella sorgente Browser spunta «Controlla l\'audio via OBS»: il suono di alert ed effetti esce dalla diretta invece che dal browser.' },
    ] },
    { p: [
      'Ogni overlay ha il suo link: in ogni scena metti quello che ti serve.',
      '<strong>Il link è un segreto.</strong> Chi ce l\'ha può far comparire cose nel tuo overlay. Non dà accesso al pannello. Non va in un video, in uno screenshot o in una chat. Se è scappato, il proprietario fa un link nuovo con la chiave accanto al link.',
    ] },

    { h3: 'Player musica' },
    { p: ['Quello che stai ascoltando, a schermo. Compare quando la musica parte e, di serie, sparisce quando la fermi. Legge da Spotify, che si collega nella scheda «Musica» (<a href="/manuale/diretta">manuale della diretta</a>). Si accende con l\'interruttore «Player musica».'] },
    { tabella: [
      ['Impostazione', 'Di base', 'Scelte e limiti'],
      ['«Disposizione»', 'copertina a sinistra', 'copertina a sinistra · a destra · sopra · solo la copertina · libera: ogni pezzo dove vuoi'],
      ['«Righe»', 'una riga', 'una riga · due: titolo e artista'],
      ['«Dove»', 'in basso a sinistra', 'i quattro angoli, o dove lo trascini'],
      ['«Prima riga», «Seconda riga»', '<code>{titolo}</code> e <code>{artista}</code> sulla prima, <code>{artista}</code> sulla seconda', 'fino a 80 caratteri; si usano <code>{titolo}</code>, <code>{artista}</code>, <code>{album}</code>; la seconda vale solo con due righe'],
      ['«Copertina»', 'quadrata', 'quadrata · tonda · vinile che gira · il mio video, in chiaro · niente'],
      ['«Avanzamento»', 'barra sotto', 'barra sotto · anello sulla copertina · niente'],
      ['«Tempi»', 'niente', 'trascorso · quanto manca · tutti e due'],
      ['«Entrata»', 'dissolvenza', 'dissolvenza · scivola da lato · sale dal basso · secca'],
      ['«Se è in pausa»', 'sparisce', 'sparisce · resta a schermo'],
      ['«Le onde»', 'onde che ballano', 'onde che ballano · onde e copertina che pulsa · niente onde'],
      ['«Sfondo»', 'niente', 'niente · copertina sfocata · colori del disco · il mio video, sfocato'],
      ['«Il mio video»', 'nessuno', 'un video caricato in «Effetti & suoni», in loop e muto'],
      ['«Corpo»', 'Normale', 'Slim · Normale · Cicciotto: la taglia di tutto il player'],
      ['«Tema»', 'Nessuno', 'Vinile · CD · Cassetta · Terminale · Manga · Esagono'],
      ['«Larghezza del testo»', '0', 'da 0 a 30; a 0 decide il corpo'],
      ['«Il titolo lungo scorre»', 'acceso', 'scorre solo se non ci sta'],
      ['«Colore preso dalla copertina»', 'spento', 'acceso, l\'accento cambia disco per disco'],
      ['«Si rianima a ogni brano»', 'acceso', 'la copertina rientra e il testo risale a ogni cambio'],
      ['«Misure»', 'tutte a 100', 'un cursore per pezzo, da 40 a 250: spazio attorno, copertina, figura dietro, prima e seconda riga, tempi, barra, onde; «Di serie» le riporta a 100'],
      ['«Colori a parte»: «Ogni pezzo col suo colore»', 'spento: testo e accento per tutti', 'acceso, prima riga, seconda riga, tempi, barra e onde hanno ognuno il suo colore'],
    ] },
    { p: [
      'Ogni <strong>tema</strong> porta la sua figura e si muove solo mentre suona. Il vinile sporge da dietro e gira. Il CD gira e cambia riflesso. La cassetta fa girare le bobine. Il terminale ha prompt e cursore. Il manga ha un retino che pulsa. L\'esagono ha la copertina a sei lati e un anello che ruota. Ogni tema entra ed esce come l\'oggetto vero. «Rivedi l\'entrata» te lo mostra sulla tela.',
      'Con la disposizione <strong>«libera»</strong> compare «Le parti»: scegli il «Pezzo» e ne scrivi «X», «Y», la «Larghezza» (da 5 a 100) e l\'allineamento del «Testo». Sulla tela trascini ogni pezzo; righe e barra hanno una maniglia a destra per la larghezza. «Come in riga» li rimette in fila.',
      'Il video è tuo: un loop corto caricato in «Effetti & suoni», perché Spotify non dà un video del brano. Con i temi vinile e CD la copertina resta quella del disco.',
      '«Niente onde» le toglie, non le lascia ferme. La copertina pulsa solo se Spotify dice il tempo del brano. Quando non lo dice resta ferma, e le onde ballano comunque.',
    ] },

    { h3: 'Conto alla rovescia e subathon' },
    { p: ['Quanto manca all\'inizio. Scegli i minuti e premi «Fai partire». Il conto sta nel canale: se ricarichi l\'overlay o riavvii tutto, continua da dove era. «Ferma» lo ferma. Accanto ai pulsanti leggi «in corso» mentre gira.'] },
    { tabella: [
      ['Impostazione', 'Di base', 'Limiti'],
      ['«Conto alla rovescia» (interruttore)', 'spento', ''],
      ['«Titolo»', 'Si comincia tra', '60 caratteri'],
      ['«Quando arriva a zero scrive»', 'Si comincia!', '60 caratteri'],
      ['«Dove»', 'in alto a destra', 'i quattro angoli, o dove lo trascini'],
      ['«A zero»', 'resta a schermo', 'resta a schermo · sparisce'],
      ['«Minuti»', '15', 'da 1 a 600'],
      ['«Parte da solo quando l\'overlay si apre»', 'spento', 'per la schermata d\'attesa'],
    ] },
    { p: ['Con <strong>«Parte da solo»</strong> il conto parte quando lo accendi e ogni volta che un overlay si apre e lo trova fermo. Se sta già andando non riparte da capo.'] },
    { p: ['Il <strong>subathon</strong> non è un secondo conto: è questo, con una regola in più. Lo accendi sotto il conto alla rovescia. Da quel momento sub, bit e donazioni aggiungono tempo a quello che manca, e a schermo si vede il conto che hai già in scena.'] },
    { tabella: [
      ['Impostazione', 'Di base', 'Limiti'],
      ['«Subathon» (interruttore)', 'spento', ''],
      ['«Minuti per sub»', '5', 'da 0 a 120'],
      ['«Minuti ogni 100 bit»', '1', 'da 0 a 120; 50 bit valgono metà'],
      ['«Minuti per euro donato»', '2', 'da 0 a 120'],
      ['«Non può mancare più di (ore)»', '12', 'da 0 a 72; a 0 non c\'è tetto'],
      ['«Dillo in chat quando il conto sale»', 'acceso', ''],
      ['«Cosa scrive»', 'Grazie {chi}! Il conto sale di {quanto}.', '200 caratteri, con <code>{chi}</code> e <code>{quanto}</code>'],
    ] },
    { p: ['Il tetto è su quanto manca, non su quanto hai aggiunto in tutto. Se il conto è già arrivato a zero, un sub non lo fa ripartire. Chi guarda chiede <code>!subathon</code> per sapere quanto manca.'] },

    { h3: 'Conto alla pubblicità' },
    { p: [
      'Dice a chi guarda quanto manca alla prossima pausa pubblicitaria, e durante la pausa quanto manca al tuo ritorno. Qui non scegli nessun tempo: li dice Twitch, e il conto li segue da solo, anche quando rimandi la pausa. Si vede solo mentre sei in diretta e c\'è una pausa in programma; negli altri momenti non c\'è niente a schermo.',
      'Serve il permesso di leggere la programmazione delle pubblicità. Se manca, nella scheda «Stato» premi «Aggiorna i permessi». Gli avvisi in chat sulla pubblicità (<a href="/manuale/diretta">manuale della diretta</a>) sono un\'altra cosa: il conto funziona anche con quelli spenti.',
    ] },
    { tabella: [
      ['Impostazione', 'Di base', 'Limiti'],
      ['«Conto alla pubblicità» (interruttore)', 'spento', ''],
      ['«Prima della pausa»', 'Pubblicità fra', '60 caratteri; vuoto, esce nella lingua della chat'],
      ['«Durante la pausa»', 'Torno fra', '60 caratteri; vuoto, esce nella lingua della chat'],
      ['«Dove»', 'in alto a destra', 'i quattro angoli, o dove lo trascini'],
      ['«Da quando si vede»', 'sempre', 'sempre · 1, 2, 5, 10 o 30 minuti prima'],
      ['«Resta anche durante la pausa, col conto del ritorno»', 'acceso', ''],
    ] },
    { p: ['Quando la pausa comincia il conto passa da solo al titolo di «Durante la pausa». Arrivato a zero se ne va: non resta mai un 0:00 a schermo. Se apri o ricarichi l\'overlay a pausa in corso, riparte da dove era.'] },

    { h3: 'Hype train' },
    { p: ['Il treno lo fa Twitch: livello, punti e tempo che resta li decide lui, e qui si vedono. Non c\'è niente da far partire. Quando il treno parte compare; quando Twitch dice che è finito, la carta resta il tempo di leggere il livello raggiunto e poi va via. Se il pannello ti chiede un permesso nuovo di Twitch, serve per questo.'] },
    { tabella: [
      ['Impostazione', 'Di base', 'Note'],
      ['«Mostralo nella scena»', 'spento', 'la carta in scena'],
      ['«Titolo»', 'Hype train', '60 caratteri'],
      ['«Dove»', 'in alto a destra', 'i quattro angoli, o dove lo trascini'],
      ['«Mostra chi ha spinto di più»', 'acceso', ''],
      ['«Mostra il record del canale, quando Twitch lo manda»', 'spento', ''],
      ['«Dillo in chat»', 'spento', 'le righe in chat, separate dalla scena'],
      ['«Quando parte»', 'Hype train partito! Spingiamo.', '200 caratteri'],
      ['«Quando sale di livello»', 'Hype train al livello {livello}!', '<code>{livello}</code>'],
      ['«Quando manca poco al livello»', 'Manca poco al livello {prossimo}: {manca} punti!', '<code>{prossimo}</code> <code>{manca}</code>; si dice nell\'ultimo quarto della salita'],
      ['«Quando finisce»', 'Treno finito al livello {livello}. Grazie {chi}!', '<code>{livello}</code> <code>{chi}</code> <code>{punti}</code>'],
    ] },
    { p: ['Il bot parla una volta per momento, non a ogni sub: i sub li annunciano già gli alert. Svuota una casella e quella frase non si dice più. Chi ha il treno già a schermo da Twitch può tenere solo le righe in chat. I sub e i bit che fanno crescere il treno contano già negli obiettivi e nel subathon, uno per uno. Chi guarda chiede <code>!treno</code>.'] },

    { h3: 'Classifica Bit' },
    { tabella: [
      ['Impostazione', 'Di base', 'Scelte e limiti'],
      ['«Mostrala nella scena»', 'spento', ''],
      ['«Titolo»', 'Classifica Bit', '60 caratteri'],
      ['«Dove»', 'in alto a sinistra', 'i quattro angoli, o dove la trascini'],
      ['«Di quando»', 'questo mese', 'oggi · questa settimana · questo mese · quest\'anno · da sempre'],
      ['«Quante righe»', '3', 'da 1 a 10'],
      ['«Mostra anche quanti Bit»', 'acceso', ''],
    ] },
    { p: ['I numeri sono quelli di Twitch, gli stessi che rispondono a <code>!bit</code>. La classifica si aggiorna quando arriva un cheer. Chi ha cheerato in anonimo non compare, perché non compare nemmeno su Twitch. Se Twitch per un momento non risponde, resta la classifica di prima. Se il pannello ti chiede il permesso di leggere i Bit, serve per questo.'] },

    { h3: 'Boss' },
    { p: [
      'La carta del boss di turno: il nome, la vita che resta, il tempo che gli rimane, chi lo colpisce e quanto. Compare quando arriva un boss. Quando arriva, quanta vita ha e quanto dura si decide nella scheda «Giochi», con «Apri i Giochi» (<a href="/manuale/giochi">manuale dei giochi</a>).',
      'Qui c\'è l\'interruttore «Mostralo nella scena», acceso di serie, e la sua veste: di serie fondo scuro e vita rossa. Di serie sta in alto al centro. Sulla tela lo vedi com\'è in onda: lo sposti, lo ingrandisci, gli dai un riquadro e lo togli da un overlay con l\'occhio, come gli altri elementi.',
    ] },

    { h3: 'Testo a schermo' },
    { p: [
      'Le scritte che un comando mette in scena con «Mostra testo sull\'overlay». Cosa dicono e quanto restano si decide nel comando, con «Apri i Comandi». Qui decidi dove stanno e come sono vestite.',
      '«Mostralo nella scena» è acceso di serie. Di serie la scritta sta al centro, bianca e senza fondo. Per darle un fondo alza «Opacità» nella sua veste.',
    ] },

    { h3: 'Nome del comando' },
    { p: [
      'La pastiglia col nome del comando che compare quando parte un effetto, per esempio «!applausi»: chi guarda capisce chi l\'ha fatto partire e come rifarlo. Gli effetti si fanno nella scheda «Effetti & suoni», con «Apri Effetti & suoni».',
      '«Mostralo nella scena» è acceso di serie. Di serie la pastiglia sta in basso al centro, rosa e tonda. La sposti, la vesti e la togli da un overlay come gli altri elementi.',
    ] },

    { h3: 'Il muro delle emote' },
    { p: [
      'Ogni emote scritta in chat vola nell\'area del muro: di serie <strong>tutto lo schermo</strong>, oppure un riquadro, per esempio sopra la webcam o in una fascia in basso. Si accende con «Mostralo nella scena», spento di serie.',
      'Sulla tela dello Studio il muro di serie è il livello di fondo, sotto a tutto: se occupa tutta la tela, un clic sulla tela vuota lo sceglie. Un\'area grande quanto la tela non ha dove andare: per spostarla la stringi prima dai bordi.',
    ] },
    { tabella: [
      ['Cosa', 'Come funziona', 'Di serie'],
      ['«Cosa vola»', '«Emote di Twitch», «Emote 7TV del canale» ed «Emoji». «Al massimo per messaggio», da 1 a 20. «La stessa emote più volte nello stesso messaggio»: spenta, ogni emote di un messaggio vola una volta sola.', 'Twitch e 7TV, 5 per messaggio, ripetute sì'],
      ['«Movimenti»', 'Dieci: sale come una bolla, attraversa dritta, rimbalza sul fondo, sfreccia, resta appesa e cade, scende come un foglio, salta dal basso, lanciata rimbalza ed esce, batte ferma in un punto, gira attorno al centro. Ogni emote ne pesca uno fra quelli accesi, e almeno uno resta acceso. «Come compare chi nasce dentro l\'area»: «Si ingrandisce», «Appare piano» o «Compare e basta». «Durata (secondi)» da 2 a 20.', 'tutti accesi, si ingrandisce, 6 secondi'],
      ['«Grandezza e veste»', '«Grandezza (% del lato corto dell\'area)» da 2 a 40, «Quanto varia (%)», «Minimo (px)» e «Massimo (px)». Mai più di metà del lato corto, così ogni movimento ci sta anche in un\'area bassa. «Ombra», e «Colori che girano»: «Mai», «Sempre» o «Durante l\'hype train».', '8%, varia del 30%, da 28 a 140 px; ombra; colori durante l\'hype train'],
      ['«Quante»', '«Al massimo a schermo», da 1 a 150. Oltre, le nuove aspettano in una coda breve, «In attesa oltre il massimo» da 0 a 100, che perde le più vecchie; quelle in attesa da più di otto secondi si lasciano perdere, perché arriverebbero fuori tempo.', '50 a schermo, 20 in attesa'],
      ['«Combo»', 'Quando la chat ripete la stessa emote, «Da quante ripetizioni» (da 2 a 50) ne resta una sola che cresce con il suo contatore («×12»). Quando per «Finisce dopo (secondi senza ripetizioni)» nessuno la ripete, esplode nella figura di «Poi esplode in». «Conta una volta per persona»: una persona sola che ripete non fa una combo della chat.', 'accesa, da 4, 6 secondi, fuochi, una volta per persona'],
      ['«Esplosioni»', 'Otto figure fatte di emote: fuochi d\'artificio, fontana, spirale, pioggia, trenino, piramide, scritta e cuore, più «A caso». «Quante emote» da 5 a 80, «Durata (secondi)» da 3 a 15, «La parola della scritta» fino a 8 lettere. Ne parte una alla volta, e al massimo tre aspettano.', '30 emote, 6 secondi, HYPE'],
      ['<code>!esplodi</code>', 'Chi lo scrive fa esplodere le emote del suo messaggio: se ne scrive due volte una, pesa il doppio. «Con !esplodi» sceglie la figura. «Attesa fra due !esplodi (secondi, per tutti)» da 0 a 600. Chi può scriverlo, come si chiama e se è acceso si sceglie nei comandi pronti, con «Apri i Comandi».', 'a caso, 30 secondi'],
      ['«Eventi»', '«Raid» (con le emote 7TV del canale che arriva, se le ha) «da spettatori», «Abbonamenti» «da quanti in un colpo» (una raffica di regali esplode una volta sola), «Bit» «da», «Donazioni» «da (nella tua valuta)», «L’hype train parte», «L’hype train finisce», «Il boss cade». Ognuno ha la sua «Figura».', 'tutti accesi; raid da 5, abbonamenti da 1, bit da 100, donazioni da 5'],
      ['«Premi a punti canale»', '«Aggiungi un premio»: fino a dieci premi, ognuno con la sua figura. Il testo scritto nel riscatto porta le sue emote. Serve il permesso dei punti canale: se manca leggi «Per scegliere un premio a punti canale serve un permesso in più.» e «Concedi il permesso».', 'nessuno'],
      ['«Chi»', '«Chi fa volare le emote»: «Tutti», «Abbonati in su», «VIP in su», «Moderatori e streamer». «Escludi i bot di chat più comuni». «Persone escluse» ed «Emote escluse», separate da virgola.', 'tutti, bot esclusi'],
    ] },
    { p: ['Nello Studio il muro gira con emote d\'esempio mosse dallo <strong>stesso motore</strong> dell\'overlay: i movimenti che vedi sulla tela sono quelli della diretta. Sotto «Prova una figura» c\'è un tasto per ogni figura: la mostra sulla tela e la manda anche all\'overlay vero, con le emote 7TV del tuo canale. Mandarla all\'overlay è del proprietario del canale, come le altre prove.'] },

    { h3: 'Gli obiettivi' },
    { p: [
      'Barre che si riempiono da sole mentre arrivano follower, sub, bit o donazioni. Ne puoi avere <strong>fino a 6</strong>: al settimo il pannello risponde «Sei obiettivi sono il massimo.» Premi «Aggiungi obiettivo»; l\'obiettivo compare sulla tela, già scelto.',
      'Ogni riga mostra l\'interruttore, il nome, il punto a cui è arrivato e il traguardo, poi «Dov’è», che lo sceglie sulla tela, e «Togli».',
    ] },
    { tabella: [
      ['Impostazione', 'Di base', 'Limiti'],
      ['«Titolo»', 'vuoto, si vede «Obiettivo» col numero', '60 caratteri'],
      ['«Conta»', 'follower', 'follower · abbonati · bit · euro donati'],
      ['«Traguardo»', '100', 'da 1 a 1.000.000'],
      ['«Parte da»', '0', 'da 0 a 1.000.000'],
      ['«Parti da quanti ne ho adesso»', 'spento', 'solo per follower e abbonati'],
      ['«Dove» (in «Proprietà»)', 'in alto a sinistra', 'i quattro angoli, o dove lo trascini'],
      ['Aspetto (in «Proprietà»)', 'dimensione Media, carattere sistema, testo bianco, barra rosa, opacità 85, angoli 12', '«Dimensione», «Carattere», «Testo», «Sfondo», «Barra», «Opacità» da 0 a 100, «Angoli» da 0 a 30, «Forma», «Materia», «Cornice»'],
    ] },
    { p: [
      'Il traguardo, il conto e l\'aspetto sono <strong>uno solo per il canale</strong>. Per ogni overlay scegli se l\'obiettivo si vede e dove sta.',
      '<strong>Il conto è quello vero.</strong> Lo tiene il bot contando gli eventi: un cheer da 500 bit vale 500, un sub regalato vale uno, gli euro salgono dell\'importo di ogni donazione. Due obiettivi che contano la stessa cosa salgono insieme: è il modo di fare una scala, «100 follower» e poi «500 follower». Conta da quando l\'hai acceso.',
      '<strong>«Parte da»</strong> è il gradino sotto: «1000 follower in tutto» invece di «altri 1000». Con <strong>«Parti da quanti ne ho adesso»</strong> il bot chiede a Twitch il numero vero e lo tiene allineato, invece di fermarsi a una lettura vecchia. Vale per follower e abbonati. Per bit ed euro la spunta è spenta: Twitch non tiene un totale di sempre dei bit, e le donazioni non passano da Twitch. Lì la partenza la scrivi tu. Se Twitch non risponde leggi «Non riesco a leggerlo da Twitch: controlla i permessi e riprova.»',
      'Il conto sta nelle impostazioni del canale e sopravvive a un riavvio. Lo rimetti a zero solo tu, con «Riparti da zero» e una conferma.',
    ] },

    { h3: 'Cartelli' },
    { p: [
      'Una scritta o un\'immagine tua, ferma in scena: il titolo della serata, le regole, il logo, un «torno subito». Nessun evento la muove. Ne puoi avere <strong>fino a 8</strong>; al nono leggi «Otto cartelli sono il massimo.» Premi «Aggiungi cartello»: il cartello compare sulla tela, già scelto. Ogni riga mostra l\'interruttore, il nome, «scritta» o «immagine», poi «Dov’è» e «Togli».',
      'Il contenuto e l\'aspetto sono <strong>uno solo per il canale</strong>. Per ogni overlay scegli se si vede e dove sta. Per avere due vesti diverse in due scene fai due cartelli.',
    ] },
    { tabella: [
      ['Impostazione', 'Di base', 'Limiti'],
      ['«Cos’è»', 'una scritta', 'una scritta · un’immagine'],
      ['«Nome» (per te)', 'vuoto: si vede la prima riga del testo, o «Cartello» col numero', '40 caratteri; si vede solo nel pannello'],
      ['«Cosa c’è scritto»', 'vuoto', '300 caratteri, anche su più righe'],
      ['«Allineato»', 'a sinistra', 'a sinistra · al centro · a destra'],
      ['«Va a capo dopo (% schermo)»', '0', 'da 0 a 100; a 0 è largo quanto la riga più lunga'],
      ['«Quale immagine»', 'nessuna', 'le immagini che hai in «Effetti & suoni»'],
      ['«Dove» (in «Proprietà»)', 'in basso a sinistra', 'i quattro angoli, o dove lo trascini'],
      ['Aspetto (in «Proprietà»)', 'nessuna scatola: opacità dello sfondo 0, cornice «Nessuna»', '«Dimensione», «Carattere» e «Testo» per le scritte, «Sfondo», «Opacità sfondo», «Angoli», «Forma», «Materia», «Cornice»'],
    ] },
    { p: ['Di suo un cartello non ha una scatola dietro. Se la vuoi alzi l\'opacità dello sfondo e scegli forma, materia e cornice. Le immagini si caricano in «Effetti & suoni» e qui si trovano già pronte.'] },

    { h3: 'Alert eventi' },
    { p: ['Un cartello animato con suono quando arriva un evento. Servono due interruttori accesi: quello generale «Alert eventi», acceso di serie, e quello del singolo evento, spento di serie.'] },
    { tabella: [
      ['Evento', 'Testo di serie', 'Suono di serie', 'Colore di serie', 'Soglia'],
      ['«Nuovo follower»', '<code>{user} ha seguito il canale!</code>', 'Campanello', 'rosa', ''],
      ['«Abbonamento»', '<code>{user} si è abbonato! ({mesi} mesi)</code>', 'Ta-daa!', 'arancio', ''],
      ['«Bit (cheer)»', '<code>{user} ha lanciato {bits} bit!</code>', 'Moneta', 'verde', '«Bit minimi»'],
      ['«Raid»', '<code>{user} è arrivato in raid con {viewers} spettatori!</code>', 'Trombetta', 'rosso', '«Spettatori minimi»'],
      ['«Donazione»', '<code>{user} ha offerto {importo}! {messaggio}</code>', 'Moneta', 'verde scuro', '«Importo minimo»'],
    ] },
    { p: [
      'Sotto la soglia l\'alert non parte: è il modo di non suonare per un bit solo. Le donazioni arrivano dai servizi collegati nella scheda «Donazioni» (<a href="/manuale/vetrina">manuale della vetrina</a>).',
      'Ogni evento ha «Testo», fino a 200 caratteri; lasciato vuoto vale quello di serie. Ha anche «Colore», «Volume» da 0 a 100 e «Font», che di serie segue lo stile comune e se lo cambi vale per quell\'evento soltanto.',
      '«Icona» sceglie fra venti icone (Stella, Cuore, Fulmine, Megafono, Corona, Fuoco, Diamante, Trofeo, Regalo, Razzo, Scudo, Cuffie, Controller, Nota, Fumetto, Campana, Scintille, Saluto, Occhio, Moneta) e le tue immagini, sotto «Le mie».',
      '«Suono» sceglie fra tredici suoni pronti (Campanello, Campana, Goccia d\'acqua, Moneta, Tamburo, Trombetta, Errore / buzzer, Ta-daa!, Pop, Whoosh, Applausi, Laser, Power-up) e i tuoi, sotto «I miei suoni caricati». Di serie ogni evento ha il suono della tabella.',
      '«Immagine o video» mette una tua immagine o un tuo video accanto al testo. Suono e immagine partono insieme: una tua GIF col tuo suono.',
      'Accanto a icona, suono e immagine ci sono «La mia icona…», «Carica un suono tuo», «Carica immagine/video tuo» e «Dalla libreria». Il file caricato si comprime, finisce nella tua libreria di «Effetti & suoni» e si assegna subito. Vale per tutti e cinque gli eventi, donazione compresa. Il file arriva a 60 MB. Il suono vuole un file audio, l\'immagine o video un\'immagine o un video, l\'icona un\'immagine; se sbagli tipo il pannello te lo dice. Un file caricato così diventa anche un comando in chat col nome del file, che solo i moderatori possono lanciare.',
      '«Prova» salva e manda all\'overlay l\'alert di quell\'evento con valori finti: MarioRossi, 3 mesi, 500 bit, 42 spettatori, 5 nella valuta delle tue donazioni col messaggio «grande live!». Le prove sono del proprietario del canale. L\'overlay deve essere aperto, in OBS o in una scheda.',
    ] },
    { tabella: [
      ['Impostazione comune', 'Di base', 'Limiti'],
      ['«Posizione»', 'in alto al centro', 'in alto al centro · al centro · in basso al centro, o dove lo trascini'],
      ['«Durata (secondi)»', '6', 'da 2 a 20'],
      ['«Forma»', 'Carta', 'Carta · Pillola · Squadrata · Angolo tagliato · Insegna · Esagono · Nastro · Fumetto'],
      ['«Materia»', 'Tinta piatta', 'Tinta piatta · Sfumata · Vetro · Carta ruvida · Neon · Schermo CRT · Griglia'],
      ['«Cornice»', 'Linea', 'Linea · Nessuna · Spessa · Solo gli angoli · Barra laterale'],
      ['«Composizione»', 'In colonna', 'In colonna · In riga · In riga, al contrario · Testo sopra l\'immagine'],
      ['«Entrata»', 'Scivola', 'Scivola · Pop · Zoom · Dissolvenza · Ribalta · Rimbalzo'],
      ['«Uscita»', 'Come l\'entrata', 'Come l\'entrata, o una delle sei'],
      ['«Font»', 'Sistema', 'Sistema · Arrotondato · Condensato · Monospazio · Serif · Manga · i tuoi font'],
      ['«Testo»', '27 px', 'da 14 a 56 px'],
      ['«Peso»', 'Normale', 'Normale · Leggero · Grassetto · Nero'],
      ['«Lettere»', 'Come scritto', 'Come scritto · TUTTO MAIUSCOLO · Iniziali Maiuscole'],
      ['«Spaziatura»', '0 px', 'da −2 a 12 px'],
      ['«Icona»', '46 px', 'da 0 a 120 px'],
      ['«Sfondo», «Testo»', 'quasi nero, bianco', 'qualunque colore'],
      ['«Opacità»', '88%', 'da 0 a 100'],
      ['«Angoli»', '18 px', 'da 0 a 40 px'],
      ['«Bordo»', '2 px', 'da 0 a 10 px'],
      ['«Bagliore», «Mostra icona», «Ombra del testo», «Nome a colori»', 'tutte accese', ''],
    ] },
    { p: [
      'L\'aspetto vale per tutti gli alert di <strong>questo overlay</strong>. Il colore di ogni evento resta suo, così a colpo d\'occhio si capisce cosa è appena successo.',
      '<strong>I tuoi font.</strong> «Carica un font tuo» accetta file .woff2, .woff, .ttf o .otf fino a 3 MB, al massimo 8 font. Il font caricato compare col suo nome in tutti i menù «Font». La ✕ accanto al nome lo cancella dopo una conferma. Se il file non va leggi «serve un font .woff2, .woff, .ttf o .otf», «font troppo grande (max 3MB)» o «massimo 8 font (togline uno)».',
      '<strong>I font di Google.</strong> Nel campo «Font» scrivi il nome di un font Google, oppure premi «Sfoglia i font» e scegli dall\'elenco con l\'anteprima, filtrando per nome. Il font Google vince sul menù. La ✕ lo toglie. Se l\'elenco non arriva leggi «Elenco non disponibile ora: puoi scrivere il nome del font a mano.»',
      'Premi «Salva alert» oppure «Salva overlay».',
    ] },

    { h3: 'Chat a schermo' },
    { p: ['I messaggi della chat in sovraimpressione, con le emote di Twitch e quelle 7TV come immagini e i badge accanto al nome. I messaggi che cominciano con <code>!</code> non compaiono, e ogni riga si ferma a 200 caratteri. Le emote 7TV si gestiscono in «Emote (7TV)» (<a href="/manuale/emote">manuale delle emote</a>).'] },
    { tabella: [
      ['Impostazione', 'Di base', 'Limiti'],
      ['«Chat a schermo» (interruttore)', 'spento', ''],
      ['«Posizione»', 'in basso a sinistra', 'i quattro angoli, o dove la trascini'],
      ['«Messaggi visibili»', '8', 'da 1 a 20'],
      ['«Spariscono dopo (s, 0=restano)»', '0', 'da 0 a 120 secondi'],
      ['«Dimensione»', 'Media', 'Piccola · Media · Grande · Enorme'],
      ['«Animazione»', 'Scivola', 'Scivola · Dissolvenza · Nessuna'],
      ['«Larghezza»', '30', 'da 18 a 60, in centesimi della larghezza dello schermo'],
      ['«Opacità»', '78%', 'da 0 a 100'],
      ['«Angoli»', '10 px', 'da 0 a 30 px'],
      ['«Cornice»', 'Nessuna', 'come per gli alert'],
      ['«Spaziatura»', '0 px', 'da −2 a 8 px'],
      ['«Colore nomi»', 'Colore di Twitch', 'Colore di Twitch · Colore fisso, scelto in «Colore nomi (se fisso)»'],
      ['«Ombra», «Nome in grassetto»', 'accese', ''],
      ['«Ombra del testo», «Segna da dove arriva»', 'spente', ''],
    ] },
    { p: [
      'Font, font Google, sfondo, testo, forma, materia, peso e lettere funzionano come per gli alert. L\'aspetto vale per questo overlay.',
      'Se hai collegato Twitch e Kick compare <strong>«Quali chat in questo overlay»</strong>. Togline una e resta fuori da questo overlay e basta: il bot continua a leggerla e a rispondere. Per tenerle divise fai un secondo overlay con l\'altra accesa. Per tenerle unite lasciale accese tutte e due, e con «Segna da dove arriva» ogni riga porta il segno della sua chat.',
      '«Prova» salva e manda all\'overlay tre messaggi finti. È del proprietario del canale. Premi «Salva chat» oppure «Salva overlay».',
    ] },

    { h3: 'Ultimo follower e ultimo sub' },
    { p: ['Due pastiglie che restano a schermo col nome dell\'ultimo arrivato. Il nome si aggiorna da solo a ogni follow e a ogni sub, e si ferma a 40 caratteri. Tutte le impostazioni valgono per questo overlay.'] },
    { tabella: [
      ['Impostazione', 'Di base', 'Limiti'],
      ['Interruttore', 'spento', ''],
      ['«Testo»', 'Ultimo follower: {nome} / Ultimo sub: {nome}', '80 caratteri; <code>{nome}</code> è chi'],
      ['«Posizione»', 'in basso a destra', 'i quattro angoli, o dove lo trascini'],
      ['«Font», «Dimensione»', 'Sistema, Media', 'come per la chat'],
      ['«Icona»', 'Cuore per il follower, Stella per il sub', 'le venti icone, nessuna, le tue immagini; «La mia icona…» ne carica una'],
      ['«Sfondo», «Testo», «Nome»', 'quasi nero, bianco, rosa', '«Nome» è il colore del nome'],
      ['«Opacità»', '85%', 'da 0 a 100'],
      ['«Angoli»', '12 px', 'da 0 a 30 px'],
      ['«Forma», «Materia», «Cornice»', 'Carta, Tinta piatta, Nessuna', 'come per gli alert'],
    ] },
    { p: ['«Prova» salva le impostazioni della pastiglia e mostra un nome finto (MarioRossi o GiadaTTV) senza tenerlo, così in diretta resta il nome vero. È del proprietario del canale. Per il resto le modifiche si salvano con «Salva overlay».'] },

    { h3: 'CSS avanzato' },
    { p: [
      'Per cambiare quello che i menù non toccano: un foglio di stile tuo, applicato a <strong>questo overlay</strong>. Le classi principali sono <code>.alert-card</code>, <code>.chat-riga</code>, <code>.ovl-widget</code> e <code>.pen-card</code>.',
      'Arriva a 8000 caratteri. Si salva con «Salva CSS» oppure «Salva overlay».',
    ] },
    { esempio: '.alert-card { letter-spacing: 1px; }' },

    { h3: 'Quando non si vede niente' },
    { ul: [
      '<strong>La pagina è bianca o vuota in OBS.</strong> Controlla il link: senza la sua chiave l\'indirizzo risponde «non trovato». Se hai fatto un link nuovo, quello vecchio non funziona più.',
      '<strong>Gli alert non partono.</strong> Deve essere acceso l\'interruttore del singolo evento, oltre a «Alert eventi». Per follow, sub, bit e raid servono i permessi di Twitch: si riautorizzano dalla scheda «Stato». Controlla anche la soglia.',
      '<strong>Parte l\'alert ma non il suono.</strong> In OBS la sorgente Browser deve avere «Controlla l\'audio via OBS». Controlla anche il volume dell\'evento.',
      '<strong>«Prova» non mostra niente.</strong> L\'overlay deve essere aperto in OBS o in una scheda, e l\'elemento deve essere acceso in quell\'overlay.',
      '<strong>Vedo tutto doppio.</strong> Due sorgenti Browser con lo stesso link nella stessa scena: tienine una.',
      '<strong>La chat non compare.</strong> È spenta di base: si accende dal suo interruttore. I comandi con <code>!</code> non compaiono mai.',
      '<strong>La chat si è fermata.</strong> La pagina aveva perso il filo col bot, per un riavvio o un salto di rete. Lo riprende da sola e rilegge tutto.',
      '<strong>Un elemento c\'è nel pannello ma non in diretta.</strong> Guarda i livelli: un «!» rosso vuol dire che è spento, un occhio barrato che è tolto da questo overlay. Controlla anche se è accesa un\'occasione che lo toglie.',
      '<strong>L\'obiettivo resta a zero.</strong> Conta da quando l\'hai acceso: gli eventi di prima non tornano indietro. Per partire dal numero vero usa «Parti da quanti ne ho adesso» o «Parte da».',
      '<strong>Ho spostato tutto e non mi piace.</strong> Ctrl+Z torna indietro. Doppio clic o «Ripristina» rimettono un elemento al suo posto di serie.',
    ] },
  ],
  faq: [
    { d: 'Serve un plugin in OBS?', r: 'No. L\'overlay è una pagina web: basta la sorgente Browser che OBS ha già. Va bene anche Streamlabs o qualunque programma che apra una pagina web come sorgente.' },
    { d: 'Se cambio qualcosa devo ricaricare OBS?', r: 'No. Quello che salvi arriva subito in diretta, occasioni comprese.' },
    { d: 'Posso usare overlay diversi in scene diverse?', r: 'Sì, fino a 12. Ognuno ha il suo link, i suoi elementi, le sue posizioni e l\'aspetto di alert, chat e widget. «Nuovo…» o «Duplica» ne fanno uno in più.' },
    { d: 'Voglio un obiettivo con due colori diversi in due scene.', r: 'L\'aspetto di un obiettivo è uno per il canale. Fai due obiettivi che contano la stessa cosa, dai a ognuno la sua veste e in ogni overlay accendi quello giusto: salgono insieme.' },
    { d: 'Chi ha il link può fare danni?', r: 'Può far comparire cose nel tuo overlay. Non entra nel pannello né nel tuo account. Se il link è scappato, il proprietario preme due volte la chiave accanto al link: il vecchio smette subito di funzionare.' },
    { d: 'Stasera è una serata diversa: devo rifare l\'overlay?', r: 'No. Crea un\'occasione con «Nuova…», accendi e sposti quello che serve e spunta «In onda adesso». A fine serata la spegni e torna tutto com\'era.' },
    { d: 'I moderatori possono lavorare sull\'overlay?', r: 'Sì: spostano, accendono, vestono e salvano. Fare un link nuovo e le prove di alert, chat, ultimo follower e sub e delle figure del muro restano al proprietario.' },
    { d: 'L\'obiettivo conta anche a canale spento?', r: 'Conta gli eventi che arrivano, e i follow arrivano anche offline. Se non li vuoi, spegnilo e riaccendilo quando serve.' },
  ],
};
