// © 2024–2026 Andrea Taliento (ANDRYXify) — Tutti i diritti riservati — socialbot.live
// Proprietà intellettuale · ANDRYX-IP::a7f39c1e8b424d90-4f7b-taliento::socialbot.live
// Manuale: Manuale degli strumenti. La forma dei manuali e il perche' stanno in
// src/web/manuali.js; le lingue in docs/LINGUE.md. Come e' fatto il QR, e
// perche' si legge, sta in docs/STRUMENTI.md.

export default {
  slug: 'strumenti',
  schede: ['qr', 'misure', 'kit', 'pannelli'],
  titolo: 'Manuale degli strumenti: QR, emote, kit e pannelli | SocialBot',
  h1: 'Manuale degli strumenti',
  desc: 'QR col tuo logo che si legge davvero, emote e badge anche animate per Twitch, 7TV e Discord, media kit coi numeri veri, pannelli già pieni con una pagina dentro.',
  aggiornata: '2026-10-03',
  corpo: [
    { p: [
      'Nel menù del pannello, sotto <em>Strumenti</em>, ci sono le cose che servono intorno alla diretta: il <strong>QR su misura</strong>, le <strong>emote e i badge</strong> alle misure di Twitch, 7TV e Discord, ferme o animate, il <strong>media kit</strong> e i <strong>pannelli</strong> del canale.',
      'Si disegnano tutti nel tuo browser. Le immagini che prepari per emote e badge non passano dal nostro server; il logo del QR, le scelte del media kit e i pannelli ci arrivano solo se premi <em>Salva</em>, per ritrovarli la volta dopo.',
    ] },

    { h2: 'QR su misura', scheda: 'qr' },
    { p: [
      'In cima scrivi dove porta il QR. I tasti sotto lo riempiono per te con la tua <strong>pagina link</strong> o il tuo canale, ma puoi scriverci qualunque indirizzo o testo.',
      'Nel QR c\'è proprio quello che hai scritto, senza passaggi da noi: non scade, e funziona finché funziona il link che ci hai messo.',
    ] },
    { h3: 'Forme e colori' },
    { tabella: [
      ['Cosa', 'Scelte', 'Nota'],
      ['I quadratini', 'Quadrati, morbidi, puntini, a penna', 'Nei morbidi si arrotondano solo gli angoli liberi, così i gruppi restano uniti. A penna ogni quadratino è tracciato a mano, ed è sempre lo stesso tratto per il tuo canale.'],
      ['Gli occhi', 'Quadrati, morbidi, tondi, a penna', 'Sono i tre quadri grandi agli angoli: servono al telefono per trovare il codice.'],
      ['I colori', 'Cinque accoppiate pronte, o i tuoi', 'Quadratini, fondo e occhi hanno ognuno il suo colore.'],
    ] },
    { h3: 'Il logo al centro' },
    { p: [
      'Puoi mettere al centro <strong>la tua foto</strong> (quella del canale) o <strong>un\'immagine</strong> tua, PNG, JPG o WebP. Se è pesante la rimpiccioliamo noi.',
      'Un logo copre una parte del codice, e il QR la recupera con i suoi codici di riserva. Per questo, quando c\'è un logo, usiamo la correzione più alta, e il logo non prende mai più della <strong>metà</strong> di quello che si può correggere: l\'altra metà resta per un graffio, un riflesso, una piega della carta. Non tocca mai gli occhi né gli altri segni fissi.',
      'Il cursore <em>Grandezza del logo</em> va dal più piccolo al più grande che quel link permette. Più il link è lungo, più il codice è fitto e meno posto resta: con un link lungo il logo può non starci.',
    ] },
    { h3: 'La cornice con la frase' },
    { p: ['Se scrivi una frase (fino a 40 caratteri, tipo «Inquadrami»), il QR prende una cornice tracciata a penna e la frase sotto, scritta a mano.'] },
    { h3: 'Come sappiamo che si legge' },
    { p: ['Un QR personalizzato si rompe facilmente: basta un colore troppo chiaro o un logo troppo grande, e il telefono non lo legge più. Qui le regole sono dentro il disegno:'] },
    { ul: [
      '<strong>Contrasto.</strong> Fra quadratini e fondo misuriamo la differenza di luce vera, non dei numeri del colore, e deve arrivare ad almeno 0,55 su 1. Il fondo deve essere il più chiaro dei due: molti lettori non leggono i QR in negativo.',
      '<strong>Margine.</strong> Intorno restano i quattro quadratini vuoti che la norma chiede: senza, il telefono non capisce dove finisce il codice.',
      '<strong>Forme.</strong> Ogni forma copre il centro del suo quadratino, che è il punto dove il telefono guarda.',
      '<strong>Occhi.</strong> I tre anelli di ogni occhio sono la stessa forma in scala, così il telefono lo riconosce da qualunque verso; i quadri piccoli dentro il codice seguono gli occhi. Gli occhi quadrati, quelli di serie, li legge proprio qualunque lettore.',
    ] },
    { p: [
      'Poi lo <strong>rileggiamo</strong>: prendiamo i pixel dell\'anteprima, guardiamo il centro di ogni quadratino e decodifichiamo come un lettore vero, correzione degli errori compresa. Se il testo che ne esce non è identico a quello che hai scritto, i tasti per scaricare restano spenti e sotto ti diciamo cosa cambiare. La stessa prova si ripete sull\'immagine grande, prima di scaricarla.',
      'La rilettura vede il disegno dritto e a fuoco: non sa come lo stamperai. Per la stampa tieni il QR ad almeno <strong>2 cm</strong> di lato, e di più se va inquadrato da lontano: una regola comoda è un decimo della distanza.',
    ] },
    { h3: 'Scaricarlo e salvarlo' },
    { ul: [
      '<strong>PNG</strong> a 1024, 2048 o 4096 pixel. Il più grande è per la stampa.',
      '<strong>SVG</strong>: un disegno che si ingrandisce senza perdere niente, col logo e il carattere della frase dentro il file.',
      '<strong>Salva lo stile</strong>: lo ritrovi la volta dopo, e lo usano le <em>Grafiche social</em> per il QR che mettono nelle immagini, senza cornice. Se lì il QR con il tuo stile non si rileggesse, le Grafiche usano quello semplice.',
    ] },

    { h2: 'Emote e badge', scheda: 'misure' },
    { p: ['Twitch chiede ogni emote in tre misure, <strong>112, 56 e 28</strong> pixel, e ogni badge in tre, <strong>72, 36 e 18</strong>. 7TV e Discord ne vogliono una sola, da <strong>128</strong>. Qui carichi un\'immagine sola, ferma o animata (GIF, WebP, APNG), o un video corto, e le hai tutte, pronte da caricare.'] },
    { h3: 'Rimpicciolite bene' },
    { p: ['Rimpicciolire un\'immagine vuol dire fare la media dei suoi pixel. Se la media si fa sui numeri del colore, come fanno molti programmi, i bordi fra due colori si scuriscono e i contorni sottili spariscono. Noi la facciamo sulla luce vera, e teniamo conto della trasparenza: un bordo trasparente non sporca di nero i pixel vicini.'] },
    { h3: 'Se non è quadrata' },
    { ul: [
      '<strong>Intera</strong>: l\'immagine entra tutta, e dove avanza resta trasparente.',
      '<strong>Riempi</strong>: riempie il quadrato e taglia quello che esce, tenendo il centro.',
    ] },
    { h3: 'Emote animate' },
    { p: ['Da un\'immagine animata, o dal pezzo di video che scegli (al massimo 10 secondi), escono GIF già nelle regole di chi le riceve:'] },
    { ul: [
      '<strong>Fotogrammi</strong>: Twitch ne vuole al massimo 60. Se sono di più ne prendiamo 60 a tempi uguali, e il giro dura uguale: più l\'animazione è corta, più resta fluida. 7TV e Discord le tengono tutte.',
      '<strong>Peso</strong>: Twitch vuole ogni misura animata sotto i <strong>512 KB</strong>, Discord sotto i <strong>256 KB</strong>. Se non ci sta, togliamo prima colori e poi fotogrammi, finché ci sta; sotto ogni misura c\'è scritto quanti colori e fotogrammi ha.',
      '<strong>Il fotogramma fermo</strong>: è quello che Twitch, 7TV e Discord mostrano quando l\'emote sta ferma. Lo scegli tu con la barra, e l\'animazione parte da lì. Per i badge, che su Twitch non si muovono, è l\'unico che conta.',
      '<strong>Lampi</strong>: se l\'animazione lampeggia più di tre volte in un secondo te lo diciamo in rosso. Può far male a chi soffre di epilessia fotosensibile, e Twitch la rifiuta.',
      '<strong>Trasparenza</strong>: in una GIF un punto è pieno o vuoto, senza vie di mezzo. Il bordo sfumato diventa netto, quindi conviene controllare l\'anteprima su tutte e due le chat.',
    ] },
    { p: ['Le animazioni si leggono con il browser: Chrome ed Edge le aprono tutte. Se il tuo browser legge solo il primo fotogramma, te lo diciamo e l\'emote esce ferma.'] },
    { h3: 'Come si vedono in chat' },
    { p: ['Sotto le misure le vedi come in chat, sul fondo scuro e su quello chiaro: l\'emote di Twitch a 28 pixel accanto al testo, il badge a 18 prima del nome, quella di 7TV a 32, quella di Discord a 22 sui colori di Discord. Sugli schermi più fitti il browser prende le misure grandi, come fanno loro.'] },
    { h3: 'Pesi e download' },
    { p: ['Twitch accetta emote ferme fino a <strong>1 MB</strong> e badge fino a <strong>25 KB</strong>, 7TV fino a <strong>7 MB</strong>, Discord fino a <strong>256 KB</strong>: se una misura li supera, te lo diciamo. Ogni misura si scarica da sola, oppure tutte insieme in uno zip.'] },

    { h2: 'Media kit', scheda: 'kit' },
    { p: ['È il foglio da mandare a un marchio quando proponi una collaborazione, o quando te la chiedono: chi sei, cosa trasmetti, quanta gente ti guarda, quando sei in onda, dove trovarti e come scriverti. Esce in PDF, coi link che si aprono con un clic, o in PNG.'] },
    { h3: 'Da dove vengono i numeri' },
    { ul: [
      '<strong>Dalle tue dirette degli ultimi 30 giorni</strong>, quelle concluse: il bot le segue mentre sei in onda e a fine serata ne scrive il rapporto. Sono gli stessi numeri della scheda Dirette.',
      '<strong>Gli spettatori in media</strong> sono pesati sul tempo: una diretta di sei ore conta sei volte una di un\'ora.',
      '<strong>Il picco</strong> è il massimo di spettatori in una diretta del periodo.',
      '<strong>Le persone in chat</strong> sono quelle diverse che hanno scritto almeno una volta, tu escluso.',
      '<strong>I follower totali</strong> sono quelli che dice Twitch nel momento in cui apri la scheda.',
      '<strong>Cosa trasmetti</strong> è la parte di tempo di ogni categoria. Si conta dalle dirette di adesso in poi.',
    ] },
    { p: [
      'Sotto i numeri c\'è sempre scritto di quale periodo sono, chi li ha misurati e quando. I numeri non si cambiano a mano: puoi solo scegliere quali mostrare.',
      'Con meno di tre dirette nel periodo i numeri delle dirette non escono, e sotto la scheda c\'è scritto quante ne mancano: tre serate sono il minimo per dire qualcosa di vero.',
    ] },
    { h3: 'Il resto del foglio' },
    { ul: [
      '<strong>Due righe su di te</strong>: di partenza c\'è la frase della tua pagina link. Ci stanno quattro righe.',
      '<strong>Quando sei in onda</strong> viene dalla tua settimana, <strong>dove trovarti</strong> dai social della tua pagina link.',
      '<strong>I marchi con cui hai lavorato</strong> e <strong>l\'email per le collaborazioni</strong> li scrivi tu. L\'email va in una fascia in fondo al foglio.',
      '<strong>I colori</strong> sono quelli della tua pagina link, oppure Carta (chiari) o Notte (scuri).',
    ] },
    { p: ['Le scelte si salvano con <em>Salva</em> e le ritrovi la volta dopo. I numeri invece si aggiornano da soli ogni volta che apri la scheda. Il media kit non è una pagina pubblica: esiste quando lo scarichi, e lo mandi tu a chi vuoi.'] },

    { h2: 'Pannelli', scheda: 'pannelli' },
    { p: ['Sono i riquadri sotto il tuo canale Twitch, in <em>Informazioni</em>: ognuno ha un\'immagine, un link e una descrizione. Qui li prepari tutti insieme, nello stesso stile, e li scarichi in un file solo.'] },
    { h3: 'Nascono già pieni' },
    { ul: [
      '<strong>Chi sono</strong> porta alla tua pagina link, con la sua frase come descrizione.',
      '<strong>Programma</strong> scrive i giorni e le ore della tua settimana, e il fuso.',
      '<strong>Social</strong> mette in fila i social della tua pagina link, ognuno col suo link.',
      '<strong>Discord</strong> porta alla porta d\'ingresso del tuo server, se è aperta; se no al Discord che hai sulla pagina link.',
      '<strong>Sostienimi</strong> porta alla pagina delle donazioni, se è accesa e le donazioni sono pronte.',
      '<strong>Comandi</strong> elenca i tuoi comandi, fino a dodici. <strong>Regole</strong> parte da quattro regole che riscrivi come vuoi.',
    ] },
    { p: [
      'Un pannello compare da solo solo se il canale ha qualcosa da metterci: senza settimana non c\'è <em>Programma</em>, senza donazioni pronte non c\'è <em>Sostienimi</em>. Li aggiungi da <em>Aggiungi</em>, in fondo all\'elenco, insieme a quello libero, dove scrivi tu tutto.',
      'Ogni campo si riscrive. Se poi cambi qualcosa nel canale, per esempio un social, <em>Riprendi dal canale</em> rimette il link e la descrizione di adesso.',
    ] },
    { h3: 'Uno stile per tutti' },
    { p: [
      'Colori, forma, carattere, altezza e icona valgono per tutti i pannelli: stanno in fila sulla stessa pagina, e uno diverso dagli altri si nota subito. I colori possono essere quelli della tua pagina link, Carta, Notte o <em>I miei colori</em>, dove scegli tu sfondo, testo e accento; la forma a penna, netta o piena. Anche il titolo ha una misura sola per tutti: quella che fa stare il più lungo.',
      'Ogni pannello può avere un <strong>sottotitolo</strong>, una riga piccola sotto il titolo («ogni sera dalle 21», «entra nel server»): anche quello ha una misura sola per tutta la serie. Con <em>Una freccina sui pannelli che portano da qualche parte</em> chi guarda capisce al volo quali si cliccano: la freccina compare solo su quelli che hanno davvero un link.',
      'Il testo sul pannello si legge sempre: se il colore non contrasta abbastanza, diventa bianco o nero, anche coi tuoi colori. Con <em>Twitch scuro</em> e <em>Twitch chiaro</em> vedi come stanno sulle due pagine di Twitch.',
    ] },
    { h3: 'Un pannello con una pagina dentro' },
    { p: [
      'Su Twitch un pannello è un\'immagine con un link e poche righe. Quando hai più cose da dire (tutti i comandi, le regole spiegate, il programma con i giochi, le foto della postazione) scegli <em>Quando lo clicchi: Apre la sua pagina</em>. Chi clicca il pannello arriva a una pagina tua, <code>socialbot.live/u/tuonome/p/…</code>, e il link del pannello si scrive da solo.',
      'La pagina si fa con lo stesso editor della pagina link, e di serie ne ha l\'aspetto: un canale, un vestito. Nasce già piena di quello che il pannello promette: il <em>Programma</em> con la tua settimana, i <em>Comandi</em> coi tuoi comandi, <em>Chi sono</em> con la tua frase e i social, <em>Discord</em> col tasto per entrare, e gli altri con la descrizione del pannello riga per riga.',
    ] },
    { ul: [
      '<strong>Il programma e i comandi si aggiornano da soli</strong>: sono letti quando la pagina si apre. Cambi la settimana o aggiungi un comando, e la pagina è già giusta, senza ricaricare niente su Twitch. Gli stessi due pezzi li puoi mettere anche nella pagina link.',
      '<strong>Si vedono solo i comandi che può usare chiunque</strong>: quelli per i moderatori no. Accanto a ognuno c\'è cosa risponde il bot, quando è una frase fissa.',
      '<strong>La pagina si apre quando è pubblicata e il pannello salvato ci porta.</strong> Se togli il pannello, o lo fai portare a un indirizzo, la pagina non si apre più ma resta salvata: se torni indietro, torna com\'era.',
      '<strong>Non finisce sui motori di ricerca</strong>: è una porta da Twitch, non una pagina da trovare. La tua pagina link resta quella che si trova.',
    ] },
    { h3: 'Metterli su Twitch' },
    { passi: [
      { t: 'Premi «Scarica tutti».', d: 'Ti arriva un file con le immagini in ordine e un testo con titolo, link e descrizione di ognuno. Puoi anche scaricare un pannello solo, da sotto la sua immagine.' },
      { t: 'Apri il tuo canale su Twitch.', d: 'Vai in <em>Informazioni</em> e accendi <em>Modifica pannelli</em>.' },
      { t: 'Aggiungi i pannelli uno alla volta.', d: 'Per ognuno carica l\'immagine, incolla il link e la descrizione. Nella scheda, sotto ogni pannello, ci sono <em>Copia il link</em> e <em>Copia la descrizione</em>.' },
    ] },
    { p: ['Le immagini sono larghe 320 pixel, la misura con cui Twitch le mostra. La descrizione Twitch la legge in Markdown: <code>**grassetto**</code>, <code>[parole](link)</code> per un link, un trattino davanti per un elenco.'] },

    { h2: 'Quando non funziona' },
    { ul: [
      '<strong>I tasti per scaricare il QR sono spenti.</strong> Sotto l\'anteprima c\'è scritto perché: di solito sono i colori troppo vicini, o un logo che con quel link non ci sta.',
      '<strong>Il logo non ci sta.</strong> Il link è troppo lungo: accorcialo. L\'indirizzo della tua pagina link è già corto.',
      '<strong>La tua foto non compare.</strong> È quella del canale, e a volte non arriva subito: riprova, o carica un\'immagine.',
      '<strong>Voglio cambiare il logo caricato.</strong> Quando è scelto <em>Un\'immagine</em>, sotto c\'è <em>Cambia immagine</em>.',
      '<strong>La misura grande delle emote è sgranata.</strong> L\'immagine di partenza è piccola: parti da almeno quattro volte la misura più grande.',
      '<strong>Una GIF animata esce ferma.</strong> Qui si prende il primo fotogramma: le emote animate si preparano a parte.',
      '<strong>Nel media kit mancano i numeri.</strong> Negli ultimi 30 giorni ci sono meno di tre dirette concluse: sotto la scheda c\'è scritto quante.',
      '<strong>Nel media kit mancano le categorie.</strong> Si contano dalle dirette fatte da quando c\'è il media kit, ed escono dopo tre dirette.',
      '<strong>Un pannello che mi aspettavo non c\'è.</strong> Il canale non ha ancora niente da metterci: per esempio la pagina delle donazioni è spenta. Aggiungilo da <em>Aggiungi</em> e scrivi tu link e descrizione.',
      '<strong>Un titolo di pannello finisce coi puntini.</strong> Non ci sta nemmeno col carattere più piccolo: accorcialo, togli l\'icona o scegli un carattere più stretto.',
      '<strong>Tutti i titoli dei pannelli sono diventati piccoli.</strong> La misura è una per tutti, quella del titolo più lungo: accorcia quello.',
    ] },
  ],
  faq: [
    { d: 'Il QR scade?', r: 'No. Dentro c\'è solo il link che hai scritto, senza passaggi da noi: funziona finché funziona quel link.' },
    { d: 'Posso fare un QR per un sito che non è il mio canale?', r: 'Sì: nel campo in cima scrivi qualunque indirizzo o testo.' },
    { d: 'Quanto grande lo devo stampare?', r: 'Almeno 2 cm di lato. Se va inquadrato da lontano, circa un decimo della distanza: per tre metri, trenta centimetri.' },
    { d: 'Perché col logo il QR ha più quadratini?', r: 'Col logo usiamo la correzione più alta, che aggiunge codici di riserva: sono loro a recuperare la parte che il logo copre.' },
    { d: 'Le immagini delle emote finiscono sul vostro server?', r: 'No: si rimpiccioliscono nel tuo browser, e da lì le scarichi. Anche i video.' },
    { d: 'Perché la mia emote animata è a scatti?', r: 'Twitch tiene 60 fotogrammi: un\'animazione di 4 secondi ne mostra 15 al secondo, una di 2 secondi 30. Accorciala e torna fluida.' },
    { d: 'I numeri del media kit si possono modificare?', r: 'No: vengono dalle tue dirette, e puoi solo scegliere quali mostrare. È quello che li rende credibili per chi li legge.' },
    { d: 'Il media kit è una pagina pubblica?', r: 'No: esiste quando lo scarichi, e lo mandi tu a chi vuoi.' },
    { d: 'I pannelli si aggiornano da soli su Twitch?', r: 'No: Twitch non lascia cambiare i pannelli da fuori. Quando cambi qualcosa, riscarichi e ricarichi il pannello che è cambiato. Quello che sta nella pagina dietro un pannello, invece, si cambia qui e su Twitch è già giusto.' },
    { d: 'Perché il mio pannello non porta da nessuna parte?', r: 'Se apre la sua pagina e la pagina non è ancora pubblicata, il link resta vuoto: sotto l\'anteprima c\'è scritto. Preparala e premi «Salva e pubblica», poi salva i pannelli.' },
    { d: 'Posso usare i pannelli su Kick o YouTube?', r: 'Le immagini sì, sono normali PNG. Le misure però sono quelle di Twitch.' },
  ],
};
