// Manuale: Manuale della vetrina: pagina link, grafiche e notifiche social. La forma dei manuali e il perche' stanno in
// src/web/manuali.js; le lingue in docs/LINGUE.md.

export default {
  slug: 'vetrina',
  schede: ['pagina', 'donazioni', 'settimana', 'grafiche', 'notifiche', 'telegram', 'ruoli', 'dcavvisi', 'dcserver', 'dcentra', 'dcfiltro'],
  titolo: 'Manuale della vetrina: pagina link, grafiche e social | SocialBot',
  h1: 'Manuale della vetrina: pagina link, grafiche e notifiche social',
  desc: 'La pagina pubblica da mettere in bio, le tre grafiche pronte da pubblicare, quelle che escono da sole e gli avvisi quando vai in diretta o pubblichi qualcosa.',
  aggiornata: '2026-09-25',
  corpo: [
    { p: [
      'Tre schede che lavorano <strong>fuori dalla diretta</strong>: dove ti trovano, cosa vedono, e come sanno che sei partito.',
      'Sono la parte che si configura una volta e poi lavora da sola per mesi — motivo per cui vale la pena farla bene subito.',
    ] },

    { h2: 'La pagina link' },
    { p: ['Una pagina pubblica all\'indirizzo <code>socialbot.live/u/&lt;tuonome&gt;</code>, da mettere nella bio di Instagram o TikTok. La <strong>foto la prendo dal tuo profilo Twitch</strong>: non devi caricare niente. Quando incolli il link in una chat, l\'anteprima è una <strong>card coi colori della tua pagina</strong> (nome, sottotitolo, faccia, indirizzo): nel riquadro «Quando condividi il link» la vedi e, se vuoi, la rifai con lo stesso editor delle locandine; vale anche per la pagina delle donazioni.'] },
    { p: ['È fatta per stare in una bio, quindi è costruita per una cosa sola: <strong>aprirsi subito su una connessione mobile scadente</strong>. Nessuno script, nessun font remoto, niente da scaricare — funziona anche a JavaScript spento e le anteprime dei social la leggono bene.'] },
    { h3: 'I blocchi' },
    { p: ['La pagina si compone a blocchi, che si riordinano trascinandoli.'] },
    { tabella: [
      ['Blocco', 'Cosa mette'],
      ['Link', 'Un pulsante con etichetta e indirizzo. L\'icona giusta la riconosco dall\'indirizzo.'],
      ['Titolo', 'Una intestazione per separare le sezioni.'],
      ['Testo', 'Un paragrafo libero.'],
      ['Separatore', 'Una riga di respiro.'],
      ['Social', 'La fila di icone dei tuoi profili.'],
      ['Embed', 'Video e musica: YouTube, Spotify, TikTok.'],
      ['Immagine', 'Una tua immagine.'],
      ['La mia diretta', 'Il player: resta lì e dice da sé se sei online o no.'],
      ['Sostieni', 'Le donazioni, col tuo tema: gli importi da scegliere e il pagamento sui tuoi conti, il tasto verso la tua pagina Ko-fi, oppure il tasto verso PayPal o altro; se vuoi, sotto c\'è l\'obiettivo che sale.'],
      ['Chi ha donato', 'Gli ultimi che hanno donato, o i primi per somma (del mese o di sempre), quanti nomi vuoi. I nomi sono quelli scritti nel modulo; le rimborsate non contano.'],
    ] },
    { p: ['Il blocco «La mia diretta» è quello che cambia di più la pagina: chi arriva dalla bio non deve chiedersi se sei live, lo vede.'] },
    { h3: 'Le donazioni' },
    { p: ['Nella scheda <strong>Donazioni</strong> colleghi il tuo conto Stripe. Il conto lo apri e lo gestisci tu, come chiunque: a SocialBot dai solo una <strong>chiave con restrizioni</strong> (nel Dashboard di Stripe: Sviluppatori → Chiavi API → Crea chiave con restrizioni, con i permessi «Checkout Sessions» e «Products» in scrittura). Con quella apre il pagamento sul tuo conto e legge se è andato a buon fine; niente rimborsi, niente bonifici, niente dati bancari, e la revochi quando vuoi. Da quel momento chi apre la tua pagina link sceglie un importo, scrive un nome e un messaggio se vuole, e paga con carta, Apple Pay o Google Pay: i soldi arrivano sul tuo conto, SocialBot non trattiene niente, e l\'avviso parte da solo.'] },
    { p: ['Nella stessa scheda decidi gli <strong>importi suggeriti</strong>, il minimo e il massimo per una donazione (500 di serie, fino a 5.000), se chi dona può lasciare un messaggio, il testo del tasto, una frase e la valuta. Il blocco «Sostieni» della pagina legge tutto da lì: si imposta una volta sola e la pagina resta coerente col tema. Sotto, il <strong>registro</strong>: i totali di oggi, del mese e dell\'anno, la lista con nome e messaggio, la ricerca e lo scarico in CSV. Per ogni riga puoi rimandare l\'avviso in overlay (senza contare di nuovo l\'obiettivo), rimborsare dal tuo conto se la chiave ha il permesso «Refunds», o cancellarla, nome e messaggio compresi. Il registro tiene un anno.'] },
    { p: ['Vuoi una pagina tutta per le donazioni? Nella scheda Donazioni c\'è <strong>la tua pagina delle donazioni</strong> (<code>dona.socialbot.live/iltuonome</code>, o <code>socialbot.live/dona/iltuonome</code>): stessi strumenti della pagina link (stile, colori, caratteri, blocchi, puntatore), un\'altra pagina. La modifichi lì, nella scheda Donazioni, con lo stesso editor, e sulla pagina link il blocco «Sostieni» può portare lì invece di mostrare il modulo.', 'Può avere <strong>lo stesso aspetto della pagina link</strong>: nell\'editor, in «Aspetto», scegli «Uguale alla pagina link», e stile, colori, sfondo, caratteri e bottoni sono quelli della pagina link, anche quando li cambi là. Titolo, foto e blocchi restano suoi. Una pagina delle donazioni nuova parte così; con «Tutto suo» ha un aspetto suo, e «Parti da quello della pagina link» lo copia per cominciare da lì.'] },
    { p: ['Le <strong>offerte</strong>: nella scheda Donazioni componi fino a otto scaglioni, ognuno con un importo da cui vale, un nome e un effetto della tua libreria. Chi dona le vede al posto degli importi suggeriti (per esempio «5 € · Applauso»); all\'arrivo della donazione, dopo l\'avviso, parte l\'effetto dell\'offerta raggiunta, e a decidere quale è l\'importo pagato, non il tasto premuto.'] },
    { p: ['L\'<strong>immagine di chi dona</strong>: da un importo in su, che scegli tu nella scheda Donazioni, chi dona può allegare al modulo un\'immagine o una GIF (PNG, JPG, WEBP o GIF, fino a 8 MB). Viene ricompressa come gli effetti e non va in onda finché non la vedi: la trovi nel registro sotto «Da mandare in onda», con nome, importo e messaggio; «Manda in onda» la fa partire nell\'overlay, «Scarta» la cancella dal server e la donazione resta. Se preferisci che parta da sola appena il pagamento è confermato, accendi «va in onda da sola»; i secondi a schermo delle immagini li decidi tu, una GIF dura quanto è lunga. Sotto la soglia, o se il pagamento non arriva, il file si cancella da solo; se la mandi, resta con la donazione nel registro e la rimandi o la togli quando vuoi.'] },
    { p: ['Vuoi anche <strong>Satispay</strong>? Nel tuo pannello Business apri un negozio online di tipo API e genera il codice di attivazione (vale una volta sola): incollato nella scheda, SocialBot registra una chiave sua per firmare i pagamenti sul tuo conto. Solo in euro. Con Stripe e Satispay insieme, chi dona sceglie con quale pagare; nel registro le donazioni Satispay si rimborsano da qui come le altre.'] },
    { p: ['Hai già una pagina <strong>Ko-fi</strong>? Collegala nella stessa carta, sotto Stripe e Satispay: scrivi l\'indirizzo della tua pagina, su Ko-fi (Settings → API) incolli in «Webhook URL» l\'indirizzo che trovi nella scheda, e da «Advanced» copi qui il «Verification Token». Da quel momento nella pagina delle donazioni c\'è il tasto «Oppure su Ko-fi» (da solo, se Ko-fi è l\'unico conto), e ogni mancia o abbonamento su Ko-fi fa partire l\'avviso «Donazione», il grazie in chat se lo accendi, e fa salire l\'obiettivo. Gli acquisti del negozio di Ko-fi non contano, e un messaggio che chi dona tiene privato resta privato. Del token teniamo solo l\'impronta.'] },
    { p: ['L\'obiettivo e le offerte contano nella valuta che scegli nella scheda: una donazione in un\'altra valuta fa partire l\'avviso e il grazie, ma non si somma, perché un cambio non lo inventiamo. Su Ko-fi usa la stessa valuta.'] },
    { p: ['Preferisci un altro servizio? Scegli «un link esterno» e metti l\'indirizzo della tua pagina PayPal, Streamlabs o altro: il tasto porta lì.'] },
    { p: ['Da un servizio che non ha un collegamento qui, le mance arrivano con la chiave API del canale, azione <code>donazione</code>, con <code>importo</code> e <code>user</code>.'] },
    { h3: 'L\'aspetto' },
    { ul: [
      '<strong>Sette temi</strong>: minimal, neon, retro, sunset, glass, brutal, pastello.',
      '<strong>Sei famiglie di carattere</strong>: di sistema, inter, mono, serif, condensato, tondo.',
      '<strong>Ventitré icone</strong> a tratto, che prendono il colore del tema.',
    ] },
    { p: ['Le icone sono disegni, non emoji, <strong>di proposito</strong>: le emoji cambiano forma su ogni sistema operativo — su Linux diventano grigie e sfocate — e non si possono colorare. Su una pagina che deve sembrare tua sono un difetto, non una scorciatoia.'] },
    { p: ['C\'è un\'anteprima: salvi e la apri, così vedi la pagina com\'è davvero prima di metterla in bio.'] },

    { h2: 'Le grafiche social' },
    { p: ['Tre grafiche pronte da pubblicare, che si scaricano in PNG: la <strong>programmazione settimanale</strong>, il <strong>«Live ora»</strong> e <strong>«Stasera alle…»</strong>, che annuncia la prossima diretta con la copertina del gioco. L\'immagine del gioco ha tre modi: <strong>a tutto schermo</strong>, con un velo e una sfocatura che regoli, <strong>in un riquadro</strong> che trascini sull\'anteprima e ingrandisci con «Grandezza», oppure <strong>niente</strong>, e allora si vede il tema e il gioco va nella pillola. Le impostazioni restano salvate, e i giorni arrivano dalla tua settimana: cambi un orario lì e la grafica è già aggiornata. Nella carta «In automatico» la storia prima della diretta, «Live ora» e la settimana escono da sole.'] },
    { p: ['Si parte da uno <strong>stile pronto</strong>, con l\'anteprima vera fatta coi tuoi testi, o da uno dei ventuno temi: sette fermi e quattordici animati, fra cui synthwave, vaporwave, pioggia al neon, notte di stelle, sakura e lo-fi. Poi si cambia tutto: colori, carattere e stile del titolo, forma delle righe, e per le scene animate cosa si vede, la velocità e quanto si fa notare la scena. L\'anteprima è dal vivo: quello che vedi è quello che esce.'] },
    { p: ['Le scritte si leggono sempre, anche sopra le scene che si muovono: dove sotto passa qualcosa di chiaro compare un contorno, e dove non serve il colore resta il tuo. La GIF e il video fanno un giro intero dell\'animazione e ricominciano senza scatti. Col QR, il riquadro ha una fascia sua in basso e le righe gli fanno posto.'] },
    { p: ['Su telefono l\'anteprima resta appiccicata in alto mentre scorri i controlli, così non devi fare avanti e indietro per vedere l\'effetto di una modifica.'] },

    { h2: 'La tua settimana' },
    { p: ['I giorni in cui vai in onda si scrivono una volta sola, nella scheda <strong>La tua settimana</strong>: per ogni giorno l\'ora e cosa fai, oppure «riposo», e quanto dura di solito una diretta. Da lì li prendono la grafica della settimana, il calendario del tuo server Discord e il <strong>Programma</strong> del tuo canale Twitch.'] },
    { p: ['In «cosa fai» va bene un gioco o un titolo. Mentre scrivi compaiono le categorie di Twitch; se scrivi un titolo, sotto il giorno leggi quale categoria finirà sul Programma, o che non ce n\'è una e resta solo il titolo.'] },
    { p: ['I calendari si tengono in pari da soli: quando salvi, e poi ogni sei ore, anche quando cambia l\'ora. Sul Programma di Twitch ogni giorno diventa una diretta che si ripete, con il gioco trovato su Twitch; quelle che scrivi a mano restano tue.'] },
    { p: ['L\'immagine invece parte quando premi <em>Manda</em>, nei posti che spunti: i gruppi e i canali Telegram collegati, i canali degli avvisi su Discord, la storia di Instagram. Compaiono solo i servizi che hai collegato.'] },
    { p: ['Le storie di Twitch e di YouTube non ci sono: Twitch non le apre a nessuna app, e YouTube le ha chiuse nel 2023. Per la storia di Instagram servono un account professionale e il permesso di pubblicare.'] },

    { h2: 'Le notifiche' },
    { p: ['Avvisare che sei partito, e avvisare che hai pubblicato. Ogni rete si accende da sola e ha il suo messaggio: puoi lasciare quello di base o scriverne uno tuo.'] },
    { h3: 'I tuoi social' },
    { p: ['Nella scheda <strong>I tuoi social</strong>, in cima, ci sono i tuoi account: Instagram e TikTok si collegano con un tasto, di YouTube scrivi il canale. Ognuno dice com\'è messo: collegato, da ricollegare, o a cui manca un permesso, con il tasto per rimediare.'] },
    { p: ['Sotto, un riquadro per ogni cosa che si può annunciare: il post nuovo su Instagram, il video e la diretta su TikTok, il video su YouTube. In fondo gli altri siti, con l\'indirizzo del loro feed. Gli annunci sul tuo Discord si scelgono nella sezione Discord.'] },
    { h3: 'Telegram' },
    { p: ['Qui il bot è <strong>tuo</strong>: lo crei tu, le chiavi sono tue e restano tue. Tre passi.'] },
    { ul: [
      'Su Telegram apri <strong>@BotFather</strong>, scrivi <code>/newbot</code>, segui le istruzioni e copia il <em>token</em>.',
      'Incolla il token nel pannello e premi <em>Collega</em>.',
      'Aggiungi il bot al tuo gruppo, scrivici dentro <code>/collega</code>, poi premi <em>Rileva gruppo</em>.',
    ] },
    { p: ['Da quel momento, quando vai live il gruppo lo sa. Il terzo passo è quello che si dimentica: senza <code>/collega</code> scritto <em>dentro</em> al gruppo, il bot non sa dove scrivere.'] },
    { p: ['Se hai collegato anche la <strong>chat privata</strong>, a fine diretta il bot può scriverti lì il rapporto della serata: lo accendi nella scheda <em>Dirette</em>, dove il rapporto resta comunque, insieme all\'opzione via mail.'] },
    { h3: 'Chi entra nel gruppo' },
    { p: ['Un gruppo aperto si riempie di account che entrano, spammano e spariscono. Il <strong>cancello</strong> fa la cosa vecchia che funziona: chi entra non può scrivere finché non preme un tasto. Un bot il tasto non lo preme, perché non sa che c\'è.'] },
    { p: ['Serve il <strong>bot interattivo</strong> acceso, e che il bot sia <strong>amministratore</strong> del gruppo con il permesso <em>Blocca utenti</em>. Senza, il cancello non si accende e il pannello dice quale delle due cose manca: un interruttore che si accende e non fa niente è peggio di uno che rifiuta.'] },
    { p: ['Decidi tu <strong>quanto tempo</strong> ha per rispondere (da uno a sessanta minuti), <strong>cosa gli scrivi</strong> (con <code>{nome}</code> e <code>{minuti}</code>), <strong>cosa c\'è scritto sul tasto</strong>, e cosa succede a chi non risponde: lo togli dal gruppo — potrà rientrare e riprovare, non è un bando — oppure resta dentro ma muto.'] },
    { p: ['Chi passa il cancello riprende <strong>i permessi del gruppo</strong>, quelli che hanno tutti gli altri: non una lista decisa da noi, che gli darebbe più o meno diritti degli altri. E se i permessi del gruppo non si riescono a leggere, il cancello non silenzia nessuno: non si toglie la parola a qualcuno se non si sa come ridargliela.'] },
    { p: ['Gli amministratori e gli altri bot non passano dal cancello, e chi era già dentro non viene toccato.'] },

    { h3: 'Compleanni' },
    { p: ['Gli auguri partono in due posti, e sono due cose separate perché i momenti sono diversi. Nel <strong>gruppo Telegram</strong> partono a mezzanotte italiana. In <strong>chat</strong> la mezzanotte non esiste — a quell\'ora non c\'è nessuno — quindi partono al <strong>primo messaggio</strong> di chi compie gli anni quel giorno, una volta l\'anno.'] },
    { p: ['Con gli auguri in chat accesi, chi ti guarda si segna da solo scrivendo <code>!compleanno 25/12</code>; <code>!compleanno</code> da solo rilegge la data, <code>!compleanno via</code> la toglie. Tu scrivi il testo (con <code>{nome}</code>) e, se vuoi, scegli un <strong>effetto</strong> della tua libreria che parte insieme agli auguri.'] },
    { p: ['L\'elenco dei compleanni è uno solo, e accanto a ognuno c\'è da dove arriva: dal gruppo, dalla chat, o aggiunto a mano da te. Chi non passa in chat il giorno del suo compleanno non riceve auguri in chat: si fanno a chi c\'è.'] },

    { h2: 'I ruoli del tuo Discord' },
    { p: ['Discord i <strong>sub</strong> di Twitch se li sincronizza da solo. Tutto il resto no: chi ti segue, chi &egrave; VIP, chi &egrave; moderatore, quante ore ti ha guardato, quante monete ha, da quante dirette di fila c\'&egrave;. Quei dati ce li abbiamo noi, e qui diventano ruoli sul tuo server.'] },
    { p: ['Si comincia con <strong>un tasto</strong>: «Porta il bot nel tuo server». Ti manda su Discord, che ti fa scegliere il server da un elenco &mdash; ci sono solo quelli dove comandi tu &mdash; e ti chiede di confermare due permessi: <em>Gestire i ruoli</em> e <em>Gestire i canali</em>. Torni qui e ti diciamo come si chiama il server e quali ruoli il bot riesce davvero a muovere. L&rsquo;id del server non devi copiarlo: ce lo dice Discord.'] },
    { p: ['Se avevi gi&agrave; portato il bot prima che arrivasse il costruttore, ripassa da quel tasto: reinvitarlo &egrave; il modo con cui Discord gli aggiorna i permessi. Non succede niente di brutto se te ne scordi &mdash; il costruttore se ne accorge e te lo dice prima di cominciare, invece di fermarsi a met&agrave; strada.'] },
    { p: ['Se invece hai gi&agrave; un <strong>bot tuo</strong>, apri &laquo;Preferisci un bot tuo?&raquo; e incolla il suo token: da quel momento &egrave; lui a dare i ruoli, e resta cifrato da noi.'] },
    { p: ['Quella riga &mdash; &laquo;quali riesce a muovere&raquo; &mdash; &egrave; il passo che si sbaglia sempre. Discord non guarda il nome del permesso, guarda la <strong>posizione</strong>: se il ruolo del bot sta sotto quello che deve dare, non lo tocca, e nessuno ti dice perch&eacute;. Vai in <em>Impostazioni server &rarr; Ruoli</em> e trascina il bot sopra.'] },
    { p: ['Poi scrivi le regole: una condizione e il ruolo che le corrisponde. &laquo;&Egrave; abbonato&raquo;, &laquo;ti segue&raquo;, &laquo;ha almeno 500 monete&raquo;, &laquo;ti ha guardato almeno 10 ore&raquo;, &laquo;&egrave; di fila da 5 dirette&raquo;.'] },
    { h3: 'Chi si collega, e come' },
    { p: ['Chi ti guarda si collega <strong>da solo</strong>: scrive <code>!discord</code> in chat e apre l\'indirizzo che gli diamo &mdash; <code>discord.socialbot.live/iltuocanale</code> dove quel nome &egrave; acceso. Dice a Discord che &egrave; lui, e nello stesso momento <strong>entra nel server</strong>: niente link d\'invito da cercare, niente invito scaduto. La pagina gli d&agrave; un codice da riscrivere in chat, ed &egrave; quello che chiude il giro.'] },
    { p: ['Il codice va in <strong>quel verso</strong> per un motivo: la chat &egrave; pubblica. Se fossimo noi a scrivere in chat un link personale, chi sta guardando lo aprirebbe prima di lui e si prenderebbe i suoi ruoli. Cos&igrave; invece il codice nasce sul suo schermo e vale una volta sola: chi lo ricopia dalla chat lo trova gi&agrave; bruciato. Con <code>!discord via</code> si stacca, e i ruoli che ha restano suoi.'] },
    { p: ['Quello che il bot <strong>dice</strong> in chat &mdash; tutte e cinque le risposte, da &laquo;ecco dove si comincia&raquo; a &laquo;collegato&raquo; &mdash; lo scrivi tu, in &laquo;Le parole che dice in chat&raquo;. Dentro puoi mettere <code>{nome}</code>, <code>{link}</code> e <code>{codice}</code>. Un campo lasciato vuoto usa la nostra, e anche il nome del comando lo cambi come tutti gli altri.'] },
    { p: ['Il bot tocca <strong>solo</strong> chi si &egrave; collegato, e <strong>solo</strong> i ruoli che le tue regole nominano. Un ruolo che hai dato a mano, o che d&agrave; un altro bot, non lo guarda nemmeno: sennonch&eacute; la prima volta che accendi l\'interruttore spoglierebbe il server.'] },
    { p: ['E se Twitch per un momento non risponde, non conclude che &laquo;allora non &egrave; abbonato&raquo;: quella condizione, per quel giro, non vale. Meglio un ruolo dato in ritardo che mezzo server spogliato per una domanda caduta.'] },

    { h2: 'Gli avvisi sul tuo Discord' },
    { p: ['Nella scheda <strong>Avvisi</strong>, dentro Discord, decidi in quali canali del tuo server arriva cosa. Non &egrave; un canale solo: le tue dirette possono stare in <code>#annunci</code>, quelle degli streamer che segui in <code>#amici-in-diretta</code>, i video nuovi da un\'altra parte ancora. Per ogni canale scegli <strong>quali avvisi</strong> (Twitch, Kick, YouTube, TikTok, i post nuovi) e <strong>di chi</strong>.'] },
    { p: ['Il <strong>testo</strong> lo scrivi tu, per ogni canale, con gli stessi segnaposto di Telegram: <code>{nome}</code>, <code>{titolo}</code>, <code>{gioco}</code>, <code>{spettatori}</code>, <code>{link}</code>, <code>{piattaforma}</code>. Lascialo vuoto e usa quello di casa. Titolo, gioco e spettatori stanno gi&agrave; dentro il riquadro sotto il messaggio: ripeterli vuol dire dire due volte la stessa cosa.'] },
    { p: ['Puoi far <strong>chiamare un ruolo</strong>: sveglia quello e nessun altro. Scrivere <code>@everyone</code> nel testo non serve e non funziona &mdash; il bot non lo lascia passare, perch&eacute; una parola scritta per sbaglio non deve poter svegliare un server intero.'] },
    { p: ['Con &laquo;<strong>Chiudi l\'avviso a diretta finita</strong>&raquo; il messaggio non resta l&igrave; a dire &laquo;sono in diretta&raquo; fino a domani: a diretta chiusa diventa &laquo;ha finito la diretta&raquo;. Non sparisce, e non &egrave; una scelta estetica: cancellarlo vorrebbe dire usare la porta che cancella i messaggi di <em>chiunque</em>, e quel potere il bot lo tiene solo per passarlo al ruolo Moderatori. Riscrivere invece Discord lo permette solo su quello che hai scritto tu, quindi non pu&ograve; toccare nessun altro.'] },
    { p: ['Nell&rsquo;elenco dei canali quelli dove il bot <strong>non pu&ograve; scrivere</strong> sono segnati e non si scelgono: sarebbe scegliere un posto che poi non funziona. E &laquo;<strong>Prova</strong>&raquo; manda l\'avviso esattamente dove finirebbe davvero, col tuo testo e la tua menzione.'] },
    { h3: 'Chi annunciare' },
    { p: ['Oltre alle tue: le dirette di <strong>altri streamer</strong> che aggiungi, e se vuoi quelle di chi fa parte della community. La lista &egrave; <strong>la stessa</strong> che vedi nella scheda Telegram &mdash; il bot chiede a Twitch una volta sola come stanno, non due &mdash; ma cosa farne lo decidi qui, per il tuo server: la levetta della community vale solo per Discord, e accenderla non accende niente su Telegram.'] },
    { h2: 'Il server Discord, costruito da qui' },
    { p: ['Nella scheda <strong>Il server</strong> descrivi com&rsquo;&egrave; fatto il tuo Discord: le categorie, i canali dentro, di cosa si parla in ognuno e chi pu&ograve; fare cosa. Poi guardi cosa cambierebbe, e se ti convince lo fa lui.'] },
    { p: ['Non parti dal foglio bianco. Ci sono quattro tracce &mdash; <em>Si comincia</em>, <em>Intorno alle dirette</em>, <em>Si gioca insieme</em>, <em>Siamo in tanti</em> &mdash; e ognuna risponde a una domanda diversa. Se il server ce l&rsquo;hai gi&agrave;, c&rsquo;&egrave; <em>Leggi il mio server</em>: prende la forma che ha adesso e la usa come punto di partenza, e da l&igrave; cambi quello che vuoi.'] },
    { h3: 'Si guarda, poi si fa' },
    { p: ['&laquo;Fammi vedere cosa faresti&raquo; non &egrave; un riassunto di cortesia: &egrave; esattamente l&rsquo;elenco che verr&agrave; eseguito. Le categorie si creano prima dei canali, perch&eacute; un canale ci va dentro solo se la categoria esiste gi&agrave;. Un canale che qualcuno aveva trascinato fuori dalla sua categoria non viene rifatto: viene <strong>rimesso a posto</strong>, con dentro tutto quello che ci si erano detti.'] },
    { p: ['Fra il &laquo;guarda&raquo; e il &laquo;fai&raquo; passa del tempo, e in quel tempo il server &egrave; vivo: qualcuno pu&ograve; creare un canale, spostarne un altro. Se succede, il costruttore <strong>si ferma</strong> e ti rif&agrave; vedere invece di applicare alla cieca quello che avevi guardato prima.'] },
    { h3: 'Quello che non si tocca' },
    { p: ['Di suo il costruttore va solo in avanti: crea quello che manca e sistema quello che &egrave; fuori posto. Quello che il tuo server ha e la traccia non prevede te lo <strong>elenca</strong>, con da quanto tempo &egrave; fermo, e lo lascia dov&rsquo;&egrave;.'] },
    { p: ['Quel &laquo;da quanto tempo &egrave; fermo&raquo; non viene da un messaggio letto. Dentro ogni identificativo di Discord c&rsquo;&egrave; l&rsquo;istante in cui &egrave; nato, e l&rsquo;ultimo messaggio di un canale &egrave; un identificativo: cos&igrave; si sa che un canale non parla da otto mesi <strong>senza aprire la conversazione di nessuno</strong>. Non &egrave; discrezione, &egrave; che quel permesso il bot non ce l&rsquo;ha proprio.'] },
    { h3: 'Chi &egrave; chi: i ruoli' },
    { p: ['Nella stessa scheda decidi anche i <strong>ruoli</strong>: come si chiamano, di che colore sono, se stanno a parte nell&rsquo;elenco delle persone, e cosa possono fare. Le tracce ne portano gi&agrave; qualcuno &mdash; <em>Streamer</em>, <em>Moderatori</em>, <em>VIP</em>, <em>Abbonati</em> &mdash; e da l&igrave; cambi quello che vuoi.'] },
    { p: ['<strong>&laquo;Streamer&raquo; &egrave; solo un colore e un posto a parte</strong>, senza privilegi, e non &egrave; una dimenticanza: su Discord un bot non pu&ograve; creare niente pi&ugrave; in alto di s&eacute;, quindi un ruolo coi poteri del padrone di casa da qui non potrebbe nascere. Quello che sa fare &egrave; farti vedere, e lo fa.'] },
    { p: ['<strong>&laquo;Moderatori&raquo; invece ha i poteri veri</strong>: mettere in pausa, cacciare, ripulire. Il bot li pu&ograve; passare perch&eacute; li ha anche lui &mdash; Discord non lascia dare a un ruolo un privilegio che chi lo crea non possiede. Se all&rsquo;invito non glieli hai concessi, l&rsquo;anteprima te lo dice PRIMA, con quali mancano: ripassi dal tasto dell&rsquo;invito e torni qui.'] },
    { p: ['Quello che non pu&ograve; toccare te lo elenca invece di far finta: i ruoli <strong>pi&ugrave; in alto del bot</strong> (il tuo, gli amministratori) e quelli delle altre applicazioni restano dove sono. E se hai due ruoli con lo stesso nome non indovina quale intendi: te lo dice e li lascia stare.'] },
    { p: ['In <strong>piazza pulita</strong> valgono anche loro: i ruoli che non sono nella traccia spariscono. Si cancellano per ultimi, dopo i canali, per una ragione: se qualcosa va storto a met&agrave; ti resta un server a met&agrave; costruzione, non un server dove met&agrave; delle persone ha perso i suoi privilegi. E un ruolo che portava dei poteri conta come un canale vivo: se ne stai per perdere uno, ti chiedo di scrivere il nome del server.'] },
    { h3: 'Quando invece vuoi fare piazza pulita' },
    { p: ['A volte non vuoi aggiungere: vuoi che il server diventi <strong>esattamente</strong> la traccia, e che quello che non ci sta dentro sparisca. Per quello c&rsquo;&egrave; una modalit&agrave; a parte, che accendi tu dal fondo della scheda. Non &egrave; un interruttore che resta acceso: <strong>dura dieci minuti e si spegne da sola</strong>, e appena entri la pagina cambia colore, cos&igrave; non ti capita di esserci dentro senza saperlo.'] },
    { p: ['L&igrave; dentro il costruttore fa le stesse cose di sempre &mdash; crea, sistema &mdash; e in pi&ugrave; cancella. L&rsquo;elenco te lo fa vedere uguale, solo che quello che sparisce sta sotto <strong>Cancella</strong> invece che sotto &laquo;non &egrave; in questa traccia&raquo;, e il tasto in fondo non dice pi&ugrave; &laquo;Costruisci&raquo;.'] },
    { p: ['Se fra le cose da cancellare c&rsquo;&egrave; un canale in cui si &egrave; parlato nell&rsquo;ultimo mese, o se sono pi&ugrave; di dieci in un colpo, non basta confermare: ti chiedo di <strong>scrivere il nome del server</strong>. Su Discord un canale cancellato non torna, e con lui se ne va tutto quello che vi eravate detti l&igrave; dentro; un &laquo;sei sicuro?&raquo; si clicca a memoria, il nome no.'] },
    { p: ['Di ogni giro resta scritto chi &egrave; stato, quando, e cosa ha creato, sistemato o tolto &mdash; coi <strong>nomi</strong> di quello che non c&rsquo;&egrave; pi&ugrave;. &Egrave; l&rsquo;unico posto dove quei nomi restano, e lo trovi nella scheda.'] },
    { h3: 'Chi pu&ograve; fare cosa' },
    { p: ['Dentro ogni canale scrivi righe come &laquo;tutti &mdash; non pu&ograve; &mdash; scrivere&raquo;, oppure con un ruolo al posto di &laquo;tutti&raquo;. Il preset &egrave; un <strong>pacchetto di differenze</strong>, non una copia: tocca solo i permessi che nomina, e tutti gli altri &mdash; quelli messi a mano, quelli di un altro bot &mdash; restano dove sono.'] },
    { p: ['Se una riga nomina un ruolo che nel server non c&rsquo;&egrave; pi&ugrave;, quella riga viene <strong>saltata</strong> e te lo diciamo. Un ruolo che non esiste non &egrave; &laquo;nessuno&raquo;: se lo trattassimo cos&igrave;, un permesso scritto per proteggere un canale lo chiuderebbe a tutto il server, e sembrerebbe una scelta tua.'] },

    { h3: 'TikTok, YouTube, Instagram' },
    { tabella: [
      ['Rete', 'Cosa serve', 'Cosa avvisa'],
      ['TikTok', 'il tuo nome utente', 'quando vai in diretta lì, e quando pubblichi un video'],
      ['YouTube', 'il canale (<code>@nome</code>)', 'quando esce un video nuovo'],
      ['Instagram', 'il tasto «Collega Instagram», con un account professionale', 'quando esce un post nuovo'],
    ] },
    { p: ['Ogni avviso può anche <strong>uscire nella tua chat Twitch</strong>: è la parte che di solito conviene di più, perché chi ti sta già guardando è il pubblico più facile da portare sull\'altra piattaforma.'] },

    { h2: 'Quando qualcosa non si vede' },
    { ul: [
      '<strong>La pagina è vuota.</strong> Va <em>pubblicata</em>: finché non lo è, l\'indirizzo risponde ma non mostra niente.',
      '<strong>La foto non c\'è.</strong> Arriva dal profilo Twitch: se l\'hai appena cambiata lì, ci mette un po\'.',
      '<strong>L\'icona del link è sbagliata.</strong> Si ricava dall\'indirizzo: se il link passa da un accorciatore, l\'indirizzo vero non si vede e resta l\'icona generica.',
      '<strong>Telegram non scrive.</strong> Il bot deve essere <em>dentro</em> al gruppo e il <code>/collega</code> va scritto lì, non in privato.',
      '<strong>L\'avviso live non parte.</strong> Controlla che la rete sia accesa: collegata e accesa sono due cose diverse.',
      '<strong>La grafica esce sfocata.</strong> Scaricala di nuovo dopo aver chiuso l\'anteprima: il PNG esce alla risoluzione piena, non a quella che vedi a schermo.',
    ] },
  ],
  faq: [
    { d: 'La pagina link è come Linktree?', r: 'Fa la stessa cosa, ma è servita dal nostro server come pagina già pronta: si apre in un istante anche con poca rete, e il blocco della diretta dice da sé se sei online.' },
    { d: 'Posso usare un mio dominio?', r: 'L\'indirizzo è <code>socialbot.live/u/&lt;tuonome&gt;</code>. Nella bio si mette quello.' },
    { d: 'Le chiavi di Telegram le vedete voi?', r: 'Il token serve al server per parlare col tuo bot ed è tuo: puoi revocarlo da BotFather quando vuoi, e da lì il collegamento smette di funzionare.' },
    { d: 'Perché sulla pagina pubblica non ci sono emoji?', r: 'Perché cambiano forma su ogni sistema e non si possono colorare. Le icone sono disegni monocromatici che seguono il tema.' },
    { d: 'Le grafiche si aggiornano da sole ogni settimana?', r: 'No: restano salvate, ma il PNG lo scarichi tu quando la programmazione cambia. È una grafica da pubblicare, non un widget.' },
  ],
};
