// Manuale in inglese: la scheda Strumenti. Traduzione di src/web/manuali/it/strumenti.js (vedi docs/LINGUE.md).
export default {
  id: 'strumenti',
  slug: 'tools',
  titolo: 'Tools manual: custom QR, emotes, media kit, panels | SocialBot',
  h1: 'Tools manual',
  desc: 'A QR code with your logo that really scans, emotes and badges at Twitch sizes, a media kit with real numbers and channel panels already filled in.',
  corpo: [
    { p: [
      'In the panel menu, under <em>Tools</em>, you find the things you need around the stream: the <strong>custom QR</strong>, <strong>emotes and badges</strong> at Twitch sizes, the <strong>media kit</strong> and the channel <strong>panels</strong>.',
      'They are all drawn in your browser. The images you prepare for emotes and badges never pass through our server; the QR logo, the media kit choices and the panels reach us only if you press <em>Save</em>, so you find them again next time.',
    ] },

    { h2: 'Custom QR', scheda: 'qr' },
    { p: [
      'At the top you write where the QR leads. The buttons below fill it in for you with your <strong>link page</strong> or your channel, but you can type any address or text.',
      'The QR holds exactly what you typed, with no detour through us: it never expires, and it works as long as the link you put in it works.',
    ] },
    { h3: 'Shapes and colors' },
    { tabella: [
      ['What', 'Choices', 'Note'],
      ['The modules', 'Squares, soft, dots, hand drawn', 'With soft, only the free corners get rounded, so groups stay joined. With hand drawn every module is traced by hand, and it is always the same stroke for your channel.'],
      ['The eyes', 'Square, soft, round, hand drawn', 'They are the three big squares in the corners: the phone uses them to find the code.'],
      ['The colors', 'Five ready-made pairs, or your own', 'Modules, background and eyes each have their own color.'],
    ] },
    { h3: 'The logo in the middle' },
    { p: [
      'In the middle you can put <strong>your picture</strong> (the one from your channel) or <strong>an image</strong> of your own, PNG, JPG or WebP. If it is heavy, we shrink it for you.',
      'A logo covers part of the code, and the QR recovers that part with its spare codes. That is why, when there is a logo, we use the highest error correction, and the logo never takes more than <strong>half</strong> of what can be corrected: the other half is left for a scratch, a glare, a fold in the paper. It never touches the eyes or the other fixed marks.',
      'The <em>Logo size</em> slider goes from the smallest to the largest logo that link allows. The longer the link, the denser the code and the less room is left: with a long link the logo may not fit.',
    ] },
    { h3: 'The frame with a line' },
    { p: ['If you write a line (up to 40 characters, like «Scan me»), the QR gets a hand-drawn frame with the line underneath, in handwriting.'] },
    { h3: 'How we know it scans' },
    { p: ['A custom QR breaks easily: one color that is too light or a logo that is too big, and the phone can no longer read it. Here the rules are built into the design:'] },
    { ul: [
      '<strong>Contrast.</strong> Between modules and background we measure the real difference in light, not the color numbers, and it has to reach at least 0.55 out of 1. The background has to be the lighter of the two: many readers do not read inverted QR codes.',
      '<strong>Margin.</strong> Around the code stay the four empty modules the standard asks for: without them, the phone cannot tell where the code ends.',
      '<strong>Shapes.</strong> Every shape covers the center of its module, which is the spot the phone looks at.',
      '<strong>Eyes.</strong> The three rings of each eye are the same shape at different scales, so the phone recognizes it from any direction; the small squares inside the code follow the eyes. Square eyes, the default ones, can be read by any reader at all.',
    ] },
    { p: [
      'Then we <strong>read it back</strong>: we take the pixels of the preview, look at the center of each module and decode it like a real reader would, error correction included. If the text that comes out is not identical to what you typed, the download buttons stay off and below we tell you what to change. The same test runs again on the large image, before you download it.',
      'The read-back sees the design straight and in focus: it does not know how you will print it. For print, keep the QR at least <strong>2 cm</strong> on a side, and larger if it will be scanned from far away: a handy rule is one tenth of the distance.',
    ] },
    { h3: 'Downloading and saving it' },
    { ul: [
      '<strong>PNG</strong> at 1024, 2048 or 4096 pixels. The largest is for print.',
      '<strong>SVG</strong>: a drawing that scales up without losing anything, with the logo and the font of the line inside the file.',
      '<strong>Save the style</strong>: you find it again next time, and <em>Social graphics</em> use it for the QR they put in their images, without the frame. If the QR with your style did not read back there, Social graphics use the plain one.',
    ] },

    { h2: 'Emotes and badges', scheda: 'misure' },
    { p: ['Twitch asks for every emote in three sizes, <strong>112, 56 and 28</strong> pixels, and for every badge in three, <strong>72, 36 and 18</strong>. Here you upload a single image and you get them all, ready to upload to Twitch.'] },
    { h3: 'Shrunk properly' },
    { p: ['Shrinking an image means averaging its pixels. If the average is taken on the color numbers, as many programs do, the edges between two colors get darker and thin outlines disappear. We take it on real light, and we account for transparency: a transparent edge does not smear black onto the pixels next to it.'] },
    { h3: 'If it is not square' },
    { ul: [
      '<strong>Whole</strong>: the whole image fits in, and the leftover space stays transparent.',
      '<strong>Fill</strong>: it fills the square and crops whatever sticks out, keeping the center.',
    ] },
    { h3: 'How they look in chat' },
    { p: ['Under the three sizes you see them as they look in chat, on the dark background and on the light one: the emote at 28 pixels next to the text, the badge at 18 before the name. On denser screens the browser picks the larger sizes, as Twitch does.'] },
    { h3: 'File sizes and downloads' },
    { p: ['Twitch accepts emotes up to <strong>1 MB</strong> and badges up to <strong>25 KB</strong>: if a size goes over, we tell you. Each size downloads on its own, or all together in a zip.'] },

    { h2: 'Media kit', scheda: 'kit' },
    { p: ['It is the sheet you send to a brand when you pitch a collaboration, or when they ask you for one: who you are, what you stream, how many people watch you, when you are live, where to find you and how to reach you. It comes out as a PDF, with links that open with a click, or as a PNG.'] },
    { h3: 'Where the numbers come from' },
    { ul: [
      '<strong>From your streams in the last 30 days</strong>, the finished ones: the bot follows them while you are live and writes the report at the end of the night. They are the same numbers you see in the Streams tab.',
      '<strong>Average viewers</strong> are weighted by time: a six-hour stream counts six times as much as a one-hour stream.',
      '<strong>The peak</strong> is the highest number of viewers in a single stream of the period.',
      '<strong>People in chat</strong> are the different people who wrote at least once, not counting you.',
      '<strong>Total followers</strong> is the number Twitch gives at the moment you open the tab.',
      '<strong>What you stream</strong> is the share of time for each category. It is counted from the current streams onward.',
    ] },
    { p: [
      'Under the numbers it always says which period they cover, who measured them and when. The numbers cannot be changed by hand: you can only choose which ones to show.',
      'With fewer than three streams in the period the stream numbers do not appear, and under the tab it says how many are still missing: three nights are the minimum to say anything true.',
    ] },
    { h3: 'The rest of the sheet' },
    { ul: [
      '<strong>A couple of lines about you</strong>: it starts with the line from your link page. Four lines fit.',
      '<strong>When you are live</strong> comes from your week, <strong>where to find you</strong> from the socials on your link page.',
      '<strong>The brands you have worked with</strong> and the <strong>email for collaborations</strong> are up to you. The email goes in a band at the bottom of the sheet.',
      '<strong>The colors</strong> are those of your link page, or Paper (light) or Night (dark).',
    ] },
    { p: ['Your choices are saved with <em>Save</em> and you find them again next time. The numbers, instead, update by themselves every time you open the tab. The media kit is not a public page: it exists when you download it, and you send it to whoever you like.'] },

    { h2: 'Panels', scheda: 'pannelli' },
    { p: ['They are the boxes under your Twitch channel, in <em>About</em>: each one has an image, a link and a description. Here you prepare them all together, in the same style, and download them in a single file.'] },
    { h3: 'They start already filled in' },
    { ul: [
      '<strong>About me</strong> leads to your link page, with its line as the description.',
      '<strong>Schedule</strong> writes the days and times of your week, and the time zone.',
      '<strong>Socials</strong> lines up the socials from your link page, each with its own link.',
      '<strong>Discord</strong> leads to the entrance door of your server, if it is open; otherwise to the Discord on your link page.',
      '<strong>Support me</strong> leads to the donations page, if it is on and donations are ready.',
      '<strong>Commands</strong> lists your commands, up to twelve. <strong>Rules</strong> starts from four rules you rewrite as you like.',
    ] },
    { p: [
      'A panel shows up by itself only if the channel has something to put in it: without a week there is no <em>Schedule</em>, without donations ready there is no <em>Support me</em>. You add them from <em>Add</em>, at the bottom of the list, together with the free panel, where you write everything yourself.',
      'Every field can be rewritten. If you later change something in the channel, a social for example, <em>Refill from the channel</em> puts back the current link and description.',
    ] },
    { h3: 'One style for all of them' },
    { p: [
      'Colors, shape, font, height and icon apply to every panel: they sit in a row on the same page, and one that looks different from the others stands out right away. The colors can be those of your link page, Paper or Night; the shape hand-drawn, clean or full. The title also has a single size for all panels: the one that fits the longest title.',
      'The text on the panel is always readable: if its color does not contrast enough, it turns white or black. With <em>Dark Twitch</em> and <em>Light Twitch</em> you see how they look on the two Twitch pages.',
    ] },
    { h3: 'Putting them on Twitch' },
    { passi: [
      { t: 'Download all', d: ': you get a file with the images in order and a text with the title, link and description of each panel. You can also download a single panel, from under its image.' },
      { t: 'Open your channel', d: ' on Twitch, go to <em>About</em> and turn on <em>Edit panels</em>.' },
      { t: 'For each panel', d: ' upload the image, paste the link and the description. In the tab, under each panel, you find <em>Copy the link</em> and <em>Copy the description</em>.' },
    ] },
    { p: ['The images are 320 pixels wide, the size Twitch shows them at. Twitch reads the description as Markdown: <code>**bold**</code>, <code>[words](link)</code> for a link, a dash in front for a list.'] },

    { h2: 'When something does not work' },
    { ul: [
      '<strong>The QR download buttons are off.</strong> Under the preview it says why: usually the colors are too close, or the logo does not fit with that link.',
      '<strong>The logo does not fit.</strong> The link is too long: shorten it. The address of your link page is already short.',
      '<strong>Your picture does not show up.</strong> It is your channel picture, and sometimes it does not arrive right away: try again, or upload an image.',
      '<strong>I want to change the logo I uploaded.</strong> When <em>An image</em> is selected, below it you find <em>Change image</em>.',
      '<strong>The large emote size looks grainy.</strong> The starting image is small: start from at least four times the largest size.',
      '<strong>An animated GIF comes out still.</strong> Here only the first frame is taken: animated emotes are prepared elsewhere.',
      '<strong>The numbers are missing from the media kit.</strong> In the last 30 days there are fewer than three finished streams: under the tab it says how many.',
      '<strong>The categories are missing from the media kit.</strong> They are counted from the streams done since the media kit exists, and they appear after three streams.',
      '<strong>A panel I expected is not there.</strong> The channel has nothing to put in it yet: for example, the donations page is off. Add it from <em>Add</em> and write the link and description yourself.',
      '<strong>A panel title ends with dots.</strong> It does not fit even with the smallest font: shorten it, remove the icon or pick a narrower font.',
      '<strong>All the panel titles got small.</strong> There is one size for all, set by the longest title: shorten that one.',
    ] },
  ],
  faq: [
    { d: 'Does the QR expire?', r: 'No. It only holds the link you typed, with no detour through us: it works as long as that link works.' },
    { d: 'Can I make a QR for a site that is not my channel?', r: 'Yes: in the field at the top, type any address or text.' },
    { d: 'How big should I print it?', r: 'At least 2 cm on a side. If it will be scanned from far away, about one tenth of the distance: for three meters, thirty centimeters.' },
    { d: 'Why does the QR have more modules when it has a logo?', r: 'With a logo we use the highest error correction, which adds spare codes: they are what recovers the part the logo covers.' },
    { d: 'Do the emote images end up on your server?', r: 'No: they are shrunk in your browser, and you download them from there.' },
    { d: 'Can I edit the numbers in the media kit?', r: 'No: they come from your streams, and you can only choose which ones to show. That is what makes them credible to whoever reads them.' },
    { d: 'Is the media kit a public page?', r: 'No: it exists when you download it, and you send it to whoever you like.' },
    { d: 'Do the panels update by themselves on Twitch?', r: 'No: Twitch does not let anyone change panels from outside. When you change something, you download again and re-upload the panel that changed.' },
    { d: 'Can I use the panels on Kick or YouTube?', r: 'The images, yes: they are normal PNG files. The sizes, though, are the Twitch ones.' },
  ],
};
